### ISSUE TITLE
Cannot export any Recoil classes for re-use as modules

### ISSUE THREAD

**Issue by gubpalma** [facebookexperimental/Recoil#1008]
Hi, not sure what I'm doing wrong here.

I have copied the `useRecoilCallback()` sample as outlined [here](https://recoiljs.org/docs/api-reference/core/useRecoilCallback/#lazy-read-example) into my local project and it works as expected:
![image](https://user-images.githubusercontent.com/19819334/117095876-f3b98780-adaa-11eb-9da2-a458cfd672f7.png)

Here is the code:
`UseRecoilCallback.tsx`
```
import React from 'react';
import { atom, useRecoilCallback } from 'recoil';

const itemsInCart = atom({
    key: 'itemsInCart',
    default: 0,
});

export default () => {
    const logCartItems = useRecoilCallback(({ snapshot }) => async () => {
        const numItemsInCart = await snapshot.getPromise(itemsInCart);
        console.log('Items in cart: ', numItemsInCart);
    });

    return (
        <>
            <div>
                <button onClick={logCartItems}> Log Cart Items </button>
            </div>
        </>
    );
}
```

And here is the page that implements the control:
`Landing.tsx`
```
import React from 'react';
import { RecoilRoot } from 'recoil';

import CartInfoDebug from './UseRecoilCallback';

export default () => {

    return (
        <>
            <RecoilRoot>
                <CartInfoDebug />
            </RecoilRoot>
        </>
    );
};
```
However, if I take this **exact** code and put it into an external module / package i.e.
```
import CartInfoDebug from '@my-package-library/UseRecoilCallback';
```
The same page fails with `Error: This component must be used inside a <RecoilRoot> component.`
![image](https://user-images.githubusercontent.com/19819334/117096500-96bed100-adac-11eb-8d1e-fc785b792cdd.png)

The same error occurs regardless of how I implement the Recoil component.

I really want to implement the recoil patterns across multiple services without having to write local implementations per service. I have been able to do this successfully with React `useContext()`.

**Comment by BenjaBobs** [comment]
According to the error message it looks as though you don't have a `<RecoilRoot>` somewhere up the hierarchy. This is necessary because the `<RecoilRoot>` storesnthe state and exposes it to its children.

**Comment by gubpalma** [comment]
So my problem was using `yarn link` to reference the external module.

When I actually _published_ the module, the referenced class worked the same as if it were local. 

Makes testing a bit cumbersome, but at least I can use Recoil in the services.

Apologies and many thanks.
