### ISSUE TITLE
[docs] Add some examples for working with nested state

### ISSUE THREAD

**Issue by jaredpalmer** [facebookexperimental/Recoil#101]
Right now, the docs show nearly all atom state to be strings or numbers. It would be great to show how to use atomFamily and selectorFamily to work with nested data and normalized data

**Comment by davidmccabe** [comment]
Good idea, we're rolling out more docs and examples. Thanks for the feedback.

**Comment by davidmccabe** [comment]
The short answer is that the contents of atoms is opaque as far as Recoil is concerned, so there's nothing to do.

**Comment by jaredpalmer** [comment]
I would just show one example. It removes the reader from having to guess.

**Comment by drarmstr** [comment]
@jaredpalmer - Is something like https://recoiljs.org/docs/guides/asynchronous-data-queries#data-flow-graph what you were thinking?

**Comment by jaredpalmer** [comment]
@drarmstr I _think_ I figured this out. 

https://codesandbox.io/s/recoil-sandbox-20200516-meh12?file=/src/App.js

- Fake fetch a list of objects
- Normalize them by id
- Make nested fields editable
- Provides a way to denormalize the data back into a list with a selector 

> Note: I'm not data fetching with recoil or with suspense

![Kapture 2020-05-18 at 15 03 14](https://user-images.githubusercontent.com/4060187/82250040-c6b16200-9918-11ea-835a-628591bc07c3.gif)
