### ISSUE TITLE
Allow setting atom value to a promise or error in TypeScript types

### ISSUE THREAD

**Issue by migueloller** [facebookexperimental/Recoil#1018]
The TypeScript type signature for setting a state value is:

```typescript
type SetterOrUpdater<T> = (valOrUpdater: ((currVal: T) => T) | T) => void
```

But since the "true" representation of Recoil state is the `Loadable`, one could do `set(0)`, `set(Promise.resolve(0)`, or `set(new Error('Boom!')` for an atom of type `number`. My current use case is for an atom that holds a response object from an HTTP request. I want to be able to just set the promise value (i.e., `set(responsePromise)`) but I'm running into TypeScript errors.

Perhaps I'm not looking hard enough and there's a better way to achieve what I'm trying to do, but given that everything works as expected if I just the value to the promise I'm include to conclude that this is a type definition issue and not an issue in Recoil itself.

Also, one could try something like this, but there are issues:

```typescript
responsePromise
  .then(response) => {
    set(response)
  })
  .catch(error => {
    set(error as Error) // TypeScript complains here
  })
```

**Comment by drarmstr** [comment]
Full support for the ability to set Atoms to a `Promise` is still pending.  See #237
