### ISSUE TITLE
Mocking state in jest

### ISSUE THREAD

**Issue by zbyte64** [facebookexperimental/Recoil#1019]
Howdy, I am currently using jest to mock atom state and it appears to work but with warnings. The motivation is that we want to test various subsystems in isolation, so instead of having a selector interface with another system we mock the module and replace a selector with an atom with the desired test state.  The alternative would require more knowledge and mocking of other systems and becomes less of a unit test and more of an integration test with mocked API calls.

Our tests with this method looks like this:

```
import { snapshot_UNSTABLE } from 'recoil';
import { activeSources } from './tileSources';

test('active Sources yeilds tile specs', async () => {
  require('state/datasets');
  const initialSnapshot = snapshot_UNSTABLE();
  expect(
    await initialSnapshot.getLoadable(activeSources).toPromise(),
  ).toMatchSnapshot();
});

beforeAll(() => {
  jest.mock('state/datasets');
});
```

Aside from having to require the mocked module in the test itself, things work as expected. However recoil complains about duplicate atom keys. It would be nice to use this method without the warnings or have some guidance on how to test selectors in isolation. Thank you.

**Comment by drarmstr** [comment]
For this usecase in unit testing we ended up using `jest.resetModules()`.  You can see an example in `Recoil_TestingUtils.js`

**Comment by zbyte64** [comment]
Thank you for the feedback. Here's a direct link to the example to save others some time: https://github.com/facebookexperimental/Recoil/blob/master/src/testing/Recoil_TestingUtils.js#L252
