### ISSUE TITLE
Is Recoil a build-system?

### ISSUE THREAD

**Issue by Lucifier129** [facebookexperimental/Recoil#1020]
Hi folks

Recoil is awesome, thanks for your great job.

I have a question, Is Recoil a build-system?

I recently read a paper "[Build Systems à la Carte: Theory and Practice](https://www.microsoft.com/en-us/research/uploads/prod/2020/04/build-systems-jfp.pdf)", and I found that the Recoil API is very similar to what is described there.

```haskell
-- the fetch callback is like the get in selector of Recoil
sprsh1 :: Tasks Applicative String Integer
sprsh1 "B1" = Just $ Task $ \fetch -> ((+) <$> fetch "A1" <*> fetch "A2")
sprsh1 "B2" = Just $ Task $ \fetch -> ((*2) <$> fetch "B1")
sprsh1 _ = Nothing

```

And I have implemented the Recoil-like API via build-system abstraction written by TypeScript, [click to see the gist](https://gist.github.com/Lucifier129/4d07491e90c84fbe5afabd8c737fc350#file-recoil-via-build-system-ts-L167-L222)

I'm curious if the Recoil project was inspired by that paper, or is it just a coincidence?

**Comment by davidmccabe** [comment]
Cool paper, thanks for sharing. Both Recoil and build systems are systems for incremental computation.
