### ISSUE TITLE
Did not retain recoil value on render, or committed after timeout elapsed. This is fine, but odd. undefined 

### ISSUE THREAD

**Issue by kvbalib** [facebookexperimental/Recoil#1034]
I'm getting this error after React hot-reload, since I've updated Recoil to 0.3.0. I haven't noticed any issues in my app related to this, but console throws this every time. Don't know which part exactly is causing it, since it started after Recoil update, not in the development process.

I'm using latest create-react-app + react-app-rewired, RxJS, Recoil and Material UI.

**Comment by Svarto** [comment]
same here!

**Comment by jeonyeonkyu** [comment]
same here! :)

**Comment by CloudDrivenSolutions** [comment]
Also receiving the same error message.  I rolled back to 0.2.0

**Comment by fultonm** [comment]
Just installed recoil ^0.3.1 and getting this issue after following a basic setup tutorial.

**Comment by lejonmanen** [comment]
I can confirm this warning occurs in my simple "counter" project with create-react-app (with typescript) + recoil. Warning disappears if the page is reloaded. However, despite the message, the recoil state value is retained after hot reload. I'm guessing maybe recoil doesn't check for hot reloads.

**Comment by minhna** [comment]
I have this issue with react native and expo, recoil 0.3.1

**Comment by drarmstr** [comment]
We investigated this and will be removing the warning. It should be safe to ignore.  (cc @davidmccabe)

**Comment by snsie** [comment]
I encountered this warning today after switching to the latest experimental version of react. Additionally, the state variable wasn't updating when using useRecoilState. Downgrading to an earlier experimental version of react/react-dom fixed the issue.

**Comment by davidmccabe** [comment]
You can safely ignore this warning. Next point release will remove it. Sorry about this :(

**Comment by drarmstr** [comment]
Removed in #1062

**Comment by shanoysinc** [comment]
stilling facing this error in 0.3.1 update

**Comment by drarmstr** [comment]
> stilling facing this error in 0.3.1 update

This was after `0.3.1`, it's in `nightly` and expect it in the next release shortly.
