### ISSUE TITLE
[Feature Request]: I think renaming useRecoilValue to useGetRecoilState is easier to remember.

### ISSUE THREAD

**Issue by puxiao** [facebookexperimental/Recoil#1035]
Hmmm... 

`get / set / reset `

I think they're more like a series of connected.

1. useSetRecoilState
2. useResetRecoilState
3. ... useGetRecoilState

<br>

**maybe:**

```
export {
   useRecoilValue,
   useRecoilValue as useGetRecoilState
};
```

**Comment by drarmstr** [comment]
See rename proposal here for a potential future release: #804
