### ISSUE TITLE
state not update through setInterval method.

### ISSUE THREAD

**Issue by Arif-un** [facebookexperimental/Recoil#1044]
I tried Recoil with a basic setup but stuck in a problem.

I added some nested components and trying to update the state in the setInterval method.
It this [example](https://codesandbox.io/s/recoil-implementation-ozc9o?file=/src/components/J.jsx), I tried to update state from "J.jsx" component usign setInterval method but its not updating.
Thanks

**Comment by Arif-un** [comment]
so, I achieve the wanted result using settimeout (not using setinterval).

```
useEffect(() => {
    setTimeout(() => {
      setCount(count + 1);
    }, 1500);
  }, [count]);
```

Is there an advantage of using `useRecoilCallback` instead?

Thank you.

**Comment by BenjaBobs** [comment]
Actually, forget what I said, I just realized, that the easiest and cleanest solution to this problem is really passing a `valueUpdater` instead of a raw value.
```ts
useEffect(() => {
  const autoCountInterval = setInterval(() => {
    console.log(count);
    setCount(previousCount => previousCount + 1);
  }, 1500);

  return () => clearInterval(autoCountInterval);
}, []);
```

**Comment by Arif-un** [comment]
great, thanks
