### ISSUE TITLE
Got TypeError: Object(...) is not a function when trying to import { selectorFamily } from "recoil" 

### ISSUE THREAD

**Issue by jimmyandrade** [facebookexperimental/Recoil#105]
## Developer Story

*As a* developer
*I want to* use the `selectorFamily` helper function
*So that* I can make asynchronous queries with parameters

## Description

I am trying to make an asynchronous data query with parameters. So I am trying to use the `selectorFamily` helper. But when I try to `import { selectorFamily } from "recoil"`, the application throws `TypeError: Object(...) is not a function`.

## How to fix it

Maybe exporting the `selectorFamily` helper at the `recoil` library.

## Steps to reproduce the behavior

1. Initialize or open a React project;
2. Run `npm install recoil --save-exact` to install version `0.0.7`;
3. Create a JS file;
4. Try to `import { selectorFamily } from "recoil"` in this file;
5. Run `npm start` and check if error occurs.

## Expected behavior

Application should not throw a TypeError.

## Actual behavior

```
TypeError: Object(...) is not a function
Module.<anonymous>
src/recoil/selectors/reportedParkingsQuery.js:20
```

```js
  17 |   throw error.response.error
  18 | }
  19 | 
> 20 | export const reportedParkingsQuery = selectorFamily({
  21 |   key: "ReportedParkings",
  22 |   get: (carPlate) => async ({ get }) => {
  23 |     const response = await getParkingsByCarPlate(carPlate)

```

```
Module../src/recoil/selectors/reportedParkingsQuery.js
http://localhost:8000/commons.js:120193:30
__webpack_require__
/webpack/bootstrap:789
```

## Environment

* **OS**: macOS Catalina 10.15.4 (19E287);
* **Node version**: v12.16.0;
* **NPM version**: 6.13.4;
* **React version**: 16.13.1;
* **Recoil version**: 0.0.7.

## Related code

https://github.com/facebookexperimental/Recoil/blob/1e6e077de77e35dadf28b1a452980f2cb76620a5/src/recoil_values/Recoil_selectorFamily.js#L88-L135

**Comment by drarmstr** [comment]
`selectorFamily` isn't currently exported in published version on npm.  Though, the code is there so you can explore using it directly.  #33 should help fix the exporting issue for the open-source version.

**Comment by jimmyandrade** [comment]
@drarmstr thank you.

Since, for now, the code is not available in the library, does it make sense to put that information at [`selectorFamily` at docs](https://recoiljs.org/docs/guides/asynchronous-data-queries/), and update it as #33 is fixed?

**Comment by drarmstr** [comment]
@jimmyandrade The code is available here, it's just not being exported nicely with the build.  Thanks for bearing with us as we're getting the initial release of this beta library up and going.

**Comment by jimmyandrade** [comment]
Sorry, I didn't express myself well in the last comment. Thank you for the support.

**Comment by davidmccabe** [comment]
Hey @jimmyandrade, sorry about that mis-match. We are pretty new at this. Anyway, selectorFamily is (for now) just a simple memoized function, although we will probably add some other tricks for memory management soonish. Hope that unblocked you for now?

**Comment by jimmyandrade** [comment]
Hey @davidmccabe! Don't worry, the work you are doing is already helping a lot.

In fact, I still haven't been able to unlock what I need.

I am building a part of my application to check for traffic tickets for a specific car. After entering a car license plate number and clicking a submit button, an API call is made using `axios`. I use the car plate as the argument, so this is why I want to use `selectorFamily`.

Is it worth it to create am issue to ask for help on how to implement this using `recoil`?

**Comment by kivervinicius** [comment]
@jimmyandrade Hey bro, do you already resolved this?

**Comment by timeswind** [comment]
Is this the same issue for using atomFamily?

**Comment by Cadrach** [comment]
Hi there, thanks for the work on this library!

Is there an easy way to use selectorFamily in recoil currently? I have looked at #33 and #82 but it does not seem to be quite there yet...

**Comment by drarmstr** [comment]
@timeswind - Yes, same issue for `atomFamily` or any of the other utils

@Cadrach - Can you fork the repository instead of using the NPM package as a workaround for now?  We're getting close, though..
