### ISSUE TITLE
Existing cache must have a branch midway through the route with matching node key

### ISSUE THREAD

**Issue by Shmew** [facebookexperimental/Recoil#1061]
I upgraded to 0.3 after a while of being on 0.1, and I noticed I was getting this error in a few places in my code. I'm not exactly sure what this error is hinting at, would anyone have a hint for me to help track down what exactly is going on here?

**Comment by davidmccabe** [comment]
@Shmew This is a bug in Recoil. If you have steps to reproduce it would help us figure out what's going on.

@csantos42  Want to take this?

**Comment by Shmew** [comment]
I was able to reproduce the error without too much code [here](https://codesandbox.io/s/cocky-shaw-kvj2e?file=/src/App.js).

You'll see that it works without issue until the second atom value is incremented. There's a section in the App.js that you uncomment and it will show that the functions themselves work fine.

**Comment by csantos42** [comment]
Thanks for the repro @Shmew ! Will look into and fix asap

**Comment by JerryLeeCS** [comment]
What's the status on this issue?

**Comment by drarmstr** [comment]
There were some bug fixes for this in recent releases.  Please re-open if it occurs with version 0.7.5 or later.
