### ISSUE TITLE
Selector is not updated when atom changes

### ISSUE THREAD

**Issue by vesai** [facebookexperimental/Recoil#1072]
Scenario
---------
1. Create atom with promise in default value. This promise must be resolved after long period (or never)
2. Create selector that get value from this atom and return it
3. Create component that show value of atom and another one for selector
4. Change atom value before atom's default promise is resolved

Expected behavior
------------------
Atom and selector value updated when atom value is changed

Current behavior
----------------
Atom value is changed but selector wait for resolving atom's default promise and then show new atom value. It can be critical when you have promise that never resolves.

Example
---------
We have default atom value: promise, that resolves after 5 seconds with "timeout" string.
We have button that set value "value" for atom.
https://codesandbox.io/s/quirky-robinson-hlmb1?file=/src/index.js

**Comment by csantos42** [comment]
Thanks for reporting and for providing sandbox link-- will look into this bug soon and provide an update
