### ISSUE TITLE
Recoil not working in internet explorer 11

### ISSUE THREAD

**Issue by 1omercohen** [facebookexperimental/Recoil#1073]
does recoil supports IE ?
![image](https://user-images.githubusercontent.com/14128432/122076979-02f90f80-ce04-11eb-95fc-1233b3a461cb.png)

**Comment by mallchel** [comment]
Currently, many libraries move from es5 target build. There are many reasons why. But if you need to support old browsers, you can transpile it yourself

**Comment by 1omercohen** [comment]
how? 
I use webpack and babel

**Comment by jonbnewman** [comment]
> how?
> I use webpack and babel

https://webpack.js.org/configuration/target/

**Comment by csantos42** [comment]
At this time we do not support ES5 (https://recoiljs.org/docs/introduction/installation/#es5-support), so you would have to set up your own build pipeline as suggested here and in docs page
