### ISSUE TITLE
waitForAll and other wait helpers should never freeze values

### ISSUE THREAD

**Issue by dm-gh** [facebookexperimental/Recoil#1074]
I am working with 3d models that I load inside recoil selectors and render with react-three-fiber. When added on scene react-three-fiber wants to patch these models with its own properties so all selectors that load 3d models should have 'dangerouslyAllowMutability' flag, or else scene crashes.
To speed up loading time I've wrapped a bunch of models in waitForAll function. Models now load simultaneously but after they load scene crashes with error. `Cannot add property __r3f, object is not extensible`
After some digging I've discovered that waitForAll function implemented with selectorFamily and as a result wraps it return value in Object.freeze.
If waitForAll is a selectorFamily it would be logical to have the ability to pass dangerouslyAllowMutability flag to it

**Comment by drarmstr** [comment]
We discussed and think the right thing to do is for the `waitFor*` helpers to never freeze, since the underlying selectors/atoms will already have done that if necessary.
