### ISSUE TITLE
releaseNodesNowOnCurrentTree should only be called at the end of a batch

### ISSUE THREAD

**Issue by nikhilag** [facebookexperimental/Recoil#1077]
In an example project for my tsdx based library, I am getting the following warning after upgrading to Recoil 0.3.1:-

> releaseNodesNowOnCurrentTree should only be called at the end of a batch
![image](https://user-images.githubusercontent.com/54072321/122642321-85950e00-d127-11eb-94c1-0eff6d40d149.png)

Coulc someone please explain what this warning means and how I could fix it? Thanks.

**Comment by dsboo** [comment]
i also got this message.

in my case, i call atom set function in effects_UNSTABLE. onset

```
const uploadFileListState = atom<File[]>({
    key: 'uploadFileListState',
    default: [],
    effects_UNSTABLE: [
        ({ onSet, setSelf, trigger }) => {
            onSet((newState) => {
                console.log('CCCCCCCCCCCCCCCCCC' + newState);
                otherAtomSetFunc(2);
            });
        }
    ]
});
```

i intend update other atom value from origin atom updated. like event chaining

**Comment by nikhilag** [comment]
Thanks for sharing this info @dsboo 
Figured out that it was happening in my case because I was setting recoil state inside `useRecoilTransactionObserver_UNSTABLE`
Fixed it by setting local state and then setting the atom value with the help of `useEffect`

**Comment by drarmstr** [comment]
> i also got this message.
> 
> in my case, i call atom set function in effects_UNSTABLE. onset
> 
> ```
> const uploadFileListState = atom<File[]>({
>     key: 'uploadFileListState',
>     default: [],
>     effects_UNSTABLE: [
>         ({ onSet, setSelf, trigger }) => {
>             onSet((newState) => {
>                 console.log('CCCCCCCCCCCCCCCCCC' + newState);
>                 otherAtomSetFunc(2);
>             });
>         }
>     ]
> });
> ```
> 
> i intend update other atom value from origin atom updated. like event chaining

Setting other atoms from an Atom Effect is not currently supported.  Depending on your requirements you can consider a writeable selector wrapper, `useRecoilCallback()`, or `useEffect()` to achieve updates to multiple atoms.

**Comment by artygrand** [comment]
In 0.4.1 I also have this error. but I set data to the current atom
```js
const invoice = atom({
    key: 'invoice',
    default: {},
    effects_UNSTABLE: [
        ({onSet, setSelf}) => {
            onSet(invoice => {
                const total = invoice.products.reduce((sum, prod) => sum + prod.price * prod.qty, 0);
                setSelf({ ...invoice, total });
            });
        },
    ],
});
```

**Comment by drarmstr** [comment]
> I am also getting this error with 0.4.1 while updating the current atom. Should this issue be reopened @drarmstr?

Hmm, if you're getting an error setting the atom itself then please open a new issue with a reproducer.  The example above unconditionally calls `setSelf()` for each `onSet()`, though this shouldn't have an infinite loop since an effect shouldn't call `onSet()` for changes made by the same effect.  As an aside, this doesn't seem like the best design pattern since there will always be some delay or double render and potential for rendering components when the invoice total has not been set yet.  The invoice total could instead be a selector for derived state based on the atom.
```jsx
const invoiceState = atom({
    key: 'invoice',
    default: null,
});

const invoideTotalState = selector({
    key: 'invoice total',
    get: ({get}) => get(invoiceState)?.products.reduce((sum, prod) => sum + prod.price * prod.qty, 0),
});
```
