### ISSUE TITLE
Duplicate atom key when i use Nextjs Framework 

### ISSUE THREAD

**Issue by neerajcodes** [facebookexperimental/Recoil#1078]
### Here is my error with Nextjs Framework 
 This error comes in my console 
```

Duplicate atom key . This is a FATAL ERROR in
production.

```
Any solution of this problem

**Comment by nikhilag** [comment]
This seems to be a duplicate of https://github.com/facebookexperimental/Recoil/issues/733

**Comment by csantos42** [comment]
Closing in favor of duplicate #733 -- see that issue for a workaround and discussion
