### ISSUE TITLE
Initial read on the atom value triggers another render

### ISSUE THREAD

**Issue by denniscual** [facebookexperimental/Recoil#110]
First of all, thank you for this wonderful library. I just encountered some behaviour when trying to profile my app through reloading it. It triggers extra re-rendering to the Component when using `useRecoilValue` hook. The component doesn't update the state. It's just reading the value. And also, the Component already captures the default value set on the atom on the first render. I assume the re-render happens when the Component subscribes, via the hook, to the atom value and `Batcher` queues an update. But why does it need if the Component already gets it on the first place? Does it mean all of the subscribed Components to the atoms will have this behaviour?

**Comment by acutmore** [comment]
Hi @denniscual.  Possible duplicate of #75. If you using `<React.StrictMode>` React will render components twice in development to help catch bugs.

**Comment by denniscual** [comment]
Cool, I didn't see it.
