### ISSUE TITLE
Testing a component that mutates state produces "not wrapped in act" warnings

### ISSUE THREAD

**Issue by thebalaa** [facebookexperimental/Recoil#1101]
Trying to write a simple unit test for a component that sets some recoil state. Tests passes but get the warning below regardless if my mutating calls are wrapped in an `act`:

Any suggestions on how to avoid this warning?
```

    console.error
      Warning: An update to Batcher inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at Batcher (/code/node_modules/recoil/cjs/recoil.js:3624:3)
          at RecoilRoot_INTERNAL (/code/node_modules/recoil/cjs/recoil.js:3724:3)
          at RecoilRoot (/code/node_modules/recoil/cjs/recoil.js:3875:5)

```

**Comment by zawi99** [comment]
I had the same problem. A working solution/workaround (not sure) for me was to use `await/async` together with `act`:
`
await act(async () => {/* some actions */});
`

However, I'm not 100% sure why it worked. I suspect that changes to recoil state happen outside of React call stack and this is why `act` warning is shown.

**Comment by drarmstr** [comment]
It can be hard to say without specific reproducers.  But yes, if the actual state change call is done from an async callback or otherwise not part of the synchronous stack of the act() then you can have this problem.  Also try putting the act() around the specific setter.
