### ISSUE TITLE
how to share atoms and selectors between projects

### ISSUE THREAD

**Issue by 1omercohen** [facebookexperimental/Recoil#1102]
## development consult issue
I have two project, they have common components with the same state.
can I share atoms and selector between them like module federation ?
[Module Federation](https://webpack.js.org/concepts/module-federation/)

**Comment by mondaychen** [comment]
I'm not familiar with Module Federation, but I think the answer is yes. Just like react components, you can re-use your atoms and selectors in different projects. To be clear, the data will be stored separately in each project.
