### ISSUE TITLE
WriteOnlySelector

### ISSUE THREAD

**Issue by eaubin** [facebookexperimental/Recoil#1114]
Hi, I'm experimenting with Recoil and find I sometimes want to create a update only  selector with a different type than the state it's modifying. E.g. something like

```ts
export const xsAtom = atom<string[]>({
  key: "xsAtom",
  default: [],
});

type ListAction =
  | { type: "add"; value: string }
  | { type: "remove"; value: string };

export const updateXs = selector<ListAction>({
  key: "xsUpdater",
  get: ({ get }) => {
    throw "Do not call";
  },
  set: ({ set, get }, newValue) => {
    if (newValue instanceof DefaultValue) {
      // ...
    } else {
      const { type, value } = newValue;
      const xs = get(xsAtom);
      if (type === "add") {
        set(xsAtom, [...xs, value]);
      } else if (type === "remove") {
        set(
          xsAtom,
          xs.filter((x) => x !== value)
        );
      }
    }
  },
});
```

I'd like to omit `get` as it's return type is constrained to be a ListAction. Could a WriteOnly selector variant be added?

**Comment by drarmstr** [comment]
#806 Proposes distinct types for the `get()` and `set()` operations of a selector.  But, if you only need to set, then a selector is overkill and you should be able to just use [`useRecoilCallback()`](https://recoiljs.org/docs/api-reference/core/useRecoilCallback), or the new `useRecoilTransaction_UNSTABLE()` that's still in flight.
