### ISSUE TITLE
Objects are Read only

### ISSUE THREAD

**Issue by WhoAdarshPandya** [facebookexperimental/Recoil#112]
First of all, thank you for this **wonderful** library. I got a issue when **updating** **object** inside **array** . Saying objects are **Read Only**, I used **useRecoilState** 's set method , but **objects** are read-only.
I appreciate your answer
Thanks

**Comment by incepter** [comment]
Could you please provide a sample of your code ? I managed to work with objects and arrays. So to be able to help, we need a sample of your code.

**Comment by drarmstr** [comment]
The state from atoms and selectors is meant to be immutable.  Selectors must be pure functions, values may be cached, etc.  To help enforce safety, objects are frozen.  However, you can use the `dangerouslyAllowMutability: true` option to disable this.

**Comment by WhoAdarshPandya** [comment]
> Could you please provide a sample of your code ? I managed to work with objects and arrays. So to be able to help, we need a sample of your code.

````
//setTodos is useRecoilState method
setTodos(prev => prev.map(todo =>{
         // todo_id comming from function
         if(todo.id === todo_id)
          {
            todo.completed = !todo.completed
          }
          return todo
})
)

**Comment by x4080** [comment]
Yes I found read only too, is it inefficient for large array to recopy all the times ?
