### ISSUE TITLE
Missing `initializeState` property in `RecoilRoot` when using `override` property

### ISSUE THREAD

**Issue by rtritto** [facebookexperimental/Recoil#1126]
Using `RecoilRoot`, with `initializeState` and `override` properties,
```JSX
<RecoilRoot
  initializeState={({ set }) => {
    ...
  }}
  override={false}
>
  ...
</RecoilRoot>
```
produces in Visual Studio Code IntelliSense:
```
Type '{ children: Element; override: false; initializeState: ({ set }: { set: any; }) => void; }' is not assignable to type 'IntrinsicAttributes & PropsWithChildren<RecoilRootProps>'.
  Property 'initializeState' does not exist on type 'IntrinsicAttributes & { override: false; } & { children?: ReactNode; }'.ts(2322)
```
#### Recoil Version: `0.3.1`

**Comment by drarmstr** [comment]
This is an expected error because It is not valid to both disable `override` for `<RecoilRoot>` and `initializeState` at the same time.  This is because it could lead to ambiguities if the local `initializeState` should be used or not if there was an outer `<RecoilRoot>` it inherits from.

**Comment by mildfuzz** [comment]
The problem with this as expected behaviour is that is creates unexpected results when using libraries that also use a `RecoilRoot` with `initialiseState` set. The outer state gets ignored, and it's not obvious what the issue is
