### ISSUE TITLE
can't have updated recoil state on tests

### ISSUE THREAD

**Issue by OrMenashe** [facebookexperimental/Recoil#1128]
i am using react-native 0.64.1
react 17.0.1
recoil 0.3.1
for testing i am using
 jest 27.0.4
@testing-library/jest-native 4.0.1,
@testing-library/react-native 7.2.0

i have a component that uses recoil state, when pressing a button in it, it updates an atom.
i am trying to write tests for that behavior. i want to stimulate a press and make sure the state was changed to the correct value.
i have tried to use but it seems that the state didn't change.

this is my test:
```JS
const activationButton = mockComponent.getByText('activate show')

fireEvent.press(activationButton)

const snapshot = snapshot_UNSTABLE()
expect(snapshot.getLoadable(appCoverState).valueOrThrow().showCover).toBe( true)
```

i think that maybe i am having a race condition - the state doesn't get changed before the snapshot_UNSTABLE gets executed
do you think am i right with my speculation?
if so, is there any way of making a call after the state has changed?

**Comment by drarmstr** [comment]
Creating a snapshot via `snapshot_UNSTABLE()` will create a stand-alone snapshot and store of state.  It doesn't look like there is any way the button press handler would be hooked up to mutate that state.  Even if it did, it would mutate to a new snapshot as each snapshot represents immutable atom state.  Checking for the value of an atom in a snapshot immediately after creating a fresh snapshot will always provide just the default value or value initialized with an atom effect.

**Comment by OrMenashe** [comment]
@drarmstr thank you for your reply.
i've already went over the provided example, but it doesn't help on my case.
so if i got it right, you are actually saying that i don't have a way to test UI component behavior according to state/atom changes?

**Comment by OrMenashe** [comment]
@drarmstr can you please reply?

**Comment by drarmstr** [comment]
Creating a fresh Snapshot with `snapshot_UNSTABLE()` is immutable and not connected to the React UI, so it won't reflect button presses.  But, you can absolutely use Jest for unit tests using React.  You'll need to make sure you are setting up a `<RecoiRoot>` in your unit test and the button is contained within that.  After your button press event the state of the atom will be updated.  A useful pattern for that is to also put in your test React components a component which just renders the value of the atom.  Check out [`renderElements()`](https://github.com/facebookexperimental/Recoil/blob/master/src/testing/Recoil_TestingUtils.js#L130) Then, you can use jest to do something like:
```jsx
const container = renderElements(<Your Components Which Have Button and Render Atom State/>);
expect(container.textContent).toBe('EXPECTED VALUE');
```
See example unit tests in the source such as [`Recoil_atom-test.js`](https://github.com/facebookexperimental/Recoil/blob/master/src/recoil_values/__tests__/Recoil_atom-test.js)
