### ISSUE TITLE
set Error in socket event, cannot set data to atom

### ISSUE THREAD

**Issue by 1omercohen** [facebookexperimental/Recoil#1129]
hello guys :)

I do not understand what the error in the next code I did:

my index.js react project
`
import React from "react"
import ReactDom from "react-dom"
import App from "./App"
import "./index.css"
import {RecoilRoot} from "recoil";
import { initialize } from "./state/init"

ReactDom.render(
    RecoilRoot initializeState={initialize}
        App
    RecoilRoot,
    document.querySelector('#root')
)
`
the initialize fruntion is :=>
`
import IO from 'socket.io-client';
import { SocketHandler} from '../../state'

export const initialize = ({set}) => {
    const socket = IO("/client");
    socket.on("connect", () => {
        set(SocketHandler, socket.emit)
        console.log("we start listen ")
    })
}
`
the error I got is : =>
Recoil Snapshots only last for the duration of the callback they are provided to. To keep a Snapshot longer, do this:
  const release = snapshot.retain();
  try {
    await useTheSnapshotAsynchronously(snapshot);
  } finally {
    release();
  }

This is currently a DEV-only warning but will become a thrown exception in the next release of Recoil.

I made some debugging to understand witch row is fallen and is that row
set(SocketHandler, socket.emit)

for atom I can set to function like emit and use that where I what ?
if not do you have better idea for solution ?

**Comment by drarmstr** [comment]
The error message is saying that Snapshots are normally only valid for the lifetime of the initial callback execution unless you explicitly retain it longer.  For example, if you obtained a `Snapshot` from `useRecoilCallback()` and wanted to reference it after that callback completed then you need to call `retain()` and `release()`.  

However, in this case the Snapshot is coming from the `initializeState` prop callback.  This is a synchronous initialization, so you should not try to asynchronously set state during the synchronous initialization.  If you would like to initialize the initial state of an atom based on an asynchronous query you have a few options:

* Set the atom `default` to a `Promise`, which can query for the initial value
* Set the atom `default` to an asynchronous selector, which can query for the initial value
* Use an [Atom effect](https://recoiljs.org/docs/guides/atom-effects#initialize-with-promise) to initialize the atom with a `Promise`

With the above options the atom will be in a "pending" state until the async initial value resolves.  You can provide a placeholder for any components that use this pending state via React "Suspense".  

Another alternative would be to provide an initial placeholder as the `default` value which will be seen on initial render.  Then, wither with `useEffect()` or with an [Atom effect](https://recoiljs.org/docs/guides/atom-effects#asynchronous-setself) you can asynchronously set the value of the atom when available.

**Comment by 1omercohen** [comment]
@drarmstr did you close the topic, ok understand about the lifetime of the callback.
but you do not being any solution, atom effect is not relevant for socket.
I still get this error even when I get event from my server side to client.
can not set data to atom from socket event
`
export const initialize = ({set, reset}) => {
    const socket = IO("/support");
    socket.on("initialize", (data) => {
        console.log(data)
        set(ChatState, data.chats);
    })
    set(SocketHandler, () => (...args) => socket.emit(...args));
}
`
console the data from server but to set the data to atom. is put the error.

**Comment by drarmstr** [comment]
> @drarmstr did you close the topic, ok understand about the lifetime of the callback.
> but you do not being any solution, atom effect is not relevant for socket.
> I still get this error even when I get event from my server side to client.
> can not set data to atom from socket event
> `export const initialize = ({set, reset}) => { const socket = IO("/support"); socket.on("initialize", (data) => { console.log(data) set(ChatState, data.chats); }) set(SocketHandler, () => (...args) => socket.emit(...args)); }`
> console the data from server but to set the data to atom. is put the error.

The point is you cannot initialize or set the atom state from your Socket callback there, as it occurs after the synchronous initialization is complete, i.e. from the Socket.on() callback.  Please see the previous comment for alternative solutions.  For example, you could statically set the atom, through initialization, default, or effect, to a Promise that resolves when the Socket is initialized.

**Comment by 1omercohen** [comment]
that I understand, why I should do that ?
if you was instead me, where do you listen to all events and set the right atom each time ?
