### ISSUE TITLE
Should we create .flowconfig?

### ISSUE THREAD

**Issue by leushkin** [facebookexperimental/Recoil#115]
How do you type check your codebase? Now I can write literally everything and it won't be typechecked

**Comment by davidmccabe** [comment]
Please go ahead and create one! Thanks for pointing this out. A good starting place might be the config for draftjs, since that's another project that originates in the same repo inside FB.

https://github.com/facebook/draft-js/blob/497a47879d6172adb14f88d492781880471b8f4d/src/.flowconfig
