### ISSUE TITLE
selector caching for http errors

### ISSUE THREAD

**Issue by Art2058** [facebookexperimental/Recoil#1157]
```typescript
export const searchFlagmentState = atom({
  key: 'SearchFlagmentState',
  default: ''
})
export const searchItemsState = selector({
  key: 'SearchItemsState',
  get: async ({ get }) => {
    const flagment = get(searchFlagmentState)
    try {
      const { data } = await searchItems(flagment)
      return data
    } catch (error) {
      // Cancel or Http Error
      throw error
    }
  }
})
```

input 'a' -> `setSearchFlagment('a')` -> Cancel or Http Error -> `useRecoilValueLoadable(searchItemsState)` -> hasError
Next input 'b' -> ... -> hasValue
Next input 'a' -> ... -> hasError

How to clear caching for errors?

**Comment by drarmstr** [comment]
Here is a pattern for manual query refreshes: https://recoiljs.org/docs/guides/asynchronous-data-queries#query-refresh
