### ISSUE TITLE
Solution for near-global atom use in atomFamily params

### ISSUE THREAD

**Issue by awdyson** [facebookexperimental/Recoil#1161]
I'm curious if there's a way for `atomFamily`s to rely on an `atom` without needing to fetch/pass it in each consuming component.

Here's an example of a code pattern I find myself repeating all over:
```tsx
const brandId = useRecoilValue(brandStore.currentBrandId);
const products = useRecoilValue(productStore.productList({ brandId }));
```
`currentBrandId` is an `atom` because it's not uncommonly user-changed.
`productList` is an `atomFamily` to deal with things like data refreshes/updates.

We're already saving `currentBrandId` in `sessionStorage` as part of its set method.
It'd be nice to register a listener on `sessionStorage` to keep the logic together and smaller.

**Comment by rbaxter08** [comment]
Seems like you could accomplish this with a `selectorFamily` https://recoiljs.org/docs/api-reference/utils/selectorFamily/

```ts
// import currentBrandId Atom
import { currentBrandId } from ...

const currentProductList= selector({
  key: 'current-product-list',
  get: ({get}) => {
    const brandId = get(currentBrandId)
    // logic from "productList" to return product list for the brandId
  }
});
```
