### ISSUE TITLE
Switch to Flow strict?

### ISSUE THREAD

**Issue by FezVrasta** [facebookexperimental/Recoil#1167]
Hi, is there any plan to switch the code-base to the Flow strict mode? Being already well typed I don't think it should be a lot of work.

**Comment by drarmstr** [comment]
Recoil already uses the `@flow strict-local` mode, which is basically the same as strict, just doesn't require dependencies to be strict.

**Comment by FezVrasta** [comment]
The problem with  that is that I can't use strict in my own project because it won't allow me to import Recoil.

**Comment by drarmstr** [comment]
Hmm, the issue is that Recoil also depends on other modules which in turn are not pure strict mode.  Can your project also use `strict-local` to avoid this significant issue with Flow strict?

**Comment by FezVrasta** [comment]
I could use strict-local but I felt like strict was the suggested approach by the Flow team. It just feels more natural to be able to use strict across modules that are both strictly typed.
