### ISSUE TITLE
snapshot_UNSTABLE does not read atom's value

### ISSUE THREAD

**Issue by protium-dev** [facebookexperimental/Recoil#1178]
When trying to assert the value of an atom in tests, I always get the default value of the atom.
Example
```ts
export const CurrentRouteState = atom({
  key: 'CurrentRoute',
  default:'',
});

function Test() {
  const setCurrentRoute = useSetRecoilState(CurrentRouteState);
  useEffect(() => {
    setCurrentRoute('testing');
  }, [setCurrentRoute]);
  return <h1>TEST</h1>
}
```

in tests
```ts
export const runAllPromises = (
) => new Promise((resolve) => setTimeout(resolve, 0));

...
mount(
<RecoilRoot><Test /></RecoilRoot>
);
// Run useEffect
await runAllPromises();
expect(
        snapshot_UNSTABLE().getLoadable(CurrentRouteState).valueOrThrow(),
      ).toEqual('testing'); // value is still null
```

setup:
- Enzyme
- Jest
- React 17

**Comment by drarmstr** [comment]
`snapshot_UNSTABLE()` is a factory which provides a fresh Snapshot, so it would be expected that it always provides default values.

If you want to test the values for some test Recoil Root, then you could get a snapshot from that root using the `useRecoilSnapshot()` hook.  What Recoil often does in unit tests is include a component which renders the value of an atom and then just checks the textContents of the rendered container.  Check out some examples here: https://github.com/facebookexperimental/Recoil/blob/master/src/recoil_values/__tests__/Recoil_atom-test.js
