### ISSUE TITLE
Testing atom state in Jest (React Testing Library) after event inside the component.

### ISSUE THREAD

**Issue by timbergus** [facebookexperimental/Recoil#1194]
Hi all. I'm trying to test a component called `CSV`, which has two radio buttons that change the value of an atom. I have created the following test.

```javascript
import { fireEvent, render } from '@testing-library/react'
import { RecoilRoot, snapshot_UNSTABLE } from 'recoil'
import { csvExportTypeAtom } from '../csv.atoms'

describe('CSV should', () => {
  test('select the first radio button.', () => {
    const { getByTestId } = render(
      <RecoilRoot>
        <CSV />
      </RecoilRoot>,
    )
    const component = getByTestId('radio_button_marker_standard')
    fireEvent.click(component)
    const snapshot = snapshot_UNSTABLE()
    expect(snapshot.getLoadable(csvExportTypeAtom).valueOrThrow()).toBe('standard')
  })
})
```

I get the idea that I'm getting a snapshot from a different atom due to the `RecoilRoot` context, so I don't see the updated value after the click event.

<img width="610" alt="Screenshot 2021-08-27 at 18 37 04" src="https://user-images.githubusercontent.com/1750734/131160295-60109f71-e320-4035-9496-41ad1a44c059.png">

How can I access the atom used inside of the `RecoilRoot` that receives the event?

Is there a better way to do this?

Please, help! I'm new to Recoil, and this is driving me crazy 🙇‍♂️

**Comment by drarmstr** [comment]
snapshot_UNSTABLE() is a factory which provides a fresh snapshot, so all atoms will have the default or initialized value. For testing the result of actions you can map() the snapshot with some transaction.  For testing the effect of React component actions you can use the useRecoilSnapshot() hook to get a snapshot for the current state of the <RecoilRoot>, or just read the atom state directly. Check out the example unit tests in Recoil_atom-test.js where we usually have some test component that renders the value of the atom of interest so we can just expect() the React container's textContent.

**Comment by timbergus** [comment]
Awesome! Thanks a lot. I will give it a try today.

**Comment by timbergus** [comment]
In the end, I have implemented an observer as explained [here](https://recoiljs.org/docs/guides/dev-tools). I pass the atom/selector to be observed and the `onChange` function to be called when the state changes.

```javascript
export const RecoilObserver = ({ element, onChange }) => {
  const value = useRecoilValue(element)
  useEffect(() => onChange(value), [onChange, value])
  return null
}
```

So I can pass a `jest.fn()` and check whatever I need from the returned value.

```javascript
const mockFunction = jest.fn()

const { getByTestId } = render(
  <RecoilRoot>
    <RecoilObserver
      element={myAtom}
      onChange={mockFunction}
    />
    <CSV />
  </RecoilRoot>,
)
```

And it works great 🙂 Thanks a lot @drarmstr.

**Comment by drarmstr** [comment]
Our "Testing" guide in the documentation could use some more approaches/examples/explanation.  This sounds like a useful addition?

**Comment by timbergus** [comment]
Sure! It would be really useful to test the state of the atoms/selectors used by a component because the user's action can be tested easily by observing the changes the component does in the state. If you want @drarmstr, I could add this solution to the documentation, illustrated with a simple example.
