### ISSUE TITLE
Test Suite Failing

### ISSUE THREAD

**Issue by khpatel4991** [facebookexperimental/Recoil#120]
I cloned the repo to play around and try to convert it to typescript.

As a first step, I built the package, it worked fine, then I ran `yarn test` and 43 tests failed out of total 153

I checked the GitHub actions config, and it doesn't seem to run all tests.

Is this expected?

**Comment by claudiopro** [comment]
Yes, this is consistent with the results I had with #81. The Node.js CI GitHub action does not run `yarn test` at the moment.
