### ISSUE TITLE
Is it possible to initialise atomFamily multiple values at once?

### ISSUE THREAD

**Issue by sergiybabich** [facebookexperimental/Recoil#1206]
For example, I have an atomFamily which contains scores for cities and I access them by id. So, putting 1600 values to this family takes about 70-90ms, using loop:

```js
for (const city of cities) {
  set(cityScore$(city.id), city.rating);
}
```

But if I create simple map for such values, it takes like 0.3 − 0.4 ms:

```js
for (const city of cities) {
  map[city.id] = city.rating;
}
```

So, is there a way to initialise atomFamily values at once to speed up this initialisation process?

**Comment by christiankaseburg** [comment]
The useTransaction API is performant. Take a look at the docs https://recoiljs.org/docs/api-reference/core/useRecoilTransaction/.

**Comment by drarmstr** [comment]
Atom families can also accept a function as the default which takes the family parameter and can be used to initialize the entries so you don't need to do a separate initialization process:

```jsx
const cityScoresStates = atomFamily({
  key: 'CityScores',
  default: cityID => cities.get(cityID).rating,
});
```

**Comment by kubejm** [comment]
> Atom families can also accept a function as the default which takes the family parameter and can be used to initialize the entries so you don't need to do a separate initialization process:
> 
> ```js
> const cityScoresStates = atomFamily({
>   key: 'CityScores',
>   default: cityID => cities.get(cityID).rating,
> });
> ```

If `cities` came in as a prop to a React component, what would be the appropriate pattern for initializing an `atomFamily` with those objects?

From the documentation, it would suggest that you would commonly define an `atomFamily` outside the scope of a component (potentially within another file, i.e. store.ts), so `cities` would not be accessible in the function passed to default.

In my recent investigation, it would seem you could use `initializeState` on `<RecoilRoot />`, but I believe that would put you in the same situation as described in this issue and require invoking `set` in a loop on every item. 
Alternatively, it looks like Atom Effects are a potential option, but the documentation seems to suggest one should place the data in local/remote storage and subsequently access the storage to set the atoms. However, I would prefer not to have to load my prop into storage just for initialization of an `atomFamily`, but rather initialize the atoms directly with the prop passed to my component.

**Comment by drarmstr** [comment]
Yes, if your initial state comes in as a prop, then `initializeState` would be appropriate.  Using Atom Effects would generally require the state to also be initialized outside of React render function scope so you wouldn't have access to props.  In general, it is setup this way because the set of atoms are created and exist independent of the React component tree to allow for sharing. That means that atoms should be initialized either outside of the React component tree or as part of the `<RecoilRoot>` initialization in order to avoid race conditions with which React component happened to render using the atom first.  That said, I am investigating the pattern of allowing atoms to initialize based on prop values with the upcoming state synchronization add-on library.  To keep things consistent, of course, this would still be based on the state of props at the `<RecoilRoot>` level, or the component setting up the synchronization hooks, not the component rendering the atom.  But, sounds like that's exactly what you're looking for.  Anyway, stay tuned if that's of interest.  In the meantime, is the `useRecoilTransaction()` approach more performant for you if `intializeState` is too slow?

**Comment by sergiybabich** [comment]
@kubejm @drarmstr thank you for your suggestions.

To clarify this case a bit — data coming from API and is part of page logic. So in my solution I have a selector with setter where I put values to `atomFamily` normalizing data in this way.

So I am not sure if `initializeState` can help me here, as page is a few levels lower than `RecoilRoot`.

Will take a look at `useRecoilTransaction()` then.

**Comment by kubejm** [comment]
> I am investigating the pattern of allowing atoms to initialize based on prop values with the upcoming state synchronization add-on library

I am definitely interested to explore that pattern when it becomes available and seems like it will lend itself well to what I'm experimenting with.

> In the meantime, is the useRecoilTransaction() approach more performant for you if intializeState is too slow?

Sounds like my use case is slightly different than @sergiybabich's. I'm playing with rendering a matrix (i.e. 2d array) where each element is an atom, so I'm iterating across the entire matrix within `initializeState` and invoking `set` for each element. The performance is alright when staying below 1000 elements, but I'm noticing as the size of the matrix increases the performance gets exponentially worse and several thousand elements is ill performant. For example, `<RecoilRoot>` takes about 200ms to process 1000 elements and `<RecoilRoot>` takes about 3400ms to process 5000 elements on my machine.

I don't mean to detract from @sergiybabich's original issue though. I thought it seemed more closely related. 

Appreciate your help!

**Comment by drarmstr** [comment]
> > I am investigating the pattern of allowing atoms to initialize based on prop values with the upcoming state synchronization add-on library

> I am definitely interested to explore that pattern when it becomes available and seems like it will lend itself well to what I'm experimenting with.

See #1252 for a preview of this pattern.

**Comment by drarmstr** [comment]
The [Recoil Sync Library](https://recoiljs.org/docs/recoil-sync/introduction) documentation is now published.

**Comment by jisuo** [comment]
I'm currently using this dispatcher pattern in the app: https://github.com/GeoffCox/recoil-examples/tree/master/dispatcher-tutorial

So I have multiple useRecoilCallback() in the dispatcher where I make API calls and then I do for-of loops to populate atomFamilies. Everything works nice and I got nice separation of code I think.

I've also looked into increasing the speed when inserting large numbers of items into atomFamily, and `useRecoilTransaction_UNSTABLE` looked interesting. Problem is I cannot use it in the useRecoilCallback() in my dispatcher, which means I would have to split the logic and move the transaction code into a component. So I'm not sure I want to use it in that case. But it should improve performance.

Next is the atom family default pattern:

```
const cityScoresStates = atomFamily({
  key: 'CityScores',
  default: cityID => cities.get(cityID).rating,
});
```

My atomFamily is in a separate store file which means that the `cities` Map would have to be in an atom or similar? Or do I have to refactor the dispatcher and move the atomFamily and Map<City> definition into that file?

So the other options would be:
1. API call in `useRecoilCallback()` in dispatcher, populate a simple Map (fast), insert the map into an atom (one time, fast)
2. atomFamily would get default value from atom
3. How about updating the atomFamily, how would it update the key/value in the Map (in the atom)? 

I'm constantly trying to find the optimal usage of recoil. :)

**Comment by drarmstr** [comment]
If you are storing the map in a single atom then using an `atomFamily()` which pulls the default from that atom will be separate state.  So, updating it would update its own value but leave the atom with the map of defaults alone.  If that map just is meant to contain the defaults, then that's fine.  You could also use a writable `selectorFamily()` to read and write to that atom in which case it would no longer just contain the defaults but the actual current state.  In that case, however, updates to any family member would update the single atom with the map and cause subscribers to any other member to also re-render.  I don't know your project layout, but sounds simpler to just have the `atomFamily()` default reference the map of defaults imported from whatever file.  Of course, if they come from a prop then something like the Recoil Sync library could help with lazy initialization.  And `useRecoilTransaction_UNSTABLE()` is also an option for bulk atom updates and can also be used to implement many reducer/dispatcher patterns, downside it doesn't currently support selectors.

Sounds like there are a few options, depending on your situation, so closing this issue for now; but we can re-open a more specific issue if needed.

**Comment by douglasg14b** [comment]
@drarmstr By chance can you augment your explanation with a few examples?

I'm brand new to this project, and it has me scratching my head.

**Comment by chriszrc** [comment]
Similar to @douglasg14b, I also felt like complete examples were lacking. It would appear that unlike regular atoms, atomFamilys are intended to be initialized with values from within the react app, which makes total sense, since the whole point of these families is set values dynamically. But what if we want to start off the app pre-populated with some atoms in the family to begin with? Perhaps from a fetch call? Is there a way to do that? 

I often initialize atoms with data from fetch requests, and I thought that would be an option here, but I can't determine the format or even if that is supported-
