### ISSUE TITLE
Recoil memory not freed on RecoilRoot unmount (memory leak)

### ISSUE THREAD

**Issue by HaveSpacesuit** [facebookexperimental/Recoil#1220]
When I unmount the `<RecoilRoot>` from the DOM, the memory in Recoil state is not cleaned up.

I initialize a large string as a form definition fetched from the server and save it as a Recoil atom.

```ts
const [formDefinition, setFormDefinition] = useRecoilState(formDefinitionState);

useEffect(() => {
  async function initializeFormDefinition(): Promise<void> {
    const formDefinition = await getFormDefinition(item);
    setFormDefinition(formDefinition)
  }

  void initializeFormDefinition();
}, [items, getFormDefinition, setFormDefinition])
```

If I take a memory heap snapshot, I can see this large object in the heap, which is the form definition.

![image](https://user-images.githubusercontent.com/15036346/133676757-c93309f6-7716-4d15-bd75-672b7632b253.png)

If the user closes the element containing the form, the `<RecoilRoot>` is no longer in the DOM. If the user opens and closes the form element four times, I'll see four large objects in the heap:

![image](https://user-images.githubusercontent.com/15036346/133676956-1962a27b-cd0b-4226-8b02-8af7c26e371e.png)

For smaller objects, this isn't a problem. But each of these form definitions can be quite large. If the user updates the state a few times by opening and closing the element, the browser memory usage spikes, and the browser can freeze up.

This may be a similar issue to #1040, but theirs is specific to React Native, and this is happening in a web browser.

Using recoil 0.4.1.

**Comment by mondaychen** [comment]
Any reason you cannot use [async selector](https://recoiljs.org/docs/api-reference/core/selector#asynchronous-selectors) for your use case?

**Comment by HaveSpacesuit** [comment]
> Any reason you cannot use [async selector](https://recoiljs.org/docs/api-reference/core/selector#asynchronous-selectors) for your use case?

Is that likely to help? I use that in some places where it is simple to update the state based on inputs, but with this particular piece of state, it is easier to allow the user to imperatively update the state. (E.g., select a value from the dropdown, we need to fetch the updated form definition from the server.)

**Comment by HaveSpacesuit** [comment]
After some investigation, I don't think the blame for this is on Recoil. I suspect it is coming from the forms library I'm using, keeping all [old jquery references around](https://developer.chrome.com/docs/devtools/memory-problems/heap-snapshots/#uncover_dom_leaks), and thus prevent the garbage collector from cleaning up the objects. The items I'm seeing in the memory heap are being kept in that library, and not in Recoil.

Closing the issue, thanks!
