### ISSUE TITLE
Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'

### ISSUE THREAD

**Issue by craigcosmo** [facebookexperimental/Recoil#1232]
I'm setting up the debug as I saw on recoil website

<img width="911" alt="Screen Shot 2021-09-19 at 3 11 55 PM" src="https://user-images.githubusercontent.com/538657/133920366-f963d4df-197d-4bfe-b155-a3790ada37d4.png">
<img width="580" alt="Screen Shot 2021-09-19 at 3 11 18 PM" src="https://user-images.githubusercontent.com/538657/133920373-aa94aff9-4ac2-4a57-8b42-38cc97f2c111.png">

<img width="897" alt="Screen Shot 2021-09-19 at 3 13 24 PM" src="https://user-images.githubusercontent.com/538657/133920406-37177ace-91e6-470b-8024-7835ecd9832f.png">

When I put the function debugobserver in the app, I got this error `Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'`

**Comment by BenjaBobs** [comment]
I think this is caused by a type error in your `DebugObserver` component. It should return a `React.ReactNode` rather than a `React.node`, which doesn't exist. I believe that is the reason typescript thinks your `DebugObserver()` returns a value of type `any`.

**Comment by craigcosmo** [comment]
Yea, I put React.ReactNode, Now I got another error
<img width="843" alt="Screen Shot 2021-09-20 at 12 34 38 AM" src="https://user-images.githubusercontent.com/538657/133937205-e3a78c45-b6c8-428b-a519-ade4ce7440dd.png">

**Comment by mondaychen** [comment]
`<DebugObserver>` is not meant to used as a wrapper for you `<App />`. 

The example from recoil website looks like this:

```
function MyApp() {
  return (
    <RecoilRoot>
      <DebugObserver />
      ... // this is your <App />
    </RecoilRoot>
  );
}
```

**Comment by craigcosmo** [comment]
you are right. that's a typo there. I fixed it, it works now.

**Comment by craigcosmo** [comment]
The log is not showing in the console.

my atom is like this
``` js
const uploadAtom = atom({
	key: 'tempfile',
	default: [],
})
export default uploadAtom
```

I use it like this
```
const PhotoList = () => {
	const [temp, setTemp]: any = useRecoilState(uploadAtom)
	const photos = ['1', '2']
	useEffect(() => {
		setTemp((atom) => {
			return [...photos]
		})
	},[])
}
```

With that debug component installed. I got no logs.

What am i missing ?
