### ISSUE TITLE
Turn a nested object into atoms and back again

### ISSUE THREAD

**Issue by sirganya** [facebookexperimental/Recoil#1268]
Is there a best practice for taking a state object from another application, breaking into individual atoms and reconstituting it again?

I have a theme object for a application 

```
{
  backgroundColor: "black,
  title: {
    fontSize: 12
    color: "red"
  }
  ...
}

```

that's quite large, stored remotely and needs to be read from and written to. How to  represent each key:value as an atom and preserve it's shape?

Any suggestions would be welcome.

**Comment by methodman7556** [comment]
Perhaps by using a theme selector to collect the individual attributes(background, title etc.) that you model as atoms

```
const themeSelector = selector({
   get: ({ get }) => {
      return {
         background: get(backgroundAtom),
         title: get(titleAtom) 
      }
   },
   set: ({set}, theme) => {
       set(backgroundAtom, theme.background),
       set(titleAtom, theme.title)
   } 
})
// Disclaimer: Syntax might be wrong
```

**Comment by drarmstr** [comment]
You may also want to consider [atom effects](https://recoiljs.org/docs/guides/atom-effects) or the upcoming [Recoil Sync library](https://recoiljs.org/docs/recoil-sync/introduction) if you want bi-directional syncing of this state.

**Comment by sirganya** [comment]
I decided on mapping the object to an atom family. As I'm using GraphQL and typescript mapping the object from the DB to the front-end code is pretty safe. I use an array as a param for the atom to map it's position in the object. `{ a: { b:val }} `becomes `atomFamily(val, [a, b]) `
