### ISSUE TITLE
Atoms initialised with defaultValue from an fetch-api selector behave differently after 'set' operation

### ISSUE THREAD

**Issue by rajeshbabu-oviva** [facebookexperimental/Recoil#1269]
I am currently working on a TODO app with API interaction. I have two atoms, one for tracking Query-Refresh and the other is List-Atom contains the TODO List from the server. 

The APIs are GET List, ADD Item, Delete Item.

The Atoms look like the following: 

```
export const triggerRefreshTodosAtom = atom({
  key: 'triggerRefreshTodosAtom',
  default: 0,
});

export const getTodosSelector = selector({
  key: 'getTodosSelector',
  get: async ({ get }) => {
    // Register 'triggerRefreshTodosAtom' as a dependency.
    get(triggerRefreshTodosAtom);

    try {
      const response = await getTodos();

      return response || [];
    } catch (error) {
      console.error(`getGreetingsSelector -> getGreetings() ERROR: \n${error}`);
      return [];
    }
  },
});

export const todosAtom = atom({
  key: 'todosAtom',
  default: getTodosSelector,
});
```

I have two components AddTodo and TodoList containing delete-button for each-todos. Both of them are in separate routes. Every time I add a Todo, on the success of the API call, I increment triggerRefreshTodosAtom in order to trigger the list update, which happens when I switch to the TodoList component route, as it is the dependency for the getTodosSelector.

Problem:
The real problem is when I try to do a _**set**_ on the todosAtom to track the deleted list-items locally without triggering a re-fetch of the query the AddTodo query-fresh logic no longer works. Meaning it no longer tracks the triggerRefreshTodosAtom updates to do a query-refresh.

If this is not a known problem, I can also try and create a codesandbox for the same.

**Comment by drarmstr** [comment]
I'm wondering if there are some complications by using these atoms from different "routes"?  Is going to a different route going to a different <RecoilRoot> or creating redundant atoms?  A codesandbox would be helpful.

**Comment by rajeshbabu-oviva** [comment]
I used the DebugTools to track the atom. On the initial fetch of the defaultValue from API. I see that the atom is named greetingsAtom_withFallback and once I do a local set on it, it changes to greetingsAtom.

Not sure if I am creating a redundant atom here. And my RecoilRoot is on the top level (ie) App, should I include it on the individual components loaded on the route ??

Its a bit edge scenario I ll try an create a sandbox to help you understand it better. Thanks in advance!!

**Comment by drarmstr** [comment]
If you have an atom with a default that is a selector, then under the hood Recoil will create a wrapper selector.  So, both `greetingsAtom` and `greetingsAtom_withFallback` will exist, but the later is actually a wrapper selector.  That implementation detail is subject to change.

**Comment by rajeshbabu-oviva** [comment]
Hi @drarmstr Please find the code sandbox below:
https://codesandbox.io/s/react-recoil-todo-app-forked-i0d4s?file=/src/App.js

Test steps:
1) Load the **todosList** list route.
2) Switch route to **addTodos** and add a todo.
3) Switch back to **todosList** to see that it has been added.
4) Now delete one item (which manipulates local state after DELETE success from server).
**_5) Switch to addTodos and add a todo. ()
6) Switch back to todosList to see that is missing, (ie) The triggerRefresgAtom's setValue no longer has any effect on refetch logic._**

**Comment by rajeshbabu-oviva** [comment]
Yes I have seen this one. But isnt it same as setting the atoms directly ??
If I use selector set to modify atoms it would also overwrite the default
selector value ?? No ??. May be I need to rethink the architecture a bit!
