### ISSUE TITLE
Dynamic Key Generation

### ISSUE THREAD

**Issue by Shmew** [facebookexperimental/Recoil#129]
Are there any potential issues/pitfalls from generating keys dynamically when atoms/selectors are created if we don't care about persistence for them?

**Comment by acutmore** [comment]
Hi @Shmew. You might need to provide more information about exactly how you're generating the atom/selector IDs.

Right now Atoms are never removed from Recoil, so if you over the lifetime of an App you keep creating new Atoms/Selectors then you might end up with a memory leak. Though this may change in the future.

> "[the recoil team] are adding a feature soon where atoms will be deleted when no longer used"
https://github.com/facebookexperimental/Recoil/issues/30#issuecomment-629388549

**Comment by Shmew** [comment]
Oh, good to know! The keys were not deterministic, so definitely going to not do that 😅. Thanks!
