### ISSUE TITLE
NEXT js - Duplicate Atom Key: Fatal Error in Production 

### ISSUE THREAD

**Issue by KevinSig** [facebookexperimental/Recoil#1297]
Hello All, 

Wanted to check in and see if there is a solution to this message: 
![Screen Shot 2021-10-15 at 9 50 59 AM](https://user-images.githubusercontent.com/41274608/137498279-d3651c90-dd99-4ad1-a741-274431735b0e.png)

**Comment by mondaychen** [comment]
Do you see this message on production or development?
The first thing you want to check is if you do have two atoms using the same key.

**Comment by azgskull** [comment]
I have the same issue, and I simply ignore it because I don't have duplicate key it's just the way that nextjs works that throw this error.
See this issue #733

**Comment by KevinSig** [comment]
> I have the same issue, and I simply ignore it because I don't have duplicate key it's just the way that nextjs works that throw this error. See this issue #733

That's what I figured! I was hoping there was a next config I could adjust to prevent this message because my terminal is just flooded with this error message!
