### ISSUE TITLE
useRecoilValue with uniquekey

### ISSUE THREAD

**Issue by kennguyen1103** [facebookexperimental/Recoil#136]
Is there any way that we can use useRecoilValue with the unique key of atom?
I think it is usefull in case of dynamic form.

**Comment by acutmore** [comment]
Hi @kennguyen1103. Are you able to provide more information? Maybe a small code example of what you are trying?

**Comment by kennguyen1103** [comment]
Hello,
This is just the my opinionated suggestion. But after I read the documentation again, I think this is the same with atomFamiy. So, this issue can be closed.
Thank you very much for this library.
