### ISSUE TITLE
Set state in render error

### ISSUE THREAD

**Issue by ilanolkies** [facebookexperimental/Recoil#137]
Hi team, great job! The lib is very handy. I'm getting the _Cannot update a component while rendering a different component_. This rises just when rendering up, seems I'm doing something wrong but I don't know what...

App.js:
```javascript
export const accountState = atom({
  key: ACCOUNT_STATE,
  DEFAULT: ''
})

export const networkStatusState = atom({
  key: NETWORK_STATUS_STATE,
  default: NETWORK_STATUS_UNDEFINED
})

const loginSelector = selector({
  key: 'APP_LOGIN_SELECTOR',
  get: ({ get }) => {
    const networkStatus = get(networkStatusState)
    const account = get(accountState)

    return networkStatus === NETWORK_STATUS_SUCCESS && !!account
  }
})

const App = () => {
  const logged = useRecoilValue(loginSelector) // THROWS HERE

  return (
    <>
      <Header />
      {
        !logged ? <Intro className="App" /> : <Dashboard />
      }
    </>
  );
}

export default App;
```

Stack trace:
![Screen Shot 2020-05-22 at 04 04 20](https://user-images.githubusercontent.com/36084092/82640679-6274f380-9be1-11ea-892f-86d0689e6ad6.png)

I can share you the code if you need to, cheers!

**Comment by acutmore** [comment]
Hi @ilanolkies. Thanks for reporting. This looks like a duplicate of #12

**Comment by ilanolkies** [comment]
Yep, still working. I will add notification to remind me when you close the other. I will check if this still remains or not 👍
