### ISSUE TITLE
[docs] Add Example for `useTransactionObservation`

### ISSUE THREAD

**Issue by iamawaisakram** [facebookexperimental/Recoil#138]
Hi, Today I started to implement this cool lib, but couldn't find an example for App Wide Observation using useTransactionObservation. Can anyone kindly help me with this, please!

**Comment by acutmore** [comment]
Hi @iamawaisakram. There is some information in this PR: #90

**Comment by iamawaisakram** [comment]
Thank you @acutmore !

**Comment by drarmstr** [comment]
Yeah, I'm planning to post those docs this weekend.  Though, with a heavy disclaimer as that API is under development and will be changing shortly.  I've started prototyping the new API, so we're making progress..

**Comment by drarmstr** [comment]
Duplicate of #157
