### ISSUE TITLE
useRecoilRefresher_UNSTABLE()   is not param?

### ISSUE THREAD

**Issue by yanghuilong** [facebookexperimental/Recoil#1388]
` export function useRecoilRefresher_UNSTABLE(****************): (recoilValue: RecoilValue<any>) => void;`

**Comment by drarmstr** [comment]
[`useRecoilRefresher_UNSTABLE()`](https://recoiljs.org/docs/api-reference/core/useRecoilRefresher/) does not take any arguments.  Instead it returns a callback function which accepts the selector you want to clear the cache for.

See: https://recoiljs.org/docs/api-reference/core/useRecoilRefresher#example

**Comment by yanghuilong** [comment]
> See: https://recoiljs.org/docs/api-reference/core/useRecoilRefresher#example

not serious
