### ISSUE TITLE
Changelog for the v0.5.2 release?

### ISSUE THREAD

**Issue by tabarra** [facebookexperimental/Recoil#1400]
I'm trying to troubleshoot an issue with one of my applications and one of the things that changed in our latest upgrade was recoil v0.5.1 to v0.5.2, but I couldn't find it in the changelog, nor a tag or branch for that.

**Comment by yanghuilong** [comment]
change  TypeScript:   
 - export function useRecoilRefresher_UNSTABLE(): () => void;
 +export function useRecoilRefresher_UNSTABLE(recoilValue: RecoilValue<any>): () => void;
