### ISSUE TITLE
useRecoilValue flickering between current and old values

### ISSUE THREAD

**Issue by tmcw** [facebookexperimental/Recoil#1402]
Sorry, this one's kind of hard to distill, though I'll really try and get a reduced error reproduction…

So I'm running into a very confusing scenario in which a component using `useRecoilValue` gets the _previous_ value, then the new value, then the previous value, and back and forth.

I've confirmed a few things:

- Using atom effects, I've added logging to whenever this atom was updated, to confirm that there isn't some part of my app that's unexpectedly updating it back to the old value
- I've added a `created` property to the state values themselves to make sure this is really the old versus new values fighting for control.
- None of my atoms are async. I'm not using Recoil's async stuff at all.
- Using react & react-dom at `0.0.0-experimental-6a589ad71`

But still I get logs like this: (`type: single` is the new value, `type: none` is the old one)

```
UPDATED SELECTION ATOM {type: 'single', id: 'RT0YDxXb0GkvkSefjSPgf', parts: Array(0), created: 1636404494899}
feature_editor.tsx:55 {type: 'none', created: 1636404494532}
feature_editor.tsx:55 {type: 'none', created: 1636404494532}
feature_editor.tsx:55 {type: 'single', id: 'RT0YDxXb0GkvkSefjSPgf', parts: Array(0), created: 1636404494899}
feature_editor.tsx:55 {type: 'none', created: 1636404494532}
feature_editor.tsx:55 {type: 'single', id: 'RT0YDxXb0GkvkSefjSPgf', parts: Array(0), created: 1636404494899}
```

So the state of the application flickers between a new, valid, value, and the old, invalid, value.

**Comment by drarmstr** [comment]
Do you have a reproducer?   I wonder if this is addressed with the `recoil_early_rendering_2021` feature flag..

**Comment by drarmstr** [comment]
Closing with no reproducer.
