### ISSUE TITLE
Dictionary of Atoms

### ISSUE THREAD

**Issue by KillerKiwiJuice** [facebookexperimental/Recoil#1406]
Context: I use a websocket to stream stock prices. The realtime data comes in bundles every 0.25 seconds, containing hundreds of stock prices in the following format:
`{symbol:"aapl", price:150}`

Issue: I need to create an independent state for each of the stocks, updating their prices as the data comes in. It also needs to be performant, as sometimes I receive 8000 stocks per second. The stock prices will be used in components throughout the app, some of which are not connected to the parent websocket component at all.

As far as I know there are two options:

1. Create one big Atom containing the whole websocket message, then subscribe to this big block of state
    - This would cause all subscribed components to update at once, no?
 2. Generate an Atom for each unique stock, and update the atom when a new stock price is received
    - I do not know how to do this in Recoil

Essentially it comes down to a key-value pair where the key is stock symbol and value is an _Atom_ storing the price state. Is there a way I can create such a structure and allow independent components to subscribe to these Atoms? E.g. a component "X" subscribes to the state corresponding to stock "AAPL"... Any ideas?
![image](https://user-images.githubusercontent.com/9599423/141191222-b057bddc-df54-4903-b3ef-8331a195acea.png)

**Comment by BenjaBobs** [comment]
I'd first try with https://recoiljs.org/docs/api-reference/utils/atomFamily/ and set the data with https://recoiljs.org/docs/api-reference/core/useRecoilTransaction and see if that's performant enough.

**Comment by KillerKiwiJuice** [comment]
> I'd first try with https://recoiljs.org/docs/api-reference/utils/atomFamily/ and set the data with https://recoiljs.org/docs/api-reference/core/useRecoilTransaction and see if that's performant enough.

So say, for example, I have the following:

Atoms.js
```
export const SymbolFamily = atomFamily({
    key: "symbol",
    default: {},
});
```
Websocket.js
```
import SymbolFamily from "Atoms.js"
const [symbols, setSymbol] = useRecoilState(SymbolFamily);
const onMessage = (stock) => {
    // Functionality below is what I'm aiming for
    // Where this updates the atom with symbol "stock.symbol" with state "stock.price"
    // I.e. update Atom with symbol "AAPL" with state "150" (price) 
    setSymbol(stock.symbol, stock.price)
}
```
Subscriber.js
```
import SymbolFamily from "Atoms.js"
const price = useRecoilValue(SymbolFamily(symbol));
// render price
```

How would you convert the pseudocode in `websocket.js` to code that's valid in Recoil?

**Comment by BenjaBobs** [comment]
This is a very crude sample implementation: https://codesandbox.io/s/jolly-curran-p9mg6?file=/src/App.tsx but I believe it gets the point across. 🙂 
The state and types are defined in `StockSymbol.ts`, the state updater is in `FakeWebsocket.tsx`, the visualizer in `StockVisualizer.tsx`, and `App.tsx` ties it all together.

**Comment by KillerKiwiJuice** [comment]
> This is a very crude sample implementation: https://codesandbox.io/s/jolly-curran-p9mg6?file=/src/App.tsx but I believe it gets the point across. 🙂 The state and types are defined in `StockSymbol.ts`, the state updater is in `FakeWebsocket.tsx`, the visualizer in `StockVisualizer.tsx`, and `App.tsx` ties it all together.

This is great. Looks like it will do the job, though I may need to try to optimize my code for speed. Thanks for the help! It's perfect.
