### ISSUE TITLE
Atom effects keeps re-initializing if requested via useRecoilCallback

### ISSUE THREAD

**Issue by gwre-ivan** [facebookexperimental/Recoil#1407]
I have atom (atom family) with a simple effect that fires on 'get' trigger and makes some async loading (for now I just use a delay).

Then, I have component with `useRecoilCallback` that reads that atom via `Snapshot.getPromise`.

What I'm seeing is that this async loading triggers every time I load the state of that atom. It seems like atoms requested via `Snapshot.getPromise` run effects, but the outcome of that effect is not persisted -- atom gets re-initialized every time!

**Comment by drarmstr** [comment]
If an atom is used first for a snapshot then it will execute the effect to initialize for that local snapshot, which would not affect the rendered state.  Updating snapshots should not update the rendered state.  Does your application first render using the atom before the snapshot in the callback references it?

**Comment by gwre-ivan** [comment]
>Does your application first render using the atom before the snapshot in the callback references it?

No.. What I have is part of the system living completely outside of React. To integrate with Recoil state, I create `useRecoilCallback` that basically allows reading a specific piece of Recoil family state.

What I observe is that every time that part of the system reads the atom, atom gets initialized from within the effect (effect `get` is triggered).

I'm not sure what happens on the React side of my application. Likely, nothing at all (i.e, no re-rendering / nothing).

**Comment by drarmstr** [comment]
Then it sounds like expected behavior if you're always getting new snapshots that haven't rendered with the atom before -- reading the atom from them will cause initialization.   There is `snapshot_UNSTABLE()` which can be used as a factory to make a fresh snapshot for working with Recoil state outside of React.  But, it's not clear what your goal is regarding working with Recoil state outside of React or as part of React.

**Comment by gwre-ivan** [comment]
Yeah, I kind of got sense that what I'm doing is somewhat sketchy. I was hoping for a behavior where state initialized outside of React flows back into React world somehow.

**Comment by gwre-ivan** [comment]
Okay, I did the same terrible thing as in #829 -- using async `set` to read the state. Now atoms are initialized only once. I guess, it works because updates are enqueued & initialize Recoil state properly.

Terrible, but 1) works for me (bad excuse, I know! shame on me..) 2) I probably lack deeper understanding of Recoil to figure out a better solution.
