### ISSUE TITLE
[help] recoil not work under react18 strict mode

### ISSUE THREAD

**Issue by cqh963852** [facebookexperimental/Recoil#1411]
I tried using react18 strict mode with recoil.
But the recoil api only work under none strict mode.

react,react-dom version : 18.0.0-alpha-e0aa5e205-20211109

https://codesandbox.io/s/friendly-hypatia-vn1gi?file=/src/index.tsx

**Comment by corinnaj** [comment]
We ran into the same issue. By pure chance we found out that setting any unrelated atom seems to fix it. 

I added another atom into the code in the `index.tsx` of your example which "fixed" it:  https://codesandbox.io/s/practical-satoshi-ctiby?file=/src/index.tsx

**Comment by mondaychen** [comment]
@davidmccabe @drarmstr can you look into this?

**Comment by drarmstr** [comment]
I haven't had a chance to test with your environment yet, but does #1444 help you?

**Comment by cmfcmf** [comment]
> I haven't had a chance to test with your environment yet, but does #1444 help you?

Thank you! It looks like your PR fixes this issue.
I tested the changes and can confirm that it works for @corinnaj and me.

**Comment by drarmstr** [comment]
Addressed in main/nightly branch for 0.6 release.

**Comment by danielpickett** [comment]
> Addressed in main/nightly branch for 0.6 release.

Will this be accessible on NPM? I'm having this issue now, but I don't see 0.6 on NPM.

**Comment by drarmstr** [comment]
Yes, it will be available on NPM once it is released.

**Comment by lperezdude** [comment]
Any update on this? RecoilRoot is still giving me the same issue.
Can it even be used on react18 with strict mode on ?

**Comment by hugo-valcourt** [comment]
Subscribing
