### ISSUE TITLE
[Feature request] Loadable.valueOrThrow() should expose error if in error state

### ISSUE THREAD

**Issue by BenjaBobs** [facebookexperimental/Recoil#1439]
# Proposal

When dealing with loadables in tests, doing `.valueOrThrow()` is an easy way to get a value, or make the test fail if there is none.
The error message in this case won't tell me what error caused this, instead I get `Loadable expected value, but in "hasError" state`.
I propose that this message also exposes the error that is the cause, maybe something like `Loadable expected value, but in "hasError" state, with error: <error message here>`

Codesandbox: https://codesandbox.io/s/gifted-leaf-nvjux?file=/src/errors.test.ts

**Comment by drarmstr** [comment]
The `.getValue()` accessor also returns a `T`, but if in an error state it will re-throw the actual error.  The reasoning behind this was that `.getValue()` was like accessing the state via a hook while `.valueOrThrow()` is more about making an assertion that it is in the value state.  So, the later has an error saying that assertion is false while `.getValue()` just passes it through.  The other distinction between these accessors is in the pending state.  `.valueOrThrow()` will throw the same error while `.getValue()` will throw a `Promise` to the resultant value.  This also aligns with the semantics for Suspense and can allow `.getValue()` to be used in a React component or Recoil selector to get the value while also seamlessly propagating error and Suspense.

Would `.getValue()` work for you for testing purposes is the difference in handling the pending state an issue?

**Comment by BenjaBobs** [comment]
I somehow completely missed this, and it very much solves my problem! Thank you!
