### ISSUE TITLE
Strange behavior when using recoilState for controlling animationFrame

### ISSUE THREAD

**Issue by theZiggurat** [facebookexperimental/Recoil#1449]
Recoil: 0.5.2
React: 16.12.1 & 17.0.2

### Issue
This demo creates a button that will toggle an animation frame to start and stop and animation frame loop. When using an atom to hold the running state, the button will function for a few times, then it will *seemingly* at random stop functioning and the `animationFrame` will never cease. If I were to replace `useRecoilState`  with `useState`, it works as expected again. I have also tried this with holding the animationFrame handle in in a ref, but the same issue occurs. The single cause for this bug is the use of a recoil state. 

### Sandbox
https://codesandbox.io/s/heuristic-moon-8l3g6?file=/src/App.js
### Relevant code
```
import React, { useState, useLayoutEffect } from "react";
import { useRecoilState, atom } from "recoil";

function Counter() {
  const [counter, setCounter] = useState(0);
  //const [running, setRunning] = useState(false);
  const [running, setRunning] = useRecoilState(isRunning);

  useLayoutEffect(() => {
    if (running) {
      let timerId;

      const f = () => {
        setCounter((x) => x + 1);
        timerId = requestAnimationFrame(f);
      };

      timerId = requestAnimationFrame(f);

      return () => cancelAnimationFrame(timerId);
    }
  }, [running]);

  return (
    <p>
      Counter: {counter} ...{" "}
      <button onClick={() => setRunning(!running)}>
        {!running ? "Resume" : "Pause"}
      </button>
    </p>
  );
}

export default Counter;

const isRunning = atom({
  key: "isRunning",
  default: false
});
```

**Comment by drarmstr** [comment]
This issue does not reproduce if you use `useEffect()` vs `useLayoutEffect()`.  Do you require `useLayoutEffect()` for some reason?

Note that the `recoil_early_rendering_2021` feature flag appears to fix this issue.  This can be enabled [here](https://github.com/facebookexperimental/Recoil/blob/main/packages/shared/util/Recoil_gkx.js#L15) on the nightly build.

**Comment by fiberliber** [comment]
useLayoutEffect works as-is like componentDidMount in class components, which means it is works sincronously and can block DOM update, so, in case when you logic goes to state, when component just rerender and `running` becomes true, you, formally, create and return new componentWillUnmount callback from useLayoutEffect, in other case it returns nothing and do nothing, so, React don't cancel RAF and you stay in that missing state, independently from new `running` switching. For make you code works right, you should return RAF canceling callback in any case - not only when `running` is false, and for do that, you should declare timerId outside of useLayoutEffect, but using useRef, for avoid exhausive deps by using in effect hook:
```js
import React, { useState, useLayoutEffect, useRef } from "react";
import { useRecoilState, atom } from "recoil";

function Counter() {
  const [counter, setCounter] = useState(0);
  //const [running, setRunning] = useState(false);
  const [running, setRunning] = useRecoilState(isRunning);

  const timerId = useRef(0);

  useLayoutEffect(() => {
    if (running) {
      const f = () => {
        setCounter((x) => x + 1);
        timerId.current = requestAnimationFrame(f);
      };

      timerId.current = requestAnimationFrame(f);
    } else {
      cancelAnimationFrame(timerId.current);
    }
    return () => cancelAnimationFrame(timerId.current);
  }, [running]);

  return (
    <p>
      Counter: {counter} ...{" "}
      <button onClick={() => setTimeout(() => setRunning(!running), 0)}>
        {!running ? "Resume" : "Pause"}
      </button>
    </p>
  );
}

export default Counter;

const isRunning = atom({
  key: "isRunning",
  default: false
});
```
This is not a recoil bug - this is wrong usage of useLayoutEffect
