### ISSUE TITLE
Question about generating atoms/selectors

### ISSUE THREAD

**Issue by codex-zaydek** [facebookexperimental/Recoil#145]
Thank you for building and sharing this tool. It’s interesting how subtle it is.

I’m wondering if Recoil is only meant to be used as a kind of global store? Can Recoil stores can be dynamically generated?

Let’s say for the classic counter app example, where an app simply renders a counter value, and increment, decrement buttons, if you wanted to dynamically generate _another_ counter with an independent store, is that something you could use Recoil for?

With components, you can simply use `useState` scoped to a component, create a context, and pass `state, setState` as values along the context to children components. Every time you instantiate a component, so are new stores created. Can this logic be reasonably modeled using Recoil? Also, would this be an inappropriate feature because apparently Recoil is not yet designed to support [garbage collection](https://github.com/facebookexperimental/Recoil/issues/56#issuecomment-630957954)?

Thank you!

**Comment by drarmstr** [comment]
Recoil stores are not "global", they are associated with a `<RecoilRoot>` component for a particular rendering tree.

But, for the example you describe you wouldn't need dynamic stores.  You can dynamically create multiple atoms for new counters.  Either with dynamically calling `atom()` to create them and saving the result or by using the `atomFamily()` helper provided in the utils for this pattern.

**Comment by acutmore** [comment]
Hi @codex-zaydek. Each `<RecoilRoot>` is independent. If you wanted to reuse an Atom/Selector but with a different value you could wrap that part of the app with a different root. When the root is unmounted the state should get garbage collected.
