### ISSUE TITLE
Cannot mock atom with asynchronous default function

### ISSUE THREAD

**Issue by NS-BOBBY-C** [facebookexperimental/Recoil#1457]
Hi Recoil Team!

We have successfully integrated recoil into one of our applications and we have seen incredible improvements in app performance due to this library.

I am struggling with how to write jest tests for atoms which have an asynchronous promise as the default value. I've included a codesandbox with my struggle:

https://codesandbox.io/s/sleepy-lederberg-xg38e?file=/src/components/RecoilComponent/RecoilComponent.test.tsx

The pattern below is a pretty common pattern in our application, and I am struggling to test the components where we use recoil. I have a wrapper component in a custom render function, but I'm not sure how to wait for the fetchData function to return - and wrapping in act/waitFor doesn't seem to wait for the function to finish fetching.
 
```typescript
const fetchData = async (id: string) => fetch("API/path/here")

export const dataFromId = memoize((id: string) => atom({ key: 'Atom_${id}, default: fetchData(id) })
```

**Comment by drarmstr** [comment]
In our unit testing we have a function: 
```jsx
function flushPromisesAndTimers(): Promise<void> {
  return act(
    () =>
      new Promise(resolve => {
        setTimeout(resolve, 100);
        jest.runAllTimers();
      }),
  );
}
```
Then in the tests you can do:
```jsx
  await flushPromisesAndTimers();
```
to resolve them.  If this helps you, please let us know and we can update [the documentation](https://recoiljs.org/docs/guides/testing).

Also, you may wish to use `atomFamily()` instead of direct memoization of atoms.

**Comment by NS-BOBBY-C** [comment]
Thank you for the response! This does fix the issue for me.

I can update the documentation if you would like - I'll make a PR with an example.

For those of you trying this in codesandbox like I was - there is a lingering [issue](https://github.com/codesandbox/codesandbox-client/issues/513) that jest doesn't work 100% in codesandbox.

Side note:
What is the advantage of using atomFamily over memoization? Just that it keeps things in the recoil world?
