### ISSUE TITLE
useRecoilTransaction_UNSTABLE() set does not run atom effects

### ISSUE THREAD

**Issue by cqh963852** [facebookexperimental/Recoil#1466]
Hi I found that useRecoilTransaction_UNSTABLE 's transaction.set not trigger atomFamily's effect.

Here is the demo 

[codesandbox](https://codesandbox.io/s/clever-danilo-1o7ho?file=/src/App.tsx:401-412)

Can any one help?

I don't want effect trigger by “get” after set action.

**Comment by drarmstr** [comment]
This does not seem to be specific to `atomFamily()`.   Fix coming shortly.

**Comment by dnsco** [comment]
I also just lost a couple hours to this, looking forward to the fix :)

Thanks again for this library.

**Comment by drarmstr** [comment]
> I also just lost a couple hours to this, looking forward to the fix :)
> 
> Thanks again for this library.

Fix is #1479 if you want to patch it before it's merged and/or published.
