### ISSUE TITLE
Pass parameters to set

### ISSUE THREAD

**Issue by DanaCoding** [facebookexperimental/Recoil#1467]
I have obsessive-compulsive disorder 😂, and I want to pass the logic processing through the seletor, so when I click the `+ / -` button, I only need to pass `+` / `-` to the set, and then do the processing in the set. 
But this approach is not supported in `recoil set`. Does anyone have good suggestions?
> e.g.

![QQ截图20211129152429](https://user-images.githubusercontent.com/93444868/143830081-1d2d44ef-3d4c-40bf-967b-c6ad4ac8b8f9.png)

**Comment by DanaCoding** [comment]
Sorry, I just came into contact with recoil, maybe `selectorFamily` is the effect I want. But why should it be so? Recoil is great, but there are too many similar methods of repetition, why not delete the selector directly and only keep the selectorFamily?

**Comment by drarmstr** [comment]
atoms and selectors are the core concepts for nodes in the data flow graph.  We want to keep the core foundational components as simple as possible.  Families provide useful additional functionality layered on top.  As you point out, selectors don't have parameters and selectorFamily can provide that.
