### ISSUE TITLE
Unable to clear cache in unit tests

### ISSUE THREAD

**Issue by FokkeZB** [facebookexperimental/Recoil#1480]
I'm writing unit tests for a selector that depend on external state via an HTTP request.

I've mocked the HTTP request and response, but noticed that when test N+1 uses the same selector, as test N, the selector does not get re-evaluated for test N+1, but returns the value cached for test N.

Here's an example:

```js
import { atom, selector, snapshot_UNSTABLE } from "recoil";

const numberState = atom({ key: "Number", default: 1 });

const callApiToGetMultiplier = jest.fn();

const multipliedState = selector({
  key: "MultipliedNumber",
  get: ({ get }) => get(numberState) * callApiToGetMultiplier()
});

beforeEach(() => {
  callApiToGetMultiplier.mockClear();
});

test("First test", () => {
  callApiToGetMultiplier.mockReturnValueOnce(100);
  const initialSnapshot = snapshot_UNSTABLE();
  expect(initialSnapshot.getLoadable(multipliedState).valueOrThrow()).toBe(100);
  expect(callApiToGetMultiplier).toBeCalledTimes(1);
});

test("Second test", () => {
  callApiToGetMultiplier.mockReturnValueOnce(200);
  const initialSnapshot = snapshot_UNSTABLE();

  // FAILS because value is still 100
  expect(initialSnapshot.getLoadable(multipliedState).valueOrThrow()).toBe(200);

  // FAILS because callApiToGetMultiplier is not called (again)
  // expect(callApiToGetMultiplier).toBeCalledTimes(1);
});
```

And here it is on CodeSandbox: https://codesandbox.io/s/optimistic-hooks-3714i?file=/src/repro.test.js:0-938

At https://recoiljs.org/docs/guides/testing#example-jest-unit-testing-selectors it says:

> You can build a fresh snapshot using `snapshot_UNSTABLE()` and then use that Snapshot to evaluate selectors for testing.

As the failing test shows, the returned snapshot is not entirely fresh, which is problematic for isolating unit tests.

I'm aware of https://github.com/facebookexperimental/Recoil/issues/972#issuecomment-962996375, but the "solution" there, as well as https://github.com/facebookexperimental/Recoil/pull/1413 both rely on hooks, which are not available in this context.

As far as I know there's no non-hook API to do a similar refresh, but I'd argue that this shouldn't be needed anyway, unless the above documentation is incorrect and `snapshot_UNSTABLE()` is **not** supposed to return a **fresh** snapshot.

**Comment by drarmstr** [comment]
Snapshots represent Recoil atom state.  Selector caches are shared across `<RecoilRoot>`'s and Snapshots as selectors are supposed to be idempotent.  So, a fresh Snapshot would only refer to atom state.  We can update the documentation to clarify this.

But, you're right that there is a gap with no way to refresh the selector cache when using stand-alone snapshots without access to hooks.   Will need to think about an appropriate API for that...

**Comment by drarmstr** [comment]
@FokkeZB - I was working on #1498 for another use case.  It might be a little bit awkward, but it does allow users to refresh selector caches from snapshots without hooks.

**Comment by FokkeZB** [comment]
Here's a workaround for those running into this issue.

For this, I assume you already have a `RecoilCacheReset ` to [work around the same issue for component/integration tests](https://github.com/facebookexperimental/Recoil/issues/972#issuecomment-962996375).

We'll use this to create a custom `snapshot_UNSTABLE_CUSTOM`:

```ts
import { renderHook } from '@testing-library/react-hooks';
import { MutableSnapshot, RecoilRoot, useRecoilCallback } from 'recoil';

import { RecoilCacheReset } from './RecoilCacheReset';

export const snapshot_UNSTABLE_CUSTOM = (
  initializeState?: (mutableSnapshot: MutableSnapshot) => void
) => {
  const { result } = renderHook(
    () =>
      useRecoilCallback(
        ({ snapshot }) =>
          () =>
            snapshot,
        []
      ),
    {
      wrapper: ({ children }) => (
        <RecoilRoot initializeState={initializeState}>
          <RecoilCacheReset />
          {children}
        </RecoilRoot>
      ),
    }
  );

  return result.current();
};
```

The returned callback has the same signature as `snapshot_UNSTABLE`, but uses `RecoilRoot` to initialize the state and, `useRecoilCallback` via `@testing-library/react-hooks` to the snapshot, and since we're now in a React environment, we can re-use `RecoilCacheReset` to reset node caches between tests.

You should be able to replace `snapshot_UNSTABLE` with `snapshot_UNSTABLE_CUSTOM` without further changes to your test, and change it back once this issue has been fixed and `snapshot_UNSTABLE` either clears cache automatically, or takes an option to do so.

**Comment by FokkeZB** [comment]
@drarmstr would it be possible to share an example of how https://recoiljs.org/docs/guides/testing#clearing-all-selector-caches could be applied in the context of e.g. a jest test suite?

Ideally this would be possible in a global `afterEach`, but if I'm correct doing the following wouldn't work as each snapshot has it's own tree, thus the newly created `snapshot` here does not contain any of the values used in the test.

```ts
afterEach(() => {
  const snapshot = snapshot_UNSTABLE();
  snapshot.getLoadable(clearSelectorCachesState).getValue()();
});
```

I guess one could create a wrapper around `snapshot_UNSTABLE()`, e.g.:

```ts
const withSnapshot = async (test: () => Promise<void>) => {
  const initialSnapshot = snapshot_UNSTABLE();
  const release = initialSnapshot.retain();
  try {
    await test(initialSnapshot);
  } finally {
    initialSnapshot.getLoadable(clearSelectorCachesState).getValue()();
    release();
  }
};
```

Note that this also includes the use of retain. I *think* this'll work fine, but it does feel like a lot of boilerplate to me.

**Comment by drarmstr** [comment]
When `getNodes_UNSTABLE()` is called with `isInitialized` set to nullable, then it should return all registered atoms/selectors, not just those that were initialized with that snapshot.  Since selector caches are shared across snapshots, I would expect the simple `afterEach` example should work.

**Comment by FokkeZB** [comment]
Thanks, I'll give that a try, and if it works contribute an addition to https://recoiljs.org/docs/guides/testing/#clearing-all-selector-caches to document it.

**Comment by FokkeZB** [comment]
Worked great!

Doc update: https://github.com/facebookexperimental/Recoil/pull/1619
