### ISSUE TITLE
useResetRecoilState Not Working

### ISSUE THREAD

**Issue by mjth** [facebookexperimental/Recoil#1481]
It looks like useResetRecoilState is not working to reset atom back to default value using even basic atoms.

CodeSandbox here,

[https://codesandbox.io/embed/elated-night-9zr6f?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/elated-night-9zr6f?fontsize=14&hidenavigation=1&theme=dark)

**Comment by drarmstr** [comment]
Looks like you have a typo and forgot to include the `()` after `resetHeader` to acually call the function

https://codesandbox.io/s/little-butterfly-sgs14?file=/src/App.tsx
