### ISSUE TITLE
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

### ISSUE THREAD

**Issue by pgbradbury** [facebookexperimental/Recoil#1487]
I get the above when trying to set a constant to a selector that is doing an async axios call.

This is the line causing the error:

`const Values = useRecoilValue(valuesState);`

This is the selector:

```
export const valuesState = selector({
  key: "valuesState",
  get: async () => {
    const result = await axios
      .get("api/dropdown")
      .then((response) => response.data)
      .catch((error) => captureException(error));
    console.log(result);
    return result;
  },
});
```

The console log triggers after the error and returns the expected json. I can't figure out the problem and have found similar bug reports here that seem to have been resolved by upgrading packages. However I am using the following packages

```
    "react": "^17.0.2",
    "react-dom": "17.0.2",
    "recoil": "^0.5.2"

```

If I replace the axios call with the json it returns, in the code and remove the async await, all works as expected.

**Comment by drarmstr** [comment]
The React team has removed this warning, though I think with React 18.  Please see this discussion about it here: https://github.com/reactwg/react-18/discussions/82

**Comment by gString** [comment]
I see the same, using 8.2.0
