### ISSUE TITLE
useRecoilRefresher how to  refresh the selectorFamily with params?

### ISSUE THREAD

**Issue by postbird** [facebookexperimental/Recoil#1505]
## Description

I define two methods with a `selectorFamily`: `useData` and `useRefreshData`

```jsx
const useData = (params?: { keyword?: string }) => {
  const { state, contents } = useRecoilValueLoadable(listSelector(params));
  switch (state) {
    case "loading":
      return { loading: true, contents };
    case "hasError":
      return { loading: false, contents: {} };
    case "hasValue":
      return { loading: false, contents };
  }
};

const useRefreshData = (params?: { keyword?: string }) => {
  return useRecoilRefresher_UNSTABLE(listSelector(params));
};
```
![image](https://user-images.githubusercontent.com/16200574/146530890-f8f59d9f-4977-49d2-9cc2-e7daa754216d.png)

when the  `keyword` state changed, i hope to refresh the result by click the button, and refresh data.

**how to achieve that with `useRecoilRefresher_UNSTABLE`?**

what I wanted is pass the `keyword` params to selectFamily,  then refresh the data or get a new  refresher when i changed the  `keyword`.

if i pass the `keyword` by the following way, when keyword changed, i will trigger loading every time

```jsx
 const { loading, contents } = useData({ keyword });
```
if i pass the `keyword` by the following way, refresh not works, **shouldn't it return a new refresher every time?**

```jsx
const refresh = useRefreshData({ keyword });
```

## Demo

https://codesandbox.io/s/suspicious-night-bn4fj?file=/src/Demo.tsx

**Comment by drarmstr** [comment]
Passing in the keyword to both the data hook and refresher appears to work with your sandbox: https://codesandbox.io/s/hardcore-mountain-nlhfx?file=/src/Demo.tsx

**Comment by postbird** [comment]
> Passing in the keyword to both the data hook and refresher appears to work with your sandbox: https://codesandbox.io/s/hardcore-mountain-nlhfx?file=/src/Demo.tsx

That's not what i expected

In your sandbox, i need to pass the keyword to both the data hook and refresher, that will cause the data hook to be automatically executed every time the keyword changes. When the keyword changes, I don’t want to update automatically, but update through refresher.

So the way I tried is to update the dependency in refesher, not update the dependency in the data hook， just like this

![image](https://user-images.githubusercontent.com/16200574/147323861-c595232e-1b55-4800-967a-964591cc49fa.png)

but that not working.

**Comment by drarmstr** [comment]
Not using the same parameter for the refresh and data hooks means they will refer to different selectors.
