### ISSUE TITLE
[request] Separate types for selector read and write

### ISSUE THREAD

**Issue by RayVR** [facebookexperimental/Recoil#1517]
I have something like the following:

```typescript
interface Parent  {
  a: Child[]
  b: string[]
}

interface Child {
  foo: number,
  bar: string,
}

const dataState = atomFamily<Struct, string>({
  key: "StructState",
  default: {} as Struct,
  effects_UNSTABLE: key => [syncRemoteData(key)]
})

const aState = selectorFamily<Child, string>({
  key: "Struct.a",
  get: key => ({get, getCallback}) => {
    const info = get(dataState(key)).a
    addChild = getCallback( ({})  => async (newChild: Child) => {
      apiCallToUpdateChildren(key, newChild)
    }
    return { a: info, addChild: addChild}
  },
  set: key => ({set }, newValue) => {
  ...
  }
  
})
```

My issue is that I either have typescript errors due to the return type of get not matching what is specified in the selectorFamily return type, or if I update the return type, set expects me to pass in the fields for the callbacks I'm creating.

- Is there a graceful/recommended way to handle this? 
- Am I misusing getCallback as in this particular case the state isn't used inside the callback?

**Comment by drarmstr** [comment]
This example does seem problematic in that the selector is of type `Child` with `foo` and `bar` properties, but instead it returns a different object with `a` and `addChild` properties.  So, the typescript error would be valid.  Doesn't seem related to `getCallback()` specifically.

**Comment by RayVR** [comment]
@drarmstr I 100% agree the typescript error is valid, the question is how to deal with it in a ReadWrite selector. My example was very tailored to my case (which I've refactored into recoil state plus recoil callbacks returned from a hook)

In general, I wouldn't expect a selector that returns state plus callbacks to require callbacks be passed in when a new value is written to the selector. the newValue in my original example is forced to be of the same type returned from the get.

I'll just throw this suggestion out there, I'm sure it is not _the_ ( or even _a_) answer to my question.

```typescript
interface FooRT {
  value: string,
  fooCB(x: number): Promise<void>
}

const foo = selectorWithCB<string, FooRT> // <state type, get return type>

const [{value, valueCB}, setValue] = useRecoilState(foo)
```


As I mentioned, I've refactored my code to not use getCallback and I wonder whether it actually should be part of the selector api. getCallback feels like it adds a small amount of convenience over useRecoilCallback but adds complexity to the api and especially the types.

**Comment by drarmstr** [comment]
Ah, I see your question regarding writable selectors.  The easiest way to handle that now is probably to just split it up.  One  read-only selector with the callback and another entity for writing.  That entity might be a RW selector without the callback, or maybe just a setter made with `useRecoilCallback()` or `useRecoilTransaction_UNSTABLE()` (which doesn't support selectors quite yet).

We also have a rename proposal (#804) considered for a future release that would include splitting writeable selector Read and Write types, which would accomplish what you are looking for with a single selector.

**Comment by drarmstr** [comment]
Merge with #804
