### ISSUE TITLE
useRecoilRefresher signature doesn't play nice with selectorFamily

### ISSUE THREAD

**Issue by alirezamirian** [facebookexperimental/Recoil#1521]
Currently, the signature is:
```ts
type Refresher = () => void;

function useRecoilRefresher_UNSTABLE(state: RecoilValue): Refresher
```

It would be nicer to have it like:
```ts
type Refresher = (state: RecoilValue) => void;

function useRecoilRefresher_UNSTABLE(): Refresher
```

Consider this example:

```ts
const fileContent = selectorFamily({
  key: "fileContent",
  get: (path: string) => async () => fetchFileContent(path),
});
```

Imagine I'm showing the list of files, in a `FileList` component, which renders `FileItem` components. If I want to have a 
hook for reloading file content from disk/network, etc., I can only implement it in a way that it gets the file path as the argument and returns a non-parametric reload function:
```ts
const reload = useReloadFileContent(filePath);
// reload();
```
Which means I can only use it in `FileItem` component. It would be nicer, if I were able to implement it like this:
```ts
const reload = useReloadFileContent();
// reload(filePath);
```
That would allow for having the reload action in either `FileItem` component, or in `FileList` component.

This is the current implementation: https://github.com/facebookexperimental/Recoil/blob/a58ce48c5e5139b59ae3e138566928ec5a431825/packages/recoil/hooks/Recoil_useRecoilRefresher.js#L19-L25

It seems quite feasible to change it to:

```ts
function useRecoilRefresher(): <T>(recoilValue: RecoilValue<T>) => void {
  const storeRef = useStoreRef();
  return useCallback(<T>(recoilValue: RecoilValue<T>) => {
    const store = storeRef.current;
    refreshRecoilValue(store, recoilValue);
  }, [storeRef]);
}
```

**Comment by alirezamirian** [comment]
I'd be happy to open a PR if the argument makes sense.

**Comment by drarmstr** [comment]
Yes, the proposed API would be more versatile.  The current API is more consistent with the rest of the hooks.  We debated making this change a while back, but have to consider backward compatibility of the API.

Actually, a lot of our usage now is through the even more versatile `refresh` callback from `useRecoilCallback()`.

cc @habond

**Comment by alirezamirian** [comment]
@habond 
Yes, it would be backward incompatible. I suggested it, especially because the library is still in 0.x version range, and a better API in the stable version would outweigh the cost of introducing breaking changes.
Didn't know about the `refresh` API in `useRecoilCallback`. Would you care to elaborate a little? I can't find anything [here](https://recoiljs.org/docs/api-reference/core/useRecoilCallback), but maybe you meant `reset`?

**Comment by drarmstr** [comment]
Ah, it hasn't quite been released yet, but coming shortly.  See the [0.6 documentation here](https://github.com/facebookexperimental/Recoil/pull/1514/files).

**Comment by drarmstr** [comment]
For example, with 0.6 you could do the following as a workaround for now:
```jsx
const refresh = useRecoilCallback(({refresh}) => node => refresh(node));
```

Updated API feedback for #804 RFC
