### ISSUE TITLE
Include testing example using react-hooks-testing-library

### ISSUE THREAD

**Issue by patrickspafford** [facebookexperimental/Recoil#1522]
Hi,

While the [Recoil testing documentation](https://recoiljs.org/docs/guides/testing) is helpful, I think it could be improved if there was mention / an example of how to test with React Hooks Testing Library. Because atoms and selectors require nesting inside RecoilRoot, the example could show something along these lines (see [Advanced Hooks testing](https://react-hooks-testing-library.com/usage/advanced-hooks) for where this comes from):

```javascript
// state.ts
const countAtom = atom({
key: 'countAtom',
default: 0
})

// useMyCustomHook.ts
const useMyCustomHook = () => {
  const [count, setCount] = useRecoilState(countAtom)
  // insert other state here
  // insert your custom useEffects here (that are not best written as atom effects)
  return [count, setCount]
}

// useMyCustomHook.test.ts
test('My test', () => {
  const { result } = renderHook(() => useMyCustomHook(), {
    wrapper: RecoilRoot, // <-- this is the important part. We can now access Recoil values because they are properly wrapped
  })
 expect(result.current).toEqual(0)
})
```

With this approach, I'm not sure that you'd need to use snapshots and this way seems less cumbersome. It seems to work for me in a React Native project anyway...

Thanks so much

**Comment by drarmstr** [comment]
Thanks, feel free to make a PR with the doc improvements!  Note that for our internal testing we also always wrap the tests with suspense and error boundaries in addition to `<RecoilRoot>`.

**Comment by patrickspafford** [comment]
If you can point me in the direction of the docs, will do. But it looks like the docs are included in the .gitignore?

**Comment by drarmstr** [comment]
Thanks again @patrickspafford !
