### ISSUE TITLE
Using dispatch pattern with Recoil

### ISSUE THREAD

**Issue by nickbarkhuff** [facebookexperimental/Recoil#1539]
Hello, I'm trying to create an abstraction layer on top of Recoil for my app. I would like state changes to be triggered by dispatching actions (like in Redux), while keeping the benefits of the atomic model (only updating components that are explicitly subscribed to an atom).

This works fine for atoms, but I can't figure out how to make it work for atomFamilies.

Let's say I have an atom, `foo`, and I can set its value via an action, `"setFoo"`:

```javascript
import {atom, useSetRecoilState} from "recoil";

const foo = atom({
    key: "foo",
    default: "Hello, I'm foo"
});

const useDispatch = () => {
    const setFoo = useSetRecoilState(foo);

    return (action, data) => {
        switch(action){
            case "setFoo":
                setFoo(data);
                break;
        }
    };
};
```

Now, I can call this `useDispatch` hook once at the top level of my app, and pass the dispatch function it returns down (perhaps using Context, since the function itself never changes). When a `"setFoo"` action is dispatched, the hook sets the new value of the `foo` atom, and any components that are subscribed to `foo` will rerender. So far so good.

---

Now, let's make `foo` an atom family, instead of just an atom:

```javascript
import {atomFamily, useSetRecoilState} from "recoil";

const foo = atomFamily({
    key: "foo",
    default: "Hello, I'm foo"
});

const useDispatch = () => {
    const setFoo = useSetRecoilState(foo(/* ??? */)); // Atom identifier needs to be known here

    return (action, data) => {
        switch(action){
            case "setFoo":
                setFoo(data);
                break;
        }
    };
};
```

The trouble is, the atom identifier needs to be known at the time when `useDispatch` is called. I can't call `useSetRecoilState` inside the body of the dispatcher to dynamically create the setter, since that would break the rules of hooks.

---

Here's my proposal:

What if `useSetRecoilState` and related hooks were able to accept atom families, instead of just atoms? Then, the setter it returns could take an atom identifier as an argument, and I could do something like this:

```javascript
import {atomFamily, useSetRecoilState} from "recoil";

const foo = atomFamily({
    key: "foo",
    default: "Hello, I'm foo"
});

const useDispatch = () => {
    const setFoo = useSetRecoilState(foo); // Atom *family* is passed in, instead of an atom

    return (action, data) => {
        switch(action){
            case "setFoo":
                setFoo(data.id, data.value); // Setter takes atom identifier as an argument
                break;
        }
    };
};
```

If not, are there any other ways to implement this pattern?

**Comment by mondaychen** [comment]
Can you use a `useDispatchFamily` function that takes in the `id` instead? i.e. `const useDispatch = (id) => {...}`

BTW I'm curious, why do you need to create a dispatch pattern with Recoil?

**Comment by tpict** [comment]
Here's the solution I'm using:

```tsx
export interface DispatchWithThunk<A> {
  (action: A): void | ((dispatch: Dispatch<A>) => void);
}

export function useRecoilDispatch<A>(
  fn: (callbackInterface: CallbackInterface) => DispatchWithThunk<A>,
): Dispatch<A> {
  const dispatch: Dispatch<A> = useRecoilCallback(callbackInterface => {
    const handler = fn(callbackInterface);
    return action => {
      const thunk = handler(action);
      if (typeof thunk === "function") {
        thunk(dispatch);
      }
    };
  }, []);

  return dispatch;
}
```

In usage:
```tsx
useRecoilDispatch(({ set, snapshot }) => action => {
  switch(action.type) {
    case "DO_SOME_WORK":
      set(statusAtom, "Working!");
      return async dispatch => {
        const data = await grabSomeData();
        dispatch({ type: "WRITE_DATA", data });
      }
    case "GIVE_UP_WORK":
      set(statusAtom, "Cancelled");
    case "WRITE_DATA":
      const status = await snapshot.getPromise(statusAtom);
      if (status === "Cancelled") {
        // Don't write data, user cancelled
        return;
      }

      set(dataAtom, action.data);
  }
});
```

By returning a callback that receives `dispatch` as an argument, you read the latest state snapshot, which is handy if when doing async work.

**Comment by nickbarkhuff** [comment]
@mondaychen 

> BTW I'm curious, why do you need to create a dispatch pattern with Recoil?

My app needs to share state across multiple windows/tabs. My plan is to have the app state live in a `SharedWorker`, then let the UI threads communicate with the worker so that all windows have synchronized state. [Like this](https://i.ibb.co/x23dXqw/state.png).

It seems natural to have the worker accept actions from the UI threads. That way my entire UI simply has a single `dispatch` function to trigger state changes.

If I use Recoil, I could then have the worker send back data about only the atoms that have changed. Then Recoil takes care of updating the UI. Plus, with this model, I wouldn't be sending over the entire state object every time there is a change (which would become more and more expensive the more windows you have open).

I am trying to figure out what tools would be best to implement this - Recoil seems like it could be a good fit, but if there are any other tools you think would be better, or if you think using a reducer pattern with Recoil is an anti-pattern, I would love to hear your thoughts.

---

@drarmstr @tpict

Thanks for your answers, seems like I have what I need to start experimenting. Of course there's a whole section in the Recoil docs about using reducers that I missed - oops

**Comment by tpict** [comment]
After tinkering with my solution a bit, it turns out that the thunk isn’t guaranteed to receive the next snapshot, i.e. updates are always batched unless there’s async work involved. I’m not sure how to do “go to this state via this state”.

**Comment by nmeibergen** [comment]
@tpict Did you figure out a better way to get the 'latest' state in the thunk? Struggling with it right now.
