### ISSUE TITLE
Query Default AtomFamily Values

### ISSUE THREAD

**Issue by sergiybabich** [facebookexperimental/Recoil#1540]
So, for atoms we have [Query Default Atom Values](https://recoiljs.org/docs/guides/asynchronous-data-queries/#query-default-atom-values).

Is there already or plaaning same way to initialise atomFamily?

I mean to have it filled with key value, not just default value for all keys.

**Comment by drarmstr** [comment]
The same approach can be used for initializing atom families:

```jsx
const userInfoState = atomFamily({
  key: 'userInfo',
  default: selectorFamily({
    key: 'CurrentUserID/Default',
    get: id => myFetchCurrentUserInfo(id),
  }),
});
```

**Comment by chriszrc** [comment]
@drarmstr How is that different from "default value for all keys"? If I don't manually set new atom entries, isn't the atomFamily still empty with the above example?
