### ISSUE TITLE
Unable to find @types/recoil in npm registry

### ISSUE THREAD

**Issue by Tejasp21** [facebookexperimental/Recoil#155]
I have a CRA with TS template. I was trying to install types for recoil library, but getting below error message.

> npm install @types/recoil
> _Not Found - GET https://registry.npmjs.org/@types%2frecoil - Not found_

How can I use the new experimental recoil in my CRA (TS template) project ? Is there any other way to use TS with recoil?
I believe Typescript support is not built-in and it is still under development. Any plans to publish @types/recoil in npm registry ?

@csantos42  - Appreciate quick response!

**Comment by matthewlee-toast** [comment]
This is in the works already - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44756

**Comment by Tejasp21** [comment]
@matthewlee-toast -  Thanks for the info. I hope this will be in place soon. Very excited to use this new state management library with React-TS.
