### ISSUE TITLE
Excluding a getter or setter causes an expression not callable error

### ISSUE THREAD

**Issue by JonathanMSifleet** [facebookexperimental/Recoil#1554]
When using useRecoilState in my application, not all components need the get and set methods, when removing the unnecessary method I get the error: 
> This expression is not callable. Type 'Boolean' has no call signatures.

```
const [setShowModal] = useRecoilState(modalState);

useEffect(() => {
      setShowModal(false);
 }, []);
```

```
const [showModal, setShowModal] = useRecoilState(modalState);

useEffect(() => {
      setShowModal(false);
 }, []);
```

> No error

I've hastily created a repo showing what I mean [here](https://github.com/JonathanMSifleet/RecoilBugDemonstration)

**Comment by jonbnewman** [comment]
You might want to look into [`useSetRecoilValue`](https://recoiljs.org/docs/api-reference/core/useSetRecoilState/)

**Comment by JonathanMSifleet** [comment]
> You might want to look into [`useSetRecoilState`](https://recoiljs.org/docs/api-reference/core/useSetRecoilState/) and [`useRecoilValue`](https://recoiljs.org/docs/api-reference/core/useRecoilValue/)

I wasn’t aware of that, thanks!
