### ISSUE TITLE
Unexpected behaviour: isReset flag in Atom Effect

### ISSUE THREAD

**Issue by bentron2000** [facebookexperimental/Recoil#1574]
When setting an atom in an atom family that has an Atom Effect, setting the same atom with a new value will trigger the Atom Effect with the `isReset` flag set to `true`.

Since this is not a reset, it's an overwrite, this does not make sense to me. 

@drarmstr Is this the expected behaviour?

Setting the same atom with the same object does not do the same thing.

Reproduction here [https://codesandbox.io/s/recoil-atom-effects-isreset-behaviour-p3k9f](https://codesandbox.io/s/recoil-atom-effects-isreset-behaviour-p3k9f)

Thanks

B

**Comment by drarmstr** [comment]
The type signature of the `onSet()` callback is actually:

```jsx
    (newValue: T, oldValue: T | DefaultValue, isReset: boolean) => void
```

So the second parameter is the previous value and `isReset` is the third parameter.  Here's a fix for your codesandbox: https://codesandbox.io/s/recoil-atom-effects-isreset-behaviour-forked-i4zcc?file=/src/SomeComponent.tsx

**Comment by bentron2000** [comment]
🤦🏼 derp... 

Thank you
