### ISSUE TITLE
setSelf() in atom effect produce eleaseNodesNowOnCurrentTree error 

### ISSUE THREAD

**Issue by domis77** [facebookexperimental/Recoil#1582]
I'm using effect in my atom, which causing error during changing state.

```
type blockchainStateType = {
    name: string,
    blockchain?: IAVAILABLE_BLOCKCHAINS | undefined
}

export const blockchainState = atom<blockchainStateType>({
    key: 'currentBlockchainName',
    default: {
        name: localStorage.getItem("currentBlockchainName") || DEFAULT_BLOCKCHAIN,
        blockchain: getCurrentBlockchain()
    },
    effects: [
        ({onSet, setSelf}) => {
            onSet(newValue => {
                localStorage.setItem("currentBlockchainName", newValue.name);
                const currentBlockchain = getCurrentBlockchain();
                setSelf({
                    name: newValue.name,
                    blockchain: currentBlockchain
                })
            })
        }
    ]
})
```

![](https://user-images.githubusercontent.com/16179246/151676293-2a184d26-d288-4e1d-9fcb-e21a3931f023.png)

Could someone explain me what am I doing wrong, or what could causing the issue?

**Comment by drarmstr** [comment]
The related unit test for calling `setSelf()` from an `onSet()` handler appears to be passing.  Do you have a repro on codesandbox.io?

Note this pattern of always unconditionally updating with every call to `onSet()` can be dangerous if you have multiple atom or React effects monitoring for changes.  Maybe only calling `setSelf()` if the current blockchain has changed may help?

**Comment by drarmstr** [comment]
It appears this console message is a result of the new rendering that keeps Recoil and React state in sync when done from the same batch.  The unit tests for this pattern are currently passing, though they do have the error message.  Will investigate further.

**Comment by drarmstr** [comment]
@domis77 - Looks like the error message should be spurious and can be disregarded.

**Comment by domis77** [comment]
All right, thank you for fast solution, so I closing then.
