### ISSUE TITLE
Debounce callback with version 0.6.0

### ISSUE THREAD

**Issue by xotahal** [facebookexperimental/Recoil#1604]
Hey folks! I am not sure if this is an issue or wanted behaviour. But out of curiosity. I created this [codesandbox](https://codesandbox.io/s/xenodochial-kalam-c3g5u?file=/src/App.js:830-847) where we have one atom and two buttons. Atom has a default value set to `first`. When you press any button it will change the value of the atom and then in `useEffect` it calls `useRecoilCallback` where it gets the value from the atom and console log it.

1. Without `debounce` it sets the value to `second`. Then in `useEffect` it correctly prints out the `second` as a value.
2. The debounced button sets the value to `third`. Then in `useEffect` it prints out the previous value of the atom (either `first` or `second`). But not the `third`. As I would expect.

It works with 0.5 version.

I think it could be related to this change https://github.com/facebookexperimental/Recoil/pull/1501. Any chance someone could explain to me what exactly happened?

Thank you 🙏

**Comment by xotahal** [comment]
Here is maybe a bit more "real world" [example](https://codesandbox.io/s/nice-golick-9921y?file=/src/App.js). Where I created `AmountControl` component. It has debounced `onChange`. Once it gets to the parent it changes the state.

There are two `useEffect`s, one of them uses debounced `useRecoilCallback` (that works fine) and the other one calls the `useRecoilCallback` without debounce. This one prints always previous value of the state.

**Comment by drarmstr** [comment]
It's not related to #1501, but I think I have a fix.
