### ISSUE TITLE
Selector with atom dependency that is initialised by promise in effect

### ISSUE THREAD

**Issue by xotahal** [facebookexperimental/Recoil#1609]
Hey everyone! I created this [sandbox](https://codesandbox.io/s/serene-sun-82hgt?file=/src/App.js). You can see one atom and two selectors. The `firstLevel` selector has dependency directly on the atom. The second one gets the first level selector first.

In `useRecoilCallback` it accesses the value of `secondLevel` selector. 

1. Press the button. It waits for the evaluation of the promise in atom effect.
2. Press the button again. It won't wait for the evaluation because the selector is cached I guess.
- it releases snapshot in `useRecoilCallback`
- and because the selector has no listeners it throws error

This wasn't an issue in 0.5 version (I guess because the effect wasn't cleaned up before?)

**Comment by drarmstr** [comment]
Note that from the console output the subsequent callbacks work properly and produce the expected result.  The error you see is the host environment catching uncaught exceptions and showing the error in dev mode.  That can be explained as follows:
* On the first run the callback initiates getting the selector and waits for it to resolve.  The selector waits for the atom to resolve.  The atom initializes with the callback's snapshot.  the atom effect waits 2 seconds and resolves the value, thus setting the cached value for the downstream selectors.  the callback then releases the snapshot.
* On the second run the callback requests the selector value, which is cached.  It then immediately releases the snapshot.  However, the atom is still initialized and the effect waits 2 seconds to resolve.  But, the snapshot was already released causing the downstream selector resolution to be canceled.  This is harmless, but the dev environment catches the uncaught canceled exception and renders it as an error.

In general, this pattern of usage of only using the atoms and selectors with a callback snapshot isn't very useful.  If you only use the atom from the callbacks snapshot, then it will always only get the default state and re-initialize it each time.  Generally the atom would be first used by the host `<RecoilRoot>` store and initialized there.  Then, using it from a Recoil callback snapshot would just inherit that shared state.  So, you shouldn't see this issue if you first use and initialize the atom from the `<RecoilRoot>` before reading its value from a snapshot.

Here's an example update to your sandbox which causes the atom to only be initialized once and then use shared state: https://codesandbox.io/s/serene-grass-9kblf

**Comment by xotahal** [comment]
Ok, got it. Our atoms (not all of them of course) are basically just listeners for changes on the "backend". So even when we initialized them multiple times the default value can be different each time, because it reflects the current state of the backend and starts listening for deltas. Eventually, it is used by `<RecoilRoot>` but many times we need to get the data to evaluate something else.

One more question then. About the "pre-fetching" pattern. We usually start fetching data before we render them (before the atom is used by `<RecoilRoot>`). Something similar to what you can see here - https://recoiljs.org/docs/guides/asynchronous-data-queries/#pre-fetching. Is this still a valid pattern when used with the atom's effect? I mean it will initialise the atom/effect, fetch the data, gets released and when it is rendered by `<RecoilRoot>` it has to initialise the atom again.

Thank you for your explanation. 🙏

**Comment by drarmstr** [comment]
That prefetching pattern will work to populate the selector cache, even if the snapshot it released.  But, atom state is specific to a snapshot so should not be used for prefetching using atom effects on a snapshot.  If you are using atoms to store your state you could use the prefetch to explicitly set the atom in the `<RecoilRoot>` store using the `set()` in the Recoil callback.
