### ISSUE TITLE
[bug] Using a RecoilValue or Promise as a default value throws exception.

### ISSUE THREAD

**Issue by acutmore** [facebookexperimental/Recoil#161]
Using another Atom/Selector or a Promise as the default value of an Atom is mentioned in several places.

Here: 
https://github.com/facebookexperimental/Recoil/blob/5f4491a69b8d1e383e49ddae06a1d4f3ac14c8e2/src/recoil_values/Recoil_atom.js#L18-L21

Here:
https://github.com/facebookexperimental/Recoil/blob/5f4491a69b8d1e383e49ddae06a1d4f3ac14c8e2/src/recoil_values/Recoil_atom.js#L200

and here:
https://github.com/facebookexperimental/Recoil/issues/149#issuecomment-633358455

When I try and do this the code crashes with `ReferenceError - selector is not defined`. Don't need to run the React app or use any hooks. Just trying to define the Atom will throw.

Code to reproduce:

```javascript
const defaultValue = selector({
  key: 'defaultValue',
  get() {
    return 9999;
  },
});

const state = atom({
  key: "state",
  default: defaultValue,
}); // throws exception here - no need to 
```

**Comment by drarmstr** [comment]
Sounds like this is related to the GitHub package build issues..  Duplicate of #142 
cc @mondaychen

**Comment by acutmore** [comment]
Ah yes. Duplicate. Thanks @drarmstr
