### ISSUE TITLE
[6.0 breaking change] - Async snapshots

### ISSUE THREAD

**Issue by L0v3l4c3** [facebookexperimental/Recoil#1627]
Hello, 

This is not an issue as this was originally the expected behavior anyways, but i believe it's important to note that asynchronous use of snapshots in < 6.0 would sometimes be working even when they were not being retained. In >= 6.0, this is not the case anymore, you absolutely need to retain snapshots in order to observe the resolved value and to prevent selectors from being canceled.

I began investigating it myself but didn't have enough time to get to the bottom of what change caused this. Either way, I believe this is expected behavior, so nothing to do.

**Comment by drarmstr** [comment]
Yes, retaining Snapshots was a breaking change introduced several versions back, but will be increasingly enforced as resource management features are rolled out.  Please refer to these docs [here](https://recoiljs.org/docs/api-reference/core/Snapshot#asynchronous-use-of-snapshots) and [here](https://recoiljs.org/docs/guides/testing#testing-async-selectors).  

In some cases we attempt to auto-retain snapshots.  For example, Snapshots from `useRecoilSnapshot()` will be retained for the duration that the component using them is mounted.  May try to introduce that for async `useRecoilCallback()` callbacks as well...

**Comment by L0v3l4c3** [comment]
Great initiative :) I just thought it would be a great idea to mention it in breaking changes, as this caused unexpected issues is multiple places in one of the projects I'm working on, where the developers had not been careful enough to retain snapshots in asynchronous callbacks for example. 
Thanks for getting back to me!

**Comment by drarmstr** [comment]
Also #1590
