### ISSUE TITLE
The sample code in Bi-Directional Synching has potential errors

### ISSUE THREAD

**Issue by JimLiu** [facebookexperimental/Recoil#163]
![image](https://user-images.githubusercontent.com/648674/82825562-150eb580-9e71-11ea-91d9-8b47888f5493.png)

I didn't test the example code in [Bi-Directional Synching
](https://recoiljs.org/docs/guides/asynchronous-state-sync#bi-directional-synching), but I fell like the `knownServerCurrentUserID` should be out of the functional component, otherwise it will be always `undefined` after re-render.

Correct me if I'm wrong :)

**Comment by drarmstr** [comment]
Good point, let's try `useRef`
