### ISSUE TITLE
Docs on how to delete an `Atom` from an `AtomFamily`

### ISSUE THREAD

**Issue by nvmnghia** [facebookexperimental/Recoil#1635]
- In #622, @drarmstr mentioned that [`useResetRecoilState()`][1] can be used to delete an `Atom` from its `AtomFamily`.
- In its docs, the function (or its returned function) is used to *reset* the atom to its default state, not *deleting*

Can you update the docs to show that it can also be used to delete? Or am I missing something here, that *reseting* implies *deleting* in Recoil?

  [1]: https://recoiljs.org/docs/api-reference/core/useResetRecoilState/

**Comment by drarmstr** [comment]
The term "reset" is currently the most accurate.  It will reset the atom state to default.  This "removes" the state value itself form the current store, however there is still metadata about the registered atom contained within the store so it is not fully "deleted".  With garbage collection that metadata will be removed as well.
