### ISSUE TITLE
[improvement]useRecoilCallback could be memoized

### ISSUE THREAD

**Issue by JimLiu** [facebookexperimental/Recoil#164]
Currently, the result of `useRecoilCallback` is not memoized, which means it returns a new function after re-render.

**Comment by acutmore** [comment]
Hi @JimLiu. Looking at the source `useRecoilCallback` is a wrapper around `React.useCallback`.

https://github.com/facebookexperimental/Recoil/blob/5f4491a69b8d1e383e49ddae06a1d4f3ac14c8e2/src/hooks/Recoil_Hooks.js#L583

It expects the deps to be passed in the same way.

```javascript
const logValue = useRecoilCallback(async ({getPromise}) => {
  console.log(await getPromise(someAtom));
}, []); // note passing empty deps array here
```

**Comment by JimLiu** [comment]
@acutmore 
Yes, it works as expected after passing an empty array!

Thanks!
