### ISSUE TITLE
What is the 'parameter' in an atomFamily default?

### ISSUE THREAD

**Issue by sberney** [facebookexperimental/Recoil#1644]
Hello,

I'm trying to understand [this part](https://recoiljs.org/docs/api-reference/utils/atomFamily#family-defaults) of the documentation, where it states:

> An atomFamily() takes almost the same options as a simple [atom()](https://recoiljs.org/docs/api-reference/core/atom). However, the default value can also be parameterized. That means you could provide a function which takes the parameter value and returns the actual default value. For example:

In the example:

```javascript
const myAtomFamily = atomFamily({
  key: ‘MyAtom’,
  default: param => defaultBasedOnParam(param),
});
```

But I can't begin to guess what value `param` might take on. Can you elaborate? I think it might make sense to add a sentence or two to the documentation there.

**Comment by BenjaBobs** [comment]
You might have an `atomFamily`, because you need a structure where every `atom` is identified by an id of sorts.
```ts
const people= atomFamily({
	key: 'peopleState',
	default: (id: string) => ({ id: id, name: 'John Doe' }),
});
```
So let's say you're creating a component to display the info of a person, and maybe change the name of said person.
```tsx
export function PersonInfo(props: { id: string }) {
	const [person, setPerson] = useRecoilState(people(props.id));
	
	return <div>
			Name: {person.Name}
			<br/>
			<button onClick={() => setPerson({...person, name: Utils.GetRandomName() })}>Randomize name</button>
		</div>
}
```

And then if you have a bunch of people:
```tsx
const ids = ['1', '2', '3'];

export function ListOfPeople() {
	return <div>
		{ids.map(id => <PersonInfo key={id} id={id}/>)}
	</div>
}
```
And each `<PersonInfo>` will render the person assigned to their id.
I realize this is a bit of a weird example, but I hope it makes the idea of `-families` clearer.

**Comment by sberney** [comment]
Thanks! I was confused because I thought I would need to define an `atom` to go with the `atomFamily`, and that they would be somehow linked, and that the defaulting behavior would occur in the `atom` bit. But since it's just a stand alone `atomFamily`, the idea of an id parameter makes a lot more sense. Thanks for the quick reply!
