### ISSUE TITLE
Best way to initialize from selector while still being writable

### ISSUE THREAD

**Issue by w0v002s** [facebookexperimental/Recoil#1645]
I have a use case where I have a selector that loads an array from an existing async selector
```ts
export const userConfigSelector = selector({
  key: 'user-config',
  get: async ({ get }) => {
    const user = get(userState);
    return await getUserConfig(user);
  }
});

export const userRolesSelector = selector({
  key: 'user-roles',
  get: ({ get }) => {
    const userConfig = get(userConfigSelector);
    return userConfig?.roles || [];
  }
});
```

I want to have a selected role which is initialized as the first entry from the `userRolesSelector`, but can be set at runtime so the user can change their selected role. I would also want it to reset to the 0th role when the underlying user config changes.

I also need this value within recoil since this value then feeds into other parts of our data-flow 
```ts
...
get: ({ get }) => get(selectedUserRole)
...
```

My initial thoughts were to use another selector
```ts
export const selectedUserRole = selector({
  key: 'selected-user-role',
  get: ({ get }): Role => {
    const roles = get(userRolesSelector);
    return roles?.[0] || {} as Role;
  },
});
```
But I cannot then set the value when the user wants to switch roles.

I've tried using an atom
```ts
export const selectedUserRole = atom({
  key: 'selected-user-role',
  default: {} as Role
});
```
and syncing with a normal `React.useEffect` 
```ts
const useSelectedRole = () => {
  const [role, setRole ] = useRecoilState(selectedUserRole);
  const loadable = useRecoilValueLoadable(userRolesSelector);

  React.useEffect(() => {
    if (loadable.state === 'hasValue') {
      setRole(role => loadable.content?.[0] || role || {} as Role )
    }
  }, [loadable]);

  return role;
}
```
But this causes the role to be reset to the 0th role when the component with the effect is unmounted and remounted.

My question is: Is there a way to initialize from another selector while also being able to be writable?

**Comment by wuweiweiwu** [comment]
you can use a selector as the `default` value for an atom!

docs https://recoiljs.org/docs/api-reference/core/atom

> The initial value of the atom or a Promise or another atom or selector representing a value of the same type. If a selector is used as the default, the atom may dynamically update if the default selector updates; once the atom is set then it will retain the value it was set to.

**Comment by davidrichard23** [comment]
@w0v002s did you find a solution? I'm having the same decoupling issue after setting a value on an atom with a selector used as a default value. I'm thinking about just resetting the atom instead of setting it.

**Comment by drarmstr** [comment]
It wouldn't be valid for an atom to dynamically change once set.  It either sync/subscribes to the default selector value or has its own value.  Resetting an atom will revert it to use the default selector and will dynamically update again, if that's what you're asking.
