### ISSUE TITLE
consider useSelector

### ISSUE THREAD

**Issue by omerman** [facebookexperimental/Recoil#1650]
Hello all. I've seen several issues/discussions about complex state, e.g #1164 & #1127.

I think a nice approach would be to consider having a behavior like the good old react-redux::useSelector.
defining selector's seems like a hard work, having a hook that gives us the ability to do so inline and anonymously could feel much better.

```
const atom = atom(...) // complex object {a: [{..}, {...}], b: {..}}
const selector1 = selector(atom, ...);
const selector2 = selector(atom, ...);
``` 

VS

```
const atom = atom(...) // complex object {a: [{..}, {...}], b: {..}}

const MyComponent = () => {
// Much more simple to write the selectors inline as I go.
const derived = useSelector((atom, ({get})) => {...});
}

```

What do you think?

**Comment by omerman** [comment]
I'll take a crack at it. It seems very possible to wrap the selector inside a memo, with an arbitrary key and the deriviation func which can be stored inside a ref so it doesnt have to be memoized. Hmm I'll keep you posted :)

**Comment by drarmstr** [comment]
@omerman - I would think the evaluation function should also be memoized as otherwise it may reference stale closure state.

**Comment by omerman** [comment]
@drarmstr I wa thinking something like this


```
func useSelector(atom, fn) 

cinst fnRef = useRef(fn)
fnRef.current = fn

... useMemo(() => selector(..., (...args) => fnRef.current(...args)))
```

**Comment by omerman** [comment]
@drarmstr Hey, I submitted a PR, you are welcome to take a look, please let me know what you think

**Comment by drarmstr** [comment]
Thank you!!  However, I think the semantics of `useRecoilMemo()` in #985 make more sense here.  As I mentioned the evaluation function does need to also be memoized, or else any referenced local variables or closure state can be stale.  The unit tests for the new hook should cover those situations as well.  For example:

```jsx
function MyComponent({input}) {
  const myDerivedValue = useRecoilMemo(({get}) => {
    return get(myState).foo + input;
  }, [input]);

  ...
}
```

**Comment by drarmstr** [comment]
Closing in favor of #985
