### ISSUE TITLE
Maybe need a strategy for selector(in my case, asychronous),calculate on render

### ISSUE THREAD

**Issue by WilkinWendy** [facebookexperimental/Recoil#1660]
Motivation Case:
https://codesandbox.io/s/react-hooks-playground-forked-7tuff?file=/src/index.tsx
In this case, `chartData` and `tableData` will both be calculated，when switch from `chart` to `table`(or `table` to `chart`).

Expected Feature:
```js
const ChartData = selector({
  key: 'ChartData',
  get: ({get}) => {
     //...
  },
 UNSTABLE_CALCULATEONRENDER: true
});
```

**Comment by drarmstr** [comment]
Downstream selectors of an updated atom or selector may be re-evaluated.  Though, components using them will only re-render if there is a reference-equality change in value.  Selectors are evaluated based on React components transitively depending on them.  The default rendering mode evaluates the current dependencies to determine what to re-render.  However, using the new `useRecoilState_TRANSITION_SUPPORT_UNSTABLE()` and `useRecoilValue_TRANSITION_SUPPORT_UNSTABLE()` uses a different approach which pulls after render, as you are looking for, and thus avoids computing the stale dependency in your example.  

See the updated sandbox: https://codesandbox.io/s/react-hooks-playground-forked-b151l1?file=/src/index.tsx:934-935

Also see #1416 for more discussions around controlling selector re-evaluation.

**Comment by WilkinWendy** [comment]
https://codesandbox.io/s/downstreamselector-re-evaluated-still-xsexpx
@drarmstr Look at this, still cause re-evaluate,is there any solution

**Comment by WilkinWendy** [comment]
@drarmstr  sorry, is there any solution to this? it troubles me a lot
