### ISSUE TITLE
Getting Started demo, Unexpected token in recoil/dist/recoil.js

### ISSUE THREAD

**Issue by JTangming** [facebookexperimental/Recoil#168]
Error in ./~/recoil/dist/recoil.js
Module parse failed: /Users/namexxx/Desktop/my-recoil/node_modules/recoil/dist/recoil.js Unexpected token (1:2730)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:2730)
 @ ./src/App.js 15:14-31

ENV：
- "node": v8.4.0,
- "react": "^16.13.1",
- "react-dom": "^16.13.1",
-  "react-scripts": "0.9.x",
-  "recoil": "0.0.7"

**Comment by acutmore** [comment]
HI @JTangming 

The unexpected token looks like an `...` object spread. Possibly need to use a newer version of node.js.

```javascript
Object.freeze({state:"hasValue",contents:e,...i})
```

**Comment by acutmore** [comment]
> You may need an appropriate loader to handle this file type.

This sounds like a webpack error message. Are you able to share your webpack version and loader config?

**Comment by JTangming** [comment]
> > You may need an appropriate loader to handle this file type.
> 
> This sounds like a webpack error message. Are you able to share your webpack version and loader config?

"webpack": "1.14.0",
"babel-loader": "6.2.10"
