### ISSUE TITLE
not able to sync atom without re-render, or not be able to access always the newest state

### ISSUE THREAD

**Issue by likon416** [facebookexperimental/Recoil#1682]
Hello,

I have a problem syncing an atom state across my app. 

I want to use atoms inside a callback function beyond react component. I'm using react native with IAP plugin where there is a function setPurchaseListener that is initialized at the start of the app. 

The problem is once this listener will get fired (after an IAP purchase) it has the OLD state of an atom. So I can't pass updated data there. Because this is not a react component and it does not re-render to update the atom so the state of the atom is old. 

How I can:
1. Be able to sync state with all same atom instances regardless of re-rendering
2. Be able to grab manually the newest state even if atom was not refreshed/re-rendered

Would be good that whenever I'm reading atom it always have the newest state regardless of re-rendering. 

How I can achieve any of the above?

Thanks :)

**Comment by jeffscalyr** [comment]
If you can initialize `setPurchaseListener` from within a react component, then you can use `useRecoilCallback`.

`useRecoilCallback` returns a callback function that has access to an up to date `snapshot` of your state at the time that the callback function executes.

**Comment by likon416** [comment]
@jeffscalyr that seems to do the trick :) thank you

**Comment by drarmstr** [comment]
You may also just be able to use the updater form of the atom setter.  Pass in a function as the new atom value and it will call you back with the current value of the atom as the parameter:

```jsx
  const setPurchase = useSetRecoilState(purchaseState);
 
  const myCallbackHandler = x => {
    setPurchase(oldState => {
      return ... new state based on old state ...
    });
  };
```
