### ISSUE TITLE
How can I contribute such as translation to this repository?

### ISSUE THREAD

**Issue by alstn2468** [facebookexperimental/Recoil#17]
I want to contribute to this repository by translate to Korean.
How can I participate in this repository contribution?
Should I make a separate translation repository and use it?

**Comment by alstn2468** [comment]
I am now creating and translating files in docs branch.
After working on a few files, I will send pr.

**Comment by alstn2468** [comment]
#18

**Comment by davidmccabe** [comment]
Thanks!
