### ISSUE TITLE
Keep value while refreshing selector

### ISSUE THREAD

**Issue by ikryvorotenko** [facebookexperimental/Recoil#1702]
I have a setup with an atom storing _current user id_ and selector for _retrieving user data_ from server like
```
const idState = atom({
  key: 'id',
  default: 1,
})

const userState = selector({
  key: 'user',
  get: async ({ get }) => {
    const id = get(idState)
    await fetch(`users/${id}`)
  },
})

```

I'm using React Suspense feature to handle the loading state of `userState`.  

The issue I have is that every time I reset the selector state (via `useRecoilRefresher_UNSTABLE(userState)`), it renders Suspense fallback while the data is reloading. I'm wondering what would be the right way to keep the state available while the new data is queried. 

I have tried a setup with atom+selector but it still doesn't keep the data and relies on a fallback while loading:
```
const userState = atom({
  key:'user/atom',
  default: selector({
    key: 'user',
    get: async ({ get }) => {
      const id = get(idState)
      await fetch(`users/${id}`)
    },
  })
})

```

**Comment by sifatulrabbi** [comment]
If you want to fetch data in the background without showing the Loading screen, then use a custom hook that will fetch the data asynchronously and then will update the state synchronously (no async selectors).

**Comment by drarmstr** [comment]
You can also save the previous result in the component state and access the query using the `noWait()` or `useRecoilValueLoadable()` to avoid triggering Suspense.  With any approach like that, however, care has to be taken when rendering persisted previous state to avoid bugs from using inconsistent state.

The new [React 18 Transition feature](https://recoiljs.org/docs/guides/transitions) is designed for this type of situation.
