### ISSUE TITLE
how to change two status attr with  two func and get new statue 

### ISSUE THREAD

**Issue by caichuanwang** [facebookexperimental/Recoil#1705]
eg:
i have one state 
export const userState = atom({
  key: 'userState',
  default: initialState,
});
const initialState: User = {
  modalStatus: {},
  refresh: false,
};
and i have two func is
  const [userStatus, setUserStatus] = useRecoilState(userState);
  const setClose = () => {
    setUserStatus({
      ...userStatus,
      modalStatus: {
        a: false,
      },
    });
  };
  const refreshTable = () => {
    setUserStatus({
      ...userStatus,
      refresh: !refresh,
    });
  };
and i call there in one palce
   setClose();
   refreshTable();

but  where call func refreshTable ,userStatus is not {a:false}
why?

**Comment by drarmstr** [comment]
Yes, breaking up state is often a great idea.  For example, the modal status and refresh could be separate atoms.  If you do deal with compound state and want to just update part it is recommended to use the updater form of setters by passing in a callback that gets the current state as the first parameter:

```jsx
const refreshTable = () => {
  setUserStatus(userStatus => ({
    ...userStatus,
    refresh: !refresh,
  }));
};
```
