### ISSUE TITLE
 [bug?] Typescript AtomFamily and AtomEffect<T>

### ISSUE THREAD

**Issue by alexgwolff** [facebookexperimental/Recoil#1707]
I have a bug with types. This code work but TS accuse error

```typescript

const saveOnChangeEffect = ({ onSet }: AtomEffect<Document>) => {
  onSet((document: Document) => saveDocumentRequest(document));
};

const documentAtom = atomFamily({
  key: 'document',
  default: selectorFamily<Document, DocumentRequestPayload>({
    key: 'document/default',
    get: (params) => () => getDocumentRequest(params),
  }),
  effects: [saveOnChangeEffect],
});

```

<img width="577" alt="Screen Shot 2022-04-01 at 09 32 09" src="https://user-images.githubusercontent.com/13754094/161264285-25ebc6c9-7c00-4404-88a1-540bc3824b3f.png">

> Error: Type '({ onSet }: AtomEffect<Document>) => void' is missing the following properties from type 'AtomEffect<Document>': node, storeID, trigger, setSelf, and 5 more.ts(2740)

**Comment by drarmstr** [comment]
The `saveOnChangeEffect()` function should have the `AtomEffect<Document>` type, not the first parameter:

```jsx
const saveOnChangeEffect: AtomEffect<Document> = ({ onSet }) => {
  onSet((document: Document) => saveDocumentRequest(document));
};
```
