### ISSUE TITLE
How to handle pending asynchronous selectors when using 'set' in selector with or without React.Suspense

### ISSUE THREAD

**Issue by timeswind** [facebookexperimental/Recoil#171]
I saw the example of handle pending asynchronous selectors when using 'get'.

when I try to use 'set' function in 'set' property, it seems does't work after a async request

(I am trying to add a loading state when data are being posted)

```Javascript
export const updateDataSourceItemSelector = function(dataSourceId: string) {
    return selector({
        key: `updateDataSourceItem:${dataSourceId}`,
        set: async ({get, set}, newValue) => {

            const {GatewayId, Name, Model, Description, GroupId} = newValue
            const gatewayItem = get(gatewayItemWithId(GatewayId));

            set(gatewayItemWithId(GatewayId), {...gatewayItem, loading: true});
            set(dataSourceItemWithId(dataSourceId), {...newValue, loading: true});
            
            let body = {DataSourceId: dataSourceId, GatewayId, Name, Model, Description, GroupId} 
            await fetcher('/api', {method: 'post', body: JSON.stringify(body)})

            //does't work here ---> set(gatewayItemWithId(GatewayId), {...gatewayItem, loading: false});
            //does't work here ---> set(dataSourceItemWithId(dataSourceId), {...newValue, loading: false});
        },
    });
}

**Comment by timeswind** [comment]
I just saw the issue #103 , is that related?

**Comment by drarmstr** [comment]
Selectors support async `get` callbacks; we haven't supported async `set` callbacks.  Perhaps `useRecoilCallback()` would be more appropriate for your needs?

**Comment by drarmstr** [comment]
Also, for completeness, there are a couple other notes with your example:  
* `get` is required for selectors.  The Flow types enforce that, hopefully the TypeScript bindings do as well.
* This function will attempt to make a new selector every time it is called.  So, it will create redundant selectors and run into key conflicts if called twice for the same `dataSourceId`.  You can memoize the function or use the `selectorFamily` helper for this pattern.

**Comment by timeswind** [comment]
> Also, for completeness, there are a couple other notes with your example:
> 
> * `get` is required for selectors.  The Flow types enforce that, hopefully the TypeScript bindings do as well.
> * This function will attempt to make a new selector every time it is called.  So, it will create redundant selectors and run into key conflicts if called twice for the same `dataSourceId`.  You can memoize the function or use the `selectorFamily` helper for this pattern.

Gotcha! Thank you!

**Comment by timeswind** [comment]
@drarmstr btw, typescript doesn't seem to enforce including 'get' for the selector

**Comment by drarmstr** [comment]
@csantos42 - we might need to review the TypeScript bindings for selectors if they aren't enforcing a `get`

**Comment by acutmore** [comment]
> btw, typescript doesn't seem to enforce including 'get' for the selector

The TypeScript types have not merged yet. Looking at the PR, it looks like get on selector is non-optional so should all be good.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44756/files
