### ISSUE TITLE
TypeError: Attempted to assign to readonly property. React native recoil

### ISSUE THREAD

**Issue by Malhar99** [facebookexperimental/Recoil#1742]
I am new to react-native CLI. I am using the recoil state management tool and I am trying to Update the state through recoil in react native
``
const setJobsList = useSetRecoilState(jobListState);
setJobsList((jobsList) =>
    jobsList.map((obj) => (obj.job_code === job.job_code ? obj : obj)),
);
``

![image](https://user-images.githubusercontent.com/42084390/163673948-1b806d62-9f14-438e-aecf-5605d828c3fe.png)

**Comment by noritheduck** [comment]
Hi Malhar99, are you trying to store a Promise in an atom or selector.  Recoil freezes values in dev mode to catch errors where state changes may happen without properly updating state using hooks so subscribing components can be updated. There are a bunch of duplicate issues that could be referenced.  There is a dangerouslyAllowMutability option to override this.

**Comment by noritheduck** [comment]
Closing this as it is a duplicate #794
