### ISSUE TITLE
Feature request: effects inside selector 

### ISSUE THREAD

**Issue by lishine** [facebookexperimental/Recoil#1750]
Consider an atom with []T items. Upon item change an graphql mutation should be fired with this item as a data.
I think it is best to place it in a effect in the bellow selectorFamily.

```ts
export const elementPluginFactory = <T extends IBaseConfiguration>(params: {
    pluginName: string
    _default?: T[]
    updateStateMutation: UpdateStateMutation<T>
}) => {
    const { pluginName, _default = [] } = params

    const atom = createAtom({
        key: pluginName,
        default: _default,
    })

    return {
        atom,
        getElementAtom: selectorFamily({
            key: `${pluginName} getElementAtom`,
            get: (elementId) => {
                return ({ get }) => {
                    return elementId ? get(atom)?.find((c) => c?.byond_id === elementId) : get(atom)[0]
                }
            },
            set:
                (elementId) =>
                    ({ set }, element) => {
                        set(atom, (prevValue) => {
                            if (element && !(element instanceof DefaultValue)) {
                                const index = prevValue.findIndex((c) => c?.byond_id === elementId)
                                if (index > -1) {
                                    const newValue = [...prevValue]
                                    newValue[index] = element
                                    return newValue
                                } else {
                                    return prevValue
                                }
                            }
                            return prevValue
                        })
                    },
        }),
        isEmpty: selector({
            key: `${pluginName} isEmpty selector`,
            get: ({ get }) => !get(atom).length,
        }),
    } as ElementPluginFactoryReturnType<T>
}
```

**Comment by drarmstr** [comment]
@prbxr - Note that there are only effects associated with atoms and not selectors. That is because selectors represent derived state and there could be state consistency concerns if selectors are updated independently and not just always derived and kept in sync with upstream state. Using [atom effects](https://recoiljs.org/docs/guides/atom-effects) with the atom can be used to sync the local state with a remote data source.

Also, for GraphQL, please note #1752 for GraphQL support.

**Comment by lishine** [comment]
@drarmstr 
> Note that there are only effects associated with atoms and not selectors
I know
>  That is because selectors represent derived state and there could be state consistency concerns if selectors are updated independently and not just always derived and kept in sync with upstream state
But selector do have ability to be updated.
Like in the above - it is just an array of items. `selectorFamily` select and updates item. `selectorFamily `atom is always in sync.
> Using [atom effects](https://recoiljs.org/docs/guides/atom-effects) with the atom can be used to sync the local state with a remote data source.
Yes, but then the array have to be searched for which item was updated.
Another option is to ussue server update using React `useEffect` which I would rather not do (so that not to create needless renders).

**Comment by drarmstr** [comment]
> @drarmstr 
> 
> > Note that there are only effects associated with atoms and not selectors
> 
> 
> 
> I know, that is I requested the feature
> 
> >  That is because selectors represent derived state and there could be state consistency concerns if selectors are updated independently and not just always derived and kept in sync with upstream state
> 
> 
> 
> But selector do have ability to be updated.
> 
> Like in the above - it is just an array of items. `selectorFamily` selects and updates item. `selectorFamily` atom is always in sync.

Well, a couple nuances here. Atom Effects are run when atoms are first used, so it's predictable that they're called before the atom is first used, and can initialize state for the first render. With a selector we could have the effect call the selector's set callback. But, when would the selector effect be called?  If on first use of the selector and it's set updates upstream atoms, that means just reading a selector could have side effects of updating other atom state.  So, you get into race conditions for upstream state based on the ordering of rendering, compounded with concurrent rendering.  Additionally if you think of effects as used to keep Recoil state in sync with external systems and allow effects on selectors then you can have multiple layers of selectors fighting over initialization and syncing state.  Much safer and more straightforward to have a single source of truth with atoms to synch with. 

> > Using [atom effects](https://recoiljs.org/docs/guides/atom-effects) with the atom can be used to sync the local state with a remote data source.
> 
> 
> 
> Yes, but then the array has to be searched for the updated item.
> 
> _Another option is to ussue server update using React `useEffect` which I would rather not do (so that not to create needless renders)._
