### ISSUE TITLE
Can Recoil prevent sibling components from re-rendering without using React.memo?

### ISSUE THREAD

**Issue by yzbaoo** [facebookexperimental/Recoil#1751]
I tried a lot of writing methods and still did not prevent sibling components from updating
![Apr-25-2022 17-42-43](https://user-images.githubusercontent.com/23691655/165064192-415447c2-aac5-4163-b7cd-262cdd47e06a.gif)

**Comment by yzbaoo** [comment]
If using React.memo I don't think I need to use recoil

**Comment by drarmstr** [comment]
Updates are based on an atom granularity.  So, if you have separate atoms used by separate components they won't cause siblings to re-render.  However, if you use a shared atom or cause the parent component to re-render, then siblings may also be re-rendered.
