### ISSUE TITLE
Recoil selector not working in Next.JS SSG

### ISSUE THREAD

**Issue by TaeyoonKwon** [facebookexperimental/Recoil#1800]
![image](https://user-images.githubusercontent.com/47032283/168734465-3548ad5a-242f-4a54-8e9e-aff068b7eece.png)

When I use asynchronous selector in Next.JS

It won't build to a static site.

But it works with the same code when I build SSR.

Is it intended or a bug?

**Comment by TaeyoonKwon** [comment]
It seems useRecoilValue() with SSR is not working and userRecoilValueLoadable() is working instead.

**Comment by drarmstr** [comment]
I believe that SSR rendering doesn't really support asynchronous callbacks or React Suspense.  So, an async selector with `useRecoilValue()` will trigger Suspense and not work with SSR. However, a synchronous selector or the `useRecoilValueLoadable()` hook which is synchronous will work.  Please not that if the selector is asynchronous then `useRecoilValueLoadable()` will still return a `Loadable` object in the pending state which may or may not be what you are looking for.
