### ISSUE TITLE
Error: Problem with cache lookup for selector / Attempt to serialize function in a Recoil cache key

### ISSUE THREAD

**Issue by FokkeZB** [facebookexperimental/Recoil#1804]
> **Disclaimer:** I'm well-aware that `cachePolicy_UNSTABLE` is an unstable API and `cachePolicy_UNSTABLE.equality` is even hidden (in TypeScript). I'm reporting this to inform further development of this feature.

# Reproducing CodeSandbox

Source: https://codesandbox.io/s/recoil-cache-lookup-bug-lusj7s?file=/pages/index.tsx:792-812
URL: https://lusj7s.sse.codesandbox.io/
Steps: Select either of the two other available scenarios from the dropdown.

# Error

`useRecoilValue` will throw with:

![](https://cdn.zappy.app/e2ab9e34703fc5ec5fd3b60195e75c9c.png)

# Clues

Also see comments in CodeSandbox: https://codesandbox.io/s/recoil-cache-lookup-bug-lusj7s?file=/pages/index.tsx:792-812

The following combination triggers the bug:

- Outer selector uses the unstable and hidden `cachePolicy_UNSTABLE.equality === 'value'` option and `get`s inner selector.
- Inner selector is async.
- Inner selector returns or throws (an object that contains) a function.

If you remove any of the above the bug is avoided.

**Comment by drarmstr** [comment]
Functions can't really be used for value equality because they can contain closure state which isn't easily captured for serialization and comparison.  I really wish they could...  It would open up some cool opportunities for adding `map()` methods and such..  But, it's an important aspect that could really cause trouble.

**Comment by FokkeZB** [comment]
@drarmstr I understand, but could/shouldn't we make an exception for when selectors throw errors? In our case, the issue is caused by [Axios throwing error objects](https://github.com/axios/axios/blob/master/lib/core/AxiosError.js) that have function properties.

We could assume that selectors that depend on a selector that has thrown an error, always need to be updated whenever that selector updates, even if the new value is again an error. They might "get" the selector via `waitForAllSettled` and behave different depending on the error.

That basically comes down on always using `equality: 'reference'` when the value is a thrown error, even if `equality: 'value'` is configured.

Fundamentally I think we should allow `equality` to take a function so that we as consumers of the library can fully customize the behavior. In this case, we could for example check if both the old and new value is an Axios error and use `.response.status` to compare.
