### ISSUE TITLE
Using setter without subscribing to state (useRecoilSetter?)

### ISSUE THREAD

**Issue by schnerd** [facebookexperimental/Recoil#182]
It seems like it may make sense to allow components to update an atom's state, without subscribing to its changes.

Use case: I have 50 `<BarChart/>`s on a page, and a single `<Tooltip/>` instance shared by all of them:
```
<App>
  {charts.map(c => <BarChart {...c} />}
  <Tooltip/>
</App>
```
When the user hovers on a bar, the bar chart code calls `setTooltipContent` to update the `tooltipContent` atom – but it does not need to read the state value. `<Tooltip/>` needs to read the state, but does not need the setter. With Recoil's current design, all 50 bar chart components re-render every time the tooltip is updated, which is not ideal. Instead I just opted for normal React state, lifting the state into `App` and drilling the setter/value props into BarChart/Tooltip respectively. 

Similar to how useRecoilValue lets you just get the value, maybe useRecoilSetter could just return the setter function? Or atoms could offer a way to set their state outside of react hooks (#179). 

Just wanted to put this use case on your radar, but feel free to close this if its already something you're thinking about or won't support. Loving the direction Recoil is headed, awesome work!

**Comment by drarmstr** [comment]
In fact, Recoil offers the [`useSetRecoilState()`](https://recoiljs.org/docs/api-reference/core/useSetRecoilState) and [`useResetRecoilState()`](https://recoiljs.org/docs/api-reference/core/useResetRecoilState) hooks for this very reason.

Also, keep (`useRecoilCallback()`](https://recoiljs.org/docs/api-reference/core/useRecoilCallback) in mind if you want to set arbitrary atoms/selectors in a callback or read from them in a callback without subscribing.

**Comment by schnerd** [comment]
Ahhh nice! Clearly I didn't dig deep enough into the docs, for some reason I assumed that [this `import` statement in getting started](https://recoiljs.org/docs/introduction/getting-started#recoilroot) showed the full API surface area. Thanks!
