### ISSUE TITLE
Define custom global cache?

### ISSUE THREAD

**Issue by FezVrasta** [facebookexperimental/Recoil#1822]
Hi, I was wondering if there's any way to define a custom cache system to be used by all my atoms?

I'd like to build one off the SharedWorker interface so that I can have all my data automatically synced across windows without having to duplicate it with an effect.

Right now I'm using a synchronization effect that makes use of BroadcastChannel to keep different windows in sync.

**Comment by noritheduck** [comment]
At the moment there is no custom cache system for atoms. There however is a way to configure cache in selectors. Please see `cachePolicy_UNSTABLE` in https://recoiljs.org/docs/api-reference/core/selector/. Hope that helps!
