### ISSUE TITLE
How to return a DefaultValue in read of useRecoilSync?

### ISSUE THREAD

**Issue by ci7lus** [facebookexperimental/Recoil#1824]
Hi, I am referencing an external source in useRecoilSync's read, but when it returns `undefined` or `DefaultValue` it does not fall back to the default value.

### Code

```ts
export const testAtom = atom<boolean>({
  key: `test`,
  default: true,
  effects: [
    syncEffect({ storeKey:"store-key", refine: $.boolean() }),
  ],
})
```
Try1
```ts
  useRecoilSync({
    storeKey: "store-key",
    read: (key) => {
      return store.get(key) || undefined
    },
```
Try2
```ts
  useRecoilSync({
    storeKey: "store-key",
    read: (key) => {
      return store.get(key) || DefaultValue
    },
```

### Occur
`[<root>]: value is not a boolean`

### Environment 

- recoil `0.7.3-alpha.2`
- recoil-sync `0.0.1-alpha.2`

**Comment by noritheduck** [comment]
Hi @ci7lus, have you tried.
`  useRecoilSync({
    storeKey: "store-key",
    read: (key) => {
      return store.get(key)
    } || YOUR_DEFAULT_VALUE,`

**Comment by drarmstr** [comment]
`DefaultValue` is the class, so try creating a new instance of that class with `new DefaultValue()`.

**Comment by ci7lus** [comment]
@drarmstr Thanks!
