### ISSUE TITLE
Feature Request: useRecoilValueMemo and useRecoilValueLoadableMemo

### ISSUE THREAD

**Issue by Qquanwei** [facebookexperimental/Recoil#1831]
Prerequire code 

```
const counterSelector = selector({
    key: 'my counter',
    get: async () => fetch('/some/api')
});

function Counter() {
    const value = useRecoilValue(counterSelector);
    const refreshCounter = useRecoilRefresher(counterSelector);

    const addCounter = useCallback(async () => {
        await fetch('/add/counter');
        refreshCounter();
    }, []);
    
    return (
        <div>
            <div onClick={addCounter}>{ value }</div>
        </div>
    )
}
```

Currently useRecoilValue and useRecoilValueLoadable will cause the page to be replaced by suspense when the selector is refreshed, especially when it is not rendered for the first time, this behavior often interrupts the user's operation, so I propose to add two hooks: useRecoilValueMemo and useRecoilLoadableMemo.

We can easily implement a memoize version

```
export function useRecoilValueMemo(recoilValue) {
    const loadable = useRecoilValueLoadable(recoilValue);
    const ref = useRef(null);

    if (loadable.state === 'hasValue') {
        ref.current = loadable.contents;
    }

    if (ref.current == null && loadable.state === 'loading') throw loadable.contents;

    if (loadable.state === 'hasError') {
        throw loadable.contents;
    }

    return ref.current;
}
```

Same idea for useRecoilValueLoadable. 

```
export function useRecoilValueLoadableMemo(recoilValue) {
    const loadable = useRecoilValueLoadable(recoilValue);
    const ref = useRef(loadable);

    if (loadable.state === 'hasValue') {
        ref.current = loadable;
    }

    if (loadable.state === 'hasError') return loadable;

    return ref.current;
}
```

This can be more smooth for page refresh.

**Comment by drarmstr** [comment]
It appears that `useRecoilValueMemo()` isn't really memoizing, but instead it just returns a Promise to the value instead of suspending with a pending value, since when the state is `loading` then the contents would be a `Promise` instead of `null`. 

A simpler approach may be just to:
```jsx
  const myValueOrUndefined = useRecoilValueLoadable(myRecoilValue).valueMaybe();
```
A difference here is that it returns `undefined` instead of a Promise to the value and an error state would also be `undefined`.  Tweaks to the `Loadable` accessors may be more appropriate for different semantics than proliferating hooks.

**Comment by Qquanwei** [comment]
We can change it in the existing hooks, but I don't know why the value of useRecoilValueLoadable is designed to be undefined, and whether this will cause breaking is unknown.

But for useRecoilValue, this change is breaking, so a new hook may still be needed.

**Comment by Qquanwei** [comment]
We should add new package like `recoil-enhance` , that will provide some great practice hooks.  should we create another new package?

**Comment by signorbusi** [comment]
This is exactly what I've missed! I would love such a hook. Definitely a big +1 from me for this feature.

**Comment by Qquanwei** [comment]
@signorbusi Thanks reply ! 

`recoil-enhance` was published , see also https://github.com/Qquanwei/recoil-enhance
