### ISSUE TITLE
Feature Request: useRecoilLatestValue

### ISSUE THREAD

**Issue by Qquanwei** [facebookexperimental/Recoil#1832]
Prerequire code 

```jsx
const coinSelector = selector({
    key: 'my coin',
    get: async () => fetch('/my/coin')
});

function UserPage() {
    const coin = useRecoilValue(coinSelector);
    const refreshCoinSelector = useRecoilRefresher(coinSelector);

    const onClickDetail = useCallback(async () => {
        // there will request twice, nooooo
        const latestCoin = await fetch('/my/coin');
        refreshCoinSelector();
        showMyCoin(latestCoin);
    }, []);

    return (
        <div>
            { coin }
            <button onClick={onClickDetail}>view detail</button>
        </div>
    );
}
```

In some scenarios, we always need the latest selector value. Get the current value once when you enter the page for the first time, and get the latest state and execute the corresponding logic when you click a button. At this time, the traditional useRecoilValue implementation will be quite complicated.

So I propose to provide a new hook: useRecoilLatestValue, which will return two values [value, refreshAndReturnLatestValue],
This hooks will undoubtedly be implemented more elegantly

```
function UserPage() {
    const [coin, refreshAndReturnLatestValue] = useRecoilLatestValue(coinSelector);

    const onClickDetail = useCallback(async () => {
        const latestCoin = await refreshAndReturnLatestValue();
        showMyCoin(latestCoin);
    }, []);

    return (
        <div>
            { coin }
            <button onClick={onClickDetail}>view detail</button>
        </div>
    );
}
```

**Comment by drarmstr** [comment]
For this type of usage it may make more sense to use atoms instead of selectors to represent your query results.  Instead of "refreshing" the selector you could issue the async query that updates the atom value when finished.  That way the atom will retain the previous value until a new one is available.

**Comment by Qquanwei** [comment]
Thanks for the reply, but atom does not have the ability of selector. If atom is used, it means that a bunch of code logic needs to be manually maintained, especially the loading and error states. As a unifying style, selectors have potential implications for managing asynchronous requests, so expect all GET requests to be made around selectors. So I hope Recoil can provide more about request-related functions.
