### ISSUE TITLE
Set atom using updater function from useRecoilCallback while the atom is initializing asynchronously

### ISSUE THREAD

**Issue by MaxTibs** [facebookexperimental/Recoil#1835]
Hi,

I'm having trouble calling the `set` function of the `useRecoilCallback` hook with an updater function when the default value of an atom is initialized asynchronously.

I get the following error when I try to use the `addConfiguration` function described below:
> Tried to set the value of Recoil selector configurationsState using an updater function, but it is an async selector in a pending or error state; this is not supported.

I found that if I use the `snapshot` provided by `useRecoilCallback` to read the state asynchronously, I'm then able to set the state of the atom without issue. I don't like that solution because writing the state is not supposed to be an asynchronously operation. 

I have an atom effect to read/write from local storage asynchronously:
```ts
    export const syncStorageEffect =
        <T extends any>({ key, defaultValue, useSecureStorage = false }: SyncStorageEffect<T>): AtomEffect<T> =>
        ({ setSelf, onSet, trigger }) => {
            // Storage provide asynchronous read/write to local storage
            const Storage = useSecureStorage ? LocalSecureStorage : LocalStorage;
    
            if (trigger === 'get') {
                setSelf(Storage.getItem(key).then((savedValue) => {
                        if (!_.isNil(savedValue)) {
                            return savedValue;
                        }
    
                        return defaultValue;
                    })
                );
            }
    
            onSet((newValue) => {
                if (newValue instanceof DefaultValue) {
                    Storage.removeItem(key).then(() => setSelf(defaultValue));
                } else {
                    Storage.setItem(key, newValue); // Async
                }
            });
        };
```

My atom and its default value:
```ts
    export const defaultConfigurationState: Configuration[] = [];
    export const configurationsState = atom<Configuration[]>({
        key: 'configurationsState',
        default: defaultConfigurationState,
        effects_UNSTABLE: [
            syncStorageEffect({
                key: CONFIGURATION_STORE_KEY,
                defaultValue: defaultConfigurationState
            })
        ]
    });
```

Finally, I have a custom function that uses recoil callback to update my atom.
```ts
    const addConfiguration = useRecoilCallback(
        ({ set }) => (item?: Partial<Configuration>): Configuration => {
                const newConf = new Configuration(item);
                set(configurationsState, (configurations: Configuration[]) =>([...configurations, newConf]));

                return newConf;
            },
        []
    );
```

What would be the best solution to initialize my state asynchronously and then read/write from it synchronously ?

Thank you!

**Comment by drarmstr** [comment]
Yes, the updater form of setters doesn't currently support async state.  As you point out, reading the current state asynchronously from the snapshot in your callback should work.  It actually is an async operation, not just sync, since the current state it is depending on is async.
