### ISSUE TITLE
Recoil Noob needs help: "TypeError options.get(...) is not a function"

### ISSUE THREAD

**Issue by Kunz-David** [facebookexperimental/Recoil#1838]
Hello,

I have a piece of code that gives an error and I don't know why. Can anyone please help me understand why recoil gives an error here?

What I want is a `selector`, which uses a `selectorFamily` to get some data. The input parameter of the `selectorFamily` is going to be another `selector`, but when trying to make a minimal example I found the problem is elsewhere.

The code can be seen here: https://codesandbox.io/s/elated-waterfall-3lrgp6?file=/src/App.js

Disclaimer: I am new to recoil, react, and javascript.

**Comment by vesai** [comment]
Hi, look carefully on example: https://recoiljs.org/docs/api-reference/utils/selectorFamily/#example

You can see that code:
```
get: (multiplier) => ({get}) => {
    return get(myNumberState) * multiplier;
  },
```

`get` in selectorFamily is not a function that return value. It is function that return function that return value.

In your example you need to fix:
```
const familySeletorState = selectorFamily({
  key: "autocompleteSearcherState",
  get: (term) => () => null
});
```

**Comment by Kunz-David** [comment]
@vesai Thank you! Yes, now I see.
