### ISSUE TITLE
Flow types are not exposed anymore

### ISSUE THREAD

**Issue by FezVrasta** [facebookexperimental/Recoil#1856]
The `cjs/recoil.js` file has been renamed to `cjs/index.js` but the twin `recoil.js.flow` file has not, so Flow can't find the types anymore.

**Comment by drarmstr** [comment]
Thanks, we recently updated our build scripts to support multiple packages and will follow-up on this.  (cc @mondaychen )

**Comment by mondaychen** [comment]
Thanks @FezVrasta. I'm curious, does your PR fully fix the issue in your flow project? I think there "recoil-shared" files are also missing

**Comment by FezVrasta** [comment]
@mondaychen I'm not familiar with recoil-shared, may you help me understand how it works so I can patch that part too?

**Comment by mondaychen** [comment]
Actually -- I think I misunderstood how flow works. `recoil-shared` is not necessary in our use case as long as we don't directly export a flow type from it.

I've tested your change and it works. Thanks!!!
