### ISSUE TITLE
youtube embed videos not responsive

### ISSUE THREAD

**Issue by swaroopRajwal** [facebookexperimental/Recoil#1865]
Hey there, 
I was just going through your official website while I was having my tea and found that the youtube videos you've on your official websites homepage aren't responsive 

Can I contribute to the website ?
I don't know where the websites repo exactly is 

![recoil-home-page](https://user-images.githubusercontent.com/72123851/173984975-7e2d6955-3a27-4444-a2e9-58e5be546b85.png)

**Comment by drarmstr** [comment]
It uses Docusaurus and is in the "docs" branch of this repository.

**Comment by swaroopRajwal** [comment]
I made a PR
#1868
