### ISSUE TITLE
RecoilURLSyncJSON does not render children

### ISSUE THREAD

**Issue by AkifumiSato** [facebookexperimental/Recoil#1867]
I tried recoil-sync, but it seems that `children` in `RecoilURLSyncJSON` are not rendered.

node: v16.14.0
vite: 2.9.9
recoil: 0.7.3
recoil-sync: 0.1.1-alpha.1

```tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import { RecoilRoot } from 'recoil'
import { RecoilURLSyncJSON } from 'recoil-sync'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <RecoilRoot>
      <RecoilURLSyncJSON location={ { part: 'queryParams' } }>
        <App />
      </RecoilURLSyncJSON>
    </RecoilRoot>
  </React.StrictMode>
)
```

ref: https://github.com/AkifumiSato/recoil-sync-with-history

**Comment by drarmstr** [comment]
I think this is just a case where the published alpha package isn't the latest with respect to the source or documentation. Just place your content after the component for now and it should work.

**Comment by drarmstr** [comment]
`recoil-sync` 0.1.0 is now released to match the documentation.
