### ISSUE TITLE
intermediate state updates for asynchronous operations

### ISSUE THREAD

**Issue by rmoorman** [facebookexperimental/Recoil#188]
Hello there,

Looking at the code examples for selectors I was wondering if there is (or could be) a way to do intermediate state updates. So in case calling the selector involves a long running operation, the state can be updated (e.g. for disabling some UI), during the operation updated again (to show progress), and upon success (or failure) updating the state yet again to signal the results.
Maybe using generators could be fitting (a bit like redux-saga when you have a saga putting actions to update state during a long running operation).

Best regards
Rico

**Comment by acutmore** [comment]
Hi @rmoorman.

One way to achieve this with the current API is to use the `useRecoilValueLoadable` hook.

```javascript
function useIntermediateState() {
  const loadable = useRecoilValueLoadable(asyncSelector);
  switch (loadable.state) {
    case "loading":
      return intermediateState;
    case "hasError":
      throw loadable.contents;
    case "hasValue":
      return loadable.contents;
    default:
      throw new Error(`unexpected loadable state ${loadable.state}`);
  }
}
```

Though I can see it being useful to do this in a selector to make it more composable with other selectors. Something like this:

```javascript

const asyncSelectorWithLoadingState = selector({
  // note 'getLoadable' is just an idea, not part of the current API
  get({ getLoadable }) {
    // a change in loadable state would re-trigger this get
    const loadable = getLoadable(asyncSelector);

    switch (loadable.state) {
      case "loading":
        return intermediateState;
      case "hasError":
        throw loadable.contents;
      case "hasValue":
        return loadable.contents;
      default:
        throw new Error(`unexpected loadable state ${loadable.state}`);
    }
  },
});
```

**Comment by drarmstr** [comment]
@rmoorman - selectors support async operations and can work with React ErrorBoundaries or React Suspense in order to automatically update the UI on state changes.  You can also use `useRecoilValueLoadable()` if you want to manually look at the current state during render.  [Please see these examples](https://recoiljs.org/docs/guides/asynchronous-data-queries/)
