### ISSUE TITLE
Is there any alternative to handle errors besides error boundaries?

### ISSUE THREAD

**Issue by blackout1208** [facebookexperimental/Recoil#1887]
I'm looking to handle API errors from an asynchronous query without using ErrorBoundary and crashing the whole user experience.

I see the documentation suggesting throwing an error from an async request, but it is not ideal for UX. Is there another way I can update a different atom in the middle of a selector? I.e., having an atom solely for error messages, and when it has value, the component which subscribed for it will show the message.

For more context, I have a GET endpoint returning data to be saved in an atom. However, depending on the information filled by the user profile in his journey, we want to present an error banner asking them to choose another option.

Thanks

**Comment by noritheduck** [comment]
Hi, from a UX perspective why would ErrorBoundary crash your experience?
