### ISSUE TITLE
Recoil atom weird functionality

### ISSUE THREAD

**Issue by fatcatt013** [facebookexperimental/Recoil#1897]
```
export const shoppingCart = atom({
  key: 'shoppingCart',
  default: [],
});

export const quantityById = selectorFamily({
  key: 'quantityById',
  get:
    (id: number) =>
    ({ get }) => {
      const cart = get(shoppingCart);
      let product: { id: number; quantity: number } | undefined = cart.find(
        (product) => product.id === id,
      );
      if (!product) {
        return 0;
      }
      const indexOfProduct = cart.indexOf(product);
      return cart[indexOfProduct].quantity;
    },
});
```
I use this in my app to get quantity by ID. The shopping cart data has this structure

```
[
{
  id: 1,
  quantity: 5
},
{
  id: 2,
  quantity: 10
},
.
.
.
.
]
```

When the cart.find function iterates through the cart data, it is finding a product with id from the function argument. But when it comes to

`const cart = get(shoppingCart);`

the atom returns `never[]` type and then the `product` variable has `never` type and it gives me these errors in IDE (VS code):

`Property 'quantity' does not exist on type 'never'` on `product.quantity`
`Property 'id' does not exist on type 'never'.` on `product.id`

The weird thing is that the whole application compiles without problem and the functionality runs perfectly. So it is probably just some type relates typescript errors, but even though I would like to have this fixed.

**Comment by drarmstr** [comment]
Just looks like TypeScript can't infer the type of the atom since the default is an empty array.  You can add a type annotation like this:

```jsx
export const shoppingCart = atom<ShoppingCart>({
  key: 'shoppingCart',
  default: [],
});
```
