### ISSUE TITLE
Contradiction in documentation? 

### ISSUE THREAD

**Issue by ahmedlhanafy** [facebookexperimental/Recoil#19]
[Here](https://recoiljs.org/docs/api-reference/core/atom), you're saying that all these hooks subscribe to the atom which contradicts the claim found [here](https://github.com/facebookexperimental/Recoil/blob/bd6c8a7b7c5f888c45a0eb486ee90a60413eb195/src/hooks/Recoil_Hooks.js#L274) 

### First link:
> Most often, you'll use the following hooks to read the value of atoms:
> 
> useRecoilState(): use this hook when you intend on both reading and writing to the atom.
> useRecoilValue(): use this hook when you intend on only reading the atom.
> useSetRecoilState(): use this hook when you intend on only writing to the atom.
> Note all of the hooks above result in the component subscribing to the atom, so the component will re-render on any subsequent updates to the atom.

### Second link:
https://github.com/facebookexperimental/Recoil/blob/bd6c8a7b7c5f888c45a0eb486ee90a60413eb195/src/hooks/Recoil_Hooks.js#L274

**Comment by csantos42** [comment]
@ahmedlhanafy thanks for reporting!! Fixed with https://github.com/facebookexperimental/Recoil/commit/6348f10272fc2b768cc85f8070c710bbcd05ca1d and change is live on https://recoiljs.org/docs/api-reference/core/atom

To clarify `useSetRecoilState()` will not subscribe components to Recoil state.

**Comment by ahmedlhanafy** [comment]
@csantos42 Okay one more nit:

> Most often, you'll use the following hooks to read the value of atoms:
> `useSetRecoilState()`: use this hook when you intend on only writing to the atom.

I think the main purpose of `useSetRecoilState` is to set the state and not read it.

**Comment by csantos42** [comment]
Thanks again @ahmedlhanafy ! Fixed and deployed. Updated wording to

> Most often, you'll use the following hooks to interact with atoms:
