### ISSUE TITLE
<RecoilURLSync> doesn't reset state if param is not present

### ISSUE THREAD

**Issue by koichik** [facebookexperimental/Recoil#1900]
`RecoilURLSync{JSON,Transit}` can take a `param` if the `location`'s `part` is `'queryParams'`.
However, if the new URL doesn't have the part, `RecoilURLSync{JSON,Transit}` doesn't reset a state that syncing it.

for example,

Atom:
```
const nameState = atom<string>({
  key: 'name',
  default: '',
  effects: [syncEffect({ refine: string() })],
})
```

App:
```
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <RecoilRoot>
      <RecoilURLSyncJSON
        location={{ part: 'queryParams', param: 'state' }}
      >
        <Component {...pageProps} />
      </RecoilURLSyncJSON>
    </RecoilRoot>
  )
}
```

1. access to:
`http://localhost:3000/users/1`

2. change name state to `'Foo'`, then URL is changed to:
`http://localhost:3000/users/1?state=%7B%22name%22%3A%22Foo%22%7D`

3. navigate to:
`http://localhost:3000/users/2`

expected: the `name` state is reset to the default (empty string).
actual: the `name` state still `'Foo'`.

I think that this line should return empty `Map()` instead of `null` when `stateStr` is `null`

https://github.com/facebookexperimental/Recoil/blob/1a47a17a577bf9fc96479a1f700368f4817a166d/packages/recoil-sync/RecoilSync_URL.js#L76

**Comment by koichik** [comment]
The example on Next.js is here.
https://github.com/recruit-tech/recoil-sync-next

## Install

```bash
git clone https://github.com/recruit-tech/recoil-sync-next
cd examples/url-sync-json/
yarn
yarn dev
```

# location={{ part: 'queryParams' }} (no problem)

`examples/url-sync-json/pages/_app.tsx`:

      <RecoilURLSyncJSONNext
        storeKey="url-json-store"
        location={{ part: 'queryParams' }}
      >

open http://localhost:3000/

![wo-params-1](https://user-images.githubusercontent.com/355825/179668926-d9db21a3-61b6-43c6-9923-366366edc7ad.png)

1. modify the form.
2. the URL will be updated.
![wo-params-2](https://user-images.githubusercontent.com/355825/179668945-c635199a-801c-4b94-9a02-a0ca1cfde6bd.png)

3. click the "Top" link.
![wo-params-3](https://user-images.githubusercontent.com/355825/179668961-5656cb89-46b1-48f4-bc02-8b6881a7433c.png)

4. the URL will be updated.
5. the recoil states are also updated with the initial values as expected.
![wo-params-4](https://user-images.githubusercontent.com/355825/179668976-3195e274-8d19-4788-b82f-457c17bc2484.png)

## location={{ part: 'queryParams', param: 'params' }} (problematic)

edit `examples/url-sync-json/pages/_app.tsx` as follows:

```tsx
      <RecoilURLSyncJSONNext
        storeKey="url-json-store"
        location={{ part: 'queryParams', param: 'params' }}
      >
```

open http://localhost:3000/
![w-params-1](https://user-images.githubusercontent.com/355825/179668992-ae6fcc23-b3b3-4878-b464-6d36e3c74f92.png)

1. modify the form.
2. the URL will be updated.
![w-params-2](https://user-images.githubusercontent.com/355825/179669002-2ed8812e-916a-4f01-abf6-03e1d739364f.png)

3. click the "Top" link.
![w-params-3](https://user-images.githubusercontent.com/355825/179669010-2da197c1-29d1-4157-aad7-28fbd79b548c.png)

4. The URL will be updated.
5. however, the recoil states won't be updated. (unexpected)
![w-params-4](https://user-images.githubusercontent.com/355825/179669027-4e453022-5de5-428e-8d2b-3e6c3493c889.png)

@drarmstr What do you think?

**Comment by drarmstr** [comment]
@koichik - Sorry for the delay, still haven't gone through all of the backlog since I was out.  Thank you for diving into this! 
 Please feel free to submit a PR with a unit test for this.
