### ISSUE TITLE
[recoil-sync] error TS2307: Cannot find module 'refine'

### ISSUE THREAD

**Issue by koichik** [facebookexperimental/Recoil#1902]
When I use recoil-sync in TypeScript project, tsc reports:

```
node_modules/recoil-sync/index.d.ts:18:9 - error TS2307: Cannot find module 'refine' or its corresponding type declarations.

18  } from 'refine';
           ~~~~~~~~
```

Perhaps it should be `'@recoiljs/refine'` ?

**Comment by drarmstr** [comment]
Hmm, maybe.. we have aliases setup in some of our configuration files.. @mondaychen  may be able to determine what works internally and externally.
