### ISSUE TITLE
Safely modifying atom based on previous state when asynchronously loaded

### ISSUE THREAD

**Issue by maxbarry** [facebookexperimental/Recoil#1905]
I'm having trouble with the situation where I need to modify an atom based on its current state, and that state may be pending as it's asynchronously loaded from storage.

I cant use `set(history, prevState => [ ...prevState, newItem ])`, as Recoil throws an error:
```
Tried to set atom or selector "history" using an updater function while the current state is pending, this is not currently supported.
```
However, if I use the alternative method of waiting for the promise to resolve, I become vulnerable to losing data -- because if the `history` atom is modified multiple times in the same batch, the last call will overwrite previous ones.
```
const history = atom({
    key: 'history',
    effects: [
        localforageEffect(),
    ],
})

// !! This loses data if called more than once per batch
const addToHistory = useRecoilCallback(({snapshot, set}) => async (newItem) => {
    const prevState = await snapshot.getPromise(history)
    const newState = [ ...prevState, newItem ]
    set(history, newState)
}
```
Is there a way to safely modify `history`?

I know not to set a default value, because then `addToHistory` would become vulnerable to losing ALL its data, by using that default rather than the loaded value if it's invoked before `localforageEffect()` can resolve.

**Comment by maxbarry** [comment]
I've also unsuccessfully tried this pattern, but it too loses data if invoked multiple times.
```
const historyEffect = () => ({ setSelf, onSet }) => {
    onSet((newItem, oldValue) => {
        if (oldValue instanceof DefaultValue) {
            setSelf([ newItem ])
        } else {
            setSelf([ ...oldValue, newItem ])
        }
    })
}

const history = atom({
    key: 'history',
    effects: [
        localforageLoadEffect(),
        historyEffect(),
        localforageSaveEffect(),
    ],
})

// !! This loses data if called more than once per batch
const addItem = useRecoilCallback(({set}) => (newItem) => {
    set(history, newItem)
}
```

**Comment by drarmstr** [comment]
Related: #237, #762

**Comment by drarmstr** [comment]
Duplicate of #439
