### ISSUE TITLE
why useRecoilValueLoadable  Trigger only once？

### ISSUE THREAD

**Issue by strongyc** [facebookexperimental/Recoil#1909]
export const activeArchivesType = atom<number>({
  key: 'activeArchivesType',
  default: 1,
  effects_UNSTABLE: [
    localStorageEffect('activeArchivesType'),
  ],
});

export const RecoilGetWorkList = selectorFamily({
  key: 'RecoilGetWorkList',
  get: (queryParameters) => async () => {
    const response = await workService.getWorkList(get（activeArchivesType）);

    return response.data;
  },

});

The above cases  activeArchivesType change is Trigger only once?  on 1 and 2 change RecoilGetWorkList not Trigger request

**Comment by mondaychen** [comment]
I'm not sure what this is about. Can you please follow this format

1. what are you trying to do
2. your code (better if it's a codesandbox demo)
3. expected outcome
4. actual outcome

**Comment by strongyc** [comment]
https://codesandbox.io/s/cool-https-clgdyc?file=/src/services/api.js

problem
1.Switch between 1 and 2   Switch 1 again why RecoilGetUserInfoDo not send request

**Comment by mondaychen** [comment]
In React you need to use `onClick` not `onclick`
