### ISSUE TITLE
Disable "Recoil: Spent N ms computing a cache key?

### ISSUE THREAD

**Issue by FezVrasta** [facebookexperimental/Recoil#1912]
Is it possible to disable these warnings? On CI we fail the build on console messages and this makes the builds flaky.

**Comment by mondaychen** [comment]
This is a dev mode only warning. Is it possible to build in prod mode?

**Comment by FezVrasta** [comment]
We run the tests and I guess they use the dev flag by default. I'm not sure if it's possible to change that without breaking anything around Jest and such

**Comment by mondaychen** [comment]
Why do you need to fail the build on console messages?
If you have to fail on console, I still don't think it's a good idea to disable console output in recoil. You are likely going to to encounter this issue again with other libs
If you use babel, try this plugin? https://www.npmjs.com/package/babel-plugin-transform-remove-console

**Comment by FezVrasta** [comment]
Sorry for the delay in my reply.

We disallow console.logs so that when we run tests we ensure all the console.error, console.warn, etc... are properly handled.

For example, if you do expect your code to throw a console.warn we ask the developers to do `expect(console.warn).toHaveBeenCalledWith('message')` so that we are sure the behavior is consistent.

The problem with this Recoil warning is that it's performance sensitive, so if the runner is more busy than usual it will trigger it, otherwise it will not. As this is not an issue in real-life scenarios we would like to disable it, the problem is that the warning doesn't have a known prefix or code we can use to "whitelist" it, so it's very hard to find a way to get around it.

**Comment by FezVrasta** [comment]
?
