### ISSUE TITLE
useRecoilCallback with async function is very slow

### ISSUE THREAD

**Issue by iahu** [facebookexperimental/Recoil#1913]
using an async function on useRecoilCallback makes setState very slower than using useSetRecoilState before and just then setState without useRecoilCallback.

```js
const useSomeAction = () => {
    return useRecoilCallback(({snapshot, set}) => {
        return async (name) => {
            const state = await snapshot.getPromise(myState)
            state.name = name
            set(myState, {...state}) // slower
        }
   })
}
```

```js
const useSomeAction = () => {
    const setState = useSetRecoilState(myState)
    return (name) => {
        state.name = name
        setState({...state}) // faster
    }
}
```

in my case, setState is a huge work, so the performance is remarkable. it may take 3x to 4x times relate to the faster way.

**Comment by noritheduck** [comment]
Thanks for letting us know - we will investigate further and add this work to our agenda if this is identified as a problem.
