### ISSUE TITLE
RecoilURLSyncTransit's example code is correctly `viewStateChecker`, not `viewStateChecker()`

### ISSUE THREAD

**Issue by AkifumiSato** [facebookexperimental/Recoil#1918]
Since the return value of `custom()` is `Checker`, is the following correct for `examples`?

https://recoiljs.org/docs/recoil-sync/api/RecoilURLSyncTransit#example
```diff
  const ViewState = atom<ViewState>({
    key: 'ViewState',
    default: new ViewState(true, [1, 2]),
-   effects: [syncEffect({ storeKey: 'transit-url', refine: viewStateChecker() })],
+   effects: [syncEffect({ storeKey: 'transit-url', refine: viewStateChecker })],
  });
```

**Comment by noritheduck** [comment]
A `Checker` is  a function which checks if a given mixed value matches a type V, returning the value if it does, otherwise a failure message. `viewStateChecker()` should call the Checker.

export type Checker<+V> = (value: mixed, path?: Path) => CheckResult<V>;

**Comment by AkifumiSato** [comment]
@noritheduck `number()` returns `Checker`, but `viewStateChecker` is already a `Checker`.
```
export function number(): Checker<number>;

const viewStateChecker: Checker<ViewState> = custom(x => x instanceof ViewState ? x : null);
```

In my environment, `refine: viewStateChecker()` causes an error.
<img width="468" alt="viewCheckerError" src="https://user-images.githubusercontent.com/25711332/180327785-5d1ac294-1ce4-4ccf-98de-eb5750997a8f.png">

**Comment by AkifumiSato** [comment]
@drarmstr @mondaychen @noritheduck Could you please check?

**Comment by drarmstr** [comment]
@AkifumiSato - Yup, looks like a typo in the docs!
