### ISSUE TITLE
question about  return function with selector

### ISSUE THREAD

**Issue by yuwenbai1** [facebookexperimental/Recoil#1920]
export const PositionTest = selector({
    key: 'position-Test',
    get: ({ get}) => {
        //can not get real time state inside  the following function???
        //can not get real time state inside  the following function???
        //can not get real time state inside  the following function???
        return (position: MixInfo): NeedData => {
            return get(PositionSecond(position))
        }
    }
})

export const PositionSecond = selectorFamily({
    key: 'position-fixer',
    get: (position: MixInfoExpand) => ({ get }) => {
        console.log('1-2')
        const contractList = get(RealTimeStateChangeOutSide)

contractList. is not real time      closure？

**Comment by noritheduck** [comment]
The `get` is a function that evaluates the value for the derived state. It may return either a value directly, an asynchronous. Could you provide the code for `RealTimeStateChangeOutSide `

**Comment by drarmstr** [comment]
Yeah, the selector get() function should return the evaluated value. If you want the value itself to be a function you may need to use selector.value() or just wrap it in an object or something.
