### ISSUE TITLE
A selector to return atom?

### ISSUE THREAD

**Issue by insertmike** [facebookexperimental/Recoil#1929]
I have a selector, which returns atom values based on some conditions.

I would like to instead return the atom itself, so I can also later use it to update it's value.

E.G

```

export const activeAtom = selector<string>({
  key: "----",
  get: ({ get }) => {
   ...
    if (A) {
      return get(ATOM_A);
    }
    return get(ATOM_B);
  },
});
```

Instead:

```

export const activeAtom = selector<string>({
  key: "----",
  get: ({ get }) => {
   ...
    if (A) {
      return ATOM_A;
    }
    return ATOM_B;
  },
});
```

and then

```
const [a, setA] = useRecoilState(activeAtom);
....

setA("New Val")
```

Is this possible?

**Comment by nvode** [comment]
I'd use the `getCallback` function you get from the selector. From there you can return a callback with returns a setter

This is just pseudo code to demonstrate:

```
selector({
    key: 'key',
    get: ({ get, getCallback}) => {
        return {
            get: get(atom),
            set: getCallback(({ set }) => (value) => {
                set(atom, value)
            })
        }
    }
})
```

**Comment by drarmstr** [comment]
Thanks @nvode for calling out `getCallback()`!  But for the original question, yes, you can include atoms/selectors in atom/selector values or family parameters.
