### ISSUE TITLE
React Sync unhandled promise rejection from store

### ISSUE THREAD

**Issue by zoeyfyi** [facebookexperimental/Recoil#1933]
Returning a promise that rejects, i.e. something like `<RecoilSync read={(key) => Promise.reject("oh no!")}>` causes an unhandled promise rejection.

Full example: https://codesandbox.io/s/react-playground-forked-vic5ng?file=/index.tsx

**Comment by drarmstr** [comment]
The exception error screen is added by `react-error-overlay` used in the codesandbox.io template.  If you close that with the x in the top right then you should see the stringified loadable as expected.

**Comment by drarmstr** [comment]
Add #1944 unit test
