### ISSUE TITLE
Question about the Object.freeze

### ISSUE THREAD

**Issue by miracle0930** [facebookexperimental/Recoil#1940]
Does Recoil only do ```Object.freeze``` on development build? I have an app using Recoil, when I was using ```console.log(Object.isFrozen(snapshot.getLoadable(xxxAtom).getValue())``` inside a RecoilCallback, I got ```true``` if packed under development mode and got ``false``` if packed under the production build.

**Comment by miracle0930** [comment]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/15270493/183560018-9862c572-6f22-4e09-a43b-87e5be697593.png">
According to this image, I guess the answer is true?

**Comment by csantos42** [comment]
You're correct, it's a safe-guard in development mode to help prevent errors (i.e. state mismatches) that may arise when mutating values returned from Recoil state directly. It's turned off in prod to prevent potential perf overhead of freezing. Sometimes mutation is desired, in which case you can turn on the `dangerouslyAllowMutability` flag in atoms & selectors

**Comment by miracle0930** [comment]
Gotcha, thanks!
