### ISSUE TITLE
selectorFamily doesnt return the right instance when used with a connected changing atom

### ISSUE THREAD

**Issue by felixhaeberle** [facebookexperimental/Recoil#1942]
Hey there,

thanks a ton for providing such a great module, I really like it!!

I experienced a strange issue with the following code which fetches a project by a slug:

When changing the projectState atom, the selectorFamily gets stale and doesnt return the correct project data when the projectSlug is changed, but the old project. 

The correct behavior should be that everytime the projectSlug changes, the projectState gets updated and returns the new project. 

That works, until I change the projectState atom from its default state to something else. As if not only the projectSlug is connected backwards to the projectFetch, but also the projectState gets somehow compared and rejected and the old project gets returned.

```js
// set project slug for fetching project data
export const projectSlugState = atom<string | null>({
  key: "projectSlugState",
  default: null,
});

// fetch user data from the server
export const projectFetch = selectorFamily({
  key: "projectFetch",
  get: (projectSlug) => async () => {
    try {
      if (projectSlug === null) return null;

      const response = await client
        .query(GetProjectDocument, {
          slug: projectSlug ? projectSlug : undefined,
        })
        .toPromise();

      return (response.data.project as Project) || null;
    } catch (error) {
      console.error(`projectFetch -> client.query() ERROR: \n${error}`);
      return null;
    }
  },
});

// set user data in the store
export const projectState = atom<Project | null>({
  key: "projectState",
  default: selector({
    key: "projectState/Default",
    get: ({ get }) => {
      return get(projectFetch(get(projectSlugState)));
    },
  }),
});
```

**Comment by drarmstr** [comment]
When an atom has a `default` that is a selector it will only use that dynamic selector value until the atom is set.  Once set then the atom retains the set value until set to something else or reset.  Only if reset will it use the dynamic default selector again.  So, once you set `projectState` to something then it will no longer reference the default selector based on any changed `projectSlugState`.  If you want distinct state per project that switches with the `projectSlugState` then perhaps `projectState` should also be an `atomFamily()`.

**Comment by felixhaeberle** [comment]
I follow your suggestion but I struggle a bit to make it work. 
You are talking about this pattern, right?

```js
// set project slug for fetching project data
export const projectSlugState = atom<string | null>({
  key: "projectSlugState",
  default: null,
});

// set project data in the store
export const projectState = atomFamily<Project | null, string | null>({
  key: "projectState",
  default: selectorFamily({
    key: "projectState/Default",
    get: projectSlug => async () => {
      try {
        if (projectSlug === null || params === null) return null;
  
        const response = await client
          .query(GetProjectDocument, {
            slug: projectSlug ? projectSlug : undefined,
          })
          .toPromise();
  
        return (response.data.project as Project) || null;
      } catch (error) {
        console.error(`projectFetch -> client.query() ERROR: \n${error}`);
        return null;
      }
    },
  }),
});
```

And use it like:

```js
  const projectSlug = useRecoilValue(projectSlugState);
  const [project, setProject] = useRecoilState(projectState(projectSlug));
```

First of all: This doesnt work and the application doesnt load, do I miss something here?

Second: What I don't understand is why I have to import the dependent projectSlug in the component only for providing it to the projectState, cant this be handled by a `get()` in the recoil atomFamily definition?

The use case is fairly simple: I want a project state, this project state should change and fetch a new project whenever the projectSlug gets changed. This project state should be changeable after it loads.

I'm not that far away from a solution I think but I do small thing wrong I suppose. Can you help me?
Thank you very much for your guidance!! 🙏

**Comment by felixhaeberle** [comment]
Hey, nevermind, I fixed it by myself, there was one old `useRecoilValue(projectState) `without an parameter. 😅 
But second question is still open for me? 
Maybe you can point me to the right section in the doc?

**Comment by drarmstr** [comment]
For your second question, check out the [scoped atom wrapper pattern](https://recoiljs.org/docs/api-reference/utils/atomFamily#scoped-atoms) in the docs.
