### ISSUE TITLE
`@recoiljs/refine`'s types export `Path` while the library itself doesn't

### ISSUE THREAD

**Issue by brncsk** [facebookexperimental/Recoil#1950]
I use refine's `Path` class for my zod ↔ refine adapter (see https://github.com/facebookexperimental/Recoil/discussions/1833).

As of `0.1.0`, the TS types of `@recoiljs/refine` seem to indicate that `Path` is exported, however it is not:

```ts
import { Path } from '@recoiljs/refine';

console.log(Path); // → undefined
```

Please either export `Path` or remove it from the type declarations – either is fine by me as I was already mocking it in the library. Thanks, folks!

**Comment by drarmstr** [comment]
`Path` is currently exported as a type, but not the actual class implementation.  I think we want to continue exporting the type so it can be used in custom checker implementations.  @bsouthga, what are your thoughts on exporting the actual class?
