### ISSUE TITLE
Atom Effect (onSet) is not triggered on reset

### ISSUE THREAD

**Issue by Godsenal** [facebookexperimental/Recoil#1955]
Hi.

I found Atom Effect (onSet) is not triggered on reset if it's a first-time call.

Here is codesandbox reproducer.
https://codesandbox.io/s/great-currying-y2sytl?file=/src/App.js

When clicking the first button (only reset with `useResetRecoilState`) there is no console output. It only works after the set atom state with `useSetRecoilState`.

Is this desired behavior?

**Comment by tpAtalas** [comment]
It is working. You should set the value to trigger the reset.

**Comment by drarmstr** [comment]
Also note that state transitions may be batched and `onSet()` may not be called for all intermediate states.
