### ISSUE TITLE
TypeScipt consider useRecoilState as a unknown type

### ISSUE THREAD

**Issue by tvadiep** [facebookexperimental/Recoil#1977]
Hi Team, I'm trying to run some sample codes from Jacques's courses as below

Creating a selector:
```
const eurSelector = selector({
    key: 'eurSelector',
    get: ({get}) => {
        const usd = get(usdAtom)
        return usd * exchangeRate
    },
    set: ({set}, newEurValue) => {
        //@ts-ignore
        const newUSDValue = newEurValue / exchangeRate
        set(usdAtom, newUSDValue)
    },
})
```
Pass it into other component
```
  const [eurValue, setEurValue] = useRecoilState(eurSelector)
  <CurrencyInput
      label="eur"
      amount={eurValue}
      onChange={(eur) => {
          setEurValue(eur)
      }}
  />
```
But I received this error:
```
TypeScript error in /home/dieptrv/diep/recoil-course/src/examples/Selectors.tsx(54,21):
Type 'unknown' is not assignable to type 'number'.  TS2322

    52 |                 <CurrencyInput
    53 |                     label="eur"
  > 54 |                     amount={eurValue}
       |                     ^
    55 |                     onChange={(eur) => {
    56 |                         setEurValue(eur)
    57 |                     }}
```
Although the type of `eur` is number(I printed it out) but the error still raised up. I can run the code by forcing the `Number(eurValue)` but I still don't know why this error occurs. Anyone can give me a help? I'll really appreciate it!

**Comment by drarmstr** [comment]
Can you share a reproducer such as with Codesandbox?  It's likely that TypeScript isn't fully aware of the types used in your `get`/`set` methods and thus can't infer the selector type.  Make sure those are properly annotated.  Another option is to annotate the type of the selector such as `const eurSelector = selector<number>({` or `const eurSelector: RecoilState<number> = selector({`. I usually work in Flow, so please re-open if you have a repro.

**Comment by afsheen-a** [comment]
Able to reproduce this. 
 
In my stateStore file, I have this:
 `
export const offset = atom<number>({
  key: 'offset',
  default: 0,
});
`

In my component file, I have this:
`const [offsetState, setOffsetStaet] = useRecoilState(offset);`

Typescript is throwing this error:
`Argument of type 'number' is not assignable to parameter of type 'RecoilState<unknown>'`

Can you please help in navigating the same?
