### ISSUE TITLE
Recoil utils export

### ISSUE THREAD

**Issue by kentcdodds** [facebookexperimental/Recoil#198]
I realize this is still upcoming and I'm not asking for a timeline or anything. I'm just creating some educational material on this and want to make sure that I'm making the correct assumptions.

All I want to know is that when the utils like `atomFamily` are exported, how will that be done?

```javascript
// option 1 (my personally preferred option)
import {atomFamily} from 'recoil'

// option 2
import {utils} from 'recoil'
const {atomFamily} = utils

// option 3
import {atomFamily} from 'recoil/utils'

// something else?
```

I realize that nobody can make any guarantees until it's actually released, but if someone can give me any idea of what it might be like that would be helpful :)

**Comment by csantos42** [comment]
hi @kentcdodds! The plan at the moment is option #1 -- that change should be landing today or some time this weekend

**Comment by jaredpalmer** [comment]
See my pr #200 or you can install `jared-recoil` for now

**Comment by kentcdodds** [comment]
Wonderful news! Thanks for that :)

**Comment by jaredpalmer** [comment]
`jared-recoil` also has correct TS types.

**Comment by kentcdodds** [comment]
Oh nice! Thanks @jaredpalmer! I published `@kentcdodds/recoil-with-utils` 😅

But I'll use yours instead :)

**Comment by ryansolid** [comment]
Now that #197 is merged.. Publish to npm?

**Comment by mondaychen** [comment]
Guess with 0.0.8 we can close this?

**Comment by kentcdodds** [comment]
Thanks!
