### ISSUE TITLE
query.params.operationKind - Cannot read properties of undefined reading operationKind

### ISSUE THREAD

**Issue by AndonMitev** [facebookexperimental/Recoil#1998]
Hello i do have following query:

![image](https://user-images.githubusercontent.com/32274987/188685764-d6991fd1-8f3c-4a60-9f94-2abab7ab912b.png)

But when i try to execute it, i'm hitting this error:

![image](https://user-images.githubusercontent.com/32274987/188685836-34d0bb0a-aaa4-4bad-9966-9afb1410eabd.png)

**Comment by drarmstr** [comment]
@AndonMitev - Do you have a reproducer for this error, such as with codesandbox.io?  It looks like it might be an issue with the environment compiling the GraphQL queries?

**Comment by psh0706** [comment]
@AndonMitev
hi I had the same issue and I resolved it by adding that "eagerEsModules" option in config file (package.json)

![image](https://user-images.githubusercontent.com/47502552/195259559-cbd67e35-53b9-45c3-8851-8846e6dd740c.png)

i think it was an error in the process of building a typescript modules (actually i'm not sure).
i hope it helps you solve the problem!

**Comment by liamaharon** [comment]
> @AndonMitev hi I had the same issue and I resolved it by adding that "eagerEsModules" option in config file (package.json)
> 
> ![image](https://user-images.githubusercontent.com/47502552/195259559-cbd67e35-53b9-45c3-8851-8846e6dd740c.png)
> 
> i think it was an error in the process of building a typescript modules (actually i'm not sure). i hope it helps you solve the problem!

Adding `"eagerEsModules": true` didn't help for me
