### ISSUE TITLE
Syncs randomly skipped occasionally 

### ISSUE THREAD

**Issue by nahtnam** [facebookexperimental/Recoil#2015]
Hello,

I'm coming across a bug where sometimes the state updates are not being run through recoil-sync and I'm not sure why. I have a button when clicked does the following:

```ts
function addFeedDashboard() {
    const id = v4();
    setDashboardsState(
      produce((draft) => {
        draft.currentDashboardId = id;
        draft.dashboards.push({
          id,
          type: 'feed',
        });
      }),
    );
    navigate(`/dashboards/${id}`);
  }
```

Then when navigated to the page, there is the following code:

```ts
const dashboard = useRecoilValue(dashboardsFeedStateFamily(id));
```

^ which initializes the initial values based on the refine/default value and renders the page.

Finally I have the following wrapper:

```ts
<RecoilSync
        storeKey={CHROME_LOCAL_STORAGE}
        read={async (key) => {
          console.log('read', key);
          try {
            const data = await getStorage('local').get(key);
            if (!data) return new DefaultValue();
            return data;
          } catch (e) {
            // TODO: sentry
            console.error(e);
            return new DefaultValue();
          }
        }}
        write={async ({ diff }) => {
          console.log('write', diff);
          try {
            await Promise.all(
              Array.from(diff.entries()).map(([key, value]) =>
                getStorage('local').set(key, value),
              ),
            );
          } catch (e) {
            // TODO: sentry
            console.error(e);
          }
        }}
      >
```

I tried to reproduce the bug (happens about 5-10% of the time), and as you can see in the screenshot below, it happens in the second to last time. The `dashboards` write is not called but the write for the `ff3a1262-5195-44c8-964e-380a65b18538` dashboard is called. The react app does show the dashboard though, so recoil is holding the state properly, just not syncing it. If I were to refresh the page at that point, the page would not show the new dashboard in the list. Furthermore, the next `dashboards` write contains itself and the second to last data so I'm certain the issue is more with the sync effect than anything else. Is there maybe some sort of debouncing going on? It happens rarely so its hard to reproduce, but enough that people have complained about it. I know there isn't enough information to reproduce the issue but is there anything I can do to help debug the issue?

![image](https://user-images.githubusercontent.com/20051852/190884933-23b0f3a9-91ed-4af7-965d-c97ff0af6504.png)

**Comment by drarmstr** [comment]
Note that one of the goals of recoil-sync is to be able to provide atomic updates for batched state changes.  That means batching multiple atoms that are updated in a batch, but may also include a single atom being updated multiple times in a batch.  The batching is controlled by React and subject to change. Also note that currently atom effects are also based on batch updates and may not include intermediate states.  Though, that is not formally specified and subject to change. So, it is possible that some intermediate updates may be omitted as long as the final state for the batch is consistent.  Does this sound like a reasonable explanation for what you are seeing?  Please do re-open the issue if you have an example repro where the final state of a batch is not captured.

**Comment by drarmstr** [comment]
Might also be related to #2059

**Comment by nahtnam** [comment]
Thank you for following up with the related issue! Your initial explanation made sense but I was never able to figure out why it still wouldn't be consistent all the time. I will follow that thread!
