### ISSUE TITLE
[recoil-sync] Support transactional updateItems() in RecoilSync

### ISSUE THREAD

**Issue by luishdz1010** [facebookexperimental/Recoil#2017]
When syncing from an external store to recoil in the `listen` prop of RecoilSync, each call to `updateItem(k, v)` notifies components associated with each atom's key. However, since not all the state is synced yet (more synchronous `updateItem()` calls pending), some components will observe a "partially" synced state, which can cause errors.

In my case, this is making some components observe deleted state that would otherwise be consistent if all updates were applied before components get notified. 

Using updateAllKnownItems might work, but in my case, the number of atoms is vast and updates are often, so this will do a lot of unnecessary work (assuming updateAllKnownItems has transaction semantics).

**Comment by drarmstr** [comment]
That should be straight-forward if someone want to submit a PR?  Both `updateItem()` and `updateAllKnownItems()` are implemented in terms of `updateItems()` which just isn't exposed yet.
