### ISSUE TITLE
a `phoenix` `Socket` instance couldn't be a value of an `recoil` atom

### ISSUE THREAD

**Issue by nichita-pasecinic** [facebookexperimental/Recoil#2018]
In my understanding everything could be a value of an recoil atom, but this is not the case with the `Socket` class from `phoenix` framework. I need to mention that keeping exactly the same instance of `new Socket()` (from phoenix) in a react state (via `useState`) works perfectly and the `Socket` could be manipulated and worked with, but it is strange that the same instance could not be used inside  a recoil `atom`

Original issue was opened on `phoenix` github repository - https://github.com/phoenixframework/phoenix/issues/4953

I'd appreciate if @chrismccord would give some insides of what exactly should be addressed in `recoil` to identify the issue with this kind of compatibility

Thanks!

**Comment by nichita-pasecinic** [comment]
console errors when invoking some methods from an `Socket` via atom 
![image](https://user-images.githubusercontent.com/98735377/191175698-ad319064-99c3-4dfc-8d69-b9b0ad657012.png)

**Comment by dsvgit** [comment]
@nichita-pasecinic try to add `dangerouslyAllowMutability` prop to atom

**Comment by nichita-pasecinic** [comment]
Hi @dsvgit, I've got an `atomFamily` & `selectorFamily` in combination and applied to both the `dangerouslyAllowMutability: true` and it seems to work for now 😃
Are there any downsides for using this property, why is it `dangerously*` ? 😅

Thanks

**Comment by dsvgit** [comment]
@nichita-pasecinic I'm not so familiar with it just also fixed my cases with this option, you can check it in docs https://recoiljs.org/docs/api-reference/core/atom. 

From docs:
> Recoil manages atom state changes to know when to notify components subscribing to that atom to re-render, so you should use the hooks listed below to change atom state. If an object stored in an atom was mutated directly it may bypass this and cause state changes without properly notifying subscribing components. To help detect bugs like this Recoil will freeze objects stored in atoms in development mode.

But in your case seems like you want to mutate objects that you put in the store. So it depends on your case I think.
