### ISSUE TITLE
useSnapshot may lose snapshots Ids

### ISSUE THREAD

**Issue by salvoravida** [facebookexperimental/Recoil#2048]
Hi there, I have noticed that under heavy workload (ex: a page that loads Monaco-editor) 

useSnapshot does not return all snapshots; since getID are not consecutive, randomly, it loses some ids:

ex: 1, 2,3,5, 8,9,10, 15,16,17 ... getID() result.

Is it normal?

@drarmstr

**Comment by drarmstr** [comment]
Yes, observing snapshots and atom effects observe batches.  React may batch updates and renders. So, it is not guaranteed that you will be re-rendered for all intermediate states
