### ISSUE TITLE
Provide transition support for useSetRecoilState.

### ISSUE THREAD

**Issue by tobias-tengler** [facebookexperimental/Recoil#2052]
`useRecoilState_TRANSITION_SUPPORT_UNSTABLE` works great for us, but I often use `useSetRecoilState` to not have to subscribe to state changes.

Would be great if `useSetRecoilState` could also get a variant that supports transitions. Wrapping the set call in a transition doesn't work.

**Comment by drarmstr** [comment]
`useSetRecoilState()` already supports transitions.  The difference is only necessary when reading state, so that is why only the hooks which read state have a `*_TRANSITION_SUPPORT_UNSTABLE` variant.
