### ISSUE TITLE
dynamically create "mainUser" atom for use in app components

### ISSUE THREAD

**Issue by APoint2020** [facebookexperimental/Recoil#206]
I want to create an atom for the user object. the problem is I use a signin form that makes the authentication and only then creates the atom.

after the creation of the atom the other components should be able to use it.
what is the best way to declare the atom and subscribe the components during the first render ?
I can't create it in the main App.js because it's creation requires the context of <RecoilRoot>

same problem may return in other scenarios where basic app atoms need to be initialized during first load under the context of <RecoilRoot>

any suggestions ?

**Comment by acutmore** [comment]
Hi @APoint2020 

You could use a Promise to initialise the atom before you have the value.

Worth noting that there is currently an issue (#161 and #142) which is preventing this from working with the npm version of recoil.

**Comment by drarmstr** [comment]
Without knowing more perhaps @acutmore 's suggestion of a `Promise` or `selector` atom default may help.  Other options include giving the atom a nullable type and setting it when the user signs in.  Or, wrapping it with a `selector` that could even be async to handle the login.

**Comment by APoint2020** [comment]
Sorry, i don't understand how to do it with a promise. I think it's irrelevant because of the structure of it:

I want a global atom to be used by all components, so i must declare it in the app main scope. however, Recoil would know it only if it's created under <RecoilRoot> scope.

app.js scope
   <RecoilRoot>
        --new atom must be created here in order for recoil to "know" it
   <Components...>

so i need a way to create a new atom during app startup by one of it's components and then make it global somehow so other components can register to it.

with useState its simple - you declare a state in the main app level and send it to sub components using props so they can use it to.
with Recoil - you cant use useRecoilState in the app level - you get an error that this code must run under <RecoilRoot> scope...

**Comment by acutmore** [comment]
Hi @APoint2020 

As @drarmstr mentioned you could use `null` as the default atom value. So that it can be used before the user data has been created.

// atoms.js
```javascript
export const mainUser = atom({
  key: 'mainUser',
  default: null,
});
```

// form.js
```javascript
import {mainUser} from './atoms');

export function Form() {
  const setUser = useSetRecoilState(mainUser);
  ...

  return <button onClick={() => { setUser(user) }}>Set user</button>;
}
```

// component.ts
```javascript
import {mainUser} from './atoms';

export function Component() {
  const user = useRecoilValue(mainUser);
  if (user === null) {
    // user not logged in
  }
  ...
}
```

**Comment by APoint2020** [comment]
thank you @acutmore 
i'll try that
