### ISSUE TITLE
Export useRecoilInterface()

### ISSUE THREAD

**Issue by natew** [facebookexperimental/Recoil#208]
Writing a library around recoil and having this would save a lot of overhead.

**Comment by drarmstr** [comment]
We're hoping to deprecate this API.  What aspect of it do you find useful so we can consider requirements for alternative mechanisms to support it?  (e.g. #134)

**Comment by alidlorenzo** [comment]
@drarmstr after glancing at code, I was also looking to use `useRecoilInterface` so that I could build my own state management utilities on top of recoil, without calling multiple `useRecoilState` hooks.

from reading #134, it seems like the recommended approach is to use `useRecoilCallback` .

**Comment by drarmstr** [comment]
Yes, it is recommended to use a supported mechanism such as `useRecoilCallback()`.  Note that some ongoing work we are doing to enable React Concurrent Mode is changing the semantics of `useRecoilInterface()`, and we expect to deprecate it.

**Comment by natew** [comment]
Yea, I re-opened a different issue here, I forgot I hadn't gotten back here!

Can see example of `useRecoilCallback`.

https://github.com/facebookexperimental/Recoil/issues/451#issuecomment-655243901
