### ISSUE TITLE
I was wondering, why all file formats are '*.js' instead of '.ts'

### ISSUE THREAD

**Issue by AntiMoron** [facebookexperimental/Recoil#2110]
As described in the post title, can anyone explain this? I'm really confused.

**Comment by AntiMoron** [comment]
![image](https://user-images.githubusercontent.com/6587734/203027799-eb1efad3-1125-4b1e-93ef-258bf0c1cae3.png)
Take `Recoil_state.js` as an example.

I found there are type definitions that are only supported in typescript.

![image](https://user-images.githubusercontent.com/6587734/203028069-b68ce2ae-c8ad-402c-8dca-649822859969.png)

**Comment by AntiMoron** [comment]
I feel it not easy to get some research started. I want to know the mechanism of `Recoil` so that maybe I can get my issue in production fixed in someway.

**Comment by impl** [comment]
Recoil is written using [Flow](https://flow.org/), not in TypeScript. So you'll need to set up Flow support for your IDE (see [VS Code instructions](https://flow.org/en/docs/editors/vscode/)) to work with this repo. Hope this is helpful to you!

**Comment by AntiMoron** [comment]
@impl That's helpful, I'll deep dive into that.
