### ISSUE TITLE
0.0.8 typescript selectorFamily

### ISSUE THREAD

**Issue by atanasster** [facebookexperimental/Recoil#212]
Hi, thanks for getting the typecript types exported.

It looks like v0.0.8 of recoil has now published selectorFamily etc, unfortunately @types/recoil 0.0.8 is not exporting them.

May I add my voice to the suggestions to include the types with the main package, as they will eep getting out of sync.

**Comment by drarmstr** [comment]
cc @csantos42

**Comment by vandercloak** [comment]
> May I add my voice to the suggestions to include the types with the main package, as they will eep getting out of sync. 
Ditto 👍 

@atanasster, @csantos42 mentioned here that he is working on the types in DefinitelyTyped. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44756#issuecomment-636562172

If you need something to hold you over until that gets PR'd and merged (like I did) then you can grab the types directly from his DefinitelyTyped fork: https://github.com/csantos42/DefinitelyTyped/commit/090ac0065fb4b992e406a30cbd1e839a70e06cb8

**Comment by csantos42** [comment]
thanks @vandercloak and @atanasster -- the PR for utility types lives in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45206 -- ideally any type related issues will be opened in the DefinitelyTyped repo going forward

We have a team meeting coming up where one of the topics is TS support-- if we end up moving types to the main package we'll let you all know :)
