### ISSUE TITLE
Recoil breaks w/ Next.js (window undefined on server)

### ISSUE THREAD

**Issue by Chrischuck** [facebookexperimental/Recoil#215]
Decided to play around with setting up recoil w/ next.js. The issue is it looks like in development mode, recoil looks for the window object which is undefined when next renders the app on the server.

Digging a little deeper, it stems from [these](https://github.com/facebookexperimental/Recoil/blob/52c3adf447e4f32c16e7e086a553f20d9ea743d7/src/components/Recoil_RecoilRoot.react.js#L123) window calls in dev mode.

For the time being, I created a workaround that I came up with [here](https://github.com/Chrischuck/next-recoil-setup/tree/master/src) essentially loads RecoilRoot(and its children) on the client only.

Would be happy to add a check to see if window is defined before calling any methods on it as well as diving into any other issues that might come up when combing recoil with next :)

**Comment by acutmore** [comment]
Hi @Chrischuck 

An alternative temporary solution is to only use the production version of Recoil.

```javascript
const recoil = require('recoil/dist/recoil.production');
```

**Comment by x4080** [comment]
Hi, is this solved yet ? Or must use workaround like mentioned by @Chrischuck

**Comment by drarmstr** [comment]
@x4080 - It's landing now, but that takes a bit of time...

**Comment by x4080** [comment]
@drarmstr Thanks, I'll wait for it

**Comment by parweb** [comment]
the temporary fix is working with atom but not with atomFamily

**Comment by drarmstr** [comment]
Where is the new error occurring?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
