### ISSUE TITLE
Atom is not waiting for promise used in setSelf

### ISSUE THREAD

**Issue by xotahal** [facebookexperimental/Recoil#2151]
Hey folks 👋 I got this issue with initializing atom in effect by using promise for `setSelf`. I will try to describe the problem:

- There are two atoms. Both are initialized in effect by using `setSelf`.
- There is a selector (`selectAtomValues`) that wraps both of them and concatenates the results of atoms.
- There is also another selector (`firstAtomStateSelector`) that only wraps one of those atoms and returns the value of the atom
- Now when we use only atoms in `selectAtomValues` everything works fine (you can try by uncommenting line 38)
- But if we use `firstAtomStateSelector` to get `firstAtomState` value it will not wait for `secondAtomState` and it displays default value of the atom. Later (after 3s delay) you can see the promise resolves to correct value but nothing is re-rendered. And even if it would be re-rendered it is probably not correct behaviour.

Here is repro: https://codesandbox.io/s/recoil-issue-with-promise-effect-l6ddpd?file=/src/App.js

**Comment by drarmstr** [comment]
I wonder if markRecoilValueModified(store, node); just needs to be added here: https://github.com/facebookexperimental/Recoil/blob/main/packages/recoil/recoil_values/Recoil_atom.js#L244 and here: https://github.com/facebookexperimental/Recoil/blob/main/packages/recoil/recoil_values/Recoil_atom.js#L252

**Comment by xotahal** [comment]
I tried this locally and seems it works. Any chance I could get a PR into this repo?

**Comment by drarmstr** [comment]
Would you be up for adding a unit test?  Otherwise I think @csantos42  might be able to look this weekend?

**Comment by xotahal** [comment]
I was trying to, but I got some failing tests when I ran tests locally on the clean repo. I tried to follow the steps you guys have in Github Actions. But no luck. This fails all the tests. I guess I have a different version of something.

<img width="1040" alt="Screenshot 2023-04-01 at 10 46 02 AM" src="https://user-images.githubusercontent.com/3531955/229264182-1e048140-8a58-43bc-9149-83cff9780fb2.png">

**Comment by drarmstr** [comment]
Yeah, that looks like an issue with the version of Flow as that syntax was added more recently.

**Comment by xotahal** [comment]
I had to change the code a bit but finally, I made the tests work (I won't commit these changes). I would appreciate a little hint anyway. Here is what I put together - https://github.com/facebookexperimental/Recoil/commit/42ff9410e3399b5765c426f298b09e5fc6d6c5b2

I've done my best in following the rest. But still can't make it pass.

1. I am unsure if this test should be part of atom tests or selector tests since it touches both of them.
2. It still returns `a-async/b-default`. Without any change to the codebase. Seems like it runs `atomA` effect fine. But it doesn't run the `atomB` effect. This works fine in production so I think there will be something wrong with the test. Should I run/clear anything else?

**Comment by drarmstr** [comment]
> I am unsure if this test should be part of atom tests or selector tests since it touches both of them.

It would make sense for Atom tests under the effects group since it is related to interactions of atom effects.  A more apt title might be "Atom initialized with promise update downstream selectors when resolved"

> It still returns a-async/b-default. Without any change to the codebase. Seems like it runs atomA effect fine. But it doesn't run the atomB effect. This works fine in production so I think there will be something wrong with the test. Should I run/clear anything else?

Might just need to use the following to wait for the changes:
```jsx
    await flushPromisesAndTimers();
```

**Comment by drarmstr** [comment]
@xotahal - Was that sufficient to fix the test?

**Comment by xotahal** [comment]
@drarmstr Well, I've done the updates you asked for ([here is the commit](https://github.com/facebookexperimental/Recoil/commit/c93ca3aed34c8ec739af4fbd2712898b3cd2cf9b)). I moved the tests to atom and removed `setTimeout`. I used `flushPromisesAndTimers` to wait for updates. I am unsure about using the `ReadsAtom` component to read the `directSelector`. But based on its implementation it should be fine. It just renders the value.

The problem is that the actual code doesn't make a difference to the test. It passes either way. If I add or remove `markRecoilValueModified(store, node)` lines. Which makes the test a little bit useless 😀

There has to be something more that triggers an update of React and makes it fail in the `codesandbox` example. Something more I need to call after `resolveA?.('a-async')`?

**Comment by xotahal** [comment]
I did actually try to add redundant `flushPromisesAndTimers` also some extra `act(() => undefined)` but no luck with breaking that. 

I can create PR 👍

**Comment by DouglasArmstrong-at** [comment]
Targeted for 0.7.8 release

**Comment by drarmstr** [comment]
Targeted for 0.7.8 release.
