### ISSUE TITLE
Can't import from 'recoil'

### ISSUE THREAD

**Issue by kaonashi164** [facebookexperimental/Recoil#217]
Anybody help me, I use recoil with react-native but when I import {} from 'recoil' I can't build my app but when I change to 'recoil/dist' so it work. Import from 'recoil/dist' not work with typescript.

**Comment by acutmore** [comment]
Hi @kaonashi164 

> Import from 'recoil/dist' not work with typescript.

Could you provide any more information about your `tsconfig`? Maybe this will work:

```typescript
declare function require(path: string): unknown;
const Recoil = require('recoil/dist') as unknown as typeof import('recoil');
```

>  I use recoil with react-native 

Might be worth looking at #99 for some other issues you may have using Recoil in React Native.

**Comment by kaonashi164** [comment]
> ```ts
> declare function require(path: string): unknown;
> const Recoil = require('recoil/dist') as typeof import('recoil');
> ```

Thanks, it work for me <3

**Comment by acutmore** [comment]
> Thanks, it work for me <3

Great that it worked. You shouldn't _need_ to do that so there might be something not configured corrected that you'll want to fix in the future. Good luck!
