### ISSUE TITLE
Question on setup of 'Clearing Selector Caches' 💡 

### ISSUE THREAD

**Issue by ejmvy** [facebookexperimental/Recoil#2189]
Hi everyone, have been using recoil for a few months and loving it so far. Thanks for all the work!

I'm testing my app for user interactions and updating our atoms. However like this issue in https://github.com/facebookexperimental/Recoil/issues/1480  and https://github.com/facebookexperimental/Recoil/issues/972  i'm unable to clear the cache of my state before the next test runs. 

I know this ticket resolved and the docs were updated with https://recoiljs.org/docs/guides/testing/#clearing-all-selector-caches

I have tried to implement it as shown but it's not making any difference, and any tests i conduct carry with it previous state updates, to which I would have wanted it to be cleared and reset to default. 

This is how I was implementing it initially?
<img width="461" alt="image" src="https://user-images.githubusercontent.com/36888381/222185689-b39049e5-5948-4fdf-851d-77266c76ee4b.png">

is there any difference having it the snapshot in the afterEach?
<img width="551" alt="image" src="https://user-images.githubusercontent.com/36888381/222186261-6c46168a-5caf-41de-b48c-3b5b3f574a61.png">

After that i'm carrying out basic jest tests on updating an atom we have for filters 
```
export const selectedFiltersState = atom<SelectedFilterObject>({
  key: "SelectedFiltersState",
  default: {
    brands: [],
    countries: [],
    articleTypes: [],
    seasons: [],
  },
});
```
Then in our test we render our component with the recoil wrapper including the observer of the atom's state we want to watch.
This works fine the first time. 
<img width="621" alt="image" src="https://user-images.githubusercontent.com/36888381/222190124-38426661-24f7-42f7-97bd-f531b72712e6.png">

But if we move onto the second test and target brands for example, when we make an assertion that only brands have updated within the atom it will fail as it contains the country value from the previous test as the atom didn't clear before the test ran.

I know you had a solution to this, so i'm just wondering if you can spot if i'm doing anything wrong with how i'm clearing the cache initially or after each test running ! 😅 

Thanks again for your help in advance!

**Comment by aghouas** [comment]
Having the same issue. What turned out to be the solution here?
