### ISSUE TITLE
What is the best pattern for partial renders with Suspense?

### ISSUE THREAD

**Issue by DynamicArray** [facebookexperimental/Recoil#225]
I'm trying Recoil in an app with react-leaflet, using selector to async load some polygon data over a base map. The Polygon is rendered as children component.

However, since the map shifts its center based on the polygon, it is also consuming this selector.

My problem is that, due to the Suspense wrapper, the map doesn't render at all when the polygon data is loading. What I'd like to happen is the map display anyway (without the polygon) and then be re-rendered once the polygon data is loaded, since the polygon can change as user selections change.

Is there a better pattern for my selector to allow one component not to mind that data is incomplete or missing but a child one still to suspend? Or, perhaps, just skip Suspense altogether for this data?

The parent map component is reading the state value with useRecoilValue, and passing the result through to the child as props.

`
        export const areaPolygonState = selector({
            key: 'areaPolygonState',
            get: async ({ get }) => {
                const area = get(areaState);

                if (area.id) {
                    const r = await getPolygon(area.id);

                    if (r.result && r.result.polygon) {
                        return r.result.polygon;
                    }
                }

                return null;
            },
        });
`

**Comment by acutmore** [comment]
Hi @DynamicArray 

Sounds like you are after [useRecoilValueLoadable](https://recoiljs.org/docs/api-reference/core/useRecoilValueLoadable).  This lets a component try and access a RecoilValue that might still be loading.

**Comment by DynamicArray** [comment]
Thank you! That does the job perfectly.
