### ISSUE TITLE
Can't use Recoil in Nextjs with app router.

### ISSUE THREAD

**Issue by thesatyam05** [facebookexperimental/Recoil#2261]
TypeError: createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. 

file: layout.js
nextjs with /app directory

```import { Inter } from 'next/font/google';
import { Footer } from '@/components/Footer';
import { Header } from '@/components/Header';
import { Toaster } from 'react-hot-toast';
import { RecoilRoot } from 'recoil';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
	return (
		<RecoilRoot>
			<html lang='en'>
				<body className={inter.className}>
					<div className=' relative'>
						<Toaster />
						<Header />
						<main>{children}</main>
						<Footer />
					</div>
				</body>
			</html>
		</RecoilRoot>
	);
}
```

adding "use client" directive solve the issue, but it make whole app client side right?

need help!

**Comment by Azganoth** [comment]
Seems like it is actually intended to work that way.

I suggest reading this:
https://nextjs.org/docs/getting-started/react-essentials#server-components

and how to use contexts without making the whole app client side:
https://nextjs.org/docs/getting-started/react-essentials#context

**Comment by prunusnira** [comment]
You can use wrapper using client component.
Not only for recoil, you can use it for every libraries which only works for client components

This wrapper component itself is client component, but you can still use server components as children.
check the second link from @Azganoth above

```typescript
'use client';

import { RecoilRoot } from 'recoil';
import { ReactNode } from 'react';

const RecoilRootWrapper = ({ children }: { children: ReactNode }) => (
    <RecoilRoot>{children}</RecoilRoot>
);

export default RecoilRootWrapper;

```

**Comment by thesatyam05** [comment]
> You can use wrapper using client component. Not only for recoil, you can use it for every library which only works for client components
> 
> This wrapper component itself is client component, but you can still use server components as children. check the second link from @Azganoth above
> 
> ```ts
> 'use client';
> 
> import { RecoilRoot } from 'recoil';
> import { ReactNode } from 'react';
> 
> const RecoilRootWrapper = ({ children }: { children: ReactNode }) => (
>     <RecoilRoot>{children}</RecoilRoot>
> );
> 
> export default RecoilRootWrapper;
> ```

thank you @prunusnira

**Comment by duychip0909** [comment]
but now i wondering that if there is use client in RecoilRootWrapper so how can i SEO my page if the layout is inside RecoilRootWrapper?

**Comment by sae1013** [comment]
This is what i'm currious. 
wrapping root component by 'use client' doesn't seem good practice.
it's same as defining only using CSR.

**Comment by hrutik7** [comment]
> but now i wondering that if there is use client in RecoilRootWrapper so how can i SEO my page if the layout is inside RecoilRootWrapper?

yes man do you got any solution for this ?
