### ISSUE TITLE
Cannot destructure property 'error' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by iDavidB** [facebookexperimental/Recoil#227]
Hi,

I ran into an issue where I get the following error "Cannot destructure property 'error' of 'undefined' as it is undefined.". Far as I could tell this seems to be a bug rather than a mistake on my end, but feel free to correct me.

I was able to reproduce it in [CodeSandbox](https://codesandbox.io/s/wonderful-kapitsa-d0xoy?file=/src/App.tsx)

**Comment by acutmore** [comment]
Hi @iDavidB 

The codesandbox link might have changed as it's now showing a different error.

The error it is showing at the moment is caused by using an async selector without providing a `<Suspence fallback={"Loading"}>` wrapper.

https://reactjs.org/docs/concurrent-mode-suspense.html

**Comment by iDavidB** [comment]
Hi @acutmore,

I was hoping to see the Suspense error as it should have, strangely it gave me it now too after coming back to it. But after adding the suspense component it will go back to the previous error: [CodeSandbox](https://codesandbox.io/s/wonderful-kapitsa-d0xoy?file=/src/App.tsx)

**Comment by acutmore** [comment]
Hi @iDavidB 

I could get that link to work by changing a few little things:

```javascript
const ApiData = selector({
  key: "apiData",
  get: async () => {
    const res = await fetch("https://catfact.ninja/fact") // add 'https://'  
      .then(response => response.json())
      .catch(e => {
        console.log(e);
      });

    return res;
  }
});

export default function App() {
  const value = useRecoilValue(ApiData);
  // convert value to a string before using in the DOM
  return <div className="App">{JSON.stringify(value)}</div>; 
}

```

**Comment by DynamicArray** [comment]
@iDavidB This worked for me:

`
const ApiData = selector({
  key: "apiData",
  get: async () => {
    const res = await fetch("https://catfact.ninja/fact");
    return res.json();
  }
});

export default function App() {
  return <Suspense fallback={<p>Wait!</p>}>
    <SampleKid/>
    </Suspense>
}

function SampleKid() {
  const value = useRecoilValue(ApiData);

  return <div className="App">{value.fact}</div>;
}`

**Comment by iDavidB** [comment]
Thanks both @DynamicArray @acutmore. Strangely however when forking @DynamicArray solution it gives me the error again. But i'm guessing it has to do with fetch rather than Recoil then.

**Comment by jonthomp** [comment]
https://github.com/facebookexperimental/Recoil/pull/199

**Comment by iDavidB** [comment]
Ah. Thanks @jonthomp! Closed.

**Comment by MrKirat** [comment]
Hi, I use the master branch of recoil package but I got this error even without using recoil selectors.

**Comment by MrKirat** [comment]
Hi, I'm not using recoil selectors but I faced the same error `Cannot destructure property 'error' of 'undefined' as it is undefined`. As I can see [these changes ](https://github.com/facebookexperimental/Recoil/pull/199) are not released yet. 
@jonthomp Could you please help me with how I can use the master branch of the recoil package?

**Comment by MrKirat** [comment]
@jonthomp I tried to specify `"recoil": "facebookexperimental/recoil#master"` in my package.json, but after running the `npm install` command the `dist `folder was absent in the `node_modules/recoil `directory.

**Comment by MrKirat** [comment]
@jonthomp ohh... I found that I forgot to add unique keys for my recoil atoms :) sorry, it was my fault, now everything works fine on 0.0.8 version.

**Comment by Umarkhan05** [comment]
Had same error 
Before code:
app.use('/user', userRouter);
app.use(bodyParser.json());


Problem solved by writing bodyparser above middleware route.
app.use(bodyParser.json());
app.use('/user', userRouter);
