### ISSUE TITLE
detect circular dependencies in callback

### ISSUE THREAD

**Issue by dakom** [facebookexperimental/Recoil#2271]
Codesandbox demo: https://codesandbox.io/s/clever-hofstadter-s73j3d?file=/src/App.js

When running as-is, the recoil-callback never sees new values. 

If you uncomment line 48, which does nothing other than use the same atom being read in the callback, then a "circular dependency" error is shown (codesandbox has it on the second error page):

> Recoil selector has circular dependencies: a → b

Is it possible to get this error when executing a callback or, more generally, snapshot read, too?

**Comment by csantos42** [comment]
We should probably log the error in dev to make it more clear when working with snapshots, but from the codesandbox I think it's behaving as expected as the `.contents` of the loadable points to an `Error` object which gets stringified to `{}`. To get the desired behavior the loadable value should be read using `.getValue()`, which will throw an error if the loadable is in an error state.

**Comment by dakom** [comment]
ah, good catch! updated fork here: https://codesandbox.io/s/zealous-voice-y5c24s?file=/src/App.js

**Comment by dakom** [comment]
suggestion: `valueOrDefault(() => myDefault)`

when I have a Loadable, it's usually in situations where I do _not_ want `getValue()` (i.e. I don't want suspense), but the boilerplate of checking `state` or wrapping `valueOrThrow()` in a try/catch is a bit noisey
