### ISSUE TITLE
Recoil and React Navigation Problem for React Native

### ISSUE THREAD

**Issue by burakgokcinarr** [facebookexperimental/Recoil#2276]
Hi,

React Native does not work properly when Recoil and React Navigation are used together ( RecoilRoot and NavigationController )

The content of my app's package.json;

![Ekran Resmi 2023-08-22 09 55 51](https://github.com/facebookexperimental/Recoil/assets/18294228/f0dd19a9-ea24-45a7-915b-6f54eee36a14)

This is my starting code.

![Ekran Resmi 2023-08-22 09 57 34](https://github.com/facebookexperimental/Recoil/assets/18294228/b4911c08-75f6-47f7-b323-79aad3e45a7b)

But in this case, I see blank on the screen. ( Components are available ) But when I define my home page directly without using NavigationController it works fine.

![Simulator Screenshot - iPhone 14 Pro - 2023-08-22 at 09 59 45](https://github.com/facebookexperimental/Recoil/assets/18294228/93161880-1428-4e57-a196-91f6d55a38d8)

![Ekran Resmi 2023-08-22 10 00 20](https://github.com/facebookexperimental/Recoil/assets/18294228/0e49e958-e878-4f31-9721-22107663ed32)

![Simulator Screenshot - iPhone 14 Pro - 2023-08-22 at 10 00 48](https://github.com/facebookexperimental/Recoil/assets/18294228/fdb42123-5ea4-4a8f-9924-de8be89518d1)

Have you encountered this? Am I doing it wrong :(

**Comment by bilalfawadkhan** [comment]
I am confused to see that in one example which it is working your putting component Directly but in the first one your router is one tag isn't it supposed to be be a whole enclosing tag with route pointing to the page ?

**Comment by burakgokcinarr** [comment]
The label on the first is actually where all my routes are. (GalleryPage.js, ProfilePage.js, EditPage.js etc...) If I point directly to my page in the 2nd case, it works fine, but if I do it like the first one, it doesn't.

**Comment by dskoneczny** [comment]
@burakgokcinarr Did you find a solution? I have the same issue

**Comment by theDevSoham** [comment]
@burakgokcinarr I'm facing the same issue. What I did is changed some code inside the recoil root and the screen rendered perfectly even inside navigation container. So my hard guess is that the Suspense call is running indefinitely on the first render and  suspense action stops the moment app is re rendered and dom tree refreshes. Will have to test more before confirming though.

**Comment by Shiva-cmd** [comment]
Hi,
 use "useRecoilValueLoadable" instead of "useRecoilValue"
