### ISSUE TITLE
How to share state operation ?

### ISSUE THREAD

**Issue by xialvjun** [facebookexperimental/Recoil#23]
With ContextAPI :
```js
cosnt CounterContext = React.createContext(null);
const CounterProvider = (props) => {
  const [value, setValue] = useState(0);
  const add = useCallback(() => setValue(s => s+1));
  return <CounterContext.Provider value={{value, add}}>
    {props.children}
  </CounterContext.Provider>
}
```

But with recoil, can we :
```js
const counterDefault = {
  value: 0,
  add() {
    counterDefault.value += 1;
  },
}
atom({
  key: 'counter',
  default: counterDefault
})
```

Of course the code above is wrong, but how could we share state operation ? 
With context it's easy because operation closure has captured the real `setState` function. 
But with recoil, how to do it ?

By the way, @davidmccabe , can you open source your demo in the introduction video ? I still don't know how to use recoil to handle undefined number of state.

**Comment by davidmccabe** [comment]
Here's how I would do it:

```
function useCounter() {
  const [value, setValue] = useRecoilState(countAtom);
  const add = useCallback(() => {setCount(x => x + 1)});
  return {value, add};
}
```

To make a family of atoms, just create a memoized function that returns a distinct atom for each state:

```
memoize(id => atom({
 key: `whatever${id}`,
 default: 123,
}));
```

where `memoize` is any memoization function you provide.

We are going to open-source a utility called `atomFamily`/`selectorFamily` that does this for you in the near future.

**Comment by davidmccabe** [comment]
Actually I think it's already in the repo, the build just isn't configured to include it. If you can figure out how to set up the build to include the RecoilUtils module as a separate module e.g. `recoil/utils` in the built output, that'd be a nice PR.

**Comment by tony-go** [comment]
I give a try https://github.com/facebookexperimental/Recoil/pull/33

Hope it help :)

**Comment by xialvjun** [comment]
Thanks. 
In fact, I'm so dumb that I missed the point of your answer. I used to think we need to copy code in every component like:
```js
// counterAtom.js
export const counter = atom({
  key: 'counter',
  default: 0,
});
export const operations = (setValue) => ({
  inc: () => setValue(s => s+1),
  dec: () => setValue(s => s-1),
});

// myCom.jsx --- copy the code everywhere
const [value, setValue] = useRecoilState(countAtom);
const operations = useMemo(()=>counterOperations(setValue));
```

I forgot to use hook to extract logic to outside of component.
Just a mark.
