### ISSUE TITLE
is there a difference between atomFamily default and selectorFamily get?

### ISSUE THREAD

**Issue by alexandrzavalii** [facebookexperimental/Recoil#230]
Was a bit confused by this two approaches.
```
const userInfoQuery = atomFamily({
    key: 'UserInfoQuery',
    default: async userID => {
        const response = await myDBQuery({userID});
        return response;
  });
```
and
```
const userInfoQuery = selectorFamily({
    key: 'UserInfoQuery',
    get: userID => async () => {
        const response = await myDBQuery({userID});
        return response;
    },
});
```
They both will be recomputed if we pass new `userID`. 
So if we don't need `get` or `set` then we can use `atomFamily`?

**Comment by alexandrzavalii** [comment]
Assuming they are used like this
```
const Comp = () => {
   const val = useRecoilValue(userInfoQuery(userId))
}
```

**Comment by acutmore** [comment]
Hi @alexandrzavalii 

One difference between `Atom::default` and `Selector::get` is that the default will only run once, but the Selector get will run again if it accesses other RecoilValues. For example:

```javascript
const userInfoQuery = selectorFamily({
    key: 'UserInfoQuery',
    get: userID => async ({get}) => {
        const pageToLoad = get(pageIndex); // changes to pageIndex will trigger a re-run
        const response = await myDBQuery({userID, page: pageToLoad});
        return response;
    },
});
```

**Comment by alexandrzavalii** [comment]
@acutmore thanks for your reply!
I wonder if there is any difference in the code that I wrote in the question. In my example selector does not use 'get'.
In atomFamily, looks like `default` will be called again if the userID changes.

**Comment by cybervaldez** [comment]
> @acutmore thanks for your reply!
> I wonder if there is any difference in the code that I wrote in the question. In my example selector does not use 'get'.
> In atomFamily, looks like `default` will be called again if the userID changes.

In your selector you don't have a get inside your get functions so no subscriptions are made that would trigger the re-runs.

@acutmore wouldn't a key called subscribe be more accurate?

**Comment by acutmore** [comment]
> I wonder if there is any difference in the code that I wrote in the question. In my example selector does not use 'get'.

Understood. I misread your original post, I thought you were asking if there was a difference between AtomFamily and SelectorFamily.

A difference in the behaviour for your code will be that `atomFamily` returns a ReadWrite RecoilValue, whereas the `selectorFamily` will return a read-only RecoilValue.

**Comment by alexandrzavalii** [comment]
@acutmore Okay so if I understand you correctly, if I use `useRecoilValue`, then there is no difference if I use `selectorFamily` or `atomFamily`
```
const Comp = () => {
  const val = useRecoilValue(userInfoQuery(userId))
  return val
}
```
Seems a bit misleading to met that you can achieve exactly the same thing, with quiet different api's

**Comment by acutmore** [comment]
Hi @alexandrzavalii 

Another difference is that the current (useTransactionObservation_UNSTABLE)[https://recoiljs.org/docs/guides/persistence] hook only provides access to atoms - this may change in the future but it is an example of how Recoil could treat Atoms and Selectors differently. Over time more differences may appear between the two. For example a Recoil DevTools may display Atoms and Selectors differently.

Hope that helps.

**Comment by alexandrzavalii** [comment]
yes, it does! Thanks for the info! 
haven't looked at useTransactionObservation yet

**Comment by acutmore** [comment]
Great! As the docs say "[useTransactionObserver] API is currently under development and will change." So not something to use right now, but just an email of another difference :).

**Comment by drarmstr** [comment]
Both expose the same interface and both may be read/writeable (if the selector provides a `set`).  

Atoms represent and maintain state while selectors represent functions.  Use atoms when you need state and a selector when it is derived from other state or async requests.  

In reality, atoms with asynchronous defaults are actually implemented by wrapping with a selector.  It's provided as a convenience.  So, to your original question, the `atomFamily` would actually construct selectors to get the async data as well as atoms with state that then go unused if you never set the atom.

**Comment by alexandrzavalii** [comment]
@drarmstr hmm interesting.
In the docs we have this selector
```
const userNameQuery = selectorFamily({
  key: 'UserName',
  get: (userID) => async ({get}) => {
    const response = await myDBQuery({userID});
    if (response.error) {
      throw response.error;
    }
    return response.name;
  },
});
```
It was missleading to see the `get` there even though it is not used.
Would it be okay to remove it?
