### ISSUE TITLE
Question: how to handle get/set for async state

### ISSUE THREAD

**Issue by RomeroDiver** [facebookexperimental/Recoil#239]
Hi,
after watching the awesome video on Recoil, I almost rushed to delete Redux and use Recoil on a large production project with no questions asked. It's a miracle though that I decided to first try it out. 

I've seen similar questions in the issues already, but they don't seem to answer the question - how do you handle setting an async state?.
E.g. we have a companies list, and we want to fetch the companies from the API, and then add new company to the list. From what I understand, I could do sth like this:
```
export const companiesState = atom({
  key: 'companiesState',
  default: [],
});
export const companiesQuery = selector({
  key: 'companiesSelector',
  get: async ({ get }) => {
    get(companiesState);
    const response = await fetch('http://localhost:9000/companies');
    return await response.json();
  },
  set: async ({ set, get }, newCompany) => {
    const response = await fetch('http://localhost:9000/companies', {
      method: 'POST',
      body: JSON.stringify(newCompany),
      headers: {
        'Content-Type': 'application/json',
      },
    });
    const company = await response.json();
    set(companiesState, [company]);
  },
});
``` 
Confusing parts for me are:
- do I need to set the `get(companiesState);` dependency. All I need is to e.g. push the new company to the list. I could do `companiesState || fetch(...)` in the getter, but that doesn't seem to be a good thing(?) as there wouldn't be an easy way to refresh the state
- what's the difference between **selector** and **atom**? As far as I can get, the only difference is that selector can be readonly, as atom is always writable. The docs state that `selector is a derived state` but then I see in the articles and issues selector being used as a state, not always derived from something
- would you say that in this case, the getting/posting data should be handled in the useEffect in the component instead of the state itself?

Anyway, the library looks very promising - kudos to everyone working on it!

**Comment by drarmstr** [comment]
An atom represents state, while a selector represents a function (think of it as a node in a data-flow graph that can depend on other nodes, atoms, or async requests).  Selectors are logically "pure" functions based on their inputs.  So, I don't recommend using selectors to model async requests for mutable state that may change.  We use them a lot for read-only database queries that don't change over the lifetime of the app.  For you use-case of trying to sync local and remote state, an atom probably makes more sense as the local state and then syncing it with the remote API.  For now, useEffect is one way to accomplish this.  We're working on the persistence API now which I hope will make this much cleaner in the future and we are keeping your use-case in mind.

**Comment by stephanoparaskeva** [comment]
> An atom represents state, while a selector represents a function (think of it as a node in a data-flow graph that can depend on other nodes, atoms, or async requests). Selectors are logically "pure" functions based on their inputs. So, I don't recommend using selectors to model async requests for mutable state that may change. We use them a lot for read-only database queries that don't change over the lifetime of the app. For you use-case of trying to sync local and remote state, an atom probably makes more sense as the local state and then syncing it with the remote API. For now, useEffect is one way to accomplish this. We're working on the persistence API now which I hope will make this much cleaner in the future and we are keeping your use-case in mind.

I think it would be nice to have an easy way of setting something to atomic state but also being able to observe the loadable. Right now we can set X to atomic state, but I can't find a way to view the status of X ('loading', 'hasContent') etc, while using useEffect. Currently it is always 'hasContent'.

One way to do this could be having an async Set function inside the selector. This way you could model all of your requests to the backend in your selectors and then import these, call the set() function and view the status of the value via useRecoilLoadableState which will do everything in 1 clean step. 

What alternative to this do we have that is both safe and concise?

**Comment by Shmew** [comment]
A way you could solve this is to have an atom that is an array of the object that is passed into your rest calls. You would then make a selectorFamily that accepts the company object and returns the company state, as well as a selector that depends on the array of company objects which then maps to the array of company state via the selectorfamily. This means to add a new company you simply set the atom that contains the company objects and it will recalculate/invoke the requests as needed (since most of the objects will be cached). 

So this would be something like:

```js
const companies = atom({
  key: 'companies',
  default: [],
});

const companyQuery = selectorFamily({
  key: 'companySelector',
  get: async (company { get }) => {
    const response = await fetch('http://localhost:9000/companies');
    return await response.json();
  },

const companiesQuery = selector({
  key: 'companiesSelector',
  get: ({ get }) => {
    get(companies).map(company => get(companyQuery(company)))
  },
```

**Comment by stephanoparaskeva** [comment]
> A way you could solve this is to have an atom that is an array of the object that is passed into your rest calls. You would then make a selectorFamily that accepts the company object and returns the company state, as well as a selector that depends on the array of company objects which then maps to the array of company state via the selectorfamily. This means to add a new company you simply set the atom that contains the company objects and it will recalculate/invoke the requests as needed (since most of the objects will be cached).
> 
> So this would be something like:
> 
> ```js
> const companies = atom({
>   key: 'companies',
>   default: [],
> });
> 
> const companyQuery = selectorFamily({
>   key: 'companySelector',
>   get: async (company { get }) => {
>     const response = await fetch('http://localhost:9000/companies');
>     return await response.json();
>   },
> 
> const companiesQuery = selector({
>   key: 'companiesSelector',
>   get: ({ get }) => {
>     get(companies).map(company => get(companyQuery(company)))
>   },
> ```

But this would not update the backend, and if you wanted to update the backend it'd mean you'd have to manually sync the two. Wouldn't it be easier if you could make a post to your backend in set and then just store the updated state to your frontend?

**Comment by Shmew** [comment]
I'm not sure I follow, but if you were wanting to make a new request when the result of `companiesQuery` changes you could add a "middleware" that just depends on `companiesQuery` and make the requests to the backend and then returns the original value so things automatically stay in sync. It's no longer pure at that point, which is where I'd probably reach for a transaction observer to listen for changes and make posts to the server.

**Comment by stephanoparaskeva** [comment]
> I'm not sure I follow, but if you were wanting to make a new request when the result of `companiesQuery` changes you could add a "middleware" that just depends on `companiesQuery` and make the requests to the backend and then returns the original value so things automatically stay in sync. It's no longer pure at that point, which is where I'd probably reach for a transaction observer to listen for changes and make posts to the server.

This sounds like way too much redirection to simply set and post data. This can't possibly be the way to do it with Recoil?

**Comment by Shmew** [comment]
Yeah I agree, and others have voiced a need for this time of feature. I believe they're working on this which will be called `atomEffect`. @drarmstr 

Sounds like what it will probably do is just listen for when the atom changes and call the effect function created with the new state and let it dispatch side-effects.

**Comment by bentron2000** [comment]
Excuse me if I'm completely off the mark here - but could you just give `{ set, reset }` to the `get:`... 

...so `selector` 

```
get: ({ 
          get: GetRecoilValue, 
          set: SetRecoilState,
          reset: ResetRecoilState 
      }) => T | Promise<T> | RecoilValue<T>
```

and `selectorFamily`

```
get: Parameter => ({
                    get: GetRecoilValue, 
                    set: SetRecoilState,
                    reset: ResetRecoilState
                  }) => Promise<T> | RecoilValue<T> | T
```

Then you can perform 'set-on-get' as you see fit?
Also, this would allow you to call some subscription function that can update state from outside as required. 

Not sure how this compares to the proposed persistence features @drarmstr 

ps. LOVE recoil :)

**Comment by drarmstr** [comment]
@bentron2000  - Here's the [proposed API](https://github.com/facebookexperimental/Recoil/commit/fb029cfe53e0ab22e8adaea740f3060510808a0a).  We don't want to expose set during a selector get operation, as that would essentially lead to synchronous side-effects during render.

**Comment by drarmstr** [comment]
See these updated guides: [async requests](https://recoiljs.org/docs/guides/asynchronous-data-queries) and [atom effects](https://recoiljs.org/docs/guides/atom-effects).
