### ISSUE TITLE
DefaultValue type forcing me to check the type before using the property

### ISSUE THREAD

**Issue by italodeandra** [facebookexperimental/Recoil#244]
I think this issue should be addressed by @csantos42's DefinitelyTyped, but I'm not sure where to submit this issue. If anyone could point me out where should be best I will be glad.

In this example I have the usage of a **selector** called "userState" that uses a atom called "userAtom" and it's function is to save a cache from the atom new value on localStorage and saves a bearer token inside Axios default header Authorization:
```ts
export const userState = selector<IUser | null>({
  key: "userState",
  get: ({ get }) => {
    return get(userAtom);
  },
  set: ({ set }, user) => {
    if (user !== null) {
      Axios.defaults.headers.Authorization = `Bearer ${user.token}`;
      localStorage.setItem(ls("userState"), JSON.stringify(user));
    } else {
      localStorage.removeItem(ls("userState"));
    }
    set(userAtom, user);
  },
});
```

The problem is that TypeScript is complaining that "token" used here is not a DefaultValue's property:
```ts
     Axios.defaults.headers.Authorization = `Bearer ${user.token}`;
```
`TS2339: Property 'token' does not exist on type 'DefaultValue | IUser'. Property 'token' does not exist on type 'DefaultValue'.`

But I expect that TypeScript only checks the type I informed here:
```ts
export const userState = selector<IUser | null>({
```

My suggestion is to change this type:
```ts
export interface ReadWriteSelectorOptions<T> extends ReadOnlySelectorOptions<T> {
    set: (
        opts: {
            set: SetRecoilState;
            get: GetRecoilValue;
            reset: ResetRecoilState;
        },
        newValue: T | DefaultValue,
    ) => void;
}
```

to

```ts
export interface ReadWriteSelectorOptions<T = DefaultValue> extends ReadOnlySelectorOptions<T> {
    set: (
        opts: {
            set: SetRecoilState;
            get: GetRecoilValue;
            reset: ResetRecoilState;
        },
        newValue: T,
    ) => void;
}
```

Then the DefaultValue type is only used when I don't inform any type to the **selector** usage.

For now my workaround was to check the value's type:

```ts
      if (!(user instanceof DefaultValue)) {
        Axios.defaults.headers.Authorization = `Bearer ${user.token}`;
      }
```

**Comment by drarmstr** [comment]
The reason for this is because the new value passed to the selector set actually could be a `DefaultValue` type.  An object of this type is passed in if the user resets the selector (such as with `useResetRecoilState()`.  You have to check if the input new value is an instance of that type to safely handle the reset case.

**Comment by will-stone** [comment]
However, using @italodeandra's example, wouldn't the default value have to have been of type `IUser | null`?

**Comment by drarmstr** [comment]
@will-stone - The default value of the atom has to be `IUser | null`.  But, the value of the new value passed into the selector `set` callback is of type `IUser | null | DefaultValue`.  It is expected that we have to check `user instanceof DefaultValue` to properly handle the case if the selector was reset.

**Comment by drarmstr** [comment]
Updated docs to explain more in #285

**Comment by bnayae** [comment]
If you're using typesctipt, you can use the following ([guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html))

```js
import { DefaultValue } from 'recoil';

export const guardRecoilDefaultValue = (
  candidate: any
): candidate is DefaultValue => {
  if (candidate instanceof DefaultValue) return true;
  return false;
};
```
