### ISSUE TITLE
release as es module

### ISSUE THREAD

**Issue by yuantongkang** [facebookexperimental/Recoil#245]

**Comment by Manviel** [comment]
Please review https://github.com/artalar/reatom. It would be great to merge future features with this package

**Comment by PabloSzx** [comment]
@drarmstr any comment on why closing this issue?

**Comment by drarmstr** [comment]
@PabloSzx  Looks like the issue content is missing.  Anyway, I think @aaronabramov provided an explanation on another issue why we need to use Common JS modules for now to work with our internal infrastructure, trying to find that..
