### ISSUE TITLE
(SSR) ReferenceError: window is not defined

### ISSUE THREAD

**Issue by amogower** [facebookexperimental/Recoil#248]
Rendering a React app with Recoil (v0.0.8) on the server when `NODE_ENV=development` throws the following error:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/username/project/node_modules/recoil/dist/recoil.development.js:591:3)
```

When I look at the tagged source code [here](https://github.com/facebookexperimental/Recoil/blob/5fce5a5518c9bfaa97cfc11ee7a4f62ca7f90b24/src/components/Recoil_RecoilRoot.react.js#L123) on Github the following looks correct:

```
if (__DEV__) {
  if (typeof window !== 'undefined' && !window.$recoilDebugStates) {
    window.$recoilDebugStates = [];
  }
}
```

But the module code pulled from npm shows the following which doesn't contain the `typeof window !== 'undefined` check:

```
{
  if (!window.$recoilDebugStates) {
    window.$recoilDebugStates = [];
  }
}
```

Is that intended?  Am I missing something?  

Any help is much appreciated, love the library!

**Comment by Chrischuck** [comment]
This change hasn't been released yet, that's why it's not in your npm modules :)

**Comment by amogower** [comment]
😂  could have sworn I was looking at the code under `https://github.com/facebookexperimental/Recoil/blob/0.0.8` but apparently not... Thanks!
