### ISSUE TITLE
[Feature Request] - Access store directly

### ISSUE THREAD

**Issue by nir905** [facebookexperimental/Recoil#251]
Hi,

First of all, I really like the idea behind Recoil and the "Hook syntax" it brings!

As it grows and maybe more open to changes at this point, I would like to suggest a small feature that could help us all.

Instead of accessing an atom with its instance like this:
```const [text, setText] = useRecoilState(textState);```

I would prefer to get a direct access to the store (such as useSelector in redux):
```const [text, setText] = useRecoilState(state => state.textStateKey);```

It would help us to avoid `import` each atom we use and make it more readable.

**Comment by drarmstr** [comment]
We want to manage individual atoms instead of exposing some single large mutable object that contains all atoms to help ensure that we update all state changes for subscribing components and can manage multiple concurrent states with React Concurrent Mode.
