### ISSUE TITLE
[Bug] atomValues empty using useTransactionObservation_UNSTABLE

### ISSUE THREAD

**Issue by nikoisonfire** [facebookexperimental/Recoil#253]
The subscription to the observer fires correctly when changing atoms, and returns the correct key (modifiedAtoms) but the atomValues Map is empty.

Im referring  to this method:
`useTransactionObservation_UNSTABLE(({atomValues, atomInfo, modifiedAtoms})`

Edit: atomInfo is not empty

**Comment by DynamicArray** [comment]
Have you defined your atoms with a persistence_UNSTABLE value?
`
export const myAtom = atom({
    key: 'myAtom',
    default: {},
    persistence_UNSTABLE: { type: true },
});
`

**Comment by nikoisonfire** [comment]
How could I miss that! Thank you, John!

**Comment by drarmstr** [comment]
Please note that the observability API is updating to avoid the need for this extra metadata.

**Comment by vdjurdjevic** [comment]
Is the new persistence API coming any time soon?

**Comment by drarmstr** [comment]
Yes, we're still working on it; just had some delays.

**Comment by vdjurdjevic** [comment]
Can you tell me if it's less or more than a month? I know you can't tell me the real release date for sure, I just need rough estimate what the chances are that it will be more than a month.
