### ISSUE TITLE
Version 0.0.8 in SSR - window is not defined - Version Release Needed

### ISSUE THREAD

**Issue by wilbert-abreu** [facebookexperimental/Recoil#255]
In the current version, you'll get this error in the dev build `ReferenceError: window is not defined`. This seems to be fixed in latest master, so a new version release is needed. Thanks!

**Comment by Pearce-Ropion** [comment]
Im using a forked version of master for now while waiting for the next release

**Comment by dvakatsiienko** [comment]
It seems that #337 didn't fixed this issue

**Comment by drarmstr** [comment]
@dvakatsiienko -  #337 was just updating the package for the release.  Try the actual 0.0.9 npm package and see if you still have an issue.  If so, please re-open and report the stack trace.
