### ISSUE TITLE
React-dom as peer dependency - is it intended to work with React Native too ? 

### ISSUE THREAD

**Issue by f-roland** [facebookexperimental/Recoil#264]
Hi there,

This is more of a question than an issue - I tried to fiddle a bit with Recoil in an expo snack, but I quickly got stuck because of the peer dependency to React-dom

is there a plan to make this available for React Native too ? 

Thanks

**Comment by CoenWarmer** [comment]
Please search issues first before posting https://github.com/facebookexperimental/Recoil/issues/99

**Comment by f-roland** [comment]
Thanks

**Comment by drarmstr** [comment]
Duplicate of #99
