### ISSUE TITLE
SyntaxError: Unexpected token ... in IE

### ISSUE THREAD

**Issue by teramotodaiki** [facebookexperimental/Recoil#265]
Microsoft Edge 18 throws syntax error because it doesn't support object rest spread.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility 

- How to reproduce it
  - Open Microsoft Edge 
  - Load `recoil.production.js`
  - Then it will throw error `SyntaxError: Unexpected token ...` around `setUnvalidatedAtomValue:function(state,key,newValue){return{...state,atomValues:mapByDeletingFromMap$1(state.atomValues,key)`
- Environments
  - Recoil version: 0.0.8
  - Edge version: 18 or earlier
  - Codesandbox is here: https://codesandbox.io/s/gracious-brook-d8zm7

**Edited 6/7:**
I think [@babel/plugin-proposal-object-rest-spread](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread), [@babel/plugin-transform-spread](https://babeljs.io/docs/en/babel-plugin-transform-spread) and [@babel/plugin-transform-parameters](https://babeljs.io/docs/en/babel-plugin-transform-parameters) are needed in `rollup.config.js`. I can make PR if you would like. :)

**Comment by CooCooCaCha** [comment]
Just encountered this issue as well. Any workarounds for now?

**Comment by drarmstr** [comment]
cc @mondaychen  Is this the same as #441 ?

**Comment by drarmstr** [comment]
@teramotodaiki - Is this still an issue?

**Comment by mondaychen** [comment]
I did some investigation -- this should no longer be a problem on Edge because it has support for this syntax since version 79 (the huge gap in version number is because of its switch to chromium core, if I guessed it right).

We never added those babel plugins, so this is still an issue with older version of Edge, and Internet Explorer.

**Comment by bearbytes** [comment]
I'm having the same issue with a chrome browser (56.0.2924.87) on an older Android Tablet.

**Comment by zjhou** [comment]
Firefox 54 got this error too.

**Comment by teramotodaiki** [comment]
@drarmstr Sorry for the late reply.
I solved this problem by doing the Babel `node_modules/recoil`.

The great thing is that this is now clearly documented.

> Recoil builds are not transpiled to ES5, and we do not support the use of Recoil with ES5. If you need to support browsers that do not provide ES6 features natively, you can do so by compiling your code with Babel and using preset @babel/preset-env. However, we do not support this and you may run into problems.
> https://recoiljs.org/docs/introduction/installation#es5-support

Thank you for writing this information. I think this is enough.
Therefore, I would like to close this issue.
