### ISSUE TITLE
Using ESM

### ISSUE THREAD

**Issue by itamar244** [facebookexperimental/Recoil#266]
I was reading the code, and it made me wonder why you chose CommonJS over ESM.

flowtype supports ESM very good as far as I know and generally the syntax is much nicer and better.
Also, it is better for tree shaking in some scenarios.

**Comment by drarmstr** [comment]
@mondaychen

**Comment by mondaychen** [comment]
CommonJS is our only choice for now because Recoil started as part of Facebook's internal code base and the source-of-truth still is still there.

We are discussion on the future plan. If we decided to use github as source-of-truth, it makes sense to use ESM
