### ISSUE TITLE
Suggested folder structure for atoms and selectors

### ISSUE THREAD

**Issue by sorxrob** [facebookexperimental/Recoil#27]
Hi guys. This is a very promising library.

Is there a suggested folder structure for this? This is what I currently have in mind:

<img width="268" alt="Screen Shot 2020-05-15 at 10 13 48 PM" src="https://user-images.githubusercontent.com/13049130/82060026-5ed10080-96f9-11ea-84a1-c99304e58ac3.png">

**atoms/auth.js**

```javascript
import { atom } from "recoil";

export const userState = atom({
  key: "userState",
  default: {
    id: 123,
    name: "John Doe",
    email: "test@gmail.com",
  },
});

// More atoms related to user
```

**atoms/todo.js**

```javascript
import { atom } from "recoil";

export const todoState = atom({
  key: "todoState",
  default: [],
});

// More atoms related to todo
```

or we can have all atoms inside **atoms/index.js** and selectors inside **selectors/index.js**

```javascript
import { atom } from "recoil";

export const userState = atom({
  key: "userState",
  default: {
    id: 123,
    name: "John Doe",
    email: "test@gmail.com",
  },
});

export const todoState = atom({
  key: "todoState",
  default: [],
});
```

Then we can import it like this:

```javascript
import { useRecoilState } from "recoil";
import { userState } from "./atoms/auth";

function LoginPage() {
  const [user, setUser] = useRecoilState(userState);

  return (...);
}
```

What do you guys think?

**Comment by jacobp100** [comment]
My gut instinct is put all the auth stuff in auth, all the todo in todo, and if the files get too big, then look at what you can do. Get a feel for how the project grows naturally before enforcing folder structures

**Comment by PranjaliPatil14** [comment]
I agree with @jacobp100. I think keeping state closer to where it is getting used is always more readable.And suppose if some new component is added which needs auth state then we can bring auth files file one level up.

**Comment by davidmccabe** [comment]
Honestly, just put atoms and selectors in the same module as the components that use them. If they need to be used across multiple modules, only then put them in their own modules. Co-locate as closely as possible. Organize by feature. Just my two cents.

**Comment by davidmccabe** [comment]
Also, a major aspect of Recoil as that atoms and selectors can be interchanged with each other. So I would not expose whether something is an atom or selector in its public interface. And a lot of the time you're going to be exporting hooks rather than the raw atom or selector.

**Comment by stopsopa** [comment]
> Honestly, just put atoms and selectors in the same module as the components that use them. If they need to be used across multiple modules, only then put them in their own modules. Co-locate as closely as possible. Organize by feature. Just my two cents.

What's the purpose of using regoil then when you are using it only in one component? use simple react state then

**Comment by drarmstr** [comment]
> What's the purpose of using regoil then when you are using it only in one component? use simple react state then

There are many reasons one might use Recoil state that is only used by a single component.  For example, a selector that derives state relevant for that component, but the dependent state is shared atoms or selectors.  Or, it is a selector which is issues async queries.  Or, it might be just a simple un-shared atom but is persisted in the URL/local storage/remote DB/...
