### ISSUE TITLE
Complex Data Performance

### ISSUE THREAD

**Issue by jpmtrabbold** [facebookexperimental/Recoil#288]
Hello. Sorry about one more comparison with MobX, but I'd just like to know if there is an alternative for this situation in Recoil.

So, in Mobx, let's say I have some initial state like this:

```
@observable todos: Todo[] = [
   { text: "1", details: "deets for 1", done: false },
   { text: "2", details: "deets for 2", done: false },
   { text: "3", details: "deets for 3", done: false },
   { text: "4", details: "deets for 4", done: false },
]
```

And I have an action that updates the details for a specific todo:

```
@action updateTodoDetails = (todo: Todo, details: string) => {
  todo.details = details 
}
```

If I use `updateTodoDetails` passing the position 2 of the todos array, the only react nodes that will be notified of the change will be the ones that observe `store.todos[2].details`. If there is a node that observes `store.todos[1].details` or `store.todos[2].text`, that node won't even be notified/reconciled, let alone update the DOM.

As you can see, this is very performant, especially for applications that deal with complex data structures. Can that be achieved with Recoil?

**Comment by Shmew** [comment]
Yep! Totally achievable, you can make an `atomFamily` that given a index would return the state or create a new one, and from there you could make 3 `selectorFamily`s that each return one part of that state, and when set would set that part of the state in the atom. When a component only needs one piece of state from one specific row they would call that corresponding selectorFamily. If it needs all of the state for a row they would call the atomFamily.

**Comment by jpmtrabbold** [comment]
Thanks for the reply :)

Yep, it looks like it would definitely work. Although quite a lot boilerplate...

I'm thinking about enterprise systems, where you would usually have forms with lots of fields...let's say 20? Then you don't want every field cause all the others to reconcile, then we would end up creating 20 selectors? That's not a very good developer experience (if there isn't another way)

**Comment by Shmew** [comment]
With forms, the fields themselves don't need to subscribe to their own state nor each other (unless validation is being performed real-time). So you could just create an atom for the form state, and a selector that performs validation (via getting the form atom value) and returns the result. In the input component you would just use `useSetRecoilState` and update the form atom on change, which means it won't re-render.

**Comment by AjaxSolutions** [comment]
>>> Although quite a lot boilerplate...

I like the fact the Recoil is explicit as opposed to MobX.

**Comment by Shmew** [comment]
Yeah it doesn't quite work as I wanted, your best bet is to explicitly define a selector to get and set a specific part of state.

**Comment by jpmtrabbold** [comment]
@Shmew that's alright. I was thinking if something like this would be possible:

```
const formState = atom({
  key: 'formState',
  default: {
    field1: "1",
    field2: "2",
    field3: "3",
  }
})

const getFormFieldProps = atomFamily({
  key: 'getFormFieldProps ',
  default: selectorFamily({
    key: 'getFormFieldProps/Default',
    get: fieldName => ({get, set}) => {
      
      return {
        value: get(formState)[fieldName], 
        onChange: (target) => set(formState, prevState => /* somehow sets state */) 
      }
    },
  }),
})

const Component = () => {
  const field1Props = useRecoilValue(getFormFieldProps('field1'));

  return (
    <input {...field1Props} />
    <Component2 />
  )
}

const Component2 = () => {
  const field2Props = useRecoilValue(getFormFieldProps('field2'));

  return (
    <input {...field2Props} />
  )
}
```

**Comment by Shmew** [comment]
You can't set state in the `get` of a selector.

To be clear you can definitely make a selector that gets and sets the fields, you just can't *inline* a function like that. At least not that I've discovered yet.

You would just make a selector that gets the `formState` and returns the field you want. Setting would be either explicitly creating them or creating a reducer type of selector.

**Comment by jpmtrabbold** [comment]
> You can't set state in the `get` of a selector.
That's not exactly what I proposed. The selector would be returning (among other props) a setter. This selector would be about returning props that can be used in an input field to make it "bound" to that state.

Just trying to think about better possibilities for forms here, because as far as I could dive into, it will be very tedious to use recoil with forms

**Comment by drarmstr** [comment]
@jpmtrabbold - You can wrap with a `selectorFamily` to do this:

```jsx
const formState = atom({
  key: 'formState',
  default: {
    field1: "1",
    field2: "2",
    field3: "3",
  },
});

const formFieldState = selectorFamily({
  key: 'FormField',
  get: field => ({get}) => get(formState)[field],
  set: field => ({set, get}, newValue) =>
    set(formState, state => {...state, [field]: newValue}),
});

const Component = () => {
  const [value, onChange] = useRecoilState(formFieldState('field1'));
  return (
    <input value={value} onChange={onChange} />
    <Component2 />
  )
}

const Component2 = () => {
  const [value, onChange] = useRecoilState(formFieldState('field2'));
  return (
    <input value={value} onChange={onChange} />
  )
}
```

An advantage of using selector for this is when #314 is available you will also limit re-renders to only be triggered for the fields you use versus any field in the form.

**Comment by jaredpalmer** [comment]
What’s the timeline on #314?

**Comment by danielweil** [comment]
> @jpmtrabbold - You can wrap with a `selectorFamily` to do this:
> 
> ```js
> const formState = atom({
>   key: 'formState',
>   default: {
>     field1: "1",
>     field2: "2",
>     field3: "3",
>   },
> });
> 
> const formFieldState = selectorFamily({
>   key: 'FormField',
>   get: field => ({get}) => get(formState)[field],
>   set: field => ({set}, newValue) =>
>     set(formState, prevState => {...prevState, [field]: newValue}),
> });
> 
> const Component = () => {
>   const [value, onChange] = useRecoilState(formFieldState('field1'));
>   return (
>     <input value={value} onChange={onChange} />
>     <Component2 />
>   )
> }
> 
> const Component2 = () => {
>   const [value, onChange] = useRecoilState(formFieldState('field2'));
>   return (
>     <input value={value} onChange={onChange} />
>   )
> }
> ```
> 
> An advantage of using selector for this is when #314 is available you will also limit re-renders to only be triggered for the fields you use versus any field in the form.

I tried using this solution, but I can't get prevState in set function anymore. What can I do in this case?
