### ISSUE TITLE
There is a way to update states on recoilJS outside of component?

### ISSUE THREAD

**Issue by orhalimi** [facebookexperimental/Recoil#289]
So I'm trying recoilJS for a js game that I am building and it pretty neat, but the need to update atoms from components only feels like a limitation.

To create a game loop, I put all the logic on empty component so I will be able to read and write states. Even if I will construct the logic outside of the component, I will need especially move different stats around all the time. There is a way to update atoms outside of react component (not via hooks)?

**Comment by pankerit** [comment]
it would be great,
and to subscribe outside of component would be nice

**Comment by ehahn9** [comment]
related: what would the idiom be for creating async selectors which also subscribe to an external data source and trigger component renders when the (external) data changes?

- contrived: a selector which reports the window dimensions and listens via `window.onresize` etc.

- not too contrived (my real-world case): a selector which returns a field from a firestore document, the contents of which might change externally (notified by `onSnapshotChanged`). This second case is really cool for recoil because the fetched document would be shared state (e.g. key === document.id) so you'd be pretty sure not to unneccessarily re-fetch data...

I'm sure I'm just dim, but it wasn't clear how you'd construct the selector getter in those cases?

**Comment by ehahn9** [comment]
@Shmew that sounds like an excellent direction. Thanks for the pointer. In this approach, any thoughts on how the hook would  know when to unsubscribe from it's listener? I didn't see a way for `useRecoilCallback` to provide a cleanup to its effect so I'd worry that the hook would keep listening for changes and updating the atom long after all the consumers were unmounted? Apologies if I'm not following fully.

**Comment by Shmew** [comment]
Yeah, you would need to implement some sort of mechanism to cancel the subscriber. Probably via a clean-up `useEffect` in the component.

**Comment by n8sabes** [comment]
@davidmccabe, I'm finding numerous issues requesting access to atoms and selectors outside of components, but issues on the matter get closed without a clear path forward / example.

Like @atulmy [authentication inquiry](https://github.com/facebookexperimental/Recoil/issues/73#issuecomment-631391642), I cannot figure out how to migrate our authentication logic from Redux to Recoil. We need to call authentication helper functions in our auth library from various components whereby the Recoil state gets updated upon network call completion in the auth library. After a few days of work migrating from Redux to Recoil, I've completely stalled. I am invested and really want Recoil to work.

If the answer is, "Recoil is not an end-to-end state manager", that's fine but need to get clarity on where to and where not to use Recoil.

Thanks for any thoughts / examples on this.

**Comment by orhalimi** [comment]
I did some workaround that I created a log components that listen to custom events and update the looks atom, so I can call the fiction that fire the events and send looks from everywhere.

You can do something similar untill a solution will be found

**Comment by drarmstr** [comment]
Yes, it's perfectly reasonable to create a React component that has an effect to listen to async changes and update Recoil state in response.  Here's an example for listening to changes outside of components and updating Recoil state.  Note that the Recoil state isn't "global", but coupled to the `<RecoilRoot>` that this `<Subscriber>` component is mounted in; this is important for Concurrent Mode support.

```jsx
function Subscriber() {
  const setState = useSetRecoilState(myState);
  useEffect(() => {
    const subscriber = setupSubscription();
    subscriber.onEvent(value => {
      setState(value);
    });
    return () => subscriber.unsubscribe();
  });
  return null;
}
``` 

or check out this [Read/Write example](https://recoiljs.org/docs/guides/asynchronous-state-sync#bi-directional-synching). We are working on improving the API to avoid needing to manually maintain subscriber components, but you should get the general idea.

**Comment by orhalimi** [comment]
So combine that with atom family and you can get a semi dynamic state management lib despite hooks' hoops...

**Comment by drarmstr** [comment]
Updated documentation for [syncing Recoil state with external storage](https://recoiljs.org/docs/guides/atom-effects#state-synchronization-example) in #680

**Comment by Vadorequest** [comment]
I found the examples at https://recoiljs.org/docs/guides/atom-effects/#state-synchronization-example a bit complicated to grasp and wrote an SO answer with a simpler example.

https://stackoverflow.com/a/66146954/2391795

But eventually, I noticed it didn't work and deleted the SO answer... Back to square one. 😅 

I don't understand how I can't mutate a state outside a React component.

**Comment by BenjaBobs** [comment]
In my team we use this simple component to access Recoil state outside of React. It let's you `set` state and `get` `loadables`.
```typescript
import React from 'react';
import {
  Loadable,
  RecoilState,
  RecoilValue,
  useRecoilCallback,
  useRecoilTransactionObserver_UNSTABLE,
} from 'recoil';

export let RecoilGetLoadable: <T>(
  recoilValue: RecoilValue<T>
) => Loadable<T> = null as any;

export let RecoilSet: <T>(
  recoilVal: RecoilState<T>,
  valOrUpdater: ((currVal: T) => T) | T
) => void = null as any;

export function RecoilUtilsComponent() {
  // We need to update the RecoilGetLoadable every time there's a new snapshot
  // Otherwise we will load old values from when the component was mounted
  useRecoilTransactionObserver_UNSTABLE(({ snapshot }) => {
    RecoilGetLoadable = snapshot.getLoadable;
  });

  // We only need to assign RecoilSet once because it's not temporaly dependent like get is
  useRecoilCallback(({ set }) => {
    RecoilSet = set;

    return async () => {};
  })();

  return <></>;
}
```

Keep in mind that if you use more than one `RecoilRoot` this solution isn't viable, as it doesn't keep track of the different roots.

**Comment by Vadorequest** [comment]
@BenjaBobs Thank you. I only use one root, so this might work out. Do you have any usage example?

**Comment by BenjaBobs** [comment]
Yes, we handle auth outside of react, so it can start loading as soon as the page loads, so we can get roles as fast as possible.
We load the authentiction library, authenticate, and save the user in recoil state:
```typescript
import { RecoilGetLoadable, RecoilSet } from '../../RecoilUtils';

async checkAuthentication(): Promise<boolean> {
    await __handleAuth0Flow();

    const client = await __getClient();
    if (await client.isAuthenticated()) {

      const user = await client.getUser<Auth0User>()!;
      await client.getTokenSilently();

		// s_Auth0User is the atom, and user is the data.
      RecoilSet(s_Auth0User, user);

      return true;
    }
    return false;
  },
```

**Comment by Vadorequest** [comment]
Thanks, I'll give it a try!

What is `RecoilGetLoadable` for in your example? It doesn't seem to be used.

**Comment by BenjaBobs** [comment]
Yes, here's a part of the script where we use `RecoilGetLoadable`. Also, more on loadables here: https://recoiljs.org/docs/api-reference/core/Loadable
```typescript
async function login(appState: RedirectAppState | undefined = undefined): Promise<void> {
    const client = await __getClient();

    if (!(await client.isAuthenticated())) {

      await client.loginWithRedirect({
		// Here we get a loadable for the s_Language atom
		// Since we're outside of React, we don't know if it's finished processing
		// So we use .valueMaybe() and fallback to a default value
        ui_locales: RecoilGetLoadable(s_Language).valueMaybe() || 'en',
        appState: DefaultAppState(appState),
      });

    }
  }
```

**Comment by Vadorequest** [comment]
I managed to make it work, one thing you didn't mention was it's needed to load the `<RecoilExternalStatePortal />` in the React tree, under the `<RecoilRoot>` component. (might seem obvious, but I didn't notice it at first)

I've also added a bit more documentation, it should make it easier to reason about.

_I've used the terminology "external" even though I'm not sure if there wouldn't be a better term, but that's good enough for me._


```tsx
// RecoilExternalStatePortal.tsx
import {
  Loadable,
  RecoilState,
  RecoilValue,
  useRecoilCallback,
  useRecoilTransactionObserver_UNSTABLE,
} from 'recoil';

/**
 * Returns a Recoil state value, from anywhere in the app.
 *
 * Can be used outside of the React tree (outside a React component), such as in utility scripts, etc.

 * <RecoilExternalStatePortal> must have been previously loaded in the React tree, or it won't work.
 * Initialized as a dummy function "() => null", it's reference is updated to a proper Recoil state mutator when RecoilExternalStatePortal is loaded.
 *
 * @example const lastCreatedUser = getRecoilExternalLoadable(lastCreatedUserState);
 */
export let getRecoilExternalLoadable: <T>(
  recoilValue: RecoilValue<T>,
) => Loadable<T> = () => null as any;

/**
 * Sets a Recoil state value, from anywhere in the app.
 *
 * Can be used outside of the React tree (outside a React component), such as in utility scripts, etc.
 *
 * <RecoilExternalStatePortal> must have been previously loaded in the React tree, or it won't work.
 * Initialized as a dummy function "() => null", it's reference is updated to a proper Recoil state mutator when RecoilExternalStatePortal is loaded.
 *
 * @example setRecoilExternalState(lastCreatedUserState, newUser)
 */
export let setRecoilExternalState: <T>(
  recoilState: RecoilState<T>,
  valOrUpdater: ((currVal: T) => T) | T,
) => void = () => null as any;

/**
 * Utility component allowing to use the Recoil state outside of a React component.
 *
 * It must be loaded in the _app file, inside the <RecoilRoot> component.
 * Once it's been loaded in the React tree, it allows using setRecoilExternalState and getRecoilExternalLoadable from anywhere in the app.
 *
 * @see https://github.com/facebookexperimental/Recoil/issues/289#issuecomment-777300212
 * @see https://github.com/facebookexperimental/Recoil/issues/289#issuecomment-777305884
 * @see https://recoiljs.org/docs/api-reference/core/Loadable/
 */
export function RecoilExternalStatePortal() {
  // We need to update the getRecoilExternalLoadable every time there's a new snapshot
  // Otherwise we will load old values from when the component was mounted
  useRecoilTransactionObserver_UNSTABLE(({ snapshot }) => {
    getRecoilExternalLoadable = snapshot.getLoadable;
  });

  // We only need to assign setRecoilExternalState once because it's not temporally dependent like "get" is
  useRecoilCallback(({ set }) => {
    setRecoilExternalState = set;

    return async () => {

    };
  })();

  return <></>;
}

```

**Comment by BenjaBobs** [comment]
> one thing you didn't mention was it's needed to load the `<RecoilExternalStatePortal />` in the React tree, under the `<RecoilRoot>`component
Oops. Well glad to see you figured it out.
This thread will probably serve well for other people stumbling into the same issue. 😄

**Comment by naorye** [comment]
@BenjaBobs This is a very bad workaround. Recoil should provide a proper solution for such basic use case.
Unfortunately I started a project with Recoil but now, when I see that there are many missing features I am thinking of using a more battle tested state management.

**Comment by drarmstr** [comment]
Please note a distinction between state management systems based around the concept of a "global" state and those based around the current React context.  Recoil state is dependent on the React context in order to align with the direction React is going and functionality such as Concurrent Mode, which may have multiple versions of the React component tree and state in flight asynchronously.

**Comment by eduardobalbo** [comment]
Hello everybody!
In my use case, i have a little Socket.io helper that needs a value( the user email) that i keep inside an Atom, then the helper will use the email and start a socket connection with it. So my Socket helper is not explicit to any React component, it just needs to read that value once.

@drarmstr, is there any plans to add to Recoil itself some sort of API to handle states outside of React components. much like mobx or even Redux? I don't know if thats not the scope of the project right now, but i have a fairly big Application running on Recoil, and adding another state management library just for handling this use case doesn't look right.
I also dont want to get rid of Recoil and go to another state management library just to fix this, so i might do some sort of workaround and wait for news on Recoil side.

**Comment by luisanton-io** [comment]
> @drarmstr, is there any plans to add to Recoil itself some sort of API to handle states outside of React components. much like mobx or even Redux? I don't know if thats not the scope of the project right now, but i have a fairly big Application running on Recoil, and adding another state management library just for handling this use case doesn't look right.
> I also dont want to get rid of Recoil and go to another state management library just to fix this, so i might do some sort of workaround and wait for news on Recoil side.

I went through a full rewrite and I just released Recoil Nexus, now working for the latest version of Recoil: it's a small package that lets you easily update your atoms value outside of your components.

[Repo](https://github.com/luisanton-io/recoil-nexus)
[Npm](https://github.com/luisanton-io/recoil-nexus)

Hopefully this is handy and useful for others too!
Cheers

**Comment by Vadorequest** [comment]
@luisanton-io Any pros/cons comparison overview versus the `RecoilExternalStatePortal` [workaround](https://github.com/facebookexperimental/Recoil/issues/289#issuecomment-777368767)?

**Comment by Jordan-Eckowitz** [comment]
> > @drarmstr, is there any plans to add to Recoil itself some sort of API to handle states outside of React components. much like mobx or even Redux? I don't know if thats not the scope of the project right now, but i have a fairly big Application running on Recoil, and adding another state management library just for handling this use case doesn't look right.
> > I also dont want to get rid of Recoil and go to another state management library just to fix this, so i might do some sort of workaround and wait for news on Recoil side.
> 
> I went through a full rewrite and I just released Recoil Nexus, now working for the latest version of Recoil: it's a small package that lets you easily update your atoms value outside of your React components.
> 
> [RecoilNexus on Gihub](https://github.com/luisanton-io/recoil-nexus)
> [recoil-nexus on npm](https://github.com/luisanton-io/recoil-nexus)
> 
> Hopefully this is handy and useful for others too!
> Cheers

This should be incorporated into the package - works brilliantly. Using it to update state inside Websocket client triggers and working exactly as expected 👏

**Comment by luisanton-io** [comment]
> @luisanton-io Any pros/cons comparison overview versus the `RecoilExternalStatePortal` [workaround](https://github.com/facebookexperimental/Recoil/issues/289#issuecomment-777368767)?

Hi, I see you are relying on useRecoilTransactionObserver_UNSTABLE which, apart from being unstable, might be an overkill for the requested feature: in the documentation we can read that it "subscribes a callback to be executed every time there is a change to Recoil atom state" and "provides a Snapshot of the current and previous state". 

I really don't think this might be that harmful on performance, but to be on the safe side in my implementation I'm not re-rendering the RecoilNexus component (“ExternalState” in your implementation”) every time any Recoil State gets updated. Instead, I'm assigning useRecoilCallback with empty deps to my `nexus.get`, which will return the newest snapshot every time, and from there I eventually return the promise rather than the loadable, to make sure any asynchronous selector gets evaluated.

However, based on your ideas, in a matter of days I will take the time to implement a method to read the snapshot synchronously through the loadable, which might actually be a better suit for most cases not relying on asynchronous selectors.

BTW I don’t want to flood it here: not sure if it could be the case to move this conversation to another thread?

**Comment by greatvivek11** [comment]
@luisanton-io Thanks, man. This totally worked! Check out my implementation at https://github.com/greatvivek11/TodoApp.
