### ISSUE TITLE
Components using selectors rerender when original atom changes? 

### ISSUE THREAD

**Issue by ahmedlhanafy** [facebookexperimental/Recoil#29]
I'm having trouble understanding how selectors work. From the documentation I understood that the component will only subscribe to the data returned from the selector and not the atom that the selector is using (because why have the selector in the first place if selectors are for mapping values?).

Here is a link to a codesandbox, please pay attention to the `console.log` statements: https://codesandbox.io/s/brave-fast-bcv0s?file=/src/App.js

**Comment by davidmccabe** [comment]
Atoms are the unit of subscription and their values are treated as opaque. Recoil doesn't know which parts of an atom's value a particular selector is actually using.

In this example you would decompose the X and Y coordinates into separate atoms.

**Comment by ahmedlhanafy** [comment]
@davidmccabe But why would one use a selector then? Is it purely for logically grouping atoms?

**Comment by drarmstr** [comment]
Selectors can be thought of as functions to transform and compute some derived state based on other atoms or selectors.  They only trigger re-renders in components which use them when one of their dependencies is updated.  Selectors can also be used for integrating asynchronous work or requests with Recoil.

If a component is using selector S and selector S depends on atoms A and B, then the component will re-render if either A or B are updated.  This is transitive, so if a components uses selector T, which depends on selector S, then it will also re-render when A or B are updated.

**Comment by ahmedlhanafy** [comment]
Fair enough. Thanks folks!
