### ISSUE TITLE
Move TypeScript definitions into core package

### ISSUE THREAD

**Issue by csantos42** [facebookexperimental/Recoil#291]
Hello all!

We've heard your feedback on TS types, and we've decided to migrate TypeScript types to the core package and keep it in sync with API changes. Ultimately that means you won't have to install the `@types/recoil` dependency anymore to access TS types, and you won't have to worry about mismatched versions or missing types.

Right now, the types live in DefinitelyTyped, so I'll be removing the types on that repo and opening a PR in this repo with the types to get us all set up.

**Comment by atanasster** [comment]
Thanks a lot, thats great. 

Any update when is a new version coming to npm? Between destructuring issue, ssr issue and typescript i cant yet use recoil for actual app.
