### ISSUE TITLE
I've been at it for hours now - values/states keep resetting

### ISSUE THREAD

**Issue by MorisR** [facebookexperimental/Recoil#293]
### for some reason whenever I go between react routes, the recoil states keep resetting.......
it keeps resetting the values

here I create a state/atom and export it's id
![image](https://user-images.githubusercontent.com/10247681/84205467-d6563d80-aab5-11ea-9933-b4bd7a262e31.png)

I import the state in this "test component"
![image](https://user-images.githubusercontent.com/10247681/84205382-ac048000-aab5-11ea-80f2-f107d54c9638.png)

I import the state in the app.js as well and i render the component under the provided route
![image](https://user-images.githubusercontent.com/10247681/84205714-5c728400-aab6-11ea-9486-316ce890d1f1.png)

just to be on the safe side this is my index.js as well
![image](https://user-images.githubusercontent.com/10247681/84205407-bcb4f600-aab5-11ea-8632-f4a77bd77e5e.png)

-----

I go to /dashboard route and i press the button multiple times
![image](https://user-images.githubusercontent.com/10247681/84206010-fb977b80-aab6-11ea-8838-eb453bfb4715.png)

i go back to the home route ("/") and bammm.... the value is gone
![image](https://user-images.githubusercontent.com/10247681/84206143-35688200-aab7-11ea-829d-e524889bdd2e.png)

### what am i doing wrong?

I've running version 0.0.8
![image](https://user-images.githubusercontent.com/10247681/84206264-7a8cb400-aab7-11ea-916e-2acdd4a4e18f.png)

**Comment by MorisR** [comment]
sorry for all the images.
I'm off to bed.... having a bad day and it's only getting worse by the minute

**Comment by Grohden** [comment]
@MorisR just a trick to **maybe** find out the reason why your atoms are being reseted:
```javascript
console.log('Hello there!')
export const profileState = atom({
 key: keys.ProfileState,
 default: {}
})
```
If `Hello there!` is logged twice after a route change, your entire page is being refreshed... this maybe happen if you change by hand the current route on browser url input (?)

**Comment by MorisR** [comment]
figured out the issue..
- if u use window.location to navigate through pages, it'll invoke a full page refresh...
- if you manually enter a url it'll also invoke a full page refresh...
the more you know....

thought that react router would know how to handle that
or that recoil would store the states somewhere..

it turns out that it's up to me to handle these things
that's what you get when you're a junior developer who's new to fullstack and react 👎  :/
sorry for the inconvenience

**Comment by ThomasAunvik** [comment]
@MorisR You can use this library [history](https://www.npmjs.com/package/history) to *push* the url to that location, then it won't invoke a full pake refresh.

It would look like something like this:
```ts
<Button onClick={(e) => {
     e.preventDefault();
     history.push("/newloc");
}}>
    Button
</Button>
```

**Comment by reyesGeorge** [comment]
A react-router v6 solution use: https://stackoverflow.com/a/66236803/16498652
