### ISSUE TITLE
Object not extensible when referencing old recoil value in socket.io callback

### ISSUE THREAD

**Issue by quuu** [facebookexperimental/Recoil#299]
In a Socket.io callback, I am granular-ly updating a property of a Recoil state object.

I'm doing something similar to 

```javascript
const [toUpdate, setToUpdate] = useRecoilState(someAtom) 
socket.on("this_event", (data: any) => {
    setToUpdate((toUpdate: any) => {

        toUpdate[someArray].push(data)

        return toUpdate
    })
})  
```

or the syntax
```javascript
setToUpdate((toUpdate: any) => {

    const newToUpdate = Object.assign({},toUpdate)
    newToUpdate[someArray].push(data)

    return newToUpdate

})
```

both throw an "object not extensible" error. This sytnax works fine in vanilla React state and was wondering if this is a bug or if there's a workaround to setting a property of a Recoil state?

I've been able to get a temporary workaround by doing

```javascript
setToUpdate((toUpdate: any) => {

    const newToUpdate = JSON.parse(JSON.stringify(toUpdate))
    newToUpdate[someArray].push(data)

    return newToUpdate

})
```

since it completely copies the contents, but it is very hacky and in the long term very slow

**Comment by drarmstr** [comment]
@quuu - Objects stored in Recoil state are frozen by default.  We want to ensure that we are capturing all "state changes" to properly update other nodes in the data-flow graph or React components which depend on that state.  However, in some cases it may make sense to override this, which you can do so with the `dangerouslyAllowMutability` option in the atom or selector.

**Comment by AjaxSolutions** [comment]
> Objects stored in Recoil state are frozen by default.

@drarmstr Do these objects need to be frozen in production?  For example, immer turns off this option in production.

https://immerjs.github.io/immer/docs/freezing

**Comment by drarmstr** [comment]
Yeah, we’ll probably disable this for production

**Comment by pnkflydgr** [comment]
I'm confused.  @drarmstr, you make it seem like we're not supposed to be updating the atom state via useRecoilState setters.  How is the state supposed to be updated if not with the setToUpdate function that quuu was using?

Can you show us how we should be updating an atom if not from the useRecoilState setters?

**Comment by Shmew** [comment]
You can update via `useRecoilState` just fine. Values return from recoil are immutable, so you just need to not use impure functions like `Array.push`.

**Comment by pnkflydgr** [comment]
I have a recursively nested object... so there's no way to add an element to the nested elements without cloning the current state object (...oldStateObj) and then calling a recursive function to drill down to the right level and push the new element to the cloned state object.  At the end I do: setStateObj(clonedStateObj).  

This works the first time I add a new element (doesn't matter how nested).  The next time I add an element it fails b/c now when I clone the stateObj, my cloned object has Object.preventExtensions property.

I was able to get it working using dangerouslyAllowMutability but if I'm doing something wrong, I would prefer to do it the right way.  The fact is... I'm not trying to mutate the atom.  I am cloning it and mutating the clone.

**Comment by drarmstr** [comment]
@pnkflydgr - Are you deep cloning the entire state or just the top-level object?  Would mutations to the nested object be visible from the cloned objects observed from other atoms?  If you are getting errors that nested objects in the state have been frozen it sounds like those nested objects haven't been cloned?

**Comment by pnkflydgr** [comment]
You guys are right.  I didn't realize that the spread operator only does a deep copy of one level.  All nested properties are shallow copies.  
I switched from this:
`let clonedStateObj = [ ...stateObj ]`
to this:
`let clonedStateObj = JSON.parse(JSON.stringify(object))`

Now it works without dangerouslyAllowMutability.  Thanks for taking the time to respond guys.  Really appreciate it!

**Comment by pnkflydgr** [comment]
Just for thoroughness I want to share what I found is a better approach than JSON.parse() for deep cloning.

```
import { cloneDeep } from "lodash"
...
const [stateObj, setStateObj] = useRecoilState(currentRuleState)
const nestedChangeHandler = ((...) => {
  let clonedStateObj = cloneDeep(stateObj)
  // update nested properties of clonedStateObj
  setStateObj(clonedStateObj)  
}

```

**Comment by Codeia** [comment]
Bumbing this one because I've wasted an entire day coming up with an elegant solution.
Is there any way to achieve it without the need to clone?

**Comment by drarmstr** [comment]
@Codeia - If you use immutable/read-only containers for your state then you won't need to clone them.  It may also be more appropriate to use a finer granularity of atoms to represent state which are simpler to manage.  For example, primitive values don't need to be cloned.

**Comment by craigcosmo** [comment]
holy smoke, I've been struggling with this issue. `dangerouslyAllowMutability` is the solution. But why freeze it like that?

I was doing `const list = [...TheAtomValue]` it's not even possible. I wasn't mutating the state, I'm cloning it.

**Comment by drarmstr** [comment]
Spreading into a new array only changes the outer array.  The inner objects are still referenced and may have been frozen.  As stated above and in the docs Recoil will freeze values stored in atoms/selectors in development mode to help catch potential errors where users try to mutate state without explicitly setting an atom.  This can lead to React missing re-rendering components properly for those state changes.

**Comment by AndonMitev** [comment]
Guys any idea how to debug from where this one is coming

**Comment by puxiao** [comment]
> @quuu - Objects stored in Recoil state are frozen by default. We want to ensure that we are capturing all "state changes" to properly update other nodes in the data-flow graph or React components which depend on that state. However, in some cases it may make sense to override this, which you can do so with the `dangerouslyAllowMutability` option in the atom or selector.

I found that if the object type is `Map`, it cannot be frozen.
```
xxxMap.clear() // can be executed correctly
xxxMap.set(key,value) // can be executed correctly
```
