### ISSUE TITLE
[Question] Can atoms contain atoms in their values

### ISSUE THREAD

**Issue by jacobp100** [facebookexperimental/Recoil#30]
In the talk, there was an array of ids  and a memoized id => atom function. I think in the example the id array was regular react state, but let's pretend it was a recoil atom.

If you then delete an id, you have a caching issue with the memoize function

Is it possible/a good idea to have an atom whose value is an array of atoms?

I know a downside is that the component that has the array has to treat each element inside as a black box, since the rules of hooks will stop it reading their contents. But that might be okay

**Comment by davidmccabe** [comment]
It's not an error to store an atom in an atom. It doesn't do anything special, though.

We are adding a feature soon where atoms will be deleted when no longer used, together with another hook that lets a component retain an atom without subscribing to it. These could be combined into a utility that gives you a list of IDs with automatic deletion of the individual atoms when they are removed from the list.

Currently you have to use the useResetRecoilState hook to delete atoms.

**Comment by songgao** [comment]
> Currently you have to use the useResetRecoilState hook to delete atoms.

@davidmccabe does `useResetRecoilState` actually delete the atoms themselves? The doc says it resets to the default, which seems like it’d still take some memory, at least to store the atom itself and the default value. (I know you said auto deletion is coming; just curious how `useResetRecoilState` works today.)
