### ISSUE TITLE
How do you "Start Fetching Early"?

### ISSUE THREAD

**Issue by morgs32** [facebookexperimental/Recoil#300]
If data fetching is happening in a selector, how would you kick off the request early - like in this example from the [Suspense docs](https://reactjs.org/docs/concurrent-mode-suspense.html#start-fetching-early).

```
// First fetch: as soon as possible
const initialResource = fetchProfileData(0);

function App() {
  const [resource, setResource] = useState(initialResource);
  return (
    <>
      <button onClick={() => {
        const nextUserId = getNextId(resource.userId);
        // Next fetch: when the user clicks
        setResource(fetchProfileData(nextUserId));
      }}>
        Next
      </button>
      <ProfilePage resource={resource} />
    </>
  );
}
```

**Comment by drarmstr** [comment]
Selectors follow a similar convention as components for Suspense.  I haven't tried this example with an outside source like this yet, but it should work.  Let me know!

```jsx
const resource = fetchProfileData();

const userNameQuery = selector({
  key: 'UserNameQuery',
  get: () = {
    const user = resource.user.read();
    return user.name;
  },
});
```

Or, you can just await on a pending pre-fetched promise:
```jsx
const userPromise = fetchUser();

const userNameQuery = selector({
  key: 'UserNameQuery',
  get: async () = {
    const user = await userPromise;
    return user.name;
  },
});
```

You can use [`selectorFamily()`](https://recoiljs.org/docs/api-reference/utils/selectorFamily) to parameterize the selector.  But, note that promises and functions don't work well in parameters, so you'd want to use an id or handle to reference it.

If you want to do everything with just selectors, you can do that also by using [`useRecoilValueLoadable()`](https://recoiljs.org/docs/api-reference/core/useRecoilValueLoadable) because it does not block the rendering while the query is still loading.
```jsx
const userNameQuery = selector({
  key: 'UserNameQuery',
  get: async () => {
    const user = await fetchUser();
    return user.name;
  },
});

function ProfilePage() {
  useRecoilValueLoadable(userNameQuery);  // initiate pre-fetch

  // Stat rendering while fetch was started
  return (
    <Suspense>
      <ProfileDetails />
    </Suspense>
  );
}

function ProfileDetails() {
  const userName = useRecoilValue(userNameQuery);
  return <h1>{userName}</h1>;
} 
```

**Comment by morgs32** [comment]
Thanks @drarmstr  for an answer that was far more complete than my question. 

In the example I shared the user might be navigating from one page to another - navigating from one profile to another. Say you wanted to kick off fetching the data for that user. And let's say we're not using "suspense contracts" when fetching data.

```
// getUser.js
const getUser = (userId) => fetchUser(userId)
export default _memoize(getUser)

// App.js
import getUser from './getUser'
function App() {
  return (
    <UserPicture 
        onClick={(userId) => {
           getUser(userId)
           goToRoute('profile', { userId })
        }}
     />
  );
}

// userQuery.js
const userQuery = selector({
  key: 'UserNameQuery',
  get: async () = {
    const user = await userPromise;
    return user;
  },
});

// Profile.js
function Profile() {
  const user = useRecoilValue(userQuery);
  return <h1>{user.name}</h1>;
} 
```

So I had to create my own memoized function for asynchronously fetching data. Seems a shame not be able to use the one baked into the recoil selector?

**Comment by morgs32** [comment]
Hmm can it be done with `useRecoilCallback`? Under "Callback Interface" it says:
> `set` - Update the value of an atom or selector
Would updating the userQuery selector run the `get`?

**Comment by DynamicArray** [comment]
Is there really going to be any discernible saving triggering the async fetch on the click as opposed to on the component render? Assuming fetchUser is declared async...
```
// App.js
function App() {
  return (
    <UserPicture 
        onClick={(userId) => {
           goToRoute('profile', { userId })
        }}
     />
  );
}

// userQuery.js
const userQuery = selectorFamily({
  key: 'UserNameQuery',
  get: userID => async (userID) = {
    const user = await fetchUser(userID);
    return user;
  },
});

// Profile.js
function Profile({userId}) {
  const user = useRecoilValueLoadable(userQuery(userId));

  switch (user.state) {
    case 'hasValue':
      return <h1>{user.contents.name}</h1>;
    case 'loading':
      return <h1>Loading...</h1>;
    case 'hasError':
      throw user.contents;
  }
} 
```

**Comment by morgs32** [comment]
@DynamicArray maybe read this section of the react docs: [Start fetching early](https://reactjs.org/docs/concurrent-mode-suspense.html#start-fetching-early) - which answers your question.

Meanwhile, thanks for the example, which looks a lot like the example here: [Recoil docs](https://recoiljs.org/docs/api-reference/core/useRecoilValueLoadable#example). I understand that works, too.

**Comment by drarmstr** [comment]
@morgs32 - From a [`useRecoilCallback()`](https://recoiljs.org/docs/api-reference/core/useRecoilCallback) you can generate a callback which will use the callback interface to call `getLoadable()` on a query selector.  That mechanism can also be used to trigger a pre-fetch.

**Comment by morgs32** [comment]
Nice! So something like this? That would be pretty slick.
```

// userQuery.js
import getUser from 'getUser'
const userQuery = selectorFamily({
  key: 'UserNameQuery',
  get: async (userId) = {
    const user = await getUser(userId);
    return user;
  },
});

// App.js
import userQuery from './userQuery'
function App() {

  const earlyGetUser = useRecoilCallback(async ({getLoadable}, userId) => {
     userQuery(userId)
  });

  return (
    <UserPicture 
        onClick={(userId) => {
           earlyGetUser(userId)
           goToRoute('profile', { userId })
        }}
     />
  );
}
```
