### ISSUE TITLE
"This component must be used inside a <RecoilRoot> component" when importing from "recoil."

### ISSUE THREAD

**Issue by wcleg4** [facebookexperimental/Recoil#301]
I got the recoil root error with,  
```javascript
import React from 'react';
import { RecoilRoot } from 'recoil'
import Header from 'components/Header';
import Body from 'componentsBody';

const App = () => {
    return (
        <RecoilRoot>
            <Header />
            <Body />
        </RecoilRoot>
}
```
modifying to 
```javascript
import { RecoilRoot } from 'recoil/dist/recoil.production'
```
appears to resolve it.

**Comment by drarmstr** [comment]
cc @mondaychen

**Comment by wcleg4** [comment]
Issue also isn't experienced with 0.0.7

**Comment by mondaychen** [comment]
So it's good to close?

**Comment by JonTheFox** [comment]
Neither option solved the problem for me.

**Comment by MarekMaras** [comment]
Got the same issue, even with the "hotfix".

**Comment by AlexTechNoir** [comment]
I have the same issue with Next.js. Recoil ver. ^0.4.1.

Modifying import statement didn't help.

I follow [Next.js with Recoil official example](https://github.com/vercel/next.js/tree/canary/examples/with-recoil), but it uses 0.0.7 ver.

Does anybody knows how to solve it?

**Comment by AlexTechNoir** [comment]
No, I'm just trying to learn Recoil by adopting it instead of React Context.

**Comment by Justin9606** [comment]
I solved by import RecoilRoot inside the index.js and wrap the App component instead import into to the App.js

import { StrictMode } from "react";
import ReactDOM from "react-dom";
import { RecoilRoot } from "recoil";

import App from "./App";

const rootElement = document.getElementById("root");
ReactDOM.render(
  <RecoilRoot>
    <StrictMode>
      <App />
    </StrictMode>
  </RecoilRoot>,
  rootElement
);

**Comment by Justin9606** [comment]
I solved by import RecoilRoot inside the index.js and wrap the App component instead import into to the App.js

import { StrictMode } from "react";
import ReactDOM from "react-dom";
import { RecoilRoot } from "recoil";

import App from "./App";

const rootElement = document.getElementById("root");
ReactDOM.render(
  <RecoilRoot>
    <StrictMode>
      <App />
    </StrictMode>
  </RecoilRoot>,
  rootElement
);

**Comment by Justin9606** [comment]
![Screen Shot 2022-02-24 at 1 43 23 PM](https://user-images.githubusercontent.com/54047658/155459623-df410c6b-1345-4ef9-9b6d-2f1cc2a72868.png)

I solved by import inside the index.js and wrapping the App (comontent) with RecoilRoot instead of import it into the App.js

**Comment by khashayarghajar** [comment]
simply follow the rules, use RecoilRoot at the Root.js ~ renderers instead of import it into the Component.js
