### ISSUE TITLE
[BUG] App crashes when selectors have duplicated keys. Unclear error message

### ISSUE THREAD

**Issue by babichss** [facebookexperimental/Recoil#304]
![image](https://user-images.githubusercontent.com/3343105/84359077-c1220180-abd0-11ea-8aca-175363d51607.png)

Expected behavior: Error message should be clearer.

**Comment by drarmstr** [comment]
Selector keys must be unique.  We had a bug with this error report that was resolved.  Are you using 0.0.8 or master?

**Comment by babichss** [comment]
@drarmstr 0.0.8

**Comment by drarmstr** [comment]
The fix was #199, seems like it's not in a release yet.
