### ISSUE TITLE
Question: nested atom

### ISSUE THREAD

**Issue by hatpick** [facebookexperimental/Recoil#316]
How can one model  a nested structure such as tree (without flattening it)

```typescript
type Node {
    id: string; // unique id
    label: string;
    children: readonly Node[];
}
```
Let's say my component renders this tree, and I want it to re-render when a deep Node label changes.

**Comment by drarmstr** [comment]
One option might be something like:
```
type ID = string;

type Node = {
    id: ID,
    label: string,
    children: $ReadOnlyArray<ID>,
};

const treeState = atomFamily<ID, Node>({
  key: 'Tree',
  default: id => ({id, label: id, children: []}),
});
```

If you used an [`atomFamily`](https://recoiljs.org/docs/api-reference/utils/atomFamily) per node, then your component rendering the tree would be subscribed to whatever nodes it used to render.  To further limit that, you could have a component render the tree by rendering components for each node; those node components would then depend on the atom for that node.  This way only the node with the label change would be re-rendered.  Remember that values stored in atoms are immutable and frozen by default.

**Comment by hatpick** [comment]
@drarmstr each component that is rendering a tree node should look it up by id, right? (denormlaize)

**Comment by drarmstr** [comment]
> @drarmstr each component that is rendering a tree node should look it up by id, right? (denormlaize)

Yes, that would cause the component to only be subscribed to changes from that node.
