### ISSUE TITLE
Use Symbol for keys

### ISSUE THREAD

**Issue by LyMc** [facebookexperimental/Recoil#32]
This is a proposal to use Symbol for keys in order to simplify API.

**Comment by drarmstr** [comment]
Can you clarify which "keys" you are referring to?  The API generally tries to avoid using keys.  In most usage we use objects as handles to atoms and selectors.  By using this we can do type checking if the nodes are read/write or read-only, and can perform run-time type checks to see if a variable is an atom/selector handle or some other value.

**Comment by davidmccabe** [comment]
The main thing keys are used for is persistence. Symbols by design would not work for this.

**Comment by LyMc** [comment]
When you create an atom or a selector you have to provide a key - ` A unique string used to identify the atom internally. This string should be unique with respect to other atoms and selectors in the entire application.`. You can get rid of it if you use Symbols internally. This can also help simplify the API like: `atom(defaultValue)`, `selector(getter, setter)` or you can have a generic state creator `atom(defaultValue || getter, setter)`.

**Comment by drarmstr** [comment]
Ah, those keys.  We could dynamically generate keys if they are either strings or symbols.  But, keys are intended to be used in a few use-cases where a persistent value is needed.  For example, they are used to persist atom state in some way such as the URL, a backing store DB, etc.  Another example is exposing the atom or selector in developer tools for debugging.  (This hasn't been published yet)

**Comment by LyMc** [comment]
I didn't know about these plans, thanks for clarifying.

**Comment by joslarson** [comment]
@drarmstr what do you think a bout this idea: https://github.com/facebookexperimental/Recoil/issues/446#issuecomment-702957394

**Comment by drarmstr** [comment]
> @drarmstr what do you think a bout this idea: [#446 (comment)](https://github.com/facebookexperimental/Recoil/issues/446#issuecomment-702957394)

I don't think we want to rely on a build step.  But, we are looking at options for layering the API as proposed.  We're taking this slow to avoid too much churn on the API, so considering it with some other refinements we are evaluating.

**Comment by joslarson** [comment]
@drarmstr  Glad to hear it. And to be clear, I wasn't suggesting that the build step be required, but just to build the api in a way that a build step could be implemented.
