### ISSUE TITLE
Key and Default

### ISSUE THREAD

**Issue by leeratyou** [facebookexperimental/Recoil#327]
Hi, i wonder any use cases for current syntax for key and default as object

I have created some atomHelper across my code and all project feels well:

```
import uuid from 'uuid/v4'
import { atom as recoilAtom } from 'recoil'

function atom(defaultValue) {
  return recoilAtom({
    key: uuid(),
    default: defaultValue
  })
}
```

**Comment by Shmew** [comment]
You don't want to randomly generate keys [as discussed here](https://github.com/facebookexperimental/Recoil/issues/129). What you're probably looking for is the [atomFamily](https://recoiljs.org/docs/api-reference/utils/atomFamily).
