### ISSUE TITLE
Changing the terms atom, state, value, or selector to be more consistent

### ISSUE THREAD

**Issue by verekia** [facebookexperimental/Recoil#328]
EDIT: I misunderstood how `useRecoilState` and `useRecoilValue` could be used on both atoms and selectors. I removed the content of this post to not confuse others.

**Comment by Shmew** [comment]
While I agree the term `selector` is a bit ambiguous, having separate hooks for these just adds additional complexity with no benefit. In the context of `useRecoilValue` *an atom and selector are indistinguishable*. The same applies when the selector implements `set`, and using `useRecoilState`. 

It's also my opinion that aliasing when not necessary just adds more complexity.

**Comment by verekia** [comment]
Thank you for pointing this out. I didn't realize `useRecoilValue` could be used on atoms as well. That invalids a lot of things I wrote. I will edit the post.
