### ISSUE TITLE
Components being re-rendered even when recoilstate value is the same

### ISSUE THREAD

**Issue by cybervaldez** [facebookexperimental/Recoil#340]
Is this intentional? Here's a sandbox:
https://nhcpy.csb.app/

**Comment by Shmew** [comment]
See #314

**Comment by cybervaldez** [comment]
To those that need a very quick work around for this just wrap your component with useMemo.

e.g return useMemo(()=><>{atomValue}</>, [atomValue])

**Comment by drarmstr** [comment]
Duplicate of #314
