### ISSUE TITLE
Selector + Loadable for Search stops working on Rerender/Hot-Reload Or Suspense/Loadable flashes white.

### ISSUE THREAD

**Issue by stephanoparaskeva** [facebookexperimental/Recoil#353]
### Problem:

I'm building a small search screen, and it works great. Caching properly etc. But the problem is that If the state refreshes (via changing code and saving in IDE). Or a rerender occurs in the component: The search results are all cleared from view and the Search Bar no longer accepts input. (It just shudders on typing and the value no longer changes (is reset to '')). This is the same whether I use `React.Suspense` or `useLoadable` + switch statement.

---
### Example:
```JavaScript
import React from 'react';
import { useRecoilState, selector, atom, useRecoilValueLoadable } from 'recoil';
import axios from 'axios';
import { TextInput, FlatList, SafeAreaView, View } from 'react-native';
import SearchRow from '../search_row';
import { searchListStyles } from './search_list.style';
import DismissView from '../../common/views/dismiss_view';
import { Navigation } from '../../../core/navigation/navigator.type';

const termAtom = atom({ key: 'termAtom', default: '' });

const searchSelector = selector({
  key: 'searchSelector',
  get: async ({ get }) => {
    const term = get(termAtom);
    try {
      const res = await axios({
        url: `http://localhost:4000/categories/search?q=${
          term || '*'
        }&query_by=title`,
        method: 'get',
      });

      return res?.data?.hits;
    } catch (err) {
      console.warn(err)
    }
  },
});

const SearchList = ({ navigation }: Navigation) => {
  const [term, setTerm] = useRecoilState(termAtom);
  const searchLoadable = useRecoilValueLoadable(searchSelector);

       // THIS WILL CAUSE PAGE TO GO BLANK AND NOT RESPOND
     useEffect(() => {
    setTimeout(() => setTerm(Math.random()), 10000);
  }, []);


  return (
    <DismissView style={searchListStyles.root}>
      <SafeAreaView>
        <FlatList
          style={{ height: '100%' }}
          showsVerticalScrollIndicator={false}
          stickyHeaderIndices={[0]}
          ListHeaderComponent={
            <TextInput
              value={term}
              placeholder='Search'
              onChangeText={setTerm}
              style={searchListStyles.input}
            />
          }
          initialNumToRender={25}
          data={
            (Array.isArray(searchLoadable.contents) &&
              searchLoadable.contents) ||
            []
          }
          renderItem={({ item }) => (
            <React.Suspense
              fallback={
                <View style={{ flex: 1, backgroundColor: 'transparent' }} />
              }>
              <SearchRow navigation={navigation} category={item} />;
            </React.Suspense>
          )}
        />
      </SafeAreaView>
    </DismissView>
  );
};

export default SearchList;
```

### Additional
If I remove 
`const searchLoadable = useRecoilValueLoadable(searchSelector);` and
`   data={ (Array.isArray(searchLoadable.contents) &&
              searchLoadable.contents) ||
            []}
`
And replace this all with
`  const hits = useRecoilValue(searchSelector); `
` data={hits} `

I then begin to see white flashing of the whole app rendering the Parent React.Suspense Loading page, while the request is fired.

So the issue is twofold:

#### Either I have a component that breaks on small changes or rerenders/refreshes via IDE or I have a component that completely shows/hides the global React.Suspense fallback

What is the solution?

### Version 0.0.8, IOS, React Native.

**Comment by Shmew** [comment]
The coupling of components in the `FlatList` makes things a bit difficult here. 

I've played with some stuff similar to this, and a couple things to note:
* Your component (from what I can see) doesn't need to subscribe to the term so that can just be `useSetRecoilState`. If it does, do so in the component that needs it, not the actual input component (if you can).
* Ideally you'd pull out these components so they're not all re-rendering when things they don't need change. Like the search bar itself and the data it loads. With this de-coupling you can put a `React.Suspense` around the actual list you're generating while the query loads.
* Recoil doesn't work great with HMR/fast-refresh at the moment. If you really want this, you'd need to implement a mechanism to persist them. Such as to the session storage.

**Comment by stephanoparaskeva** [comment]
> The coupling of components in the `FlatList` makes things a bit difficult here.
> 
> I've played with some stuff similar to this, and a couple things to note:
> 
> * Your component (from what I can see) doesn't need to subscribe to the term so that can just be `useSetRecoilState`. If it does, do so in the component that needs it, not the actual input component (if you can).
> * Ideally you'd pull out these components so they're not all re-rendering when things they don't need change. Like the search bar itself and the data it loads. With this de-coupling you can put a `React.Suspense` around the actual list you're generating while the query loads.
> * Recoil doesn't work great with HMR/fast-refresh at the moment. If you really want this, you'd need to implement a mechanism to persist them. Such as to the session storage.
Those are some very reasonable points!
- How would I useSetRecoilState like you're suggesting?
- Is there any way to do this all without needing to decouple just yet, I'm not at a stage where I can further refactor (I'd lose track). (I don't *need* suspense at all. Just the 'cachability' and speed of the selector.

**Comment by Shmew** [comment]
Make the `TextInput` in your `ListHeaderComponent` prop not set the `value` prop of that component. Then simply turn `const [term, setTerm] = useRecoilState(termAtom);` into `const setTerm = useSetRecoilState(termAtom);`

To make this more usable without decoupling is a bit tricky... since anything that subscribes to an async `selector` is going to *become* an async selector. This means you need a `React.Suspense` *above* your entire component. The issue here, is that your component has the search bar inside of it. Additionally, because the data also at the top level of your `FlatList` you can't move the data fetching lower in the component. If the `renderItem` component was responsible for the data (and since you're using pagination) they could call a `selectorFamily` to see if there is a result to display. That would let the list *items* become the async part of the component, rather than the entire thing.

**Comment by stephanoparaskeva** [comment]
@Shmew 
If the text input never sets the term via setTerm, what would it do? 
How do I get the term to the selector without subscribing it?
Without `term` after turning it into `  const setTerm = useSetRecoilState(termAtom);` How does the `TextInput` get it's value?

**Comment by Shmew** [comment]
You simply don't include a `value` prop at all. It makes the component uncontrolled. The selector in your example already subscribes to the term. 

So it would be:

`const setTerm = useSetRecoilState(termAtom);`

and

```js
ListHeaderComponent={
  <TextInput
    placeholder='Search'
    onChangeText={setTerm}
    style={searchListStyles.input}
  />
}
```

**Comment by stephanoparaskeva** [comment]
> You simply don't include a `value` prop at all. It makes the component uncontrolled. The selector in your example already subscribes to the term.
> 
> So it would be:
> 
> `const setTerm = useSetRecoilState(termAtom);`
> 
> and
> 
> ```js
> ListHeaderComponent={
>   <TextInput
>     placeholder='Search'
>     onChangeText={setTerm}
>     style={searchListStyles.input}
>   />
> }
> ```

Never knew you could make it uncontrolled!, what's the disadvantage of that?

I actually don't even need a selector at all, just remove setTerm all together, and put the query function as a handler for `onChangeText`  that just sets `hits` and then memoize the queries so I can cache the results :)

Or is that a less optimal route

**Comment by Shmew** [comment]
>Never knew you could make it uncontrolled!, what's the disadvantage of that?

As long as you don't need to do anything to the value (that the input component needs) as far as I know it's nothing but beneficial as it's less overhead for React.

> I actually don't even need a selector at all, just remove setTerm all together, and put the query function as a handler for onChangeText that just sets hits and then memoize the queries so I can cache the results :)

That's a good point! Just have an `atomFamily` that accepts a term, and then set it with your query results. This would let you "ask" the atom if it already has the results of that query or not. You'd need to use `useRecoilCallback` to accomplish this. I think you'd need an additional atom to store the "current" query results with this model.

Still not as nice as decoupling your component, but it should get the job done.

**Comment by stephanoparaskeva** [comment]
> > Never knew you could make it uncontrolled!, what's the disadvantage of that?
> 
> As long as you don't need to do anything to the value (that the input component needs) as far as I know it's nothing but beneficial as it's less overhead for React.
> 
> > I actually don't even need a selector at all, just remove setTerm all together, and put the query function as a handler for onChangeText that just sets hits and then memoize the queries so I can cache the results :)
> 
> That's a good point! Just have an `atomFamily` that accepts a term, and then set it with your query results. This would let you "ask" the atom if it already has the results of that query or not. You'd need to use `useRecoilCallback` to accomplish this. I think you'd need an additional atom to store the "current" query results with this model.
> 
> Still not as nice as decoupling your component, but it should get the job done.

What do you think about my code above as an alternative?

**Comment by Shmew** [comment]
Seems like it would work, you'd probably want to cap the size of that array so it doesn't eat all the memory though.

**Comment by stephanoparaskeva** [comment]
Closing as we found a resolution :)
