### ISSUE TITLE
Unique identification of snapshots

### ISSUE THREAD

**Issue by Shmew** [facebookexperimental/Recoil#365]
I'm trying to implement a time traveling hook and struggling with determining when to clear the future snapshots. What's the best way to (if there is one?) determine if a given snapshot from `useTransactionObserver` is unique when comparing it to other snapshots?

You can see what I'm talking about in this gif:
![recoil_time_travel](https://user-images.githubusercontent.com/11186595/85114596-92fb7d80-b1df-11ea-864a-fce496bcbb30.gif)

**Comment by adrianbw** [comment]
This is uggggly, but how about?

`javascript
const snapshotsAreEqual = (previousSnapshot, snapshot) => {
  const oldLoadable = previousSnapshot.getLoadable(store);
  const newLoadable = snapshot.getLoadable(store);
  const oldState =
    oldLoadable.state !== "hasError" ? (oldLoadable.contents as T) : false;
  const newState =
    newLoadable.state !== "hasError" ? (newLoadable.contents as T) : false;
  return _.isEqual(oldState, newState)
}
`

**Comment by Shmew** [comment]
@adrianbw thanks for the advice, it didn't work for me as I didn't have an anchor point, but that gave me an idea to use the snapshot itself!

I was able to do it with a `selectorFamily` to generate a hash code after feeding the snapshots into the `constSelector`.

![recoil_excel_time_travel](https://user-images.githubusercontent.com/11186595/85185421-76039080-b259-11ea-8ca4-656be7d5b776.gif)

**Comment by drarmstr** [comment]
Duplicate of #427 

@Shmew  - With #463 it should now be possible to use `snapshot.getID()` to check for the same snapshot.
