### ISSUE TITLE
useEffect setter dependency

### ISSUE THREAD

**Issue by asotog** [facebookexperimental/Recoil#367]
Hi, this is only a question, correct me if i'm wrong, on this example don't you need to specify `setCurrentUserID` 
 as dependency ?

https://recoiljs.org/docs/guides/asynchronous-state-sync#sync-state-from-server

**Comment by GR34SE** [comment]
According to Dan's blogpost: https://overreacted.io/a-complete-guide-to-useeffect/#decoupling-updates-from-actions

> (You may omit dispatch, setState, and useRef container values from the deps because React guarantees them to be static. But it also doesn’t hurt to specify them.)

So seems like setter from recoil also adds up to this rule 👍

**Comment by asotog** [comment]
Appreciate your response didn't know that, thank you https://github.com/facebookexperimental/Recoil/issues/367#issuecomment-646985256
