### ISSUE TITLE
[DX] Thoughts after first read

### ISSUE THREAD

**Issue by dcworldwide** [facebookexperimental/Recoil#373]
In the spirit of a minimal api.. why introduce selectorFamily? why not use selector(*args)?

why useRecoilState|Value when useAtomState|Value is semantically more aligned (and more terse)?

**Comment by drarmstr** [comment]
> In the spirit of a minimal api.. why introduce selectorFamily? why not use selector(*args)?

Trying to keep the base core API minimal with `selector`.  The `selectorFamily` is a helper that can be built on top of the core API as a convenience.  But, it is not required to use nor part of the core API.  We ended up including it in the primary package for convenience, but it's not required.

> why useRecoilState|Value when useAtomState|Value is semantically more aligned (and more terse)?

A `RecoilState` node can be implemented by either an atom or a writeable selector.  It's abstracted from the interface if the node is implemented as an atom or selector, and the implementation can change without affecting the user call-sites.
