### ISSUE TITLE
[bug] Bad setState in Batcher

### ISSUE THREAD

**Issue by quuu** [facebookexperimental/Recoil#374]
On the most recent version of React and Recoil, the console throws warnings on initial load about a bad state update.

Following the guide at https://fb.me/setstate-in-render, it seems like it's happening with selectors. The error the console is pointing to is the single instance in a component that I do `useRecoilValue()` on a selector.

![image](https://user-images.githubusercontent.com/32676955/85215984-6d8c8200-b34d-11ea-8d02-6435c6cafdab.png)

**Comment by markstock7** [comment]
it is a known bug described in #12, should fix in https://github.com/facebookexperimental/Recoil/pull/369

**Comment by drarmstr** [comment]
Duplicate of #12
