### ISSUE TITLE
[Question]How to achieve cache/subscribe functionality ? 

### ISSUE THREAD

**Issue by alex-sh-li** [facebookexperimental/Recoil#376]
[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ29tcG9uZW50IFNldFJlY29pbFN0YXRlXSAtLT4gfFVwZGF0ZWQgUmVjb2lsU3RhdGV8Qih0cmlnZ2VyIHNlbGVjdG9yKVxuQiAtLT4gRVt1c2UgdGhlIHN0YXRlIHRvIGNhbGwgYXBpXVxuQiAtLT4gQ1tBZGRlZCB1cGRhdGVkIHN0YXRlIGFuZCBhcGkgcmVzcG9uc2UgdG8gYSBhcnJheV1cbkUgLS0-IENcbkMgLS0-fHVzZVJlY29pbFZhbHVlfCBEW0Fub3RoZXIgY29tcG9uZW50IHVzaW5nIHRoZSBhcnJheV0gXG5cblxuXG5cbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ29tcG9uZW50IFNldFJlY29pbFN0YXRlXSAtLT4gfFVwZGF0ZWQgUmVjb2lsU3RhdGV8Qih0cmlnZ2VyIHNlbGVjdG9yKVxuQiAtLT4gRVt1c2UgdGhlIHN0YXRlIHRvIGNhbGwgYXBpXVxuQiAtLT4gQ1tBZGRlZCB1cGRhdGVkIHN0YXRlIGFuZCBhcGkgcmVzcG9uc2UgdG8gYSBhcnJheV1cbkUgLS0-IENcbkMgLS0-fHVzZVJlY29pbFZhbHVlfCBEW0Fub3RoZXIgY29tcG9uZW50IHVzaW5nIHRoZSBhcnJheV0gXG5cblxuXG5cbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

I am currently working on an application that records some user input, send it to the server , and then the response. but I want to show a backlog of the user event. with input and response. 
how should I achieve this kind of functionality?

**Comment by alex-sh-li** [comment]
any update?

**Comment by mondaychen** [comment]
This should be doable once we launch devtools.

**Comment by drarmstr** [comment]
You can also setup a component to subscribe to a state change with an effect hook to send to a server and log as desired.

```
function Logger() {
  const value = useRecoilValue(myState);
  useEffect(() => {
    sendToServer(value);
    logChange(value);
  }, [value]);
  return null;
}
```

**Comment by alex-sh-li** [comment]
@drarmstr  thanks for the reply!
