### ISSUE TITLE
How do we compose a new atom based on the values of other atoms/selectors "without" subscribing to them?

### ISSUE THREAD

**Issue by cybervaldez** [facebookexperimental/Recoil#388]
I need to create an atom that would take the current value of another atom/selector but would not subscribe to it. I figured I would be able to do this based on the [atomFamily docs](https://recoiljs.org/docs/api-reference/utils/atomFamily/):

```
const myAtomFamily = atomFamily({
  key: ‘MyAtom’,
  default: selectorFamily({
    key: 'MyAtom/Default',
    get: param => ({get}) => {
      return computeDefaultUsingParam(param);
    },
  }),
});
```
but i've tested and this is the same as (both are subscribed to the parent when using the get function)
```
const mySelectorFamily = selectorFamily({
    key: 'mySelectorFamily',
    get: param => ({get}) => {
      return computeDefaultUsingParam(param);
    },
  })

```
So either it's a bug, the document is incorrect or there's a different use-case for the two that i'm not aware of. Here's a codesandbox: https://codesandbox.io/s/pedantic-pascal-hb0ow?file=/src/App.js

**Comment by mondaychen** [comment]
In the sandbox you provided, you are using `get` inside the getter function to read the atoms. In that way, it's expected behavior that subscription is set up. If you want to create a new atom without subscribing anything, you can read the value outside (e.g. in component) then pass the value in as params.

**Comment by cybervaldez** [comment]
Just wondering what sets the two apart? What's a good use case for passing in a selectorFamily to an atomFamily's default value?

**Comment by mondaychen** [comment]
If a new `atomFamily` member depends on another atom, you'll want to use `selectorFamily`. Otherwise, a simple value or a function should work.
