### ISSUE TITLE
Best practices when using atoms or selectors with web API

### ISSUE THREAD

**Issue by iandjx** [facebookexperimental/Recoil#391]
The docs show examples of using selectors when fetching data asynchronously. The examples are just limited in fetching data on component render. 
Which would be the better option when say fetching data after onClick of a button?

a. onClick calls fetch function then stores value to an atom
b. onClick updates the value of an atom which then triggers a selector to reload due to dependency with the said atom.

**Comment by drarmstr** [comment]
Both approaches are valid.  Storing in an atom after fetching means the atom will maintain the previous value until you change it, or you could explicitly store a pending state.  Using an async selector, either triggered by changing a dependent atom input or selectorFamily parameter means the selector will go into a pending state during the query.  [Here's an example](https://recoiljs.org/docs/guides/asynchronous-data-queries#data-flow-graph) of option B where an `onClick` handler changes an atom which triggers an async selector and re-renders.
