### ISSUE TITLE
What is benefit useRecoilValue vs useRecoilState

### ISSUE THREAD

**Issue by behnammodi** [facebookexperimental/Recoil#403]
I think we should have a little API with empowering task ex:

```js
const charCountState = selector({
  key: 'charCountState', // unique ID (with respect to other atoms/selectors)
  get: ({get}) => {
    const text = get(textState);
    return text.length;
  },
});

function CharacterCount() {
  const count = useRecoilValue(charCountState);

  return <>Character Count: {count}</>;
}
```

But I think `useRecoilValue` is additional and we can use `useRecoilState`

```js
function CharacterCount() {
  const [count] = useRecoilState(charCountState);

  return <>Character Count: {count}</>;
}
```

**Comment by drarmstr** [comment]
Yes, you can use `useRecoilState()`.  Some benefits to `useRecoilValue()` is that it is cleaner to use as an expression, vs a statement, and more obvious from the call-site that the component does not mutate state.
