### ISSUE TITLE
Do you have any plans to prevent unnecessary re-render?

### ISSUE THREAD

**Issue by behnammodi** [facebookexperimental/Recoil#405]
Please point to this code:

```jsx
const textState = atom({
  key: 'textState', 
  default: '',
});

const maxLengthState = selector({
  key: 'maxLengthState', 
  get: ({get}) => {
    const text = get(textState);

    return text.length > 5;
  },
});

function MaxLengthWarning() {
  const result = useRecoilValue(maxLengthState);
  return result && (<div>Max Lenght</div>);
}
```

`maxLengthState` selector doesn't prevent to re-render <MaxLengthWarning /> when previous value and next value is equal

**Comment by drarmstr** [comment]
#386 will prevent re-renders when an atom is updated to the same value by reference equality.  #314 is tracking more general avoiding of updates for subscribers when values change.

**Comment by behnammodi** [comment]
@drarmstr Thanks
