### ISSUE TITLE
`set` from `initializeState` does not trigger hooks

### ISSUE THREAD

**Issue by Jahans3** [facebookexperimental/Recoil#408]
When reinitializing state using `initializeState` on `RecoilRoot` it appears that calling `set` does not trigger hooks, so my app is not updated.

In the image below you can see:
1. `initializeState` being run first ("Init state")
2. The first value read from `useRecoilValue` - this is the default value
3. `set` is called inside `initializeState` but `useRecoilValue` isn't triggered again

<img width="293" alt="Screenshot 2020-06-26 at 11 48 22" src="https://user-images.githubusercontent.com/12807687/85849564-1a7a5b00-b7a3-11ea-9cfc-206a9d002133.png">

I'm using Recoil with React Native based on #114 - perhaps this is related to that?

This is the code I use to persist my atoms:

```js
export default function createRecoilPersistor(
  atoms: Array<RecoilState<any>>
): Persistors {
  function initializeState({ set }: Initializer): void {
    console.log('Init state');
    for (const currentAtom of atoms) {
      const { key } = currentAtom;
      AsyncStorage.getItem(key).then(value => {
        if (value !== null) {
          console.log('Set value for ' + currentAtom.key, { value });
          set(currentAtom, JSON.parse(value));
        }
      });
    }
  }

  function RecoilPersistor(): null {
    useTransactionObservation_UNSTABLE(
      ({ atomValues, modifiedAtoms }: Observation): void => {
        for (const modifiedAtom of modifiedAtoms) {
          const matchingAtom = atoms.find(({ key }) => key === modifiedAtom);
          if (matchingAtom) {
            AsyncStorage.setItem(
              modifiedAtom,
              JSON.stringify(atomValues.get(modifiedAtom))
            );
          }
        }
      }
    );
    return null;
  }

  return {
    initializeState,
    RecoilPersistor
  };
}
```

Then in my App.js:

```js
const { RecoilPersistor, initializeState } = createRecoilPersistor([
  darkModeAtom,
  userAuthAtom,
  userDetailsAtom
]);

function useTheme() {
  const darkMode = useRecoilValue(darkModeAtom);
  console.log({ initDarkMode: darkMode });
  const baseTheme = darkMode ? eva.dark : eva.light;
  const statusBarStyle = darkMode ? 'light-content' : 'default';
  return [{ ...baseTheme, ...customTheme }, statusBarStyle];
}

function App(): React.ReactElement {
  const [theme, statusBarStyle] = useTheme();
  return (
    <ApplicationProvider {...eva} theme={theme}>
      <StatusBar barStyle={statusBarStyle} />
      <NavigationRoot />
    </ApplicationProvider>
  );
}

export default function AppRoot(): React.ReactElement {
  return (
    <>
      <IconRegistry icons={EvaIconsPack} />
      <SafeAreaProvider>
        <RecoilRoot initializeState={initializeState}>
          <RecoilPersistor />
          <App />
        </RecoilRoot>
      </SafeAreaProvider>
    </>
  );
}
```

**Comment by Jahans3** [comment]
For anyone else waiting for the finished API, you can gate your application while you initialise your atoms manually:

```js
function RecoilStorageGate({
  atom,
  storage,
  children
}: RecoilStorageGateProps): React.ReactNode {
  const [loaded, setLoaded] = useState(false);
  const setAtomValue = useSetRecoilState(atom);

  useEffect(() => {
    storage.get().then(value => {
      setAtomValue(value);
      setLoaded(true);
    });
  }, []);

  if (!loaded) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Splash!</Text>
      </View>
    );
  }

  return children;
}
```

**Comment by harryy2510** [comment]
I'm too stucked with this issue. initializeState used to work with verion 0.0.8 but with version 0.0.10, it has stopped working

**Comment by drarmstr** [comment]
The `initializeState` prop is only intended to setup the initial state before the initial render.  This is useful for supporting things like server-side rendering where it is critical the state is hydrated for that initial render.  It is not intended for async updates to state.  Use the existing Recoil hooks for updating state asynchronously, such as `useSetRecoilState()` or `useRecoilCallback()`

**Comment by Jahans3** [comment]
Thanks for the clarification and quick update to the docs 👍

Are there plans to allow for async initialisation in future?

**Comment by drarmstr** [comment]
I don't know that we'd want to complicate the core interface with this, but some helper wrapper util to support async initialization may make sense.  Haven't tested the below, but maybe something like this...  Let us know if it works for you.
```jsx
function AsyncInitRecoilRoot({children, Fallback, initializeStateAsync}) {
  const [isLoaded, setLoaded] = useState(false);
  
  function InitializeState() {
    const snapshot = useRecoilSnapshot();
    const gotoSnapshot = useGotoRecoilSnapshot();
    
    useEffect(async () => {
      const initializedSnapshot = await snapshot.mapAsync(initializeStateAsync);
      gotoSnapshot(initializedSnapshot);
      setLoaded(true);
    }, []);
    
    return null;
  }
  
  return (
    <RecoilRoot>
      {isLoaded
        ? children
        : <>
           <InitializeState />
           <Fallback />
        </>
      }
    </RecoilRoot>
  );
}
```

**Comment by ifeanyiisitor** [comment]
I believe I'm experiencing this issue with nextjs. 

Basically I have a page that uses `getServerSideProps` to fetch the initial state that is later initialised via `initializeState` on `RecoilRoot`. It works as expected when accessing the page directly from the browser. If I don't access the page directly from the browser however, but instead I click a link on a page that triggers a client side navigation to the page (via `next/router`) the state returned from `getServerSideProps` in that instance does not get initialized. My expectation is that doing the following:

```
<RecoilRoot initializeState={initializeState}>
  <App />
</RecoilRoot>
```

..should alway result in the state becoming reinitialized whenever the component re-renders with new state that must be initialised. Anything else to me seems more complicated than it should be and not quite in keeping with the 'react way' (so to speak). Am I misunderstanding things? Apologies if I am.

**Comment by drarmstr** [comment]
`initializeState` will only initialize on first mounting.  Otherwise if the host component were ever re-rendered for any reason the state would unexpectedly be re-initialized.  You can add a `key` prop to `<RecoilRoot>` to force re-mounting and re-initialization.
