### ISSUE TITLE
Question: Should we avoid keeping default values of atoms in memory?

### ISSUE THREAD

**Issue by vdanchenkov** [facebookexperimental/Recoil#415]
My app can have numerous items, some of them can be edited by the user. 

```
let editedAtomFamily =
  Recoil.atomFamily({
    key: "edited",
    default: () => undefined
  });
```

In component:
```
let [value, setValue] = Recoils.useState(editedAtomFamily(id));
```

So, by default item have `undefined` value which means that it was not edited yet. If 1000 items was rendered, we will have 1000 atoms in memory. If we assume that default function is idempotent, we could avoid atom storage and just keep calling default function when needed until first setValue is called. 

Does this optimization makes sense?

**Comment by mondaychen** [comment]
I'm not sure if I understand... Are you talking about not storing the atoms themselves, or not storing the default values (by lazy executing)?

It will be helpful if you can create a fork to demonstrate your idea for this optimization.

**Comment by g1nk1-m** [comment]
@mondaychen as far as I can understand, he's talking about caching the default value of a particular atomFamily and the call to atoms of the same family will refer to the cached default value until it's changed in which case the particular atom will store it's value in memory while the others still refer to the cached value till they're updated

**Comment by vdanchenkov** [comment]
Current behaviour is to store default value in memory for every atom once atomFamily called. 

Suggestion: do not cache and do not store default value. Just call default() on demand on every render until another state is set.

I'm not sure if I should worry about having 1000 atoms filled with default values in the first place.

**Comment by mondaychen** [comment]
If we already have 1000 atom objects in memory, having default values in isn't gonna add a lot to memory consumption. In your case, the default value is `undefined`, then it's even less a problem.
