### ISSUE TITLE
What does the setter do in useRecoilStateLoadable?

### ISSUE THREAD

**Issue by adrianbw** [facebookexperimental/Recoil#416]
I'm not clear on the correct way to use the setter useRecoilStateLoadable. Can someone show me an example? If the getter is a loadable, would I write something like useRecoilValueLoadable, but I can also overwrite it with the setter?

**Comment by drarmstr** [comment]
The setter from `useRecoilStateLoadable()` is the same setter as provided by `useRecoilState()` or `useSetRecoilState()`.

**Comment by adrianbw** [comment]
OK, but what's the use case? Get is an async call that returns the results of that call, so why would I use the setter?

**Comment by drarmstr** [comment]
The hook provides symmetry with [`useRecoilState()`](https://recoiljs.org/docs/api-reference/core/useRecoilState) which provides a tuple of the current value and a callback to set the value.  The difference is that  [`useRecoilState()`](https://recoiljs.org/docs/api-reference/core/useRecoilState) may throw errors or use React Suspense for pending async values while [`useRecoilStateLoadable()`](https://recoiljs.org/docs/api-reference/core/useRecoilStateLoadable) always returns immediately with a [`Loadable<T>`](https://recoiljs.org/docs/api-reference/core/Loadable) of the current state.  The use-case is for when you are dealing with state that may be in a pending or error state and not using React Error Boundaries or Suspense.  We are contemplating deprecating this hook, it doesn't provide anything new.
