### ISSUE TITLE
Export Loadable states

### ISSUE THREAD

**Issue by montogeek** [facebookexperimental/Recoil#418]
Would you accept a PR that exports https://github.com/facebookexperimental/Recoil/blob/master/typescript/index.d.ts#L166 state values as JavaScript constants?

Something like:
```js
import { LoadableStates } from "recoil";

LoadableStates.hasValue; // hasValue
// etc
```
?

Motivation is of course not having these strings comparisons, of course this could be done in user land but it could break in an update.

Also you could say it is not needed since they are in TS, but not everybody uses TS.

**Comment by drarmstr** [comment]
If you're not using a type system, what prevents a typo of the `LoadableStates` property names?
