### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by jacques-blom** [facebookexperimental/Recoil#420]
This issue is a general request for more context around the [html/js/recoil/oss/util](https://github.com/facebookexperimental/Recoil/commit/d4343b68eb06c6b58720adb5d0e2d3e4001921cb) and [html/js/recoil/oss/npm](https://github.com/facebookexperimental/Recoil/commit/b8139e724f05bf2dcc803cccf9c06532f90d71fc).

It'd be good to know why these changes were made. They're breaking OSS builds:

## `Recoil_sprintf` is missing
I see it was deleted in [this commit](https://github.com/facebookexperimental/Recoil/commit/d4343b68eb06c6b58720adb5d0e2d3e4001921cb). Looks like it was a sprintf wrapper. I'm not too familiar with sprintf, so I'm not sure what this wrapper did.

Can we just replace it with a direct call to `sprintf` in `Recoil_expectationViolation.js`?

## `src/npm/index.js` is missing
This is the package entry point for OSS users. Is the intention to replace this with something else?

**Comment by drarmstr** [comment]
@mondaychen - Looks like these files were deleted by the dead code reaper bot in D22184490 and D22184459 since they aren't seeing the OSS dependencies.  I'll start following-up on those diffs how to flag this for retention.

**Comment by drarmstr** [comment]
Attempt to restore sprintf() with #421

**Comment by drarmstr** [comment]
`index.js` was restored by reverting D22184490, still pending how to protect it from `DeadJSCode`...

**Comment by jacques-blom** [comment]
Makes sense. Thanks!
