### ISSUE TITLE
Idea: transaction annotations/metadata

### ISSUE THREAD

**Issue by jaredpalmer** [facebookexperimental/Recoil#423]
As a recoil developer, I want a way to easily annotate state changes so that I can build a snapshot history ui with human-readable labels, not just timestamps. 

I think this is something that recoil will have to do because there is no way to communicate metadata to the transaction observer at the moment. 

Thoughts?

**Comment by drarmstr** [comment]
What about a snapshot id?

**Comment by jaredpalmer** [comment]
Is that documented? How do I use that?

**Comment by drarmstr** [comment]
@jaredpalmer - no, not currently implemented; just asking if that feature request would work for your needs.

**Comment by jaredpalmer** [comment]
The UI I want to build is a list of: 

- Jared changed the title to “Foo”
- Jared toggled foo
- Sarah set Z
- Jared deleted thing

Where each line is a snapshot.

**Comment by drarmstr** [comment]
Snapshots from `useRecoilTransactionObserver()` might not be the right granularity for a UI like this.  Multiple state changes may be included in a single batch commit, for example.  Or, if you may have lots of unrelated state such as tab groups, pane sizes, etc that may change that you wouldn't want to be included in the history stack.  Even if you skipped storing snapshots for those transactions, going back to previous snapshots would then also revert this other state.  Snapshots from global observers like this are probably more suited for development/debug tools.

Consider using `usePrevious()` and `useEffect()` to subscribe to select atoms that you want to monitor, and pushing changes to those on a history stack with whatever metadata you wish.  [This test](https://github.com/facebookexperimental/Recoil/blob/master/src/recoil_values/__tests__/Recoil_atom-test.js#L403) kinda demonstrates the pattern.

**Comment by jaredpalmer** [comment]
Yeah, the more I think of it, the more I agree. I guess I just got excited by how easy it is to do undo and redo. I think this would be a good pattern to add to docs.

**Comment by drarmstr** [comment]
Yes, we should add this pattern of adding selected atoms to a history stack to the docs.  But, we're still working on the new singleton hook/effects pattern API, and are not yet ready to publish it.  It may yet dramatically change.
