### ISSUE TITLE
Request a way to judge the equality of two snapshots

### ISSUE THREAD

**Issue by Holybasil** [facebookexperimental/Recoil#427]
Cause of `gotoSnapshot` produces a new snapshot.

**Comment by drarmstr** [comment]
A snapshot ID may work for this.  But, may I ask what you are trying to do with snapshots?  For example, see the discussion in #423

**Comment by Holybasil** [comment]
It's similar with [#423](https://github.com/facebookexperimental/Recoil/issues/423).A new snapshot will always be produced when I use the following code to collect the history of the snapshots.
```js
useRecoilTransactionObserver(({snapshot}) => {
    setSnapshots([...snapshots, snapshot]);
  });
```
Actually, I don't want a new snapshot when I go to the history one，so I need to judge if the new snapshot is one of the history snapshots.

**Comment by drarmstr** [comment]
Document in #483
