### ISSUE TITLE
[Docs] "Bonus" section missing

### ISSUE THREAD

**Issue by pesterhazy** [facebookexperimental/Recoil#43]
From https://recoiljs.org/docs/basic-tutorial/selectors

> We could stop here, but there are some important performance considerations that we explore in the "bonus" section.

but I didn't find a bonus section or any reference to optimization.

**Comment by thisizkp** [comment]
I'm not sure if it's a still in WIP, but here's the link for the [Bonus](https://github.com/facebookexperimental/Recoil/blob/docs/docs/docs/basic-tutorial/performance.md) section

**Comment by drarmstr** [comment]
The documentation is definitely a work in progress... ;)

**Comment by thisizkp** [comment]
@drarmstr looks like everyone (including me) is searching for the hidden `bonus` section within docs. 

Maybe it makes sense to remove the para that says "explore in the bonus section..." till then. Waiting for the docs release :)

**Comment by claudiopro** [comment]
@pesterhazy thanks for bringing that up, we removed the paragraph until the tutorial is updated.
