### ISSUE TITLE
Question: Fetch end update exiting data?

### ISSUE THREAD

**Issue by Tatamethues** [facebookexperimental/Recoil#438]
I'm using selectfamily for fetching data. What is the proper way to update the exiting data? I want to do the same thing as infinity scrll.

**Comment by drarmstr** [comment]
selectors should not be used for querying mutable data.  Consider using atoms for that.  See [the docs here](https://recoiljs.org/docs/guides/asynchronous-state-sync).  But, please note, we are working on an improved API for this pattern.
