### ISSUE TITLE
provide alias for useRecoilState (useAtom)

### ISSUE THREAD

**Issue by wolfoo2931** [facebookexperimental/Recoil#44]
I would love to use say useAtom instead of useRecoilState. 
Just an idea. This library is going in the right direction!

Best Regards,
Oliver, working on [https://www.monsterwriter.app/](https://www.monsterwriter.app/)

**Comment by drarmstr** [comment]
Atoms and Selectors both share the same interface to use once constructed.  The idea is that the users of state don't need to know if that state was implemented using an Atom directly, or if it was provided via some derived state using a Selector, or even from some asynchronous data query with an asynchronous selector.  The implementation of the state can change back and forth without users of the state needing to change their callsites.  So, we don't want to bake in the term "atom" in the hook name.  Also, check out the other hooks that Recoil offers!
