### ISSUE TITLE
Next.js SSR warning with useRecoilValueLoadable

### ISSUE THREAD

**Issue by kevinwolfdev** [facebookexperimental/Recoil#440]
Given this flow:

1. User hits the profile route, which renders a loading state while fetching the user data.
2. When data is fetched, the route shows the user data.

Everything good so far, but when I reload the page, I receive a `Text content did not match` warning, specifically because the server sent the loaded state, and when the client downloaded the JS, it replaced it with the loading state.

This is an example of the code I am using extracted from [this sandbox](https://codesandbox.io/s/sparkling-cdn-ps4vh?file=/pages/index.js):

```jsx
import { selector, useRecoilValueLoadable } from "recoil";

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

const userData = selector({
  key: "auth",
  get: async () => {
    await sleep(1000);
    return { username: "Kevin Wolf" };
  }
});

export default function IndexPage() {
  const value = useRecoilValueLoadable(userData);

  if (value.state === "loading") {
    return <div>Loading user data...</div>;
  }

  return <div>Hi, {value.contents.username}</div>;
}
```

**Comment by mhmdAljefri** [comment]
it's related to life cycle `useRecoilValueLoadable` run async out side the react life cycle which provide deference values in SSR. Or I'm missing something?

**Comment by drarmstr** [comment]
Yeah, I wouldn't expect this to work with SSR since the `userData` selector always returns a `Promise` which means that on initial render it will be in the loading state for SSR.
