### ISSUE TITLE
Question: Atoms vs Selector fetching

### ISSUE THREAD

**Issue by minu1994** [facebookexperimental/Recoil#442]
Considering this basic code:
` const [state, setState] = useRecoilState(globalState)
    useEffect(()=> {
        fetch('https://<anything>')
            .then(response => response.json())
            .then(data => {
                setState(data)
            });
    }, [])
if(!state)
 return <div> loading...</div>
return (
  <div>{state.id}</div>
)
`
What are the advantages using selectors? I mean I didnt get why every example of async code in Recoil doc are based on Selector async functions instead of atoms.

Thanks

**Comment by drarmstr** [comment]
Atoms represent local mutable state.  But, besides the default value, they don't currently support setting to an async value and using React Suspense or Error Boundaries for handling pending loading or error states.  So, you can use an Atom to represent a local cached version of an async query, but it will use the default value until set.   You also currently have to manage the singleton component for the effect hook to execute the query, though we are working on an API for that.  Selectors can also reference other Recoil state when computing query parameters or post-processing.  But, selectors should only be used for queries where you get the same result for the same parameters, they should not be used for querying mutable state.  The docs provide examples for those using Atoms and effects hooks.  But, again, we are improving the API for managing that.
