### ISSUE TITLE
Good way to have type inference for functions using useRecoilValueLoadable?

### ISSUE THREAD

**Issue by adrianbw** [facebookexperimental/Recoil#445]
Hi there,

Was working with an engineer this morning on a useEffect that needed to do different things based on a Loadable's state and we had a pattern like this:

```
const {state, content} = loadable;
switch (state) {
  case "hasError": {
    return content.errorMessage;
  }
  case "hasContent": {
    return content.foo;
  }
```

However, Typescript was throwing errors because content in those cases could be an error, a promise, or the actual content. We got around it by writing type guards, but is there something better to be done for type inference here?

**Comment by drarmstr** [comment]
Internally we use Flow which supports disjoint unions, so checking the value of `state` refines the type of `contents`.  @csantos42 do they have something similar with TypeScript?

**Comment by csantos42** [comment]
hey @adrianbw , this is a design limitation of TypeScript at the moment (see https://github.com/microsoft/TypeScript/issues/9998), and will probably not be addressed any time soon.

In the meantime, the conventional way to narrow these types is to access the properties without destructuring like so:

```
const loadable = useRecoilValueLoadable({} as any as RecoilState<string>);

switch (loadable.state) {
  case 'hasError':
    loadable.contents.message; // Error
    break;
  case 'loading':
    loadable.contents.then(() => {}); // Promise
    break;
  case 'hasValue':
    loadable.contents + 'hello'; // string
}
```

Closing this issue, but let me know if you are still having problems
