### ISSUE TITLE
[TypeScript] Type {} does not satisfy the constraint 'SerializableParam'

### ISSUE THREAD

**Issue by apetti1920** [facebookexperimental/Recoil#457]
Not so much of a bug as a work around in case anyone runs into a similar problem.  When typing any `param` parameter (eg atomFamily) the error:

> Type {} does not satisfy the constraint 'SerializableParam'

will appear and can be overcome by unioning the two types together as such:

```typescript
type paramType = SerializableParam & {
  id: number
}
```

**Comment by drarmstr** [comment]
@csantos42 - is this a TypeScript typing issue?

**Comment by apetti1920** [comment]
Oh yes sorry should have prefaced with that

**Comment by drarmstr** [comment]
@csantos42 - Is this somewhat related to [this](https://github.com/facebookexperimental/Recoil/commit/1546774188238a273d27d9c8afc205c3ccc17e7f)?

**Comment by bentron2000** [comment]
Hope this is useful
Related commentary SerializableParam @csantos42
 

If I want to provide a parameter to selectorFamily

```
interface MySelectorParam {
    a: string
    b: string
}
```

For selectorFamily I get an error in the type signature when:

`const theThing = selectorFamily<ReturnType, MySelectorParam>({...`

![Screen Shot 2020-09-14 at 2 27 06 pm](https://user-images.githubusercontent.com/5344375/93043886-7bc11480-f696-11ea-86e1-ce722b975b12.png)


but not when:

`const theThing = selectorFamily<ReturnType, { a: string; b: string }>({...`

![Screen Shot 2020-09-14 at 2 28 48 pm](https://user-images.githubusercontent.com/5344375/93043944-aad78600-f696-11ea-8adb-c5593c59ef95.png)

**Comment by kaynetpc** [comment]
Change from interface to type worked for me

**Comment by KonkretneKosteczki** [comment]
> Change from interface to type worked for me

That's one weird solution, but as long as it works. 🥇
