### ISSUE TITLE
Selector does not have a generic `set` variant

### ISSUE THREAD

**Issue by jbmanning** [facebookexperimental/Recoil#459]
In the following pattern, there is a `selector` which serves as the public interface to an underlying private `atom`. In this situation, it is desirable for the setter to have the ability to accept parameters of a different type than the base value of the selector. 

I would like to propose adding a second type parameter to `selector`, which serves as the type of the accepted parameter to the setter. This would have a default value of `selector<T, TSetter = T>`. This addition of `TSetter` will need to propagate up throughout Recoil to ensure all usages remain properly typed.

I will submit a quick barebones PR to demonstrate the gist of it. If this is a pattern you would like to support I can try to introduce it fully and add to the flow typings as well. Thanks!

*No functionality change, only adding typings. Contrived example.*

```typescript
class UIStore {
  private _appName = "Hello, World!";
  private _title = atom<string | null>({
    key: "UIStore__Title",
    default: null,
  });

  title = selector<string, string | null>({
    key: "UIStore_Title",
    get: ({ get }) => {
      const title = get(this._title);
      if (title === null) return this._appName;
      else return `${title} | ${this._appName}`;
    },
    set: ({ set, get }, newValue) => {
      let title = newValue;
      if (title === "") title = null;
      set(this._title, title);
    },
  });
}
```

**Comment by drarmstr** [comment]
The `set<T>()` in a selector `set` property is not the same type as the selector `T`.  This is already the case for our Flow typing, @csantos42, is there an issue with the TypeScript types?  The PR doesn't seem right since there can be multiple upstream atoms and each as it's own type.   The selector `set<T>()` should be polymetric on its own without referencing any type variable in the selector.

**Comment by jbmanning** [comment]
Hey, thank you for the help! 

I should clarify the request. The `set<T>(...)` function (as a `selector`'s `set` property or as the `SetterOrUpdater` of a `useRecoilState` call) is generically typed against the type of the `RecoilState` it is being called with/against. So, for an `atom<string>(...)`, the setter will accept a string. (When checking this, there does seem to be a separate issue with `set<T>()` within the existing TS version, detailed at the bottom)

The request I am bringing up is to enable the setters to have a generic type for to the parameter they accept. This currently only makes sense for `selector`'s since an `atom` does not currently have a `set` property. For instance, given the UIStore example from original comment, without the secondary types I added. The following code fails typecheck, since the signature of `setTitle` is as follows `setTitle(valOrUpdater: string | ((currVal: string) => string)) => void`. 

```typescript
const Demo = () => {
  const [title, setTitle] = useRecoilState(uiStore.title);

  setTitle(null);
};
```

I would like to see a `RecoilState` have the ability to have a defined type that it gets set with, such as: 
```typescript
set<T, TSetter = T>(newVal: TSetter) => T
``` 

---

Regarding the `set<T>()` within a `selector`'s `set` property. In the TS types, `DefaultValue` is an empty class. `export class DefaultValue {}`. I have not used empty classes like that before in TS so I'm not entirely sure on their behavior. But it seems that it is behaving as a generic object, allowing any values to be passed to the `set<T>()` function, regardless of the type of the RecoilState being used. Example below satisfies type requirements (replacement for the `set` function in the original comment):

```typescript

    set: ({ set, get }, newValue) => {
      let title: string | null | DefaultValue = newValue;
      if (title === "") title = null;
      set(this._title, new UIStore());
    },

```

The `SetterOrUpdater` does not suffer from this since it does not accept `DefaultValue`

**Comment by adrianbw** [comment]
Here's an example of something else that doesn't work, which I think maybe you were saying above:
```javascript
export const exportQueueState = selector<Export[]>({
  key: `${namespace}.exportQueue`,
  get: ({ get }): Export[] => {
    return get(ExportWatcherStore).exportQueue;
  },
  set: ({ set }, newValue) =>
    set(ExportWatcherStore, (oldState) => ({
      ...oldState,
      exportQueue: oldState.exportQueue.push(newValue), // Argument of type 'Export[] | DefaultValue' is not assignable to parameter of type 'Export'.
    })),
});
```

**Comment by drarmstr** [comment]
cc @csantos42 for the `DefaultValue` empty class affecting TypeScript typing

I see now your request for selectors to accept a second type parameter to allow a different type for setting then for getting.  One of the goals of Recoil is that the `RecoilState<>` provides an interface that abstracts if the implementation is an atom or a selector.  So, that would require extending all `RecoilState<>` to have two type parameters which would add more complexity.  Your pattern of using a different type to set a selector can also be achieved with another selector that works with the other type and sets the other selector upstream, or helper functions or recoil callbacks to set the value based on a different type.

@adrianbw - That issue is actually part of the interface for defining a setter for a [`selector`](https://recoiljs.org/docs/api-reference/core/selector).  `DefaultValue` is passed in when a selector is reset, so the setter needs to check if the new value is of type `DefaultValue` in order to properly handle being reset.  Though, I don't know that I would recommend your example of trying to use a `set` action to "push" onto a queue.  The semantics should be more about actually setting the state.  Perhaps consider just making a helper function or recoil callback which provides the "push" functionality on top of setting the state.

**Comment by jbmanning** [comment]
@drarmstr I definitely agree with `RecoilState` being abstract to the idea of atoms vs selectors. I'm not sure about the pattern you suggested of using stacked selectors though... Example at the bottom. Regardless, I think there is an argument to be made; while the idea of introducing an *__optional__* generic does add a small degree of boilerplate to internal code, there would be no breaking changes or complexity for external users. Instead, it would actually eliminate the aforementioned selectors stacked on top of each other to provide a different typed interface. 

This does not break the abstraction from atoms vs selectors, since both already have a setter type. It also introduces no user facing complexity since they would have all of the same interfaces they have today, just with an optional second type parameter (if the type supports a differently typed setter, such as a `selector`). I understand if it's not a pattern you want to support, but I think it's a great way to provide an opaque interface to some underlying value.

---

@adrianbw I agree with drarmstr, but informatively if you wanted to stick to that pattern: `[].push(val)` will not return the array, instead it returns the new length of the array. You could do something like this instead: `[...oldState.exportQueue, newValue]`

---
@drarmstr Example of stacked selectors, I don't know if this is exactly what you meant, but if it is, I feel like this pattern is only going downhill:

```typescript
class UIStore {
  private _appName = "Hello, World!";
  private _title = atom<string | null>({
    key: "UIStore__Title",
    default: null,
  });

  title = selector<string>({
    key: "UIStore_Title",
    get: ({ get }) => {
      const title = get(this._title);
      if (title === null) return this._appName;
      else return `${title} | ${this._appName}`;
    },
    set: ({ set, get }, newValue) => {
      let title = newValue;
      if (title === "") title = null;
      set(this._title, title);
    },
  });

  nullableTitle = selector<string | null>({
    key: "UIStore_Title",
    get: ({ get }) => {
      const title = get(this._title);
      return `DO NOT USE, ONLY AN INTERFACE FOR SETTER: ${title}`;
    },
    set: ({ set, get }, newValue) => {
      let title = newValue;
      if (title === "") title = null;
      set(this._title, title);
    },
  });
}
```

**Comment by sanonz** [comment]
I released a `recoil-types` package as a temporary replacement.

```bash
npm i recoil-types
```

Add the following path to the `tsconfig.json` file.

```json
{
  "compilerOptions": {
    "paths": {
      "recoil": ["node_modules/recoil-types/index"]
    }
  }
}
```

After the official fix, remove the path and uninstall package `recoil-types`.
