### ISSUE TITLE
Review re-frame for other ideas?

### ISSUE THREAD

**Issue by mike-thompson-day8** [facebookexperimental/Recoil#46]
It appears this project has reinvented an idea that has existed for five years in a ClojureScript framework called re-frame.  My guess is that some of the ***other ideas*** in that framework might also be of interest. (Warning: I'm the author, I might be biased). 

To give you some idea, re-frame had functional components (via Reagent) in 2015.  So it has been consistently well ahead of the entire React ecosystem, despite leveraging React.

Remember also that it was the ClojureScript project OM (David Nolen) which introduced the idea of immutable data to the React world, back in the days of Pete Hunt. 

So there's likely interesting stuff to learn over there if your goal is to be experimental and try fresh ideas—no need to reinvent the wheel. Have you ever heard of data-oriented design? 

https://github.com/day8/re-frame/blob/master/README.md

**Comment by lishine** [comment]
Great if Reframe clone will become popular in typescript ecosystem!

**Comment by codepunkt** [comment]
@mike-thompson-day8 maybe you can summarize some of the fresh ideas and how they might apply to recoil here?

**Comment by davidmccabe** [comment]
Hi Mike, I'm a big fan of the clojurescript ecosystem including your work. Thanks for dropping by.
