### ISSUE TITLE
useRecoilValueLoadable during mount

### ISSUE THREAD

**Issue by NethraRaghu** [facebookexperimental/Recoil#461]
I would like to call the async API selector every time the component mounts. but API call happens only on the first mount. when the component rerenders, it directly goes to "hasValue" and there is no API call in the network.  I tried using useEffect as well. 

```
function MainPage() {
  const DataCall = () => {
    const response = useRecoilValueLoadable(<aync API selector>);
    if (response.state === "hasValue" ) {
     <logic>
    }
   else if (response.state === "loading")
      console.log("loading")
    return null;
  };

  return (
    <div>
      <DataCall />
    </div>
  );
```

This is because when MainPage is re-rendered there is no atom update in MainPage. But I want to force call the API on mount.

**Comment by drarmstr** [comment]
selector evaluation functions are "idempotent," such that they should return the same result for a given set of input dependency values.  Thus, they should only be used for queries where you expect the same results for the a given input.  If you are querying mutable data then consider using an atom as a local cache of state and using effects to update the atom.  We don't currently support setting an atom to a pending state for Suspense, but are looking into it.  An alternative approach some people use is having the selector depend on some counter atom which is incremented each time you would like to refresh the query.

**Comment by NethraRaghu** [comment]
@drarmstr Can you provide me an example for querying mutable data using an atom as a local cache of state and useeffect to update the atom?
