### ISSUE TITLE
Merging selector and selectorFamily

### ISSUE THREAD

**Issue by alexandrzavalii** [facebookexperimental/Recoil#47]
selector and selectorFamily has different api's. Its probably a very big ask but I wonder if they can be somewhat the same.

```
const currentUserNameState = selector({
    key: 'CurrentUserName',
    get: ({get, params}) => {
        return tableOfUsers[params.userId].name;
    },
});

function UserInfo({userId}) {
    const userName = useRecoilValue(currentUserNameState(userId));
    return <div>{userName}</div>;
}
```

I think it would be beneficial to abstract the logic into the library.

**Comment by drarmstr** [comment]
A `selectorFamily` and `atomFamily` is basically a helper which provides a function that takes some parameters and returns a selector/atom.  We could force all atoms and selectors to be functions, but then there would still be something that they need to return.  We also don't want to complicate the simple case.  Only add the extra nuance of a function call if you need to scope or parameterize your atom/selector.
