### ISSUE TITLE
Exclude state setter from exhaustive-deps lint's dependencies check

### ISSUE THREAD

**Issue by dvkndn** [facebookexperimental/Recoil#472]
There should be a way to exclude the setter returned by useRecoilState (or the value returned by useRecoilSetState) from the lint's dependencies check since they are known stable values:

```ts
const setValue = useRecoilSetState(...);
// or const [value, setValue] = useRecoilState(...);

React.useEffect(() => {
  setValue(...)
}, []) // should not require setValue
```

It should work like the values returned by React.useState and React.useReducer, which I see currently is defined in the code of the lint:

https://github.com/facebook/react/blob/61dd00db24bec6305bd72908d3617b9f2a5183da/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L296-L307

I'm not sure where to file this issue actually. Should I file an issue in the react-hooks lint repo and propose a way to add exception for dependencies?

**Comment by CharlesStover** [comment]
This should maybe be an issue for react-hooks lint repo to allow a way for library developers to mark hook results as stable or not.

You can see in the file you linked that the examples `useRef`, `useState`, etc. are hard coded into the linter: https://github.com/facebook/react/blob/61dd00db24bec6305bd72908d3617b9f2a5183da/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L369

**Comment by dvkndn** [comment]
yub thank you I created an issue in the lint repo :D

**Comment by drarmstr** [comment]
@dvkndn Actually, I'm not sure that this is valid.  With `useState()` it uses the hook convention of providing a consistent setter for state based on the sequence of hook calls.  While `useRecoilState()` itself must be called in the same order and unconditionally, the user may conditionally change the atom or selector passed to it, which would produce a different setter function.

**Comment by dvkndn** [comment]
thanks @drarmstr  I didn't think of that. So is that an expected use case or should we avoid it?

**Comment by drarmstr** [comment]
> thanks @drarmstr I didn't think of that. So is that an expected use case or should we avoid it?

It's a supported pattern and can be common.  atoms or selectors are often passed in via props or part of some dynamic config.  Or, a different atom may be used from an `atomFamily()` or `selectorFamily()` based on parameter values.

**Comment by dvkndn** [comment]
Thanks! It should not be excluded then.
