### ISSUE TITLE
useMemo breaks Recoils updates

### ISSUE THREAD

**Issue by alago1** [facebookexperimental/Recoil#477]
Example:
https://codesandbox.io/s/wonderful-hellman-yhe3l?file=/src/ListOfPeople.js:647-721

When you open the sandbox link it should work fine at first. Clicking the add button removes the person's name from the list on the top.
However, once you uncomment the 'missing_namesMemo' variable and its respective div (className="useMemo"), each person's button still updates itself when clicked, but the list of names at the top stops updating completely.

I had the same problem using useEffect in one of my projects.

I don't believe that this is an intended consequence but even if it is, I think throwing a warning or error when a Recoil state object is added to a hook's dependency list could really help nail down and avoid this bug as it took me some time to realize that useMemo was causing the issue on my project.

**Comment by drarmstr** [comment]
There shouldn't be a problem with `useMemo()`.  Instead, it looks like you are mutating the set stored in the atom.  When changing the state, please use a new instance of the set and treat them as immutable.  In development mode Recoil will attempt to deep freeze objects used in values in order to catch these errors. 

Here is a fix for your updaters:
```jsx
  const addToList = () => {
    // setNamesInList(namesInList.add(props.name));

    setNamesInList(names => {
      const newNames = new Set(names);
      newNames.add(props.name);
      return newNames;
    });
  };

  const removeFromList = () => {
    // let a = namesInList;
    // a.delete(props.name);
    // setNamesInList(a);

    setNamesInList(names => {
      const newNames = new Set(names);
      newNames.delete(props.name);
      return newNames;
    });
  };
```

**Comment by alago1** [comment]
Ah I see. Works perfectly, thank you for the feedback.
