### ISSUE TITLE
How can i use atoms / selector from non-ui code ?

### ISSUE THREAD

**Issue by davibe** [facebookexperimental/Recoil#484]
If i have a system that evolves the state over time and this system is not the UI/UX/User how do i use atoms and selectors ?

**Comment by drarmstr** [comment]
For proper support of React Concurrent Mode Recoil does not have "global" state, unlike many other state management systems.  With React CM, different parts of the tree may be asynchronously rendered with different versions of the state concurrently.  So, all Recoil state is derived from hooks to obtain the "current" state for that rendering.  That said, you can use those hooks, such as `useRecoilCallback()` to provide callbacks to access or set the state asynchronously.

**Comment by davibe** [comment]
ok I think I get it. Recoil is very react specific. I was thinking of using atoms in a core libray (think for example of a media player library) which knows nothing about the UI, and to expose a state that is already composed of atoms. In that case, the library would need something like atom.get() atom.set() but it is probably not what this is meant for
