### ISSUE TITLE
[TypeScript] RecoilRoot's initializeState setter signature permits any argument

### ISSUE THREAD

**Issue by pelotom** [facebookexperimental/Recoil#487]
For example,

```ts
export const someStringState = atom({
  key: 'someString',
  default: '',
});

const elem = <RecoilRoot initializeState={({ set }) => set(someStringState, 42)}>...</RecoilRoot>
```

This should be a type error because `42` is not a `string`, but it isn't. The setter's type is given by

```ts
type SetRecoilState = <T>(
    recoilVal: RecoilState<T>,
    newVal: T | DefaultValue | ((prevValue: T) => T | DefaultValue),
) => void;
```

where `DefaultValue` is defined as `{}`, which means that any values except `null` or `undefined` are allowed. I'm not sure what the purpose of `DefaultValue` is here, but it's causing type safety to be lost.

**Comment by drarmstr** [comment]
cc @csantos42 - It looks like the TypeScript typings are causing a problem here.  I see `DefaultValue` is defined as `class DefaultValue {}`, not just `{}`, but maybe that's still an issue?
