### ISSUE TITLE
Atom gets updated to a value not specified. 

### ISSUE THREAD

**Issue by HenrikDK2** [facebookexperimental/Recoil#494]
[Website Preview](https://recoilreacttest.netlify.app/)
[Github Repo](https://github.com/HenrikDK2/RecoilReact)

I'm trying to learn Recoil, and i'm having some difficuilties regarding an array of items that i want to update.
I will only show relevant code to keep this post small, for a more detailed view check out my repo, any help will be appreciated. 

I have a list of products, and when you click the button it will execute this function:
**I want to clearify that i don't currently use the Atom anywhere else on the site**

### ProductComponent
```Javascript
import { cartState } from "../../Store";
import { useRecoilState } from "recoil";


const ProductComponent = ({ src, alt, title, price, id }) => {
  const [cart, setCart] = useRecoilState(cartState);

  const addProductToCart = () => {
    console.log(cart);
    const product = {
      title,
      id,
      price,
      src,
    };
    setCart(cart.push(product));
    console.log(cart);
  };

  return (
      <BuyButton onClick={(e) => addProductToCart()}>Køb Nu!</BuyButton>
  );
};
```

The state does update! But right after the update the value is changed to a number, which crashes the site becuase i can't use array methods on a number.  Image of console: [Imgur](https://imgur.com/EL1GnKI)

### Store
```javascript
import { atom } from "recoil";

export const cartState = atom({
  key: "cartState",
  default: [],
});

```

**Comment by victoriafrench** [comment]
the push method of an array returns the length of the array, so the code example you gave would be setting state to that number.

consider changing the code to create a new array with the new item added:

```js
const newCart = [...cart, product];
setCart(newCart);
console.log(newCart);
```

**Comment by HenrikDK2** [comment]
That explains it, i didn't actually know that the push function returned the Array length, i will close this issue then. Thanks you very much.
