### ISSUE TITLE
Get data as loadable inside selector

### ISSUE THREAD

**Issue by dvkndn** [facebookexperimental/Recoil#495]
As far as I know from reading the doc, the "get" function provided inside a selector's get has similar behaviour to getRecoilValue. Is there a way to have a function that works like getRecoilValueLoadable inside a selector?

The use case is that I have an async selector already, but I want to have a simpler, sync version of it. For example, a work-around is this:

```ts
export const useAsyncValueAsSync = () => {
    const value = Recoil.useRecoilValueLoadable(somethingAsync);
    return value.state === "hasValue" ? value.contents : false;
}
```

Thank you

**Comment by drarmstr** [comment]
Yes, you can use [noWait()](https://recoiljs.org/docs/api-reference/utils/noWait)
```jsx
  const value = get(noWait(somethingAsync));
```

**Comment by dvkndn** [comment]
Wonderful! Thank you
