### ISSUE TITLE
Proposed Recoil Logo

### ISSUE THREAD

**Issue by ljcrapo** [facebookexperimental/Recoil#507]
# Recoil deserves a logo!
Here is a _humble_ proposal for a Recoil logo.

![recoil](https://user-images.githubusercontent.com/7049913/88991947-4bb4e200-d29f-11ea-8149-46c3d25f15fa.png)

I can produce an SVG if necessary.

Great work on this. Looking forward to a stable release.

**Comment by drarmstr** [comment]
Nice candidate for issue #10 , thanks!  We're still heads down on some development now, but should be figuring out a selection process for an upcoming significant release.

**Comment by ljcrapo** [comment]
Closed as duplicate
