### ISSUE TITLE
How to initialize root state with typescript

### ISSUE THREAD

**Issue by blatoo** [facebookexperimental/Recoil#510]
Hi,

I am trying to persist the state and initialize it, however, I got a problem with typescript:

```
export const MyApp = () => {

	const initializeState = ({set}) => {
		const persistedTokenState = localStorage.getItem('tokenState')
		if(persistedTokenState){
			set(tokenState, JSON.parse(persistedTokenState))
		}else{
			set(tokenState, null)
		}
	  }

    return (
        ...
  )
}
```

However, I got an error with typescript at the `set`: **Binding element 'set' implicitly has an 'any' type. **

So I tried:

```
export const MyApp = () => {

	const initializeState = ({set: any}) => {
            ...
		
```

But I still got the error, it doesn't work. How can I fix this problem?

Thanks very much for the help!

Conny

**Comment by NoriSte** [comment]
If you take a look at the [`RecoilRootProps` types](https://github.com/facebookexperimental/Recoil/blob/master/typescript/index.d.ts#L33) you can see that the `initializeState`' signature is the following
```ts
initializeState?: (mutableSnapshot: MutableSnapshot) => void;
```

so, replace
```ts
const initializeState = ({set}) => {
```
with 
```ts
const initializeState = ({set}: MutableSnapshot) => {
```
in your code (importing the `MutableSnapshot` type from 'recoil') and TS won't "bore" you with `set` being `any` 😉

**Comment by blatoo** [comment]
@NoriSte Thanks!!! This problem has haunted me yesterday all night! ^_^
