### ISSUE TITLE
useResetRecoilState not working properly

### ISSUE THREAD

**Issue by KristofferTolboll2** [facebookexperimental/Recoil#520]
I have some recoil state, that i want to reset. 

```
import { useRecoilValue, useResetRecoilState, useSetRecoilState } from 'recoil';
...
  //should be used for flushing the global recoil state, whenever a user submits an invoice
  const resetLabelInvoiceState = useResetRecoilState(labelInvoiceState);
  const resetMetaDataState = useResetRecoilState(metadataState);
  const resetGlobalAnnotationsState = useResetRecoilState(globalAnnotationState)
```

I have made function, that i suppoes to reset all the states like this. I have both tried with and without the reset function. 

``` 
const flushRecoilState = () =>{
     console.log('flushed state')
     return(
    resetLabelInvoiceState(),
    resetMetaDataState(),
    resetGlobalAnnotationsState()
     )
   }
```

```
...
        flushRecoilState()
        return history.push('/historyinvoices')
...
```

When i check the state it is not reset. Is it because the `useResetRecoilState´ is not working properly from the library, is not implemented properly, or is there some other problem. 

I could just use the regular `useRecoilState` hook, and just set the state back to the default value. 

Does anybody know why this could be?

**Comment by NoriSte** [comment]
The same question [is on StackOverflow](https://stackoverflow.com/questions/63365150/react-recoil-state-not-being-reset-properly), I continue there 😉

**Comment by manyopensource** [comment]
> Using useResetRecoilState() allows a component to reset the state to its default value **without subscribing the component to re-render** whenever the state changes.

My guess it's because of this statement in the documentation.

**Comment by manyopensource** [comment]
[here](https://codesandbox.io/s/hardcore-bassi-8bzfi?file=/src/App.js) it works though!

**Comment by drarmstr** [comment]
Your JS return statement syntax looks odd; the following is more idiomatic, though I think both should work.  Do you have a reproducer?  We don't have a known issue specifically with `useResetRecoilState()`.
```jsx
  const resetMyState = () => {
    console.log('reset state');
    resetLabelInvoiceState();
    resetMetaDataState();
    resetGlobalAnnotationsState();
  };
```

**Comment by IsaacTrevino** [comment]
Use `useRecoilCallback`:
https://recoiljs.org/docs/guides/asynchronous-data-queries/#use-an-atom
