### ISSUE TITLE
useRecoilValue of a selector only provides first element of the array

### ISSUE THREAD

**Issue by flogball00** [facebookexperimental/Recoil#523]
```export const getRepositories = selector({
       key: "repositories",
       get: async ({ get }) => {
         get(someOtherAtom)
         return ["a", "b", "c"];
  },

//in my component
const [repository] = useRecoilValue(getRepositories);
  console.log("rep", repository);  // rep a
```

am i missing something in the docs?

useRecoilState gets me everything however.

**Comment by manyopensource** [comment]
`get(someOtherAtom)` - what for this line intended for?

**Comment by flogball00** [comment]
> `get(someOtherAtom)` - what for this line intended for?

it was just to pseudo show that it was being triggered.  I found the problem tho, i needed to use the useRecoilValueLoadable

**Comment by drarmstr** [comment]
Possible duplicate of #103

**Comment by l3lock** [comment]
Because you destructure from useRecoilValue

`const [repository] = useRecoilValue(getRepositories);`

change to

`const repository = useRecoilValue(getRepositories);`
