### ISSUE TITLE
State persistence documentation needs updating

### ISSUE THREAD

**Issue by GimpMaster** [facebookexperimental/Recoil#524]
You have a really nice writeup for state persistence, however I think its been deperecated:

https://recoiljs.org/docs/guides/persistence

It is using a function called: useTransactionObservation_UNSTABLE, however this is not listed in the typescript definitions and looking through the development code it has been marked deprecated.

I'm curious if the new approach to state persistence is meant to use:

useRecoilTransactionObserver_UNSTABLE ??

**Comment by manyopensource** [comment]
The API will change, by as of right now you need to use `useRecoilTransactionObserver_UNSTABLE`

**Comment by drarmstr** [comment]
Yes, the plan is for the documentation to be updated when we publish the new API.  The API is currently being validated by preparing a helper package for implementing state persistence with the browser URL.
