### ISSUE TITLE
Performance issues when resetting a modestly sized atomFamily

### ISSUE THREAD

**Issue by kysley** [facebookexperimental/Recoil#526]
I have a atomFamily, `wordState`, that contains 250+ members on average. I keep track of the 'ids' in a separate atom, `wordListState.`

The user needs to be able to reset the members of `wordState` back to default. I implemented this using a `useRecoilCallback` which loops through the `wordListState`, resetting each atom individually. 

Ideally, this would be an 'instant' operation, however it takes anywhere from 100ms-500ms+ to complete. 

Basically, `wordState` contains each letter of a word. Each letter is an object with some meta information which determines how it is rendered. When the user wants to reset, we need `wordListState` to have a new list of words, and each atom in the `wordState` atomFamily to be reset.

[You can find a minimal reproduction here](https://codesandbox.io/s/recoil-atomfamily-perf-93vx7?file=/src/App.js:221-222), with the update time logged to the console.

This might not be the most efficient way to get the job done either, would be open to optimizations as well!

**Comment by manyopensource** [comment]
Why do you need this:
```javascript
for (let i = words.length; i--; i >= 0) {
    reset(wordState(i));
}
```

**Comment by kysley** [comment]
`wordState` can contain duplicate words/entries (intended) so we use the array index.

I found this comment:

**Comment by manyopensource** [comment]
I don't understand what problem do you trying to solve by this approach!

**Comment by kysley** [comment]
Let me try to give some more context!

`wordListState` -> Array of words which are available
`wordState` -> Array of objects for a given word index.

```js
// The word "hey" becomes
[
  {
    id: '0',
    letter: 'h'
  },
  {
    id: '1',
    letter: 'e'
  },
  {
    id: '2',
    letter: 'h'
  },
]
```

When building a typing test app, each letter of a word contains its own state. This is kept in `wordState`. For example `wordState(0)` contains the letters for "recoil". Each letter in "recoil" is an object with some metadata. 

We use the words index in the `wordListState` array because "recoil" may appear multiple times in the list of words to be typed.

**Comment by EricPKerr** [comment]
It looks like it's the `await snapshot.getPromise(wordListState);` that's taking a long time, not the `reset` calls

**Comment by manyopensource** [comment]
@EricPKerr I checked and it's really the reset calls that cause the issue!

**Comment by EricPKerr** [comment]
Apologies - ran it again and you're correct. Not sure what I had checked before.

**Comment by manyopensource** [comment]
I've changed the minimal reproduction to fix the issue:
```javascript
import React from "react";
import "./styles.css";
import "./state";
import { useRecoilCallback, useRecoilValue, useRecoilState } from "recoil";
import { wordListState, wordState, populateWords } from "./state";
import Word from "./Word";

export default function App() {
  const [wordList, setWordList] = useRecoilState(wordListState);
  const resetWordState = useRecoilCallback(
    ({ reset, snapshot, set }) => async () => {
      const before = performance.now();

      for (let i = wordList.length; i--; i >= 0) {
        reset(wordState(i));
      }

      // Typically this would be data from an api call
      setWordList(populateWords());

      const after = performance.now();
      console.log("reset duration -> " + (after - before) + "ms");
    }
  );

  const words = useRecoilValue(wordListState);

  return (
    <div className="App">
      <button onClick={() => resetWordState()}>reset word list</button>
      <div>
        {words.map((word, i) => (
          <Word index={`${word}-${i}`} i={i} />
        ))}
      </div>
    </div>
  );
}
```

**Comment by kysley** [comment]
@manyopensource Wow! very interesting. Thanks for digging into it, really appreciate it. Do you have any idea why it behaves this way?

**Comment by kysley** [comment]
May be worth noting that @EricPKerr was partially correct here. As long as we read the length of `wordListState` from outside of the `useRecoilCallback`, it seems to update in an acceptable time frame (4-6ms).

Here is a slightly modified repro from above:

```jsx
import React from "react";
import "./styles.css";
import "./state";
import { useRecoilCallback, useRecoilValue, useRecoilState } from "recoil";
import { wordListState, wordState, populateWords } from "./state";
import Word from "./Word";

export default function App() {
  const wordList = useRecoilValue(wordListState);
  const resetWordState = useRecoilCallback(
    ({ reset, snapshot, set }) => async () => {
      const before = performance.now();

      // const wordListSnapshot = await snapshot.getPromise(wordListState);

      for (let i = wordList.length; i--; i >= 0) {
        reset(wordState(i));
      }

      // Typically this would be data from an api call
      set(wordListState, populateWords());

      const after = performance.now();
      console.log("reset duration -> " + (after - before) + "ms");
    }
  );

  return (
    <div className="App">
      <button onClick={() => resetWordState()}>reset word list</button>
      <div>
        {wordList.map((word, i) => (
          <Word index={`${word}-${i}`} i={i} />
        ))}
      </div>
    </div>
  );
}
```

If you uncomment the snapshot to get the length of the wordList, then recoil seems to buckle. It seems to have nothing to do with setting `wordListState` inside the useRecoilCallback.

**Comment by manyopensource** [comment]
Yes, he was absolutely right! You didn't need  the line `const words = await snapshot.getPromise(wordListState);`

**Comment by drarmstr** [comment]
This performance should be improved with `0.1.1`, please let us know if you continue to have an issue.
