### ISSUE TITLE
[question] default atom state fires before RecoilRoot rendered?

### ISSUE THREAD

**Issue by david-jones10** [facebookexperimental/Recoil#528]
I noticed an odd issue with my login/user token management, which I think is caused by the default state of an atom being evaluated before the RecoilRoot is even rendered.

Before I render my application, _(I initialise my API tools, then)_ I check for a stored token and if it has expired, delete it. Only after this, the RecoilRoot-wrapped application is rendered:

- **index.tsx:**
```
Api.init().then(() => {
  let token = JwtUtils.get();
  if (token) {
    const decodedToken = JwtUtils.decode(token);
    if (decodedToken['user'] && decodedToken['expiry'] > Date.now()) {
      return Api.authenticatedInit(); // returns a resolved Promise
    } else {
      JwtUtils.delete(); // delete expired token from local storage
      return Promise.resolve();
    }
  }
})
.finally(() => {
  ReactDOM.render(
    <RecoilRoot>
      <Application />
    </RecoilRoot>,
    document.getElementById('root')
  );
});
```

My userState atom (which is referenced within Application) is defined as below. I initialise my userState atom from the stored token, if one exists. 
- **Atoms.tsx**
```
const getDefaultUserState = (): IUser => {
  let token = JwtUtils.get();
  if (!token) return null;
  const decodedToken = JwtUtils.decode(token);
  // if (decodedToken['expiry'] > Date.now()) return null; // this line is the workaround for this problem

  return {
    // IUser object from decodedToken
  };
};

export default class Atoms {
  public static userState = atom<IUser>({
    key: 'userState',
    default: getDefaultUserState(),
  });
}
```

I haven't managed to find anything explicit in documentation, but my understanding was that userState atom would only be initialised when RecoilRoot is rendered (or when it's first referenced). Since the Promise.finally explicitly makes this after I've checked/deleted my token, it is safe in getDefaultUserState to assume that if there is a token, it expired.

However, I've found through debugging with both breakpoints and console.log-ing that the default atom state function getDefaultUserState is actually firing before the token index.tsx logic, and therefore before RecoilRoot is rendered.

What I'd like to understand is, is this intended? Have I misunderstood something?

Thanks!

**Comment by mondaychen** [comment]
`RecoilRoot` does not initialize the atoms -- it's only a wrapper to make sure recoil values can be accessed and updated correctly and components are re-rendered when necessary. No matter you have `RecoilRoot` or not, no matter it's rendered or not, your atom `default` functions will be fired.

**Comment by drarmstr** [comment]
From your code example:
```jsx
export default class Atoms {
  public static userState = atom<IUser>({
    key: 'userState',
    default: getDefaultUserState(),
  });
}
```
It appears that you are calling `getDefaultUserState()` at module load-time when you first define the atom.  So, it is being called before your initialization.  If you want some lazy-default logic you could use a `selector()` as the default and the `get` function of the selector will then evaluate when needed, or you could use an `atomFamily()` and pass a default function as the default without evaluating it, or some other mechanism to ensure lazy evluation.

**Comment by ex3ndr** [comment]
I have been using this same way and unfortunatelly that was huge oversight. I am in no place to suggest, but this is a good place to receive default function that returns promise as alternative to promise itself to init everything lazily.

**Comment by rhartvig** [comment]
@ex3ndr agree.

Sorry for attempting to necro this, but it seems there's room for improvement. @mondaychen , your suggestion makes sense, but imho, conceptually both suggestions are workarounds. If neither derived state nor parameterized atoms are needed, even if seeing their applicability you may still spend time looking for other solutions, as they're described for conceptually different purposes. As I did, eventually ending here.

I would seem the most intuitive solution from a usage perspective would be to support passing a Loadable for `default` containing a function that produces the default value, which would be lazily evaluated. Or does this entail a larger rethinking?
