### ISSUE TITLE
Cleanup when changing key of atomFamily item? 

### ISSUE THREAD

**Issue by justinbelcher** [facebookexperimental/Recoil#530]
I have items stored by id in an atomFamily. Users can rename this id, which I can accommodate by creating a new atom, but is there any necessary cleanup on the previous atom? Since reset just replaces that atom w/ the default value I wasn't sure.

**Comment by drarmstr** [comment]
There is no "necessary" cleanup.  Though, you can use reset to remove the set atom state to explicitly cleanup the memory storing that state.  Ideally this can be automatic in the future when an atom is no longer subscribed to, but is currently explicit.  Additionally, there is still some memory associated with metadata for using that atom which remains.  We're working on some improved memory management, though, that will remove this duplicate metadata consumption when atomFamilies use different input parameters.

**Comment by justinbelcher** [comment]
Makes sense, thanks!
