### ISSUE TITLE
Atom destructors

### ISSUE THREAD

**Issue by alexkirsz** [facebookexperimental/Recoil#533]
Hey,

I'm using RecoilJS to store references to WebAssembly values. These values must be manually freed by calling a `.free()` method on the reference in order to avoid memory leaks[1]. As far as I can tell, there's currently no way to reliably call a destructor on a Recoil value[2].

My current approach is to define a selector wrapper around an atom with a `set` function that frees the previous value of the atom. However, when the Recoil root is unmounted, the `set` function isn't invoked, and thus the values are leaked. Furthermore, I'm noticing race conditions during updates. I reckon it might be due to Recoil yielding control to the event loop between the time a value is set and the time React re-renders components with that value. During that time, it's possible a component effect will try to use the previous recoil value, since freed. This can happen in a `requestAnimationFrame` callback.

It'd be nice to be able to define a destructor callback for atom values that gets called once the RecoilRoot tree has updated with the new value, or once the RecoilRoot that held that value has unmounted.

[1] https://rustwasm.github.io/wasm-bindgen/contributing/design/exporting-rust-struct.html
[2] I'm aware [WeakRef](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) somewhat fixes this issue, but it isn't available in Safari (yet?).

**Comment by drarmstr** [comment]
Freeing the previous state of a selector also isn't a reliable way to free resources because that previous value of the selector is likely cached by the selector and still holds a handle to it.  While selectors cache previous values, atoms only store the current and default values.   Would a solution here be to wrap a function setting the atom value to something that will call free on the previous value?  e.g.

```jsx
  const setMyAtom = useSetRecoilState(myAtom);
  const wrappedSetMyAtom = useCallback(newValue => {
    setMyAtom(previousValue => {
      previousValue.free();
      return newValue;
    });
  }, []);
```

**Comment by alexkirsz** [comment]
@drarmstr This looks like a more reliable version of what I'm doing with the selector today, but it doesn't clean up after the root unmounts(1), and I don't think it fixes the race condition I mentioned in the OP(2).

From what I gather:
1. In order to fix (1), I'd need to add a direct descendant to `<RecoilRoot>` with an effect to free the current value on unmount.
2. For (2), one solution would be to free on animation frames or after a set timeout to ensure that all updates have been propagated through the tree. But this might cause double-free issues with (1).

**Comment by drarmstr** [comment]
Hmm, yeah, freeing previous value on set also could be unsafe with React Concurrent Mode, which may still be rendering part of the tree using the previous value.

We're looking at memory management to free up resources when atoms are no longer used, but this is a slightly different situation where you care about specific atom values no longer being used. (cc @davidmccabe )

**Comment by davidmccabe** [comment]
Thanks for bringing this use case to our attention!

Is the Rust object that you're referencing mutable? If so, any mutations to it will cause bugs.

Instead of storing the object itself, can you store an immutable snapshot of its value that you generate when setting the atom?

**Comment by alexkirsz** [comment]
@davidmccabe It is mutable. The object itself is actually just a reference to a pointer (`{ ptr: number, free: () => void }`), where `ptr` gets set to `0` upon a call to `free` (which mutates the reference).

I've opted to store all the WASM-facing logic away from the React tree altogether, and storing a snapshot of the state as you suggested.

**Comment by alexkirsz** [comment]
It looks like [Atom Effects](https://recoiljs.org/docs/guides/atom-effects/) (experimental) would be a great solution to this problem.
