### ISSUE TITLE
how to force selector recompute

### ISSUE THREAD

**Issue by weird94** [facebookexperimental/Recoil#536]
when using async selector, how can i make selector recompute.

**Comment by ohansemmanuel** [comment]
What do you mean by recompute? @weird94 

If the selector is computed based off of an atom, changing that atom forces a computation. If its dependent on some other state entity in the data-flow graph I.e retrieved via the “get” function, then changing the value returned forces a re-computation. 

Are you specifically referring to invalidating the cache and getting recomputed async fetch?

**Comment by weird94** [comment]
Are you specifically referring to invalidating the cache and getting recomputed async fetch?
-----
Yes.  @ohansemmanuel

**Comment by drarmstr** [comment]
Duplicate of #422
