### ISSUE TITLE
Infinity loop occurs if the value to be set has a circular reference

### ISSUE THREAD

**Issue by Leko** [facebookexperimental/Recoil#54]
Hi there,

I've found infinity loop problem if the value to be set has a circular reference.
Is it bug or limitation of recoil?

Minimum reproduction:
https://codesandbox.io/s/intelligent-matsumoto-vsw7m?file=/src/App.js

## Actual behavior:

```
RangeError: Maximum call stack size exceeded
```

## Expected behavior:

The value can be set without error.

**Comment by drarmstr** [comment]
Yes, looks like that's a current bug of our internal hashing.

**Comment by davidmccabe** [comment]
As a temporary workaround you can add ` dangerouslyAllowMutability: true` to the atom options. This prevents us from deep-freezing the value which is where this is happening.
