### ISSUE TITLE
Best practice for storing result of selector api call in atom?

### ISSUE THREAD

**Issue by Harrisonl** [facebookexperimental/Recoil#542]
Firstly -  loving recoil so far so thanks for the fanstic library

Basically I am trying to figure out the easiest / best practice way of fetching data from an async selector, storing that in an atom and then using that atom via an id selector to pull a single value out when rendering each item from a list, whilst returning the rows from the original query.

A simplified version of the approach I've been taking is below, but not sure how good this is. Feel free to ignore the below example though if it looks confusing - it's just an idea I've been playing with. If theres a much better solution I'm happy to adopt that.

```js
const objectPool = atom({
  key: 'objectPool',
  default: []
})

const fetcher = selectorFamily({
  key: "fetcher",
  get: (filters) => async () => //api call here which returns a resovled promise of the data
})

const idFetcher = selectorFamily({
  key: "id-fecher",
  get: (id: string) => ({get}) => get(objectPool).find(o => i.id === id)
})

const useFetcher = (filters) => {
  const fetchedData = useRecoilValue(fetcher(filters))
  const setObjectPool = useSetRecoilState(objectPool)

  useEffect(() => {
    if(fetchedData) {
      setObjectPool(current => [...current, fetchedData])
    }
  }, [fetchedData, setObjectPool])

  return fetchedData
}

// In various different places in the app
const object = useRecoilValue(idFetcher("1234"))
```

The reason, I can't use the `idFetcher` selector on the `fetcher` selector is because that could be used anywhere in the app, and I want the pool to contain all the rows that were ever received from different queries for this data type. So it might be updated via not just the `fetcher` but also a different query.

Is there a better way of doing this? Current issues with the top approach is that I am running into race condtions where the fetchedData returned beats the data being stored in the `setObjectPool` meaning when the `idFetcher` is called later on, it's null.

**Comment by Harrisonl** [comment]
Also should clarify- the reason why I'm going for this objectPool approach throughout the app and having selectors pull from that instead of passing the full object from the query is because I'm building a realtime app via ws, and updates are automatically pushed into this pool and then instantly reflected in all places throughout the app where `isFetcher` is used

**Comment by drarmstr** [comment]
I'm not quite sure the reason for the indirection of the `objectPool`.  Could you have all places in the app that need the results of `fetcher` just use `idFetcher` directly as defined like this:

```jsx
const idFetcher = selectorFamily({
  key: 'id-fetcher',
  get: ({id, filters}) => ({get}) => get(fetcher(filters)).find(x => x.id === id),
});
```

Note that because this depends on `fetcher(filters)` then components subscribing to all IDs will end up re-rendering when the filters change unless #314 is implemented, however that's the same situation as your example subscribing to `objectPool`.

**Comment by Harrisonl** [comment]
@drarmstr thanks for that - I hadn't actually thought of that to be honest. However that won't solve the problem completely because there are various other queries etc. which feed into that object pool. For example there is that above fetcher, but also a subscription e.g. `socket.on('object:created`, addToPool)` where the server sends push events updating existing objects in that pool which will also need to be reflected. From my understanding won't be captured if I only go through that query? (could be wrong though).

**Comment by Harrisonl** [comment]
>  then components subscribing to all IDs will end up re-rendering when the filters change unless #314 is implemented, however that's the same situation as your example subscribing to objectPool

I guess the only way for me to avoid this would be to in a `useRecoilCallback` dynamically create/set the value of an atom for each of these records that are returned?

**Comment by drarmstr** [comment]
Yes, you could use the setter from `useRecoilState()` or `useRecoilCallback()` to update an atom's state as a callback from some remote push.  We're working on a synchronization API to help with that pattern, though it hasn't been published yet.  Also, please note feature request #237 to set an atom to a `Promise` to allow it to reflect a pending or error state from an async request.

**Comment by drarmstr** [comment]
Updated documentation for [syncing Recoil state with external storage](https://recoiljs.org/docs/guides/atom-effects#state-synchronization-example) in #680
