### ISSUE TITLE
Example of initial state or bulk insert for atomFamily

### ISSUE THREAD

**Issue by shezzor** [facebookexperimental/Recoil#544]
Hi. I've just started working with recoil and enjoying it so far. I'm currently familiarising myself with the `atomFamily` and `selectorFamily` helpers. However, from the examples and documentation that I've seen, they all tend to start with no initial state and/or insert entries one by one using an id (as per Jacques example [here](https://github.com/jacques-blom/recoil-design-tool/blob/03-data-fetching/src/LeftSidebar/useInsertElement.tsx)).

If I'd like to bulk insert state into an `atomFamily` say from an API after it was initialised. What would be the best practice for this? 

Apologies if this is not the correct place to submit this question but any help would be appreciated.

**Comment by drarmstr** [comment]
For bulk initialization of state you could consider the `initializeState` prop in [`<RecoilRoot>`](https://recoiljs.org/docs/api-reference/core/Snapshot#state-initialization), which provides a `MutableSnapshot` with a `set()` method to initialize state.  This initialized state will be used for the initial React render.
