### ISSUE TITLE
Trying to understand how to make a list of atoms

### ISSUE THREAD

**Issue by ben-tensil** [facebookexperimental/Recoil#551]
Hi, I refactored the Todo example so that the Todos are in an atomFamily
````
import {atom, atomFamily, useRecoilState, useRecoilCallback} from 'recoil';
import {v4 as uuidv4} from 'uuid';

class TodoItem {
  id : string = "";
  text : string = "";
  isComplete : boolean = false;
}

export const todoIndicesState = atom<string[]>({
  key: uuidv4(),
  default: []
})

type TodoItemOpt = TodoItem | null;

export const todoItemState = atomFamily<TodoItemOpt, string>({
  key: uuidv4(),
  default: () => null
});

export const useInsertItem = () => {
  const [indices, setIndices] = useRecoilState(todoIndicesState);

  return useRecoilCallback(
    ({set}) => {
      return (text: string) => {
        const newId = uuidv4();

        setIndices((indices) => [...indices, newId])

        set(todoItemState(newId), {
          id: newId,
          text,
          isComplete: false
        })
      }
    },
    [indices],
  )
}
````
But now I'm trying to understand how to bind todoIndicesState and todoTimeState together into a single class which is templated.
I think that it would be similar to a MobX observable array but not sure. https://mobx.js.org/refguide/array.html
Any guidence would be appricated. Thanks!
Ben

**Comment by drarmstr** [comment]
Can you clarify what you are trying to do by "bind into a single class which is templated"?

**Comment by ben-tensil** [comment]
@drarmstr This is the same question as #297 but that wasn't answered fully.
I suspect that there's a way to make a selectorFamily that is composed of the todoIndicesState and todoItemState which which acts like a Map<number, TodoItem> but I am not seeing how to do it yet. I'm hoping to get a pointer on how to do this. Thanks!

**Comment by drarmstr** [comment]
@ben-tensil - You can manage the state with one atom that contains the list of current IDs, and then an atom family which contains the state for each id:

```jsx
const todoListState: RecoilState<$ReadOnlyArray<number>> = atom({
  key: 'TODO/list',
  default: [],
});

const todoTextState: number => RecoilState<string> = atomFamily({
  key: 'TODO/text
  default: '',
});

const todoCompletedState: number => RecoilState<boolean> = atomFamily({
  key: 'TODO/completed',
  default: false,
});
```

**Comment by drarmstr** [comment]
Duplicate of #263
