### ISSUE TITLE
[question] Is it possible to update multiple components states using a loop?

### ISSUE THREAD

**Issue by KestutisMa** [facebookexperimental/Recoil#558]
Hello,
I want to update states of many components (e.g. text fields) and I want to do that from another component: e.g. when button is pressed in another component. I have array of Atoms.
 Is that possible? I know that it is not allowed to useRecoilState() in a loops.
Another question is it possible to do that outside React component? Maybe using "useEffect" hook?

**Comment by KestutisMa** [comment]
Solved using useEffect(), I don't know if it's best solution, but it works

**Comment by drarmstr** [comment]
@KestutisMa  - You can use multiple `useRecoilState()` or `useSetRecoilState()` hooks in a component to get setter callbacks for your multiple atoms.  Then, within the button click handler you can loop over and use those setter callbacks.  According to React rules you cannot loop over hooks like `useSetRecoilState()`.  If you have many atoms in an array that you would like to loop over, you can use `useRecoilCallback()`:

```jsx
function MyComponent() {
  const setManyStates = useRecoilCallback(({set}) => () => {
    for (const myAtom of myArrayOfAtoms) {
      set(myAtom, ...newValue...);
    }
  };

  return <button onClick={setManyStates} >Click me</button>;
}
```
