### ISSUE TITLE
Cannot assign to read only property of object '#' when setRecoilState twice

### ISSUE THREAD

**Issue by gnllucena** [facebookexperimental/Recoil#560]
I have two components, the first one is a filter abstraction:

```
export const ToolbarFilterItemSlider: FunctionComponent<ToolbarFilterItemSliderProps> = ({
  filter,
  onChange
}) => {
  const initial = Number.MIN_VALUE;
  const [value, setValue] = useState<number | [number, number]>(initial);
  const debounce = useDebounce<number | [number, number]>(value, 500);

  useEffect(() => {
    if (debounce === initial) {
      return;
    }
    
    filter.Value = debounce;

    onChange(filter);
  }, [debounce])

  return (
    <Slider 
      key={filter.Name}
      name={filter.Name}
      label={filter.Label}
      maxValue={filter.MaxValue}
      minValue={filter.MinValue}
      range={filter.Range}
      value={filter.Value}
      disabled={filter.Disabled}
      onChange={setValue}
    />
  );
};
```

And the second listens to filter.value changes, and everytime a change occurs, it updates FilterStockState:
```
export const StocksFilter: FunctionComponent<StocksFilterProps> = () => {
  const [filterStockState, setFilterStockState] = useRecoilState(FilterStockState);
  const resetFilterStockState = useResetRecoilState(FilterStockState);
  
  return (
    <ToolbarFilter 
      groups={filterStockState}
      onChange={setFilterStockState}
      onReset={resetFilterStockState}
    />
  );
};
```
the problem is: the first time `filter.Value = debounce;` occurs, everything goes fine and the state is changed, the second time onward it breaks, and the error is:

`Uncaught TypeError: Cannot assign to read only property 'Value' of object '#<FilterSlider>'`

```
react_devtools_backend.js:2273 ErrorBoundary caught an error TypeError: Cannot assign to read only property 'Value' of object '#<FilterSlider>'
    at ToolbarFilterItemSlider.tsx:24
    at commitHookEffectListMount (react-dom.development.js:19731)
    at commitPassiveHookEffects (react-dom.development.js:19769)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at flushPassiveEffectsImpl (react-dom.development.js:22853)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushPassiveEffects (react-dom.development.js:22820) {componentStack: "↵    in LocationProvider (created by Context.Consu… in Layout↵    in ErrorBoundary↵    in RecoilRoot"}componentStack: "↵    in LocationProvider (created by Context.Consumer)↵    in Location (created by Context.Consumer)↵    in Router↵    in Suspense↵    in section (created by Context.Consumer)↵    in BasicLayout (created by Context.Consumer)↵    in Layout↵    in ErrorBoundary↵    in RecoilRoot"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__() 
    at ErrorBoundary (http://localhost:9000/main.bundle.js:189660:47)
    at RecoilRoot (http://localhost:9000/main.bundle.js:170586:3)
```

Am I doing something wrong?

Appreciate your help, guys!

**Comment by drarmstr** [comment]
What is the type of value stored in `filterstockState`?  It looks like it might be trying to mutate some property in an object that's used as a value for this atom.  Atom values are frozen in development mode to detect problems and ensure all state mutations properly go through Recoil.  Do you need to store a mutable object as the atom state or can you store a read-only object or primitive values?  If the mutations are just due to debouncing or something and don't actually reflect state changes, then you can also consider the `dangerouslyAllowMutability` option to disable freezing the object.

**Comment by gnllucena** [comment]
@drarmstr, the ideia behind `FilterStocksState` was to have an array of filters that were changeable throught UI components (like sliders, checkboxes or inputs), everytime a user changes some values, the state would be changed and a selector would be triggered, something like this:

```
const FilteredStocksSelector = selector<Array<Stock>>({
  key: 'FilteredStocksSelector',
  get: async ({ get }) => {
    const filters = get(FilterStocksState);

    let query = '';

    filters.forEach((group: FilterGroup) => {
      group.Filters.forEach((filter: Filter) => {
        if (filter instanceof FilterCheckbox) {
          let parsed = filter as FilterCheckbox;

          query += `${parsed.Name}=${parsed.Value}&`; 
        }        
      });
    })

    const response = await axios.get<Array<Stock>>(`${process.env.URL_API_STOCK}stocks?${query}`);

    return response.data;
  }
});

export default FilteredStocksSelector;
```


Your ideia to use `dangerouslyAllowMutability` worked out, and the error `Uncaught TypeError: Cannot assign to read only property 'Value' of object '#<FilterSlider>'` was no more. 

But I found out that my selector was not triggered everytime a change occured on `FilterStocksState`.

Does `dangerouslyAllowMutability` changes the `selector` behavior?

**Comment by gnllucena** [comment]
Nevermind, just had to change my ToolbarFilter component to this:

```
<ToolbarFilter
    groups={filterStockState}
    onChange={(groups) => { 
        let newGroups = [...groups];

        setFilterStockState(newGroups);
    }}
    onReset={resetFilterStockState}
/>
```

Thanks for your help!

**Comment by drarmstr** [comment]
> Your ideia to use dangerouslyAllowMutability worked out, and the error Uncaught TypeError: Cannot assign to read only property 'Value' of object '#<FilterSlider>' was no more.
> But I found out that my selector was not triggered everytime a change occured on FilterStocksState.

Right, that's exactly why it is dangerous.  If objects used as values are mutated directly those changes are not detected and do not cause subscribers to the atoms/selectors to update.

**Comment by xiyangjun** [comment]
> 



> What is the type of value stored in `filterstockState`? It looks like it might be trying to mutate some property in an object that's used as a value for this atom. Atom values are frozen in development mode to detect problems and ensure all state mutations properly go through Recoil. Do you need to store a mutable object as the atom state or can you store a read-only object or primitive values? If the mutations are just due to debouncing or something and don't actually reflect state changes, then you can also consider the `dangerouslyAllowMutability` option to disable freezing the object.

I think the set callback should be unfreeze preValue by default, just like immer, so it's very easy to use。
e.g
```
set(xxxAtom, preValue => preValue.xx = 'xx')
```

**Comment by xiyangjun** [comment]
> > > 
> > 
> > 
> > > What is the type of value stored in `filterstockState`? It looks like it might be trying to mutate some property in an object that's used as a value for this atom. Atom values are frozen in development mode to detect problems and ensure all state mutations properly go through Recoil. Do you need to store a mutable object as the atom state or can you store a read-only object or primitive values? If the mutations are just due to debouncing or something and don't actually reflect state changes, then you can also consider the `dangerouslyAllowMutability` option to disable freezing the object.
> > 
> > 
> > I think the set callback should be unfreeze preValue by default, just like immer, so it's very easy to use。 e.g
> > ```
> > set(xxxAtom, preValue => preValue.xx = 'xx')
> > ```
> 
> That line of code is dangerous, state really should be immutable. That line would mutate the previous state in places that retained the previous state or in snapshots to the previous state. It also doesn't appear to be valid as it would change the atom to be just the string `'xx'` instead of the object containing the `xx` property.
> 
> It's easy to properly patch atom values:
> 
> ```js
> set(xxxAtom, prevValue => ({...prevValue, xx: 'xx'}));
> ```

In the following example, I have to deep clone node to make it work correctly.I mean expect 'set' to learn from immer.js's produce scheme to modify objects

```
interface Node {
     name?: string;
     config?: {
          type: string; 
     }
}
const nodeAtom = atom<Node>({
      key: 'nodeAtom',
     default: {}
});
const nodeConfigSelector = selector({
    key: 'nodeConfigSelector',
    get: ({ get }) => get(nodeAtom).config,
    set: ({ set }, config) => {
        set(nodeAtom, preValue => {
            // const node = { ...preValue }; 
            const node = _.cloneDeep(preValue);
            Object.assign(node.config, config);
            return node;
        });
    },
});
```
