### ISSUE TITLE
Can recoil selector return a "Storage" class?

### ISSUE THREAD

**Issue by blatoo** [facebookexperimental/Recoil#563]
I want to implement "remember me" function when the user login. 

if the user check "remember me", then I use the `localStorage`, else, I will use `sessionStorage`, so I did following step
1. make a `rememberMeState` atom

```
    export const rememberMeState = atom<boolean>({
         key: "rememberMeState",
         default: true,
    })
```

2. make a `selector`, which based on `remeberMeState`, and return the corresponding storage:
```
    export let storageType = selector<Storage>({
          key: "storageType",
          get: ({ get }) => {
               let rememberMe = get(rememberMeState)
               if (rememberMe) {
                      return localStorage
                  } else {
                      return sessionStorage
           }
       },
    })
```

However, during the usage of the selector, I got a big error
My code:
```
export const Experiment = () => {
    ...

      const myStorage = useRecoilValue(storageType)

    ..
}
```

After running: I got an error, I have no idea, why this happens. Does anyone know what's wrong with my code?

![2020-09-08_17-50-24](https://user-images.githubusercontent.com/3341687/92500056-e8529400-f1fc-11ea-944e-3622bd23966b.png)

**Comment by drarmstr** [comment]
Objects used as values in Recoil are frozen in development mode to help catch issues.  You could use the `dangerouslyAllowMutability` option.  But, also no need to use a selector for the storage.  You could just use a function or hook based on the atom value:

```jsx
const useStorage = () =>
  useRecoilValue(rememberMeState) ? localStorage : sessionStorage;
```

**Comment by blatoo** [comment]
Hi @drarmstr , this is a great answer! Help me so much! Thanks!
