### ISSUE TITLE
0.0.11 released, but not really?

### ISSUE THREAD

**Issue by wojtekmaj** [facebookexperimental/Recoil#564]
In [changelog](https://github.com/facebookexperimental/Recoil/blob/master/CHANGELOG.md), we can read:

> ## 0.0.11 (2020-09-02)

Suggesting that a new version has been released a few days ago, but this version is nowhere to be found on npm registry. 🤔

**Comment by MarekMaras** [comment]
same here. yarn upgrade and npm install are jsut up to 0.0.10

**Comment by drarmstr** [comment]
We’re working on that release now, it hasn’t been released yet.  The date will be updated.
