### ISSUE TITLE
Recoil easy to resue the computed result, but need to improve reuse logic.

### ISSUE THREAD

**Issue by X-neuron** [facebookexperimental/Recoil#566]
React Hook helps us improve the reusability of code. If we use hook, it is very easy to reuse the logic of the following toggle,using hox for example:

```
import { createModel } from 'hox';
import { useBoolean } from 'ahooks'

function useToggle(defValue) {
  const { state, toggle, setTrue, setFalse } = useBoolean(defValue ?? true);
  const set = (bool) => (bool ? setTrue : setFalse)
  return { state, toggle, set }
}

export const useSiderMenuToggleModel = createModel(useToggle,false);
export const useFormMenuToggleModel = createModel(useToggle,true);
```

But in recoil, because the two scenarios are separate, different component use different data, two atoms、two selectors are needed,but the logic is the same, it very hard to resue the logic,

Does it have any way to improve this?

**Comment by X-neuron** [comment]
https://codesandbox.io/s/stupefied-euler-jgq93?file=/src/CountBtn.js

**Comment by ilyichvismara** [comment]
Did you find a solution for that? By watching your code it seems that you are not able to use the same atom for different purposes.

I'm currently in the same situation, what I would like to do is reuse one atom around my app
