### ISSUE TITLE
TypeScript type for waitForAll() has extra Loadable

### ISSUE THREAD

**Issue by wmain** [facebookexperimental/Recoil#568]
Reproduction: https://codesandbox.io/s/hungry-swartz-liefn?file=/src/App.tsx (note the compiler errors within `Inner`)

~~Following the patterns expressed in the [async query guide](https://recoiljs.org/docs/guides/asynchronous-data-queries#asynchronous-example) leads to broken types in practice. Typescript seems (rightly?) incapable of understanding that `Inner` is wrapped in Suspense, meaning that the loadables will have resolved and be available/unwrapped within `Inner`. What's the fix and/or best practice for resolving this?~~

Edit: This might actually just be a type issue with `waitForAll.` Loadables alone without the async helper seem to be fine.

**Comment by drarmstr** [comment]
Yup, looks like the Typescript types for `waitForAll()` is off.   Should be an easy fix.

**Comment by drarmstr** [comment]
Fixed with 0.0.11 [commit](https://github.com/facebookexperimental/Recoil/commit/bf5698bd580b3fb3d34dcba2d9e0fa6f8580209d)
