### ISSUE TITLE
#request to reset an atom to before having a default value

### ISSUE THREAD

**Issue by reedom** [facebookexperimental/Recoil#572]
Currently, both of `useResetRecoilState` and `useRecoilCallback`'s `reset`  works as 
> reset the value of the given state to its default value.

But there are cases that prefer to re-read the default value.

```typescript
const state = atom({
  key: 'state',
  default: fetchFromRemote()
});
```

```typescript
const submit = useRecoilCallback(({ reset }) => async (data: Data) => {
  await postToServer(data); // And the server additionally updates updatedTime or something.
  reset(state);             // I wanted that a reload would happen, but…
})
```

In recoil 0.0.10, it seems that once a default value is set, it will never get re-read, possibly until unloading the RecoilRoot.

**Comment by drarmstr** [comment]
#237 would allow explicitly setting an atom to a new promise to allow it to "re-read" a remote value.

**Comment by rexthefex** [comment]
Managed to work around this by having another atom as a dependency for the default getter.
The given atom holds something unique to distinguish different use cases - for example an auth token for different users.

```ts
const state = atom({
  key: 'state',
  default: selector({
    key: 'state/default',
    get: async ({ get }) => {
      get(authAtom);
      ...rest of the logic here...
    },
  }),
});
```

This way whenever `authAtom` changes - any atoms are rerun when accessed again.
