### ISSUE TITLE
0.0.11 Typescript: DefaultValue is making selectors that set atom objects invalid

### ISSUE THREAD

**Issue by adrianbw** [facebookexperimental/Recoil#580]
The change to default value has affected selectors that we use with objects. Here's a simple example:
```typescript
import { atom, selector } from "recoil";

type AtomObject = {
  foo: string,
  quu: string[],
}

const myAtom = atom<AtomObject>({
  key: "atom",
  default: {
    foo: "bar",
    quu: [],
  },
});

const mySelector = selector<string[]>({
  key: "selector",
  get: ({ get }) => get(myAtom).quu,
  set: ({ set }, newValue) => set(myAtom, (oldState) => ({
    ...oldState,
    quu: newValue
  })),
});
```
This gets the following error on the selector:
```
Argument of type '(oldState: AtomObject) => { quu: string[] | DefaultValue; foo: string; }' is not assignable to parameter of type 'AtomObject | DefaultValue | ((prevValue: AtomObject) => AtomObject | DefaultValue)'.
  Type '(oldState: AtomObject) => { quu: string[] | DefaultValue; foo: string; }' is not assignable to type '(prevValue: AtomObject) => AtomObject | DefaultValue'.
    Type '{ quu: string[] | DefaultValue; foo: string; }' is not assignable to type 'AtomObject | DefaultValue'.
      Type '{ quu: string[] | DefaultValue; foo: string; }' is not assignable to type 'AtomObject'.
        Types of property 'quu' are incompatible.
          Type 'string[] | DefaultValue' is not assignable to type 'string[]'.
            Type 'DefaultValue' is missing the following properties from type 'string[]': length, pop, push, concat, and 26 more.ts(2345)
```
This is because `newValue` is getting inferred as `string[] | DefaultValue`. I can fix it by adding `as string[]` after `quu: newValue`, but that doesn't seem like the right thing, long-term. 

An important note is that I only see this with atoms that are objects; primitives are fine.

**Comment by drarmstr** [comment]
@adrianbw  - This is because the type of `newValue` actually is `Array<string> | DefaultValue`.  Writeable selectors should check if the incoming value is an instance of `DefaultValue` in order to handle the case if the selector was reset, such as from `useResetRecoilState()`.  Please see [this example](https://recoiljs.org/docs/api-reference/core/selector/#writeable-selectors)
