### ISSUE TITLE
What is `getStorage` in #380?

### ISSUE THREAD

**Issue by SirJosh3917** [facebookexperimental/Recoil#582]
The example in PR #380 seems to use a function called `getStorage`, but I can't find it defined anywhere, or find any information about this. How do I adapt the example in PR #380 to subscribe to when the atom's state changes?

**Comment by drarmstr** [comment]
That's just an example usage of some arbitrary storage mechanism.  You would replace that with the API of whatever storage or query API you actually want to use.  You subscribe to atom state changes with the `onSet()` callback provided in the parameter to the effect function.
