### ISSUE TITLE
How much is Recoil potentially suffering from company agenda?

### ISSUE THREAD

**Issue by lukasbuenger** [facebookexperimental/Recoil#583]
Let's be frank here: MIT is a software license and not a governance model. So my question (that's the label I'd suggest anyway) is:

If your approach of managing state somehow proofs to be main stack-worthy, can we expect the same level of obscurity in terms of roadmaps like we had with React and concurrent mode/suspense? As in 5 years (hyperbolism of course) of trying to cope with internals/tech debt/Getting It Right™?

(And I know already that Recoil is ready for suspense, that is not the question)

EDIT: I'm actually not trying to stir agenda wars but merely requesting an honest feedback in terms of what can and will happen to the library if it takes off (and if it doesn't). Negative tone, because ... you know why. Had difficulties in finding a neutral name for the issue, that's why I changed its name a couple of times. Sorry for that one.

**Comment by davidmccabe** [comment]
Hi Lukas. Thank you for your question and post. We definitely do want to make the developer experience for Recoil as open and transparent as possible. Needless to say, sharing a roadmap is an excellent idea, and something that some of Facebook’s projects [have done](https://reactnative.dev/blog/2018/11/01/oss-roadmap). We understand how such a roadmap could help the community build confidence in the project. We will chat internally to see if we can and how it is best to share a roadmap, maybe through a blog post, the GitHub Projects mechanism or some other way.

**Comment by lukasbuenger** [comment]
Hi David,

many thanks for your reply (and sorry for this one being a little late). A roadmap would certainly help. This answers my question, so I'll close this issue. I'm looking forward to the things to come and in the meantime wish you guys all the best.

Regards, Lukas
