### ISSUE TITLE
[Question] use selector in atom's default

### ISSUE THREAD

**Issue by xuzhanhh** [facebookexperimental/Recoil#593]
Hi! I saw an usage of atom's default in atomFamily's doc:
```
const myAtomFamily = atomFamily({
  key: ‘MyAtom’,
  default: selectorFamily({
    key: 'MyAtom/Default',
    get: param => ({get}) => {
      return computeDefaultUsingParam(param);
    },
  }),
});
```
I want to figure it out what it means, so I tried it on sandbox https://codesandbox.io/s/laughing-butterfly-qgef0?file=/src/App.js.

When I change `baseState`, `childState` will update。It seems there's a relation between `baseState` and `childState`

but when I directly change `childState`, The relation seems broken, which means there no relation between `baseState` and `childState` (change `baseState` will not update `childState` anymore)

Is that a feature? I want to  find more document about it.

**Comment by mondaychen** [comment]
This is expected, because only the default value of `childState` is derived from `baseState`. Once you give it a new value, `childState` no longer holds its default value.
