### ISSUE TITLE
rinput lagging while you are typing 

### ISSUE THREAD

**Issue by mayankoscod** [facebookexperimental/Recoil#595]
i have more than 100 field on my form i was trying to get old value from database , and again want to change that value using useRecoilStateLoadable and its taking time to get value of changes

**Comment by mondaychen** [comment]
We are working on improving Recoil's performance when dealing with large amount of atoms.

I can reopen if you can provide some demo code for the issue you are reporting. With what you've provided, it's hard to understand what exactly happened. Thanks.
