### ISSUE TITLE
Manage state with "multi-card" support

### ISSUE THREAD

**Issue by Codeia** [facebookexperimental/Recoil#598]
Hi everyone, my second post here.
I'm building a simple application that creates offers.
Each offer object is as the following:
![Untitled-2020-08-27-1632 (1)](https://user-images.githubusercontent.com/7532901/93803188-257f4300-fc4d-11ea-8ce3-22ffae6eb399.png)

As you can see, there are 2 arrays in here - **rooms** and **products**

When entering an offer, you can select a room, and then select products to add to this room.
In a way, this functions like a multi cart (a cart for each room).

I tried to build it with one atom state, but I don't think it would be the recommended way. 
Also, I had a lot of difficulties to reach what I want.
Look here: https://codesandbox.io/s/nifty-sun-b8wt3?file=/src/store/hooks.js
When you add a product once it works, but then it doesn't add any more products. **Is this a bug with recoil? or a side effect of my approach?**

**My biggest questions are:**
1. What would be the "recoil" approach for the given object structure and use flow above?
2. Why can't you add more than one product in the sandbox I sent?

Thanks everyone!

**Comment by drarmstr** [comment]
Glancing at your sandbox, it looks like some intricate cloning logic.  Even if you get it working, seems like it would be difficult to maintain.  Also, by storing all of this state in a single atom, you would get components re-rendering when an unrelated part of the state changes.  Have you considered a more relational database style for your state?  You could have separate tables for offers, rooms, and products.  The Rooms array in the Offer could be an array of Room IDs which then refer to the separate table of Room state.  Using [`atomFamily()`](https://recoiljs.org/docs/api-reference/utils/atomFamily) to store the tables would then also provide the benefit of only updating components that subscribe to the particular offer/room/product that changes.
