### ISSUE TITLE
How to achieve the same effect as react's "setstate" callback functions?

### ISSUE THREAD

**Issue by A-Siam** [facebookexperimental/Recoil#599]
Hey everyone, I'm very new to recoil it is so neat but I was just wondering how to add callbacks whenever the state is changed or I am missing some concept here

**Comment by BenjaBobs** [comment]
You probably already stumbled upon it, but take a look again at the example usage of atom: https://recoiljs.org/docs/api-reference/core/atom
```typescript
import {atom, useRecoilState} from 'recoil';

const counter = atom({
  key: 'myCounter',
  default: 0,
});

function Counter() {
  const [count, setCount] = useRecoilState(counter);
  const incrementByOne = () => setCount(count + 1);

  return (
    <div>
      Count: {count}
      <br />
      <button onClick={incrementByOne}>Increment</button>
    </div>
  );
}
```
The `setCount` does what you're looking for I believe. :)

**Comment by A-Siam** [comment]
@BenjaBobs thanks for your replay but I think I didn't express myself clear enough. I want to use the state after it was updated without updating the view, after i made searched it for a while i found that callback still needs updating the view so i think my question is completly wrong :confused:. For now, I'm doing a simple hack i assign the new value to another object and use that new object this didn't achieve the same effect exactly but i could use the new value 
```javascript
const newValue = {...value, ...newAttributes}
setValue(newValue)
callback(newValue)
```
is there anyway to get the new state without updating the view?
thanks in advance

**Comment by BenjaBobs** [comment]
I don't think you can update the value of an `atom` without notifying the places that subscribe to it via `useRecoilValue` or `useRecoilState`. If you get those values by using `useRecoilCallback` and store those values locally with `useState` (from React), you can get the values without subscribing to updates, and then you can update the value of the `atom`.

But I must say I can't imagine a use case where that would be the best solution.

**Comment by A-Siam** [comment]
I didn't mean updating values but getting the updated values so I think `useRecoilCallback` is what I'm looking for, thanks @BenjaBobs.
