### ISSUE TITLE
Lazily read contents of an atom

### ISSUE THREAD

**Issue by bitttttten** [facebookexperimental/Recoil#602]
Are there any discussions or ideas about lazily getting state inside a React component?

Consider the following component where it doesn't need access to the `allDataSelectors` state ahead of time, only when the user clicks on the button. This selector is also very greedy so it updates very often. This is perhaps contrived, but here the component will rerender very often, and there is a small optimisation to be made if we can lazily read the contents of the atom. 

```js
const Download = () => {
	// this data changes all the time
	const myData = useRecoilValue(allDataSelector)

	const onDownload = () => {
		const parsed = doSomethingExpensiveWith(myData)
		download(parsed)
	}

	return (
		<Button onClick={onDownload}>
			Download your data
		</Button>
	)
}
```

There have been some discussions about getting state outside of the React tree and outside of a React component, and I hope this question/discussion doesn't fall in there but I can see how with an API like that I could access the state inside the `onDownload` function.

Just thought I'd bring the discussion to the table!

**Comment by drarmstr** [comment]
Yes, absolutely.  One way to lazily get data is via [`useRecoilCallback()`](https://recoiljs.org/docs/api-reference/core/useRecoilCallback).  For example:

```jsx
const Download = () => {
  const onDownload = useRecoilCallback(({snapshot}) => async () => {
    const myData = await snapshot.getPromise(allDataSelector);
    const parsed = doSomethingExpensiveWith(myData);
    download(parsed);
  });

  return (
    <Button onClick={onDownload}>
      Download your data
    </Button>
  );
};
```

**Comment by bitttttten** [comment]
Oh that is nice, thanks so much! I didn't put two and two together when reading the docs, even though the doc page explains it extremely well. I should re-read the docs again before asking more questions ;) Thanks! ✨
