### ISSUE TITLE
Flashing components

### ISSUE THREAD

**Issue by secretlifeof** [facebookexperimental/Recoil#604]
Thanks a lot for this library. It's really fun to work with.

I am opening this issue because after upgrading to version 0.0.12 my components startet "flashing". They flash after state update using useRecoilState. This is also present in v. 0.0.13, but not in v. 0.0.10.

**Comment by javascrewpt** [comment]
Same here. Version 0.0.10 works fine as well.
Though it does happen only when I use `selectorFamily`.

Here's my source:
`export const currentCoordsState = selectorFamily({
	key: 'currentCoordsState',
	get: (hasGeolocation) => async ({ get }) => {
		const baseUrl = get(baseUrlState);
		const location = get(coordsState);
		const emptyResponse = {
			latitude: null,
			longitude: null,
			userAllowed: false,
			locationConfirmed: false,
		};
		if (hasGeolocation) {
			try {
				if (!location.longitude || !location.latitude) {
					const position = await getCurrentPosition({
						enableHighAccuracy: true,
					});
					if (position.hasOwnProperty('code') && position.code === 1) {
						throw new Error();
					} else {
						const {
							coords: { longitude, latitude },
						} = position;
						return {
							longitude,
							latitude,
							userAllowed: true,
							locationConfirmed: true,
						};
					}
				}
				return location;
			} catch (e) {
				try {
					if (baseUrl) {
						const { data } = await GetLonLatFromAppName(baseUrl);

						return {
							latitude: data.lat,
							longitude: data.lon,
							userAllowed: false,
							locationConfirmed: false,
						};
					}
				} catch (error) {}
				return emptyResponse;
			}
		} else {
			return emptyResponse;
		}
	},
	set: (_) => ({ set }, newValue) => {
		set(coordsState, newValue);
	},
});
`

**Comment by javascrewpt** [comment]
Same here. Version 0.0.10 works fine as well.
Though it does happen only when I use `selectorFamily`.

Here's my source:
```javascript
		export const currentCoordsState = selectorFamily({
			key: 'currentCoordsState',
			get: (hasGeolocation) => async ({ get }) => {
				const baseUrl = get(baseUrlState);
				const location = get(coordsState);
				const emptyResponse = {
					latitude: null,
					longitude: null,
					userAllowed: false,
					locationConfirmed: false,
				};
				if (hasGeolocation) {
					try {
						if (!location.longitude || !location.latitude) {
							const position = await getCurrentPosition({
								enableHighAccuracy: true,
							});
							if (position.hasOwnProperty('code') && position.code === 1) {
								throw new Error();
							} else {
								const {
									coords: { longitude, latitude },
								} = position;
								return {
									longitude,
									latitude,
									userAllowed: true,
									locationConfirmed: true,
								};
							}
						}
						return location;
					} catch (e) {
						try {
							if (baseUrl) {
								const { data } = await GetLonLatFromAppName(baseUrl);

								return {
									latitude: data.lat,
									longitude: data.lon,
									userAllowed: false,
									locationConfirmed: false,
								};
							}
						} catch (error) {}
						return emptyResponse;
					}
				} else {
					return emptyResponse;
				}
			},
			set: (_) => ({ set }, newValue) => {
				set(coordsState, newValue);
			},
		});
```

**Comment by drarmstr** [comment]
@secretlifeof Do you have a reproducer example?  Maybe something you could put on `codesandbox.io`?

**Comment by drarmstr** [comment]
Please re-open if we have a reproducer.
