### ISSUE TITLE
Is this psedocode? 

### ISSUE THREAD

**Issue by Nemesisesq** [facebookexperimental/Recoil#607]
`
const initializeState = ({set}) => {
  for(const [key, value] of Storage.entries()) {
    set(myLookupOfAtomWithKey(key), JSON.parse(value).value);
  }
}

`

specifically Storage.entries

**Comment by drarmstr** [comment]
Yes, it's just an example based on some hypothetical `Storage`.

**Comment by Nemesisesq** [comment]
Darn it, Got my hopes up and everything.
