### ISSUE TITLE
Error in safari - Functions cannot be declared in a nested block in strict mode

### ISSUE THREAD

**Issue by mc-aravind** [facebookexperimental/Recoil#609]
Getting the error **SyntaxError: Functions cannot be declared in a nested block in strict mode** in safari (5.1.7) windows
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/14159065/94161037-e4806c00-fea2-11ea-87b8-9f082b5e454c.png)

Version using: **0.0.13**

**Comment by drarmstr** [comment]
@csantos42 - related to new async selector
