### ISSUE TITLE
Shipping un-minified source

### ISSUE THREAD

**Issue by dustinsoftware** [facebookexperimental/Recoil#61]
It looks like the currently published version of recoil contains minified source. When debugging issues in recoil itself, it's more challenging to trace the flow of execution, even when using the devtools pretty-printer.

Would it be possible to ship both a development version alongside the minified production version? It looks like the react package takes this strategy.

<img width="1552" alt="Screen Shot 2020-05-16 at 19 27 52" src="https://user-images.githubusercontent.com/942358/82132243-b039c800-97ab-11ea-92b7-3e0e85221446.png">
<img width="1031" alt="Screen Shot 2020-05-16 at 19 27 33" src="https://user-images.githubusercontent.com/942358/82132248-b92a9980-97ab-11ea-8d37-cb2100297736.png">

**Comment by vjeux** [comment]
This sounds reasonable. Are you interested in updating the rollup config to ship both?

**Comment by dustinsoftware** [comment]
Sure :) I’ll give it a go this weekend.
