### ISSUE TITLE
useRecoilValue<string> return first char instead of the hole string value

### ISSUE THREAD

**Issue by bnayae** [facebookexperimental/Recoil#615]
Reproduce: 
use 'selector-first-char-issue' branch hhttps://github.com/bnayae/recoil-playground/tree/selector-first-char-issue
it's a nextjs app so you have to `run next dev` in order to run it.
you can check the `selectorPageTitle` which work fine.
but when consuming the selector at `InfoRaw` with `useRecoilValue` it return only the first char.
If I use it with `useRecoilState` it's work fine (but with a cast warning).

**Comment by bnayae** [comment]
I was able to work around this problem by returning string[].
If it by design, it's not intuitive and I think you have to reconsider it.
I would expect to get the exact value which I returned from the selector.

see branch 'selector-first-char-issue-work-around'
https://github.com/bnayae/recoil-playground/tree/selector-first-char-issue-work-around

**Comment by drarmstr** [comment]
It appears that you have the following code: 
```jsx
const [title] = useRecoilValue(selectorPageTitle);
```
However, the type signature for [`useRecoilValue()`](https://recoiljs.org/docs/api-reference/core/useRecoilValue) returns the value directly, not a tuple containing the value.  Use the following instead:
```jsx
const title = useRecoilValue(selectorPageTitle);
```

**Comment by bnayae** [comment]
TNX
