### ISSUE TITLE
Unwrapped Fulfilled Promises in Recoil Loadable

### ISSUE THREAD

**Issue by ohansemmanuel** [facebookexperimental/Recoil#617]
Hi there! Me again :) Thanks for fixing #534 

<br />

### The Question 
Consider the following: 

```js 
export const userDetails = selector({
  key: "userDetails",
  get: ({ get }) => {
    const userList = get(userNames);
    return userList.map(async ({ id }) => await getUserDetails(id));
  },
});
```
The selector above is hereafter referred to as **inlineQuery**.

And consider the alternative with the query managed by an external async selector: 

```js
// handle user detail query - as opposed to being inline
const userDetailQuery = selectorFamily({
  key: "userDetailQuery",
  get: (id) => async () => await getUserDetails(id),
});

export const userDetails = selector({
  key: "userDetails",
  get: ({ get }) => {
    const userList = get(userNames);
    return userList.map(({ id }) => get(userDetailQuery(id)));
  },
});
```
The selector above is hereafter referred to as **query**.

When these selectors are consumed within a component e.g. via `useRecoilLoadable`, **query** works but NOT **inlineQuery** 

**inlineQuery** returns an array of fulfilled promises e.g.:

```js
 [Promise<fulfilled>, Promise<fulfilled>, Promise<fulfilled>]
``` 
while **query** is rightly resolved with the fulfilled data

```js
 [data1, data2, data3]
```

<br />

### This may be to design, but ... 
I understand that this may be how the internals are designed. However, if you consider that the the `get` function for an async selector is typed as follows: 

```js 
get: GetRecoilValue
type GetRecoilValue = <T>(RecoilValue<T>) => T;
```

When `query` calls the external selector: `get(userDetailQuery(id))` we pass the argument of type `RecoilValue<T>` where `T` at a later time represents a fulfilled promise `Promise<fulfilled>`. 

The question then is why does **query** get resolved data but not **inlineQuery**? 

<br />
<br />
<br />

P.S 
Happy to share working project samples, but I reckon the code above may be simple enough to understand the question.

**Comment by drarmstr** [comment]
The type of the `get` property of a selector is as follows: 
```ts
export interface ReadOnlySelectorOptions<T> {
    key: string;
    get: (opts: { get: GetRecoilValue }) => Promise<T> | RecoilValue<T> | T;
    dangerouslyAllowMutability?: boolean;
}
```

If the object returned by the selector `get` is a `Promise`, then it is treated as an async value.  Promises nested in objects or arrays in a return value are not touched by Recoil.  

If you would like to use an async selector which returns an array of resolved nested promises, you could do something like:
```ts
export const userDetails = selector({
  key: "userDetails",
  get: ({ get }) => {
    const userList = get(userNames);
    return Promise.all(userList.map(({id}) => getUserDetails(id));
  },
});
```

Also, on another note, if you want the queries to occur in parallel for multiple selector dependencies you can use `waitForAll()`:
```ts
export const userDetails = selector({
  key: "userDetails",
  get: ({ get }) => {
    const userList = get(userNames);
    return waitForAll(userList.map(({id}) => userDetailQuery(id)));
  },
});
```
