### ISSUE TITLE
Deleting an Atom from an AtomFamily

### ISSUE THREAD

**Issue by c4rbon-c0py** [facebookexperimental/Recoil#622]
How does one efficiently delete a single atom from an atomfamily without triggering any sort of rerender (i'm dealing with 1000+ atoms inside the atomfamily)? I've been using what I feel is a botched approach to removing them.

Thanks!

**Comment by drarmstr** [comment]
You can use [`useResetRecoilState()`](https://recoiljs.org/docs/api-reference/core/useResetRecoilState) (or the `reset` provided by selector setters or `useRecoilCallback()` to remove the atom in an atom family from the state.  This currently still leaves some metadata around, which we're looking at optimizing.

This will cause any components currently subscribed to it to re-render.  If no components are currently subscribed to that particular atom, then they will not re-render.

**Comment by c4rbon-c0py** [comment]
Thanks for your clarification on this @drarmstr. I did notice that you made this same statement on a similar post a while back. I definitely wasn't trying to make you post the same answer twice, I just wasn't sure if "reset" was the defacto approach to removing them.

Again, very much appreciated!
