### ISSUE TITLE
Value of nested Recoil roots?

### ISSUE THREAD

**Issue by davidemmolino** [facebookexperimental/Recoil#623]
With the most recent update functionality has been added to share state between nested recoil roots. What is the value of using multiple recoil roots and the value of sharing state between them?
Is it simply to have better control over the scope of state throughout your application, to protect the state from unwanted modifications? Being able to start a component later and having the freedom to just connect it to an atom.

**Comment by drarmstr** [comment]
The functionality was added for those using custom renderers, such as three.js.  With a custom renderer there was a nested React root.  React doesn't share context across different roots so we needed an explicit mechanism to bridge them to allow Recoil state to be shared across the host and components nested in the custom renderer.

There are other potentially interesting use-cases as well.  For example, using this to help manage Recoil usage by a framework to avoid depending on or disruption of user usage of Recoil.
