### ISSUE TITLE
Include native directory in package.json

### ISSUE THREAD

**Issue by rtorr** [facebookexperimental/Recoil#624]
I noticed that the published package.json seems to be out of date with what is in master. Would we be able to include that build in a future release?

Release: https://github.com/facebookexperimental/Recoil/blob/344872da6d6547f6037b5d896359f389eebcea6e/package.json#L7

Master: https://github.com/facebookexperimental/Recoil/blob/953333a730cacc8c9f49a38eb3b5e0907de777d6/package.json#L13

**Comment by mondaychen** [comment]
Please check out "nightly" branch for our latest build. It will be included in next release.
https://github.com/facebookexperimental/Recoil/tree/nightly

You can use `yarn add https://github.com/facebookexperimental/Recoil.git#nightly` to install the nightly build if you'd like to test the react native support.

**Comment by rtorr** [comment]
@mondaychen rad, thanks!
