### ISSUE TITLE
Typescript + Selector with custom set prop

### ISSUE THREAD

**Issue by Geddard** [facebookexperimental/Recoil#626]
Hey there, I'm really happy with how nicely Recoil handles the state updates in my components, it has improved the performance of the app a lot :)

But I'm running into this scenario, I could use a kind of WriteOnly selector, but I know they are not supported.

So I have a main atom that is called query, and just has a string.
So I'm trying to create a selector where I could handle just the sort param in the query, I have the issue with typescript that I need this selector to return a string, (only because I'm forced to add the get property) and the set prop has to accept an object with `sort` and `direction`

So, something like this:

```
export const queryState = atom({
  key: 'Query',
  default: '',
});

interface SortProps {
  column: string;
  direction: 'asc' | 'desc';
}

export const sortParam: RecoilState<unknown> = selector({ // I have to use unknown here and then cast it to SortProps in the set
  key: 'SortParam',
  get: ({ get }) => get(queryState),
  set: ({ set, get }, newValue) => {
    const { column, order } = newValue as SortProps;
    const query = get(queryState); //queryState is a string like `?q=Some values here`
    // logic to add `sort={column}&asc=` depending on the props passed to the setter,
    // so the final query would for example look like `?q=value&sort=columnName&asc=1
  },
});
```

Would this be considered a good approach to handle this state update?
The only other approach I can think of would be creating a custom hook that receives these StateProps and after processing passes a string to the plain query setter. but then what's the point of the selector?

Any ideas?
If you need more info to help me I'll gladly provide it :)

**Comment by BenjaBobs** [comment]
You could deserialize the query string into an object, and then do the changes, and then re-serialize.
Example code (untested, so it might not work, but that is the basic idea):

```typescript
export const sortParam: RecoilState<unknown> = selector({ // I have to use unknown here and then cast it to SortProps in the set
  key: 'SortParam',
  get: ({ get }) => get(queryState),
  set: ({ set, get }, newValue) => {
    const { column, order } = newValue as SortProps;
    const query = get(queryState); //queryState is a string like `?q=Some values here`

	// deserialize
	const queryParams = query.slice(1).split('&');
	const paramsObject: { [key: string]: string | string[] } = {};

    for (const kvp of queryParams) {
      const [key, value] = kvp.split('=');

      let current = paramsObject[key];
      if (!current) {
        paramsObject[key] = value;
      } else {
        if (Array.isArray(current)) {
          current.push(value);
        } else {
          current = [current, value];
          paramsObject[key] = current;
        }
      }
    }

	// change values
	paramsObject.sort = column;
	if (order === 'asc') {
		paramsObject.asc = '1';
	} else {
		delete paramsObject.asc;
	}

	// serialize
	const newQuery = Object.entries(paramsObject).reduce((newQuery, [key, value]) => {
      if (Array.isArray(value)) {
        return newQuery + value.map(v => `${key}=${v}`).join('&');
      } 
      
      return newQuery + `${key}=${value}`;
    }, '?');

	// set new state
	set(queryState, newQuery);
  },
});
```

**Comment by Geddard** [comment]
@BenjaBobs i could do this but it would require me sending an untyped string like `sort={name}&asc=1` for example, and I prefer sending the exact values that i can type and then fuse into the queryState, deserializing with selectors is nice, but i would love to have a selector that takes an object and serialized it before setting it.
I can do this either in a custom hook or here, but here i need to do some tricky stuff with types, like typing the selector to unknown and then casting

**Comment by drarmstr** [comment]
How about storing the sort as the state and using the query as a derived selector?

```jsx
const sortState = atom<SortProps>({
  key: 'Sort',
  default: {column: 'foo', direction: 'desc'},
});

const queryState = selector<string>({
  key: 'QueryResults',
  get: ({get}) => {
    const {column, direction} = get(sortState);
    return `?q=${get(queryState)}&column=${column}&asc=${direction==='asc'?1:0}`;
  },
});
```

**Comment by Geddard** [comment]
> How about storing the sort as the state and using the query as a derived selector?
> 
> ```js-jsx
> const sortState = atom<SortProps>({
>   key: 'Sort',
>   default: {column: 'foo', direction: 'desc'},
> });
> 
> // This could also be a selector depending on how you generate your query string.
> const queryStringState = atom<string>({
>   key: 'Query String'
>   default: 'bar',
> });
> 
> const queryState = selector<string>({
>   key: 'QueryResults',
>   get: ({get}) => {
>     const {column, direction} = get(sortState);
>     return `?q=${get(queryStringState)}&column=${column}&asc=${direction==='asc'?1:0}`;
>   },
> });
> ```

Hmm I like this idea, I'll give it a try, thanks!
