### ISSUE TITLE
TypeScript and SerializableParam type

### ISSUE THREAD

**Issue by DanhoDE** [facebookexperimental/Recoil#627]
I had a problem with SerializableParam type 
the scenario is when I have type contend a function
the fix is sample

`export type SerializableParam = Primitive | ReadonlyArray<SerializableParam> | Readonly<{[key: string]: SerializableParam}> | Readonly<(prams: SerializableParam) => SerializableParam | void >;`

and thanks for great job

**Comment by drarmstr** [comment]
Is this with a `selectorFamily()`?  The default selector family cache implementation is based on value equality and should not use functions in the parameter.  Different functions may produce the same key.  Even if the function was serialized, the closure state would not be captured in the key.

**Comment by Newbie012** [comment]
Hey @drarmstr,

In our architecture, we use a class called `API`. It looks something like this:

```ts
class API {
    async getSomething() {
        return Promise.resolve({ hello: "world" });
    }
}
```

Now, we want to pass an instance of the API inside the `selectorFamily` to do async operation. Something like:

```ts
const selector = selectorFamily<any, { api: API }>({
    key: "Selector",
    get(api: API) {
        return async () => {
            const value = await api.getSomething();
            return { value };
        };
    }
});
```

Which causes the following error:

```ts
Type '{ api: API; }' does not satisfy the constraint 'SerializableParam'.
  Type '{ api: API; }' is not assignable to type 'Readonly<{ [key: string]: SerializableParam; }>'.
    Property 'api' is incompatible with index signature.
      Type 'API' is not assignable to type 'SerializableParam'.
        Type 'API' is not assignable to type 'Readonly<{ [key: string]: SerializableParam; }>'.
          Index signature is missing in type 'API'.ts(2344)
```

which describes what you said in the comment above. The question is, how can we approach this while maintaining the function as a pure one?

**Comment by drarmstr** [comment]
You can try using a serializable handle or a key as the family parameter instead of the actual class itself.

**Comment by Newbie012** [comment]
I guess you're right about this specific case. What if the `API` class would've been constructed like so:

```ts
class API {
    constructor(private apiToken: string) {}

    async getSomething() {
        return fetchStuff("URL", { auth: apiToken });
    }
}
```

```ts
const api = new API("THIS_IS_THE_API_TOKEN");

function App({ api }) {
    const data = useRecoilValue(selector, { api });
}
```

Note that `App` has no access to the API token, but only the instance of the API. The only alternative would be to pass the API token to the `selectorFamily` and instantiate a new `API` class, but it feels cumbersome.

**Comment by drarmstr** [comment]
A lookup map can also be used for the tokens.
