### ISSUE TITLE
class component support?

### ISSUE THREAD

**Issue by ibnumusyaffa** [facebookexperimental/Recoil#63]

**Comment by drarmstr** [comment]
Recoil is specifically designed to do things in a "Reactish" way and support new React paradigms such as hooks, suspense, concurrent rendering, etc.  As React hooks require function components, Recoil also requires function components; function components are the future.

**Comment by davidmccabe** [comment]
If you really wanted to you could make a HOC that bridges Recoil with class components. We used to have one but found the types were too complicated to maintain. You can also manually create function components that pass recoil values in as props. What we've done is just refactor components to functional as needed.

**Comment by kivervinicius** [comment]
@davidmccabe have any example please?

**Comment by NoriSte** [comment]
@kivervinicius you can find some examples on this [question on StackOverflow](https://stackoverflow.com/questions/62860300/using-recoil-js-in-react-in-class-component-without-using-hooks).

**Comment by songhlc** [comment]
HOC is the solution
