### ISSUE TITLE
0.0.11/0.0.12/0.0.13 upgrade causes async data not to complete, works fine in 0.0.10

### ISSUE THREAD

**Issue by aappddeevv** [facebookexperimental/Recoil#632]
Is there anyway to easily debug this?

The issue is that everything works fine in 0.0.10, but in 0.0.13 (with react, react-dom experimental), my data is fetched per the network debug window, but the suspense never completes indicating that the recoil data is not completing allowing the component to resume. Has this behavior been seen before?

I'm not sure how to event start debugging this issue.

**Comment by drarmstr** [comment]
Do you have a test case you could share?  Maybe something on codesandbox.io?

**Comment by aappddeevv** [comment]
I do not. I can try to make a reduced version but I may not succeed in reproducing it. My graph has about 30 atoms/selectors. However, I did find that it the initial graphql query that causes this issue. There's nothing out of the ordinary about it and it works in isolation just fine. The fetch completes Ok per the network window. Let me try to isolate that.

**Comment by aappddeevv** [comment]
I'm still trying to resolve this. I am running 0.1.2 and the latest react experimental. My initial to fetch data via a graphql call completes (confirmed that) but the react component stays suspended. I'm in a heavily transpiled environment but I don't think that's the problem.

**Comment by aappddeevv** [comment]
I have moved the RecoilRoot outside the error boundary which seems to have addressed the problem. I do not know enough about React to understand why this would have worked.
