### ISSUE TITLE
[docs] Asynchronous Data Queries dead links

### ISSUE THREAD

**Issue by ides15** [facebookexperimental/Recoil#636]
On https://recoiljs.org/docs/guides/asynchronous-data-queries/, there are two dead links in the second paragraph.

"If you are looking to synchronize local and server state, then please see **Asynchronous State Sync** or **State Persistence**."

**Asynchronous State Sync** should point to https://recoiljs.org/docs/guides/asynchronous-state-sync/
**State Persistence** should point to https://recoiljs.org/docs/guides/persistence/

**Comment by ides15** [comment]
Looks like this happens only when the original URL is https://recoiljs.org/docs/guides/asynchronous-data-queries/ (notice the trailing slash). Not sure how I got there in the first place...

**Comment by drarmstr** [comment]
@ides15  - Thanks for catching this!
