### ISSUE TITLE
How to use Recoil state in App.tsx?

### ISSUE THREAD

**Issue by wannadream** [facebookexperimental/Recoil#639]
I have implemented something as below in App.tsx.

```
function App() {
  const device = useRecoilValue(globalState.device);

  return  (
    <RecoilRoot>
      <div className={`app ${device.isMobile ? 'mobile' : ''}`}>
      ...
      </div>
    </RecoilRoot>
  );
}
```

So I got errors as the following:
![image](https://user-images.githubusercontent.com/6989212/95497323-5f478d80-095f-11eb-8deb-60c5d5f30c5b.png)

I am not sure if I did it right, need some one to assist. Thanks in advance.

**Comment by drarmstr** [comment]
The Recoil hooks should be used inside components that are nested in `<RecoilRoot>`, not in the component that hosts `<RecoilRoot>`  For example:
```jsx
function DeviceInfo() {
  const device = useRecoilValue(globalState.device);
  return (
    <div className={`app ${device.isMobile ? 'mobile' : ''}`}>
      ...
    </div>
  );
}

function App() {
  return  (
    <RecoilRoot>
      <DeviceInfo />
    </RecoilRoot>
  );
}
```
