### ISSUE TITLE
order of asynchronous operations

### ISSUE THREAD

**Issue by KarolAdamiec** [facebookexperimental/Recoil#640]
Hi,

❤️ for Recoil.
I am redesigning some code, and it so happens that currently I do:

```
await fetch(authenticate)
await fetch(settings)
```

so when rethinking this as a selectors/atoms at some point I have

```
const [authentication, setAuthentication] = useRecoilState(authenticationState);
const [userSettings, setUserSettings] = useRecoilState(userSettingsState);
```

inside of some component that handles login and fetches some extra settings for user on success.

In my experimentation above two are equivalent, i.e. useRecoilState goes into Suspense while waiting,
and once first hook resolves, second one goes in. i have put some strategic slowness here and there to confirm that.

I browsed documentation for this but it is never explicitly pointed out. 
Is that an implementation detail that can change?

Also how could one express that userSettingsState selector must wait for authenticationState to be resolved?
i did an experiment with userSettingsState selector having
` {get} : get(waitForAll([authenticationState])`
and this seems to work as well...

So what would be the recommended way to go about that?

Thanks.

**Comment by drarmstr** [comment]
If you use multiple hooks in a component for subsequent async selectors they will be serialized in the order the are accessed.  However, you can initiate them in parallel using a concurrency helper such as [`waitForAll()`](https://recoiljs.org/docs/api-reference/utils/waitForAll):

```jsx
  const [authentication, userSettings] = useRecoilValue(waitForAll([authenticationState, userSettingsState]));
```

If you want to force them to be serialized and the authentication to always run first, then yes, you can include it as a dependency.  No need for the `waitForAll()` in that case:
```jsx
  const userSettingsState = selector({
    key: "UserSettings",
    get: ({get}) => {
      get(authenticationState);
      return ...
    },
  });
```
```

**Comment by KarolAdamiec** [comment]
Excellent.

Is the serialization of multiple hooks in a component for subsequent async selectors a contract of recoil or Suspense itself?
Worth adding to documentation?

Thanks.

**Comment by drarmstr** [comment]
This is a property of Suspense.
