### ISSUE TITLE
Allowing `string | symbol` instead of `string` for `NodeKey`

### ISSUE THREAD

**Issue by m-rutter** [facebookexperimental/Recoil#645]
I was wondering if there was a reason why the `NodeKey` type in both the flow codebase and DefinatelyTyped typescript definitions (I'm guessing they aren't maintained here, but probably follow the flow types closely) is `string` instead of `symbol | string`.

https://github.com/facebookexperimental/Recoil/blob/ca888d3c3a55a3128279d0124ebca9002377770b/src/core/Recoil_Keys.js#L14

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a9e7ca81697abaff687dcfd8f775ea01a1f2b0f2/types/recoil/index.d.ts#L8

From what I can see the NodeKey is used entirely as an oqaue and unique key for `Map` and `Set` objects. Given the main requirement for `NodeKey` is uniqueness, would it not make sense to allow support for `symbol` in addition to `string`? Rather than getting users of the library to uphold a uniquenesss invariant across modules in the case of `string`, each symbol is unique by virtue of the specification.

Maybe there is a reason to avoid symbol because some users find it confusing, but it would be nice to see it as a documented alternative to allow the pattern.

**Comment by m-rutter** [comment]
From what I can tell this isn't a breaking change and involves a single line change in one file.

**Comment by drarmstr** [comment]
The goal is uniqueness.  But, that includes uniqueness across multiple application executions for features such as hot module replacement, state persistence, or synchronizing with external state.  So, `Symbol` would not be sufficient as it would have a new instance on each evocation.

**Comment by m-rutter** [comment]
Thanks, I had not thought about it in that way.
