### ISSUE TITLE
[TypeScript] Types for Loadable convenience accessors

### ISSUE THREAD

**Issue by BenjaBobs** [facebookexperimental/Recoil#648]
I found these when console logging a `Loadable` and thought they looked very handy.

https://github.com/facebookexperimental/Recoil/blob/ca888d3c3a55a3128279d0124ebca9002377770b/src/adt/Recoil_Loadable.js#L42-L48

The TypeScript type does not have them:

https://github.com/facebookexperimental/Recoil/blob/76ccb590cf2fef68d825a188fde1a3b679abba2b/typescript/index.d.ts#L167-L179

I think this would do the job:
```typescript
export type Loadable<T> = {
    errorMaybe: () => Error | void;
    errorOrThrow: () => Error;
    valueMaybe: () => T | void;
    valueOrThrow: () => T;
    promiseMaybe: () => LoadablePromise<T> | void;
    promiseOrThrow: () => Promise<T>;
  } & (
    | Readonly<{
      state: 'hasValue';
      contents: T;
    }>
    | Readonly<{
      state: 'hasError';
      contents: Error;
    }>
    | Readonly<{
      state: 'loading';
      contents: LoadablePromise<T>;
    }>
  );
```

**Comment by drarmstr** [comment]
Added in `0.1.0`
