### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by dustinsoftware** [facebookexperimental/Recoil#65]
Is the plan to use Flow as a test suite? I see many pre-existing tests, and `flow-bin` is a devDependency, but running `yarn run flow` produces an error about a missing `.flowconfig`.

**Comment by claudiopro** [comment]
Yes we were chatting about this with @vjeux and @davidmccabe yesterday. The plan is to make tests to run in Jest and then set up a GitHub Action to run tests on commits and PRs, as I also replied on #66.

I am not entirely familiar with rollup so I proposed a naive PR with a `.babelrc` and some extra boilerplate: #81

**Comment by dustinsoftware** [comment]
I think it makes sense to stick with Jest; closing now that #81 is merged.

We can get tests wired up via Github Actions once they are all passing.
