### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by dustinsoftware** [facebookexperimental/Recoil#66]
Other Facebook Experimental projects, such as `rust-shed`, appear to use Github Actions for CI.

https://github.com/facebookexperimental/rust-shed/runs/681953106

If Actions is already enabled on a Github org level, would you accept a pull request to get actions set up to build with rollup and run tests? (once the tests are working, that is)

**Comment by claudiopro** [comment]
Sure we'd love that! Let us know if you need anything from us 👍

**Comment by dustinsoftware** [comment]
OK I’ll aim to get a PR up in the next couple days.
