### ISSUE TITLE
useEffect has a missing dependency

### ISSUE THREAD

**Issue by rambabusaravanan** [facebookexperimental/Recoil#661]
I am trying to update the recoil state in useEffect and facing the lint error.

```js
  // let [params, setParams] = useRecoilState(paramsAtom);
  // let setParams = useSetRecoilState(paramsAtom);
  let resetParams = useResetRecoilState(paramsAtom);
  useEffect(() => { 
    resetParams()
  }, [])
```
> React Hook useEffect has a missing dependency: 'resetParams'. Either include it or remove the dependency array.eslint(react-hooks/exhaustive-deps)

React's setState (from useState) has no lint error whereas Recoil's setState (from useRecoilState) has the lint error.

-------------

**Workaround:** Using the set state function via ref throws no lint error and this seems to be a good workaround.
```
  let resetParams = useRef(useResetRecoilState(paramsAtom));
  useEffect(() => { 
    resetParams.current()
  }, [])
```

We're using a lot of workarounds to try using Recoil JS. Looking for help to know the proper way of using it.

**Comment by drarmstr** [comment]
The reset function returned by `useResetRecoilState()` is similar to the setter returned by `useSetRecoilState()` or `useRecoilState()` is stable and shouldn't need to be included in the `useEffect()` dependencies.  However, the React lint rule currently isn't smart enough to know that as an exception.  As a workaround you could just include it in the dependency list.  You could also suppress the lint error, though that may hide other missing dependencies.
