### ISSUE TITLE
initialize atoms dynamically

### ISSUE THREAD

**Issue by 1omercohen** [facebookexperimental/Recoil#662]
I found "initializeState" amazing code' but looking for something to replace this function myLookupOfAtomWithKey

`const initializeState = ({set}) => {
  for(const [key, value] of Storage.entries()) {
    set(myLookupOfAtomWithKey(key), JSON.parse(value).value);
  }
}

return (
    RecoilRoot initializeState={initializeState}
    PersistenceObserver 
    SomeComponent 
    RecoilRoot
);`

Also, all my atoms Set up, in this function in any key or function exports do not know of any atom.
how should I dynamically update the atoms ???

**Comment by drarmstr** [comment]
`myLookupOfAtomWithKey()` is meant to be a user function you provide to get your atom based on the persisted key.  This helps ensure type-safety when initializing the atoms.  As the documentation indicates, this is really a stop-gap approach until we publish the new persistence API and libraries.

**Comment by 1omercohen** [comment]
I know, I called this function "initAtoms",   
RecoilRoot has "initializeState" property, which is a function with a snapshot object.
Also, I set all atoms up before rendering the elements, in the snapshot in _store property did not recognize my atoms.
and can not initialize the state from storage as you display in toturial

**Comment by drarmstr** [comment]
Sorry, what are you referring to with `_store` property?  Do you have some sample code demonstrating what is not working?

**Comment by 1omercohen** [comment]
`
import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import * as serviceWorker from "./serviceWorker";
import { RecoilRoot, atom, useRecoilValue } from "recoil";

const userState = atom({
  key: "userState",
  default: null
});

const wishListState = atom({
  key: "wishListState",
  default: []
})

const initializeState = ({set}) => {
  for(const [key, value] of Object.entries(localStorage)) {
    set(key, JSON.parse(value));
  }
}


const App = () => {
  const wishList = useRecoilValue(wishListState)
  const user = useRecoilValue(userState)
  return <>
    { !!user &&
      <div>
        <div>
          {user.firstname} {user.lastname}
        </div>
        <div>
          {user.email}
        </div>
      </div>
    }
  </>
}


ReactDOM.render(
  <React.StrictMode>
    <RecoilRoot initializeState={initializeState}>
      <App />
    </RecoilRoot>
  </React.StrictMode>,
  document.getElementById("root")
);
serviceWorker.unregister();

`
both of the atoms (userState, wishList) has localStorage, and steel both of them are empty.
every key in localStorage save in atom key name.

**Comment by drarmstr** [comment]
I don't see a `<RecoilRoot>` in this example.  Try testing with a live test case on https://codesandbox.io/

**Comment by 1omercohen** [comment]
[CodeSandBox](https://codesandbox.io/s/blissful-nash-kjih4)
how can recognize witch the Atoms there?

**Comment by drarmstr** [comment]
Try this for your `initializeState()`:
```jsx
import { wishListState, userState } from "./state/atoms";

const atomsByKey = {
  userState: userState,
  wishListState: wishListState,
};

const initializeState = ({ set }) => {
  for (const [key, value] of Object.entries(localStorage)) {
    set(atomsByKey[key], value);
  }
};
```

**Comment by drarmstr** [comment]
You can now initialize dynamic atom families with [atom effects](https://recoiljs.org/docs/guides/atom-effects)
