### ISSUE TITLE
how to handle socket event

### ISSUE THREAD

**Issue by 1omercohen** [facebookexperimental/Recoil#665]
I have a chat project, try to get value, and set value when socket events happen.
`import io from 'socket.io-client';
import { selector, useRecoilCallback } from "recoil";
import { userState, messageListState, messageState } from "./atoms";
const socket = io('http://localhost:3000');

const getMsg = useRecoilCallback(({snapshot, set}) => async (data) => {
    const messages = await snapshot.getPromise(messageListState);
    const newMessages = [...messages, data];
    set(messageListState, newMessages);
})

const sendMsgSelector = selector({
    key: "sendMsgSelector",
    set: ({get, set, reset}) => {
        const msg = get(messageState);
        socket.emit('message', msg);
        reset(messageState);
    }
})

socket.on('message', getMsg)

export { userState, sendMsgSelector, messageListState, messageState }`

**Comment by drarmstr** [comment]
I haven't used socket.io myself.  But, you don't need a selector to send the message.  An atom isn't necessary there at all.  You could just emit the message when you want to send it directly.  If you are using an atom to coordinate the pending message across components for some reason, then you could just use a hook:
```jsx
function useSendMsg(): MsgType => void {
  const setLastMsg = useSetRecoilState(messageState);
  return msg => {
    socket.emit('message', msg);
    setLastMsg(msg);
  };
}
```
Or if you wanted to have another component subscribe to the pending message and emit it maybe:
```jsx
function useEmitMessages() {
  const pendingMsg = useRecoilValue(messageState);
  const resetPendingMsg = useResetRecoilState(messageState);
  useEffect(() => {
    if (pendingMsg != null) {
      socket.emit('message', pendingMsg);
      resetPendingMsg();
    }
  }, [pendingMsg]);
}
```
or maybe with an Atom Effect:
```jsx
const messageState = atom({
  key: 'PendingMessage',
  default: null,
  effects_UNSTABLE: [
    ({onSet}) => {
      onSet(msg => {
        if (!(msg instanceof DefaultType)) {
          socket.emit('message', msg);
        }
      });
    },
  ],
});
```
But, likely cleaner to avoid storing messages in atoms and just use atoms to store the client application state.  One option might be to subscribe to the application state changing and send a message when appropriate
```jsx
const fooState = atom({
  key: 'Foo',
  default: null,
  effects_UNSTABLE: [
    ({onSet}) => {
      onSet(value => socket.emit('message', {foo: value}));
    },
  ],
});
```

Or something like that.  But, really, there should be a good reason for using an atom for that state such as multiple components doing something with the pending message.  Ideally, just keep it simple and avoid using an atom:

Similar for using an atom to manage the queue of received messages.  You can do this if you really need multiple components to coordinate and handle the incoming messages.  But, it's probably cleaner and simpler to avoid using atoms to manage the message queue.  What might make more sense is to use Recoil to store the client's application state and then just update that when handling the socket messages:
```jsx
function HandleMessages() {
  const setMyFooState = useSetRecoilState(fooState);
  const setMyBarState = useSetRecoilState(barState);
  useEffect(
    () => {
      socket.on('message', msg => {
        setMyFooState(msg.foo);
        setMyBarState(msg.bar);
      });
    },
   [],
  );
});
```

**Comment by 1omercohen** [comment]
@drarmstr Thanks,
understand the socket must be a global variable or using context
