### ISSUE TITLE
How to update selector's 'temporary' value and do a request to api at the same time

### ISSUE THREAD

**Issue by nikitatrifan** [facebookexperimental/Recoil#669]
Hey guys!

I'm fascinated by this library and wanted to try it out. I came across a use case where I have to display to the user what he's changed in the UI while making a request to the server to save that data.

Here is my selector to retrieve the data:
```js
export const eventsListQuery = selector({
  key: "eventsList",
  get: async ({ get }): EventType[] => {
    const currentUser = get(userState);
    return await fetchEvents(currentUser);
  },
});
```
Then I render `events`, each event item gets only its id from props and selects the event data using this selector:
```js
export const eventItemQuery = selectorFamily({
  key: "eventItem",
  get: (eventId: string) => ({ get }): EventType => {
    return get(eventsListQuery).find((event: EventType) => event.id === eventId);
  },
});
```
The user can change almost anything in the data, so I wanted to have this selector updating the state in a way that I could render some updates everywhere it's being used and send a request to the server to get it updated on the backend side at the same time. 

I tried to use `set` method of a selectorFamily but it throws an error indicating that `eventsList` could not be updated because it's read-only which is I guess make sense.
```js
export const eventItemQuery = selectorFamily({
  key: "eventItem",
  get: (eventId: string) => ({ get }): EventType => {
    return get(eventsListQuery).find((event: EventType) => event.id === eventId);
  },
  set: (currentItem: EventType) => ({ set, get }, updatedValue) => {
    const events = get(eventsListQuery).map((event: EventType): EventType => {
      if (event.id === currentItem.id) return { ...event, ...updatedValue };
      return event;
    });

    set(eventsListQuery, events);
  },
});
```

My question is, how can I achieve that user experience using Recoil?

**Comment by BenjaBobs** [comment]
I think you're looking atom effects.

The pr for the typescript types was merged here, but there hasn't been a release yet so hang in there.
https://github.com/facebookexperimental/Recoil/pull/634

**Comment by jkulubya** [comment]
I believe you can try out the (unstable) atom effects with the nightlies ->

```
yarn add https://github.com/facebookexperimental/Recoil.git\#nightly
```

**Comment by drarmstr** [comment]
The Atom Effects are also actually in released 0.0.13 build, just not documented yet.  As @BenjaBobs mentions, the TypeScript annotations are only in the nightly so far, though.

**Comment by nikitatrifan** [comment]
Cool! I tried to utilize atoms effects, looks like it solved part of the use case as I can sync new data with the backend now.

Is there a way to access other states in atom effects so that requests could be made based on those values? Eg for the use case, I have to get user's data before fetching/syncing his events:

```js
export const eventsList = atom({
  key: "eventsList",
  default: [],

  effects: [async ({ setSelf, onSet, get }) => {
    setSelf(await fetchEvents(get(userState)));

    onSet(async (updatedEvents) => {
      try {
        await syncEvents(get(userState), updatedEvents);
      } catch (e) {console.error('Couldnt update events data:', e);
    })
  }],
});
```
(obviously `get` doesn't work here but it's used to illustrate the example)

**Comment by drarmstr** [comment]
Please note that the effect function itself should not be `async`.  Though, you can set the initial `setSelf()` to a `Promise`.

We are exploring some ability to read other state from the handlers, perhaps though a `getSnapshot()` approach.

**Comment by drarmstr** [comment]
Consolidate discussion of getting other state from effects in #707
