### ISSUE TITLE
[React Native]  Can't find variable Window error and possible solution

### ISSUE THREAD

**Issue by a-sane** [facebookexperimental/Recoil#671]
Updating the value of recoil state on react native throws the following exception: `Can't find variable: Window` if type of value is array or object

Looks like this line:
https://github.com/facebookexperimental/Recoil/blob/b4db14bbf3135778ea237a80b30239ea9c7fb473/src/util/Recoil_deepFreezeValue.js#L62

from https://github.com/facebookexperimental/Recoil/pull/633 causes this error because there is no Window object on react native

Maybe there can be something like this check?

```js
const isReactNative = typeof navigator !== 'undefined' &&  navigator.product === 'ReactNative';

if (!isSSR && !isReactNative && (value === window || value instanceof Window)) { 
```

**Comment by drarmstr** [comment]
Thanks for proposing a fix for this @a-sane!
