### ISSUE TITLE
Recommended usage of trigger in AtomEffect

### ISSUE THREAD

**Issue by bentron2000** [facebookexperimental/Recoil#677]
Re: #380 and #634 

I'm testing out Atom Effects on the nightly builds and I'm not sure I understand the usage of the `trigger` parameter.

Is it possible to provide an example of how it might be used or could you point me to a doc?

Thanks!

B

**Comment by drarmstr** [comment]
The intended use of `trigger` is for optimizations to potentially ignore initialization of the atom value if the trigger event for initialization of the atom was a `set` operation.  We don't have documentation published yet, but probably in the next week or so.
