### ISSUE TITLE
get loadable atom initial data without fetch

### ISSUE THREAD

**Issue by juyeong1260** [facebookexperimental/Recoil#679]
```ts
const fetchList = (): Promise<typeof LIST> =>
  new Promise((resolve) => {
    setTimeout(() => resolve(LIST), 100);
  });
const fetchItem = (id: string) =>
  new Promise((resolve) => {
    setTimeout(() => resolve(LIST.find((item) => item.id === id)), 100);
  });

const listAtom = atom({
  key: "listAtom",
  default: selector({
    key: 'listAtom/Default',
    get: async () => {
      console.log('executed!');
      return await fetchList()
    }
  })
});
const itemAtom = atomFamily({
  key: "itemAtom",
  default: selectorFamily({
    key: "listAtom/Default",
    get: (id: string) => async ({ get }) => {
      const list = get(listAtom) || [];
      if ("find" in list) {
        const item = (list as any[]).find((d) => d.id === id);
        if (item) {
          return item;
        }
      }
      return await fetchItem(id);
    }
  })
});

const Test = () => {
  const data = useRecoilValueLoadable(itemAtom("1"));

  return <>{data.state}</>;
};
```

then, `executed!` is logged

can i get `listAtom`'s value or null without async call??

**Comment by BenjaBobs** [comment]
You can use `noWait` to get a loadable instead of waiting for a value: https://recoiljs.org/docs/api-reference/utils/noWait

**Comment by drarmstr** [comment]
Thanks again @BenjaBobs!  Yes, [`noWait()`](https://recoiljs.org/docs/api-reference/utils/noWait) is great for getting a [`Loadable`](https://recoiljs.org/docs/api-reference/core/Loadable) object including the current state (`hasValue`, `hasError` or `loading`).  You can also use the [`useRecoilValueLoadable()`](https://recoiljs.org/docs/api-reference/core/useRecoilValueLoadable) hook from a component.  The advantage of `noWait()` is that it can also be used from a selector evaluation function.

**Comment by juyeong1260** [comment]
no! i want no call async function! just get value if selector has. but `noWait` call async function.

**Comment by drarmstr** [comment]
> no! i want no call async function! just get value if selector has. but `noWait` call async function.

For that, you could set the `default` value of `listAtom` to `null`, then explicitly make your async call and set the value of `listAtom` to the results when available.

**Comment by juyeong1260** [comment]
hmm.. what about add `skipAsync` on `noWait` option, and get stored data from atom? if has not data then return null.

if i set `listAtom` to store data, then i will call async function on component. but i want set data on selector...

**Comment by wojtekmaj** [comment]
I don't think this issue should have been closed.

`noWait` does NOT cause the atom passed to it to skip fetching initial data, it only makes it return a `Loadable` and, well, skip waiting for the data being fetched.

**Comment by BenjaBobs** [comment]
You can do 
```typescript
const list = get(noWait(listAtom)).valueMaybe() || [];
```

**Comment by wojtekmaj** [comment]
I think I figured it out...

```js
function useRecoilValueLoadableWithoutFetch(recoilValue) {
  const snapshot = useRecoilSnapshot();

  return snapshot.getInfo_UNSTABLE(recoilValue).loadable;
}
```

This would return `Loadable` just like `useRecoilValueLoadable` but won't trigger fetch when accessing it.

**Comment by drarmstr** [comment]
@wojtekmaj  - Note that use of `useRecoilSnapshot()` will subscribe the component using it to re-render for state changes for all atoms/selectors.  This hook is primarily intended for debug tools, link generation, etc.  But, you could use a `Snapshot` from `useRecoilCallback()` to avoid that issue.
