### ISSUE TITLE
Initialize a large amount of atoms can be very slow and may crash app

### ISSUE THREAD

**Issue by otakustay** [facebookexperimental/Recoil#690]
I have created a sandbox: https://codesandbox.io/s/entity-store-implements-sm1bl

Despite `ReduxWithManual` and `ReduxWithNormalizr` component, click "Recoil & Atom Family" on the page, there is a long time loading indicator and the app can crash sometimes (1 out of  3 tries).

The data is prepared before the app starts, I simply put all these entities into 3 atom families:

```js
const initialize = useRecoilCallback(
    ({set}) => () => {
        const postFamily = postStore.unwrap();
        const userFamily = userStore.unwrap();
        const commentFamily = commentStore.unwrap();
        Object.entries(entities.posts).forEach(([k, v]) => set(postFamily(k), v));
        Object.entries(entities.users).forEach(([k, v]) => set(userFamily(k), v));
        Object.entries(entities.comments).forEach(([k, v]) => set(commentFamily(k), v));
        set(postsState, posts);
    },
    []
);
useEffect(() => {
    console.log('initialize store');
    initialize();
}, [initialize]);
```

There are 1000 posts, 500 users and 10000 comments, so a total of 11500 atoms should be initialized here, this costs more than 10 seconds on my 16 inch macbook pro, which is way slower than I expected.

**Comment by drarmstr** [comment]
@otakustay - Would you mind testing again with version `0.1.1`, we implemented some performance fixes in there for this exact scenario.

**Comment by drarmstr** [comment]
Just checked it out in your sandbox with `0.1.1`, it seems like the issue is mostly resolved now.  Please let us know if you have additional concerns about it, we have more performance improvements in the works for scalability.

**Comment by otakustay** [comment]
Yes it's super fast now, it seems `0.1.1` is published just hours ago, thanks for the performance work
