### ISSUE TITLE
[Reveal.js] Recoil 0.0.13 doesn't initialize Reveal.js framework

### ISSUE THREAD

**Issue by alinealvesvianna** [facebookexperimental/Recoil#696]
Hi! I would first like to congratulate the work done! Recoil is simple to use and helps a lot in the mission of managing complex states.

I started having a problem with version 0.0.10 when generating the bundle for production with the [rollup-plugin-terser(version 7.0.0)](https://www.npmjs.com/package/rollup-plugin-terser). I took the following error:
![image](https://user-images.githubusercontent.com/7591901/97731598-185b3c80-1ab4-11eb-9d24-f3dfe32fcde1.png)

I found the [following issue](https://github.com/facebookexperimental/Recoil/issues/122) talking about exactly the same error, saying that this problem was solved in version 0.0.8, but I was in version 0.0.10. Anyway, I decided to update the recoil to the latest version available (0.0.13). After that, the bug that occurred when generating the production bundle was resolved, but the [Reveal.js framework](https://revealjs.com/) stopped being initialized.

Using version 0.0.10 of recoil without generating the bundle for production, loaded Reveal.js the right way:
![image](https://user-images.githubusercontent.com/7591901/97733058-185c3c00-1ab6-11eb-89d2-987b5ef18d75.png)

Using version 0.0.13 of recoil generating the package for production with teser, but Reveal.js does not load:

![image](https://user-images.githubusercontent.com/7591901/97733532-be0fab00-1ab6-11eb-8d81-75a4c1e7bb66.png)

Code snippet where I launch Reveal.js:

```javascript
  const hasRevealDOMNode = useCallback((node) => {
    if (node !== null && !deckInitialized) {
      const deck = new Reveal(node, {
        plugins: [Markdown],
        embedded: true,
      })
      setDeckState(deck)
      deck.initialize().then(() => {
        setDeckCurrentSlideId(deck)
        deck.on("slidechanged", () => {
          setDeckCurrentSlideId(deck)
        })
        setDeckInitialized(true)
      })
      deck.configure({
        pdfMaxPagesPerSlide: 1,
        pdfSeparateFragments: true,
        margin: 0,
        pdfPageHeightOffset: -1,
      })
    }
  }, [])
...

  return (
    <div style={{
        minHeight: '90vh',
        background: '#000'
      }}
      className="reveal-viewport"
    >
      <div ref={hasRevealDOMNode} className="reveal bg-gray-300">
        <div className="slides">
          {slidesList &&
            slidesList.map(({ id }) => {
              return <Slide slideId={id} key={id} />
            })}
        </div>
      </div>
    </div>
  )
```

Thank you very much for your attention and congratulations once again for the library

**Comment by mondaychen** [comment]
In your code, are the setters (`setDeckState`, `setDeckCurrentSlideId`, `setDeckInitialized`) from `useRecoilState`? If yes, can you share your atoms/selectors?

**Comment by alinealvesvianna** [comment]
Thank you @mondaychen for your attention!
Here's the complete canvas code:

```javascript

import React, { useCallback, useState, useEffect } from "react"
import Reveal from "reveal.js"
import Markdown from "reveal.js/plugin/markdown/markdown.esm.js"
import { useParams } from "react-router-dom"
import { currentSlideState, slidesListState, deckStateReveal } from "../../store/atoms"
import { useRecoilState, useSetRecoilState } from "recoil"
import db from "../../db"
import Slide from "../Slide"

const RevealBase = () => {
  const { reportId } = useParams()
  const initialSlidesList =
    db.get("reports").find({ id: reportId }).value()?.slides || []

  const setCurrentSlide = useSetRecoilState(currentSlideState)

  const [slidesList, setSlidesList] = useRecoilState<any[]>(slidesListState)

  const [deckInitialized, setDeckInitialized] = useState<boolean>(false)

  const [deckState, setDeckState] = useRecoilState<RevealStatic>(deckStateReveal)


  const [previousSlideListLength, setPreviousSlideListLength] = useState(slidesList.length);

  const setDeckCurrentSlideId = (deck: RevealStatic) => {
    const currentSlideElement = deck.getCurrentSlide()
    const currentSlideId = currentSlideElement?.getAttribute("data-slideid")

    setCurrentSlide(currentSlideId)
  }

  useEffect(() => {
    setSlidesList(initialSlidesList)
    setPreviousSlideListLength(initialSlidesList.length)
    const firstSlideId = initialSlidesList[0]?.id || ""
    if (firstSlideId) {
      setCurrentSlide(firstSlideId)
    }
  }, [])


  const hasRevealDOMNode = useCallback((node) => {
    if (node !== null && !deckInitialized) {
      const deck = new Reveal(node, {
        plugins: [Markdown],
        embedded: true,
      })
      setDeckState(deck)
      deck.initialize().then(() => {
        setDeckCurrentSlideId(deck)
        deck.on("slidechanged", () => {
          setDeckCurrentSlideId(deck)
        })
        setDeckInitialized(true)
      })
      deck.configure({
        pdfMaxPagesPerSlide: 1,
        pdfSeparateFragments: true,
        margin: 0,
        pdfPageHeightOffset: -1,
      })
    }
  }, [])

  useEffect(() => {
    if (deckState) {
      deckState.sync()
      setPreviousSlideListLength(slidesList.length)
      if (slidesList.length < previousSlideListLength) {

        const currentSlideIndex = deckState.getState()?.indexh

        deckState.slide(currentSlideIndex)

        deckState.sync()

        setDeckCurrentSlideId(deckState)
      }
    }
  }, [slidesList])

  return (
    <div style={{
        minHeight: '90vh',
        background: '#000'
      }}
      className="reveal-viewport"
    >
      <div ref={hasRevealDOMNode} className="reveal bg-gray-300">
        <div className="slides">
          {slidesList &&
            slidesList.map(({ id }) => {
              return <Slide slideId={id} key={id} />
            })}
        </div>
      </div>
    </div>
  )
}

export default RevealBase

```


Here's the code with the atoms:

```javascript
  export const currentSlideState = atom({
    key: "currentSlide",
    default: null,
  })

  export const slidesListState = atom({
    key: "slidesList",
    default: [],
  })

  export const deckStateReveal = atom({
    key: 'deckStateReveal',
    default: null
  })

```

**Comment by alinealvesvianna** [comment]
Hello @mondaychen , how are you?
Did you find out why this happens? can you give me a light how to proceed?

**Comment by mondaychen** [comment]
Hi @alinealvesvianna 

I'm not expert in reveal.js so I might not be the best person to help you.
It's pretty weird that you are managing your reveal.js app via React. To my knowledge, reveal.js takes the dom node (`. reveal` in your case), read its content as input and hijacked the rendering in the node. At the same time React might want to render the dom node too. Have you considered using libs like https://github.com/dennismorello/react-awesome-reveal ?

In your code, I think you are getting empty deck list result because the first time your component renders, `slidesList` is empty (default of `slidesListState`). Then it might not be re-rendered correctly, or maybe your `useEffect` callbacks are not correctly executed. You can put logs to check if they are fired.

In general I'd avoid setting a recoil atom in a `useEffect` of a component that depends on it.

I'm closing this because I don't believe it's an issue of Recoil.
