### ISSUE TITLE
Unit testing default atom values

### ISSUE THREAD

**Issue by sazzer** [facebookexperimental/Recoil#706]
Sorry if this is already answered somewhere, but I couldn't find it from looking.

I've got an atom which has a default value loaded via a promise - it actually makes an XHR call to the server to load data, but the data is such that it never needs refreshing.

This works great within the webapp itself, but I can't work out how to actually test things properly.

The atom itself is as follows:
```
interface ListProvidersResponse {
  entries: string[];
}

async function listProviders(): Promise<string[]> {
  const response = await request<ListProvidersResponse>("/authentication");
  const providers: string[] = response.body?.entries ?? [];

  return providers.sort();
}

export const providers = atom<string[]>({
  key: "providers",
  default: listProviders(),
});
```

And using this within a component - via `useRecoilValue()` - does exactly what I'd expect it to do.

However, trying to test this is just not working. I've got nock set up to handle the actual HTTP calls, and I can test it just fine *as long as I only test it once*. But if I add a second test then I get `Loadable expected promise, but in "hasValue" state` returned from that one instead:

```
describe("List Authentication Providers", () => {
  test("None returned", async () => {
    nock("http://example.com")
      .get("/authentication")
      .reply(200, {
        entries: []
      });

    const snapshot = snapshot_UNSTABLE();
    const [result] = await snapshot
      .getLoadable(waitForAll([sut.providers]))
      .promiseOrThrow(); // <-- This works.
    expect(result).toEqual([]);
  });

  test("Some returned", async () => {
    nock("http://example.com")
      .get("/authentication")
      .reply(200, {
        entries: ["google", "facebook", "twitter"]
      });

    const snapshot = snapshot_UNSTABLE();
    const [result] = await snapshot
      .getLoadable(waitForAll([sut.providers]))
      .promiseOrThrow(); // <-- This line fails.
    expect(result).toEqual(['facebook', 'google', 'twitter']);
  });
});
```

What am I missing here?

Cheers

**Comment by sazzer** [comment]
It might be that this exact case is better handled as a selector instead of an atom. It's not something that my code will ever change, and instead will be loaded from the server once and persist throughout the session thereon.

However, I have the exact same problems with selectors as with atoms. I can't find a way to indicate that the selector needs to be recalculated.

I've also today tried doing this with rendering inside a real component tree - via https://react-hooks-testing-library.com/ - and this hasn't made any difference, since it seems the atom/selector maintain their values within themselves instead of within the `RecoilRoot`.

**Comment by drarmstr** [comment]
As you have found, selectors can cache their values or be executed multiple times.  If you want to force re-evaluation, one option is using the [query refresh pattern](https://recoiljs.org/docs/guides/asynchronous-data-queries#query-refresh)

**Comment by sazzer** [comment]
The problem is that, for *normal* usage, I don't want the selector/atom to be re-evaluated. Ever.

The exact case I've got here is loading constant data from the API, so re-evaluating it at any other time will be wasteful.

The problem is in unit testing, when I want to have multiple unit tests that have different backend state - via nock - and so the selector/atom evaluates to the appropriate different value.

Effectively what I want is the ability to, for every unit test, indicate that all cached state should be reset. Then each unit test can stand in complete isolation as they should, and I can test all manner of different paths through them without any concern of an earlier test having any influence on things.

(And, in hindsight, that paragraph is a much better description of the actual need/want :) )

**Comment by drarmstr** [comment]
If this is for testing purposes, consider making a new selector with a unique key for each test.

**Comment by sazzer** [comment]
But then that's not testing the actual selector being used. Unless I'm
missing something?

**Comment by drarmstr** [comment]
I mean construct the actual selector for each test.  If the selector is built at the module-level, then you could reset the module between tests (e.g. `jest.resetModules()`) along with the entire Recoil runtime to ensure a clean slate for each test.

**Comment by sazzer** [comment]
`jest.resetModules()` wasn't something I knew about, so that's useful to know. However, it's not helping here because my multiple tests are in the same test file. You can see the example above.

As for constructing the selector/atom, doesn't that mean that it's not testing the actual production code? The benefit for production seems to be to use the same instance everywhere - so that you get the caching. But if you have to construct the instances differently for the tests then the tests are *not* representative.

**Comment by drarmstr** [comment]
You can reset modules used between tests in the same file.  Actually, check out `Recoil_TestingUtils.js` for an example of a hack that does this.

How is it not testing the code used in production?
