### ISSUE TITLE
Need to check state of Loadable from useRecoilValueLoadable

### ISSUE THREAD

**Issue by delucca** [facebookexperimental/Recoil#720]
Hi!

I'm trying to set a proper type for my custom interface, but getting a weird error.

I have the following interface:

```typescript
export interface ReorderCustomSortState {
  userID: User['id']
}
```

And the following configured hook:

```typescript
  const userID = useRecoilValueLoadable<User['id']>(userIDAtom)
```

The issue happens when I pass the `userID.contents` to an object with my custom interface, like the following:

```typescript
  const state: ReorderCustomSortState = {
    userID: userID.contents,
  }
```

When I do so, I receive the following error at my IDE:

```txt
Type 'string | LoadablePromise<string> | Error' is not assignable to type 'string'.
   Type 'LoadablePromise<string>' is not assignable to type 'string'. (lsp)
```

I've tried to import `LoadablePromise` from `recoil`, but it seems that it is not exported.

Anyone can help me?

**Comment by drarmstr** [comment]
[`useRecoilValueLoadable()`](https://recoiljs.org/docs/api-reference/core/useRecoilValueLoadable) returns a [`Loadable<>`](https://recoiljs.org/docs/api-reference/core/Loadable).  The `contents` of that `Loadable` may or may not contain the `string` value of the User ID depending on the state of the atom, it may also be an `Error` or a promise.  If you want to use React Suspense and Error Boundaries, then you can use the `useRecoilValue()` hook instead to just get the value and have errors or promises thrown.  If you want a `Loadable` to manually check the state, then you need to inspect the `state` property to determine if the `contents` contains the value or not, or you can use one of the convenience assessor methods such as `getValue()`, `valueMaybe()`, `valueOrThrow()`, or `toPromise()`.

**Comment by delucca** [comment]
@drarmstr actually, I would like to use `useRecoilValue()` directly instead, but my application uses NextJS and if I use `useRecoilValue` hook it simply crashes giving me the error that `ReactDOM doesn't support Suspense` (since it tries to server-side render it)

There are any workaround in NextJS?

**Comment by delucca** [comment]
I'm going to open a new issue regarding my above comment.
