### ISSUE TITLE
Atom effect onSet() causing infinite loop

### ISSUE THREAD

**Issue by bentron2000** [facebookexperimental/Recoil#724]
In the atom effects documentation - it is noted that the `onSet()` listener will not be called due to changes triggered from `setSelf()`

>   // The callback is not called due to changes from this effect's own setSelf().

I seem to be getting an infinite loop when using `setSelf()` - but maybe I'm missing something important.

I have created a contrived example on codesandbox which adds random numbers and illustrates the behaviour.

[![Edit Atom Effects Random Adder Causes Infinite Loop](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/atom-effects-random-adder-causes-infinite-loop-ov0lv?fontsize=14&hidenavigation=1&theme=dark)

Cheers

B

**Comment by justintoman** [comment]
You aren't supposed to call setSelf inside of an onSet handler. The value will be updated without you having to set it manually. I believe the intention of onSet handlers is to allow you to interact with other APIs based on the new value, such as remote storage or logging.

**Comment by bentron2000** [comment]
> You aren't supposed to call setSelf inside of an onSet handler. The value will be updated without you having to set it manually. I believe the intention of onSet handlers is to allow you to interact with other APIs based on the new value, such as remote storage or logging, not intercept the value and do something to it before it gets committed.

I was hoping to use it to intercept set calls and use `setSelf()` to eagerly set state while waiting for some long running async process to complete. 🤷🏼‍♂️

**Comment by justintoman** [comment]
That is what will happen if you kick off the long running async process from inside the onSet handler. The value will be eagerly set, and then some async thing will happen. 

Although, I'm not sure how error handling is supposed to work. If I update my atom with an invalid state and my server responds with a 400 (or the service is down or messed up and I get a 500), how am I supposed to revert the change back to the previous valid value?

**Comment by justintoman** [comment]
Okay, now I'm not so sure I was right about "you aren't supposed to call setSelf inside of an onSet handler". It seems like you should be able to. Maybe calling setSelf from inside an onSet handler causes another set cycle because the value is different after onSet but before the entire set batch is finished? Or something? I don't know. Maybe it would work asynchronously?

Would this work?

```
const state = atom({
  key: 'whatever',
  default: 0,
  effects_UNSTABLE: [
    ({onSet, setSelf}) => {
      onSet(async (newValue, oldValue) => {
        if(newValue === oldValue) {
          return;
        }

        try {
          await remoteStorage.post(newValue);
        } catch(e) {
          selfSelf(oldValue); // maybe this will work because it's not synchronous?
        }
      });
    }
  ]
});
```

**Comment by BenjaBobs** [comment]
You could use a recoil callback to achieve this, by setting the temporary value in the beginning, then doing the long running task and setting the result when done.

**Comment by bentron2000** [comment]
> Okay, now I'm not so sure I was right about "you aren't supposed to call setSelf inside of an onSet handler". It seems like you should be able to. Maybe calling setSelf from inside an onSet handler causes another set cycle because the value is different after onSet but before the entire set batch is finished? Or something? I don't know. Maybe it would work asynchronously?
> 
> Would this work?
> 
> ```
> const state = atom({
>   key: 'whatever',
>   default: 0,
>   effects_UNSTABLE: [
>     ({onSet, setSelf}) => {
>       onSet(async (newValue, oldValue) => {
>         if(newValue === oldValue) {
>           return;
>         }
> 
>         try {
>           await remoteStorage.post(newValue);
>         } catch(e) {
>           selfSelf(oldValue); // maybe this will work because it's not synchronous?
>         }
>       });
>     }
>   ]
> });
> ```

Yep - that's precisely how I've handled this for my current work around. But the wording of the docs does seem to suggest that it should not call the listener. hmmm

**Comment by drarmstr** [comment]
Atom effects aren't intended to act as middleware.  They allow you to observe sets, but not intercept and modify a value before it is being set.  So, if you observe a set an initiate a new set it can cause a loop.  Atom sets are queued, so you can't guarantee if the effect observation handlers are called before or after other components see the new value, though we reserve the ability to make guarantees and maybe allow this in the future.  

If you want a temporary value while something is pending you could use `useRecoilCallback()`:

```jsx
const startAThink = useRecoilCallback(({set}) => async () => {
  set(myAtom, pendingValue);
  const newValue = await fetchLongRunningThing();
  set(myAtom, newValue);
});
```

or maybe wrap with a selector

```jsx
const wrappedState = selector({
  key: 'MyWrappedState',
  get: ({get}) => {
    const longRunningLoadable = get(noWait(longRunningSelector));
    return longRunningLoadable.state === 'hasValue'
      ? longRunningLoadable.contents
      : pendingValue;
  },
});
```
