### ISSUE TITLE
Atom effect (setSelf) "trigger" before default value

### ISSUE THREAD

**Issue by Bruno-Tavares-Bose** [facebookexperimental/Recoil#728]
I'm getting a strange behavior, if I have a synchronous effect setting a value, I get the default value instead of the setted by the effect.

Consider this example:
```javascript
const potatoAtom = atom({
  key: 'potato',
  default: false,
  effects_UNSTABLE: [({ setSelf }) => {
    setSelf(true);
  }]
});

function Component() {
  const potato = useRecoilValue(potatoAtom);

  console.log(potato); // false instead of true :(
}
```

**Comment by ecreeth** [comment]
I can't reproduce your example. The expected result is `true` -->[result code here](https://codesandbox.io/s/amazing-sun-6800g?file=/src/App.js)

**Comment by Bruno-Tavares-Bose** [comment]
Thanks for the testing, we will check if we are doing any set.

(if we do a reset, would the value be set to default or would the effect run again?)

**Comment by drarmstr** [comment]
Calling `setSelf()` in an effect will initialize the atom state to a value.  However, it does not change the default.  So, if you reset an atom then it will revert to the default value instead of the initialized value.  This is important to allow state persistence mechanisms to initialize to some saved value while also retaining default value behaviour.  

Effects are only run when an atom is initialized.  Note that atoms may be garbage collected and then re-initialized, which would cause the effect to re-run.  However, that is not coupled to reseting the value to the default.

**Comment by idubrov** [comment]
Hmm, I think, we are hitting the same issue -- calling `setSelf` immediately in the effect (on `get` trigger) does not set the value.

We have plenty of various states, and this issue only manifests when we set some other, unrelated, state.

Say, we have state "A" which has effect (for simplicity, let's assume it's this potato atom from above -- I removed all our logic in effect, making it to call `setSelf` immediately and was able to reproduce the issue). State "B" is some unrelated state (maybe, very loosely related, like some piece of code would look at state "B" and try to read atomFamily "A" with some key from the state "B").  

Roughly, we have the following two scenarios:

## Scenario 1

1. User is on the main page, clicking some card.
2. This triggers setting some unrelated state B. Also, this triggers navigation.
3. In some other place, component reacts to navigation and tries to read state A.
4. State A effect is called, which immediately calls `setSelf(<some value>)`.
5. State A appears as empty (bug)! 

## Scenario 2

1. User navigates directly to page from step 3.
2. Component reacts to navigation and tries to read state A. 
4. State A effect is called, which immediately calls `setSelf(<some value>)`.
5. State A appears with correct value (no bug).

What is interesting, is I delayed `setSelf` via `window.requestAnimationFrame`, and it fixed the issue.  An equivalent code would be:

```javascript
const potatoAtom = atom({
  key: 'potato',
  default: false,
  effects_UNSTABLE: [({ setSelf }) => {
    // This fixed it!
    window.requestAnimationFrame(() => setSelf(true));
  }]
});

function Component() {
  const potato = useRecoilValue(potatoAtom);

  console.log(potato); // false instead of true :(
}
```

@Bruno-Tavares-Bose, if you still have this issue, could you try doing `window.requestAnimationFrame` and see if it "fixes" it?

**Comment by drarmstr** [comment]
Calling `setSelf()` from `window.requestAnimationFrame()` would be calling it async and later changing the atom value from the initial default, which is a different action than initializing the initial atom value for the first render.  It's important we can set the initial value for SSR and so we can load an initial state without flicker.

I'd be interested if you could get a reproducer for the scenario where synchronous `setSelf()` doesn't initialize the atom.  It sounds like there may be more going on with page navigation and I wonder if that is causing some interactions...

**Comment by drarmstr** [comment]
Duplicate of #774
