### ISSUE TITLE
Read/Write outside of component

### ISSUE THREAD

**Issue by JesperLekland** [facebookexperimental/Recoil#73]
Hi, first of all big kodus on this library, it looks amazing. 

I couldn't find anything in the docs regarding reading/writing state outside of a component (the Redux equivalent would be `Store.dispatch(action)`). Is this something that is undocumented/in the pipeline or something that will never be possible?

**Comment by davidmccabe** [comment]
It's not currently possible. Recoil state is not global but exists within a particular React context, and there is also no "current" state, just the most recently committed state from the point of view of a particular component.

If you tell me what you actually need to do then I can suggest how to do it.

**Comment by atulmy** [comment]
I was wondering same. My use case was more around the user login state from localStorage. I ended up doing this:

**Redux** (inside `/src/index.js`):
```javascript
// User Authentication
const token = window.localStorage.getItem('token')
if (token && token !== 'undefined' && token !== '') {
  const user = JSON.parse(window.localStorage.getItem('user'))
  if (user) {
    loginSetUserLocalStorage(token, user)
    store.dispatch(loginSetUser(token, user))
  }
}
```

**Recoil** (inside `/src/user/api/state.js`):
```javascript
const userAuthDefault = {
  isAuthenticated: false,
  user: null
}

// on page load
// try to get user token and details from localStorage
const token = window.localStorage.getItem('token')
if (token && token !== 'undefined' && token !== '') {
  const user = JSON.parse(window.localStorage.getItem('user'))

  if (user) {
    userAuthDefault.isAuthenticated = true
    userAuthDefault.user = user
  }
}

// auth
export const userAuth = atom({
  key: 'userAuth',
  default: userAuthDefault
})
```

Hope this will help for some use cases.

**Comment by JesperLekland** [comment]
We have a pretty big brownfield app, meaning that we would need to gradually migrate from our current solution of Redux (which have the feature in question, and which we use to a certain extent). We also have a few "external" modules that are agnostic to the component context but still have access to the state, e.g an API module, a deep-linking module etc.

**Comment by keene-dalveytech** [comment]
It looks like an ugly way to write it
