### ISSUE TITLE
I can mutate atom state in selector get directly, but not in set

### ISSUE THREAD

**Issue by Royfangs** [facebookexperimental/Recoil#730]
Hello, I recently want to test few things in order to know the API behavior and I found that I can change atom state directly in selector get, but not in set.

For Example:
```
const userState = atom({
  key: "userState",
  default: {
    name: "john",
    address: {
      road: "103 road",
      nested: {
        value: "someNestedValue"
      }
    }
  }
});

export const userSelector = selector({
  key: "userSelector",
  get: ({ get }) => {
    const user = get(userState);
    console.log("user.name", Object.getOwnPropertyDescriptor(user, "name"));
    // value: "john"
    // writable: true
    // enumerable: true
    // configurable: true
    console.log(
      "user.address",
      Object.getOwnPropertyDescriptor(user, "address")
    );
    // value: Object
    // writable: true
    // enumerable: true
    // configurable: true

    user.address.road = "301 road";
    // the state is mutated

    console.log("get user", user);

    return user;
  },
  set: ({ set, get }) => {
    const user = get(userState);

    console.log(
      "set user.address",
      Object.getOwnPropertyDescriptor(user, "address")
    );
    // value: Object
    // writable: false
    // enumerable: true
    // configurable: false
    user.address.road = "narrow road";

    console.log("set user", user);

    return set(userState, user);
  }
});

```

Here is the example codesandbox: [https://codesandbox.io/s/bold-taussig-o9vf9?file=/src/App.js](https://codesandbox.io/s/bold-taussig-o9vf9?file=/src/App.js)

That's very interesting so I dig in more. I found that's because the writable attribute is set to false in set, but not in get.
Is that expected and desirable behavior? If so, why don't you also set the writable attribute to false for the state in get?
Am I missing something? I'm curios about it.

**Comment by mondaychen** [comment]
@drarmstr this is unwanted operation, but shall we freeze the value during `get` too?

**Comment by drarmstr** [comment]
That is curious.. Values should be frozen in both cases (in dev mode) since only immutable objects should be stored in atom state (`dangerouslyAllowMutability` can be used to disable this).  Atoms attempt to freeze their values when written, so it shouldn't matter if we're getting their value from a selector `set` or getting the value from a selector `get`.  @csantos42 this may be something to look at with the new selector implementation.

**Comment by likern** [comment]
I also experienced that freeze doesn't work. If I'm correct in `DEV` mode even in `set` we can't mutate state, it should be freezed. Am I correct?

**Comment by drarmstr** [comment]
Yes it should always be frozen.  Freezing is just to help detect user bugs, though.  There shouldn't be any actual functionality broken if values aren't getting frozen.

Note that values may also not get frozen even in dev mode for certain types of objects such as a `Window`, `ArrayBufferView`, &c.

**Comment by likern** [comment]
> Yes it should always be frozen. Freezing is just to help detect user bugs, though. There shouldn't be any actual functionality broken if values aren't getting frozen.
> 
> Note that values may also not get frozen even in dev mode for certain types of objects such as a `Window`, `ArrayBufferView`, &c.

If object (array in my case) is not frozen and we directly mutate state Recoil will not rerender because reference hasn't changed.

**Comment by drarmstr** [comment]
> > Yes it should always be frozen. Freezing is just to help detect user bugs, though. There shouldn't be any actual functionality broken if values aren't getting frozen.
> > Note that values may also not get frozen even in dev mode for certain types of objects such as a `Window`, `ArrayBufferView`, &c.
> 
> If object (array in my case) is not frozen and we directly mutate state Recoil will not rerender because reference hasn't changed.

Yup! Recoil just freezes values in dev mode so that an error is thrown to help detect this situation for users.
