### ISSUE TITLE
Single atom for updating a large list

### ISSUE THREAD

**Issue by tonyabracadabra** [facebookexperimental/Recoil#735]
Is that the best practice? 

I've seen example like Todolist on the website, it writes

```ts
const todoListState = atom({
  key: 'todoListState',
  default: [],
});

function TodoItem({item}) {
  const [todoList, setTodoList] = useRecoilState(todoListState);
  const index = todoList.findIndex((listItem) => listItem === item);

  const editItemText = ({target: {value}}) => {
    const newList = replaceItemAtIndex(todoList, index, {
      ...item,
      text: value,
    });

    setTodoList(newList);
  };

  const toggleItemCompletion = () => {
    const newList = replaceItemAtIndex(todoList, index, {
      ...item,
      isComplete: !item.isComplete,
    });

    setTodoList(newList);
  };

  const deleteItem = () => {
    const newList = removeItemAtIndex(todoList, index);

    setTodoList(newList);
  };

  return (
    <div>
      <input type="text" value={item.text} onChange={editItemText} />
      <input
        type="checkbox"
        checked={item.isComplete}
        onChange={toggleItemCompletion}
      />
      <button onClick={deleteItem}>X</button>
    </div>
  );
}

function replaceItemAtIndex(arr, index, newValue) {
  return [...arr.slice(0, index), newValue, ...arr.slice(index + 1)];
}

function removeItemAtIndex(arr, index) {
  return [...arr.slice(0, index), ...arr.slice(index + 1)];
}

function TodoList() {
  const todoList = useRecoilValue(todoListState);

  return (
    <>
      {/* <TodoListStats /> */}
      {/* <TodoListFilters /> */}
      <TodoItemCreator />

      {todoList.map((todoItem) => (
        <TodoItem key={todoItem.id} item={todoItem} />
      ))}
    </>
  );
}
```

This makes sense to me, however how is the performance of it if I actually need to create a whole new list every time one element is changed within the todo list. I am having a similar application where I have to update the cells of a spreadsheet, which does not seem so optimal if I were taking this approach. 

Is there a better way for solving this problem or how can we improve upon that?  

I have something in my mind that is using `atomFamily` and I wrote it as 

```ts
type CellValueQuery = {
  workspaceId: string, 
  tableId: string, 
  recordId: string, 
  fieldId: string
}

export const cellValueStates = atomFamily<CellValue, CellValueQuery>({
  key: 'cell-value-states',
  default: null,
});

function Cell({cellValueQuery}) {
  const [cellValue, setCellValue] = useRecoilState(cellValueStates(cellValueQuery));

  const editItemText = ({target: {value}}) => {
    setCellValue(value);
  };

  return (
    <div>
      <input type="text" value={item.text} onChange={editItemText} />
      <input
        type="checkbox"
        checked={item.isComplete}
        onChange={toggleItemCompletion}
      />
      <button onClick={deleteItem}>X</button>
    </div>
  );
}
```

Am I doing the right thing here?

**Comment by drarmstr** [comment]
Yes, it is common practice to break up large state like this with an `atomFamily()`, particularly when you may only want to re-render `<Cell>`'s whose values have changed.  The initial tutorial only covered the core `atom()` API, but was supposed to get an additional section including families.

**Comment by tonyabracadabra** [comment]
> Yes, it is common practice to break up large state like this with an `atomFamily()`, particularly when you may only want to re-render `<Cell>`'s whose values have changed. The initial tutorial only covered the core `atom()` API, but was supposed to get an additional section including families.

Thanks for getting back to me! I am just curious what is the reason that `atomFamily` does not support getting all the keys from it? Is it going to be improved in the future?

**Comment by postbird** [comment]
Same doubts to me. When I create a new TodoItem to the TodoList, is there any way to prevent re-render the whole list?

example:
```javascript
const todoList = atom({
	key: 'todo_list',
	default: [],
});
```
when I create a new TodoItem:
```javascript
const [list, setList] = useRecoilState(todoList);

const handleClick = () => {
	const todo = { id: +new Date() };
	setList([...list, todo]);
};
```
It seems  to be no way to avoid re-rendering the entire list in this case.

Is there any best practice?

@drarmstr

**Comment by harjis** [comment]
I struggled a bit with this issue too. I ended up splitting the atoms this way:
```ts
import { atom, atomFamily, selectorFamily } from "recoil";

import { Todo } from "../types";

export const todoIdsState = atom<number[]>({
  key: "todoIdsState",
  default: [],
});

const tempTodo = atomFamily<Todo | null, number>({
  key: "todo",
  default: null,
});
export const todoState = atomFamily<Todo, number>({
  key: "todoState",
  default: selectorFamily<Todo, number>({
    key: "todoState/default",
    get: (todoId) => ({ get }) => {
      const todo = get(tempTodo(todoId));
      if (todo === null) {
        throw new Error(`Fatal error: Todo with id ${todoId} was not found`);
      }
      return todo;
    },
    set: (todoId) => ({ set }, newTodo) => set(tempTodo(todoId), newTodo),
  }),
});

export const todoListFilterState = atom({
  key: "todoListFilterState",
  default: "Show All",
});
```
The atoms are used like this:

```ts
//useTodos.ts
import React from "react";
import { useRecoilCallback, useRecoilState, useRecoilValue } from "recoil";

import { getId, getTodos } from "../../../api/todos";
import { todoIdsState, todoState } from "../atoms";
import { filteredTodoIdsState } from "../selectors";

export const useTodos = () => {
  const [todoIds, setTodoIds] = useRecoilState(todoIdsState);

  const loadTodos = useRecoilCallback(
    ({ set }) => async () => {
      const fetchedTodos = await getTodos();
      const ids = [];
      for (const todo of fetchedTodos) {
        ids.push(todo.id);
        set(todoState(todo.id), todo);
      }
      set(todoIdsState, ids);
    },
    []
  );
  React.useEffect(() => {
    loadTodos();
  }, [loadTodos]);

  const addTodo = useRecoilCallback(
    ({ set }) => (text: string) => {
      const id = getId();
      setTodoIds((prevIds) => prevIds.concat(id));
      set(todoState(id), {
        id,
        text,
        isComplete: false,
      });
    },
    []
  );

  const removeTodo = (id: number) => {
    setTodoIds(todoIds.filter((todoId) => todoId !== id));
  };

  const filteredTodoIds = useRecoilValue(filteredTodoIdsState);

  return {
    filteredTodoIds,
    addTodo,
    removeTodo,
  };
};
```

```ts
// useTodo.ts
import { ChangeEvent } from "react";
import { useRecoilState } from "recoil";

import { todoState } from "../atoms";

export const useTodo = (todoId: number) => {
  const [todo, setTodo] = useRecoilState(todoState(todoId));

  const editItemText = (event: ChangeEvent<HTMLInputElement>) => {
    const value = event.currentTarget.value;
    setTodo((todo) => ({
      ...todo,
      text: value,
    }));
  };

  const toggleItemCompletion = () => {
    setTodo((todo) => ({ ...todo, isComplete: !todo.isComplete }));
  };

  return {
    todo,
    editItemText,
    toggleItemCompletion,
  };
};
```

The reason why `todoState` uses selectorFamily is that I wanted to fail hard in cases where invalid primary key was supplied. I guess todoState could also as follows:
```ts
export const todoState = atomFamily<Todo, number>({
  key: "todoState",
  default: {} as Todo
});
```



Entire project can be found here: https://github.com/harjis/react-recoil

Let me know if there is a better way to achieve similar behavior.

**Comment by postbird** [comment]
> I struggled a bit with this issue too. I ended up splitting the atoms this way:
> 
> ```ts
> import { atom, atomFamily, selectorFamily } from "recoil";
> 
> import { Todo } from "../types";
> 
> export const todoIdsState = atom<number[]>({
>   key: "todoIdsState",
>   default: [],
> });
> 
> const tempTodo = atomFamily<Todo | null, number>({
>   key: "todo",
>   default: null,
> });
> export const todoState = atomFamily<Todo, number>({
>   key: "todoState",
>   default: selectorFamily<Todo, number>({
>     key: "todoState/default",
>     get: (todoId) => ({ get }) => {
>       const todo = get(tempTodo(todoId));
>       if (todo === null) {
>         throw new Error(`Fatal error: Todo with id ${todoId} was not found`);
>       }
>       return todo;
>     },
>     set: (todoId) => ({ set }, newTodo) => set(tempTodo(todoId), newTodo),
>   }),
> });
> 
> export const todoListFilterState = atom({
>   key: "todoListFilterState",
>   default: "Show All",
> });
> ```
> 
> The atoms are used like this:
> 
> ```ts
> //useTodos.ts
> import React from "react";
> import { useRecoilCallback, useRecoilState, useRecoilValue } from "recoil";
> 
> import { getId, getTodos } from "../../../api/todos";
> import { todoIdsState, todoState } from "../atoms";
> import { filteredTodoIdsState } from "../selectors";
> 
> export const useTodos = () => {
>   const [todoIds, setTodoIds] = useRecoilState(todoIdsState);
> 
>   const loadTodos = useRecoilCallback(
>     ({ set }) => async () => {
>       const fetchedTodos = await getTodos();
>       const ids = [];
>       for (const todo of fetchedTodos) {
>         ids.push(todo.id);
>         set(todoState(todo.id), todo);
>       }
>       set(todoIdsState, ids);
>     },
>     []
>   );
>   React.useEffect(() => {
>     loadTodos();
>   }, [loadTodos]);
> 
>   const addTodo = useRecoilCallback(
>     ({ set }) => (text: string) => {
>       const id = getId();
>       setTodoIds((prevIds) => prevIds.concat(id));
>       set(todoState(id), {
>         id,
>         text,
>         isComplete: false,
>       });
>     },
>     []
>   );
> 
>   const removeTodo = (id: number) => {
>     setTodoIds(todoIds.filter((todoId) => todoId !== id));
>   };
> 
>   const filteredTodoIds = useRecoilValue(filteredTodoIdsState);
> 
>   return {
>     filteredTodoIds,
>     addTodo,
>     removeTodo,
>   };
> };
> ```
> 
> ```ts
> // useTodo.ts
> import { ChangeEvent } from "react";
> import { useRecoilState } from "recoil";
> 
> import { todoState } from "../atoms";
> 
> export const useTodo = (todoId: number) => {
>   const [todo, setTodo] = useRecoilState(todoState(todoId));
> 
>   const editItemText = (event: ChangeEvent<HTMLInputElement>) => {
>     const value = event.currentTarget.value;
>     setTodo((todo) => ({
>       ...todo,
>       text: value,
>     }));
>   };
> 
>   const toggleItemCompletion = () => {
>     setTodo((todo) => ({ ...todo, isComplete: !todo.isComplete }));
>   };
> 
>   return {
>     todo,
>     editItemText,
>     toggleItemCompletion,
>   };
> };
> ```
> 
> The reason why `todoState` uses selectorFamily is that I wanted to fail hard in cases where invalid primary key was supplied. I guess todoState could also as follows:
> 
> ```ts
> export const todoState = atomFamily<Todo, number>({
>   key: "todoState",
>   default: {} as Todo
> });
> ```
> 
> Entire project can be found here: https://github.com/harjis/react-recoil
> 
> Let me know if there is a better way to achieve similar behavior.

I have a question about your demo, if we use `filteredTodoIdsState` ( such as [https://github.com/harjis/react-recoil/blob/main/src/features/Todos/selectors/index.ts](https://github.com/harjis/react-recoil/blob/main/src/features/Todos/selectors/index.ts)) to filter the todo ids, each TodoItem component will be re-rendered when we only change one Todo's info(such as todo's completed status)

how could I design the atom or selector to prevent this problem?

**Comment by harjis** [comment]
@postbird Doesn't it already work like that? Here is a screenshot on what gets rendered when a todo is marked as complete:

![Screenshot 2020-12-30 at 8 48 33](https://user-images.githubusercontent.com/2409276/103335286-3675f680-4a7d-11eb-9549-de57e2b9eced.png)

If you change `filteredTodoIdsState` so that it depends on a complete todo then all todos get re-rendered when one changes:
```ts
export const todosQuery = atom<Todo[]>({
  key: "todosQuery",
  default: selector({
    key: "todosQuery/default",
    get: ({ get }) => get(todoIdsState).map((todoId) => get(todoState(todoId))),
  }),
});

export const filteredTodosState = selector({
  key: "filteredTodoListState",
  get: ({ get }) => {
    const filter = get(todoListFilterState);
    const todos = get(todosQuery);

    switch (filter) {
      case "Show Completed":
        return todos.filter((todo) => todo.isComplete);
      case "Show Uncompleted":
        return todos.filter((todo) => !todo.isComplete);
      default:
        return todos;
    }
  },
});
```
![Screenshot 2020-12-30 at 8 56 09](https://user-images.githubusercontent.com/2409276/103335478-b308d500-4a7d-11eb-9852-7b4926c7b034.png)

**Comment by harjis** [comment]
Having a tempTodo actually brings no benefits: 
```ts
const tempTodo = atomFamily<Todo | null, number>({
  key: "todo",
  default: null,
});
export const todoState = atomFamily<Todo, number>({
  key: "todoState",
  default: selectorFamily<Todo, number>({
    key: "todoState/default",
    get: (todoId) => ({ get }) => {
      const todo = get(tempTodo(todoId));
      if (todo === null) {
        throw new Error(`Fatal error: Todo with id ${todoId} was not found`);
      }
      return todo;
    },
    set: (todoId) => ({ set }, newTodo) => set(tempTodo(todoId), newTodo),
  }),
});
```
`todoState` get and set methods are never called. In terms of typesafety this seems to be the equivalent:

```ts
export const todoState = atomFamily<Todo, number>({
  key: "todo",
  default: {} as Todo,
});
```

I found this quite confusing

**Comment by postbird** [comment]
> @postbird Doesn't it already work like that? Here is a screenshot on what gets rendered when a todo is marked as complete:
> 
> ![Screenshot 2020-12-30 at 8 48 33](https://user-images.githubusercontent.com/2409276/103335286-3675f680-4a7d-11eb-9549-de57e2b9eced.png)
> 
> If you change `filteredTodoIdsState` so that it depends on a whole todo object then all todos get re-rendered when one changes:
> 
> ```ts
> export const todosQuery = atom<Todo[]>({
>   key: "todosQuery",
>   default: selector({
>     key: "todosQuery/default",
>     get: ({ get }) => get(todoIdsState).map((todoId) => get(todoState(todoId))),
>   }),
> });
> 
> export const filteredTodosState = selector({
>   key: "filteredTodoListState",
>   get: ({ get }) => {
>     const filter = get(todoListFilterState);
>     const todos = get(todosQuery);
> 
>     switch (filter) {
>       case "Show Completed":
>         return todos.filter((todo) => todo.isComplete);
>       case "Show Uncompleted":
>         return todos.filter((todo) => !todo.isComplete);
>       default:
>         return todos;
>     }
>   },
> });
> ```
> 
> ![Screenshot 2020-12-30 at 8 56 09](https://user-images.githubusercontent.com/2409276/103335478-b308d500-4a7d-11eb-9852-7b4926c7b034.png)

thanks so much!
my fault.
my code about selector: 
> it will return a new list each time..
```jsx
return todoIds.filter(id => {
	const todo = get(todoIdState(id));
	console.log('todo', todo);
	switch (filter) {
		case TODO_FILTER.ACTIVE:
			return !todo.completed;
		case TODO_FILTER.COMPLETED:
			return todo.completed;
		default:
			return true;
	}
});
```

**Comment by postbird** [comment]
> @postbird Doesn't it already work like that? Here is a screenshot on what gets rendered when a todo is marked as complete:
> 
> ![Screenshot 2020-12-30 at 8 48 33](https://user-images.githubusercontent.com/2409276/103335286-3675f680-4a7d-11eb-9549-de57e2b9eced.png)
> 
> If you change `filteredTodoIdsState` so that it depends on a whole todo object then all todos get re-rendered when one changes:
> 
> ```ts
> export const todosQuery = atom<Todo[]>({
>   key: "todosQuery",
>   default: selector({
>     key: "todosQuery/default",
>     get: ({ get }) => get(todoIdsState).map((todoId) => get(todoState(todoId))),
>   }),
> });
> 
> export const filteredTodosState = selector({
>   key: "filteredTodoListState",
>   get: ({ get }) => {
>     const filter = get(todoListFilterState);
>     const todos = get(todosQuery);
> 
>     switch (filter) {
>       case "Show Completed":
>         return todos.filter((todo) => todo.isComplete);
>       case "Show Uncompleted":
>         return todos.filter((todo) => !todo.isComplete);
>       default:
>         return todos;
>     }
>   },
> });
> ```
> 
> ![Screenshot 2020-12-30 at 8 56 09](https://user-images.githubusercontent.com/2409276/103335478-b308d500-4a7d-11eb-9852-7b4926c7b034.png)

A problem with your demo project:
if I changed the filter state, such as `Uncompleted`, then modify any TodoItem, the whole list will be re-rendered.

**Comment by harjis** [comment]
I see. I suppose it works this way when having a filter because those call `.filter()` on an array which returns always a new array. No idea if this can be avoided somehow

**Comment by BenjaBobs** [comment]
> I see. I suppose it works this way when having a filter because those call `.filter()` on an array which returns always a new array. No idea if this can be avoided somehow

You could re-use an array you save in some static place, outside of those scopes.
This also means that you have to manually tell the components that you want to update, that they have to update.
I'm not sure this is a smart route to go down.

```javascript
// This exists somewhere where it doesn't get replaced with a new array or re-instantiated
const filterBuffer = [];

function applyFilter(todos, predicate) {
	// clear the array first
	filterBuffer.splice(0, filterBuffer.length);

	// fill it with the filtered data from todos
	filterBuffer.push(...todos.filter(predicate));

	return filterBuffer;
}
```

**Comment by harjis** [comment]
Yeah so with memoize-one it would some something like this (quick&dirty):
```typescript
import { selector } from "recoil";

import { todoIdsState, todoListFilterState, todoState } from "../atoms";
import memoizeOne from "memoize-one";

const getCompletedTodoIds = (todoIds: number[], get: any): number[] =>
  todoIds.filter((todoId) => get(todoState(todoId)).isComplete);
const memoizedGetCompletedTodoIds = memoizeOne(
  getCompletedTodoIds,
  (newArgs, lastArgs) => newArgs[0].length === lastArgs[0].length
);

export const filteredTodoIdsState = selector({
  key: "filteredTodoListState",
  get: ({ get }) => {
    const filter = get(todoListFilterState);
    const todoIds = get(todoIdsState);

    switch (filter) {
      case "Show Completed":
        return memoizedGetCompletedTodoIds(todoIds, get);
      case "Show Uncompleted":
        return todoIds.filter((todoId) => !get(todoState(todoId)).isComplete);
      default:
        return todoIds;
    }
  },
});
```

I also found [this](https://github.com/facebookexperimental/Recoil/pull/749). Not sure if it should help with stuff like this

**Comment by postbird** [comment]
> Yeah so with memoize-one it would some something like this (quick&dirty):
> 
> ```ts
> import { selector } from "recoil";
> 
> import { todoIdsState, todoListFilterState, todoState } from "../atoms";
> import memoizeOne from "memoize-one";
> 
> const getCompletedTodoIds = (todoIds: number[], get: any): number[] =>
>   todoIds.filter((todoId) => get(todoState(todoId)).isComplete);
> const memoizedGetCompletedTodoIds = memoizeOne(
>   getCompletedTodoIds,
>   (newArgs, lastArgs) => newArgs[0].length === lastArgs[0].length
> );
> 
> export const filteredTodoIdsState = selector({
>   key: "filteredTodoListState",
>   get: ({ get }) => {
>     const filter = get(todoListFilterState);
>     const todoIds = get(todoIdsState);
> 
>     switch (filter) {
>       case "Show Completed":
>         return memoizedGetCompletedTodoIds(todoIds, get);
>       case "Show Uncompleted":
>         return todoIds.filter((todoId) => !get(todoState(todoId)).isComplete);
>       default:
>         return todoIds;
>     }
>   },
> });
> ```
> 
> I also found [this](https://github.com/facebookexperimental/Recoil/pull/749). Not sure if it should help with stuff like this

yeah, it is useful. but the feature is not enabled yet. see: #845 

I build a local bundle of recoil, enable the feature with `gkx.setPass('recoil_suppress_rerender_in_callback');`

then the selector return the immutable value such as:

```javascript
let immutableStats = ImmutableMap({ all: 0, active: 0, completed: 0 });

const todosState = atom({
	key: uuidv4(),
	default: [],
});

const todoStats = selector({
	key: uuidv4(),
	get: ({ get }) => {
		const todos = get(todosState);
		const active = todos.filter(todo => !todo.completed).length;
		if (active === immutableStats.get('active')) {
			return immutableStats;
		}
                // @ugly
		immutableStats = immutableStats.set('all', todos.length);
		immutableStats = immutableStats.set('active', active);
		immutableStats = immutableStats.set('completed', todos.length - active);
		return immutableStats;
	},
});
```
it works.

I am looking forward to this feature, and thanks to @drarmstr
