### ISSUE TITLE
returning null after setting value

### ISSUE THREAD

**Issue by WhoAdarshPandya** [facebookexperimental/Recoil#736]
Hey , thank you for creating this awesome library, i was trying out recoil and encountered a problem.

in **App Component** 
```
function App (){
      const [userData,setUserData] = useRecoilState(userAtom);
      useEffect(()=>{
           setUserData({name:"xyz",age:15});
           console.log(userData); // returns null 
      },[])      
}
```
**although if i access same value in different component it returns expected value**

please help
Thank You :)

**Comment by drarmstr** [comment]
Setting the value of an atom doesn't change it immediately. It actually queues the atom to update to the new value and schedules subscribed to re-render. In fact, with React Concurrent Mode it is possible to be rendering components that have different perspectives of the current value of an atom at the same time. 

If you would like to see the "current" value of an atom, you could use the updater form when setting an atom by passing a function as the new value. This function is provided the current value as a parameter. So, if you used this set after the first set, then the updater callback would get the new value.

**Comment by WhoAdarshPandya** [comment]
sorry mistake from my end, had to add userData in useEffect(()=>{},[userData]);

Thank you 👍 :)
