### ISSUE TITLE
[React-native] Recoil state and TextInput onChangeText

### ISSUE THREAD

**Issue by Svarto** [facebookexperimental/Recoil#737]
Hi,

I have run into a issue with Recoil (love the library by the way) that if I try to use a useRecoilState Atom with a Textinput and update it everytime onChangeText fires - it seems like the update speed is not fast enough as if a user types at a slightly faster rate the cursor falls "behind" and new characters entered are placed before the previous ones.

Currently my work around is to use local state (useState hook) in the component, and then onEndEditing updates the Recoil atom. But I was just wondering if this is intended behaviour (that it shouldn't be used with TextInput onChangeText) or if there is something I should do differently?

Code snippet:
```
export function TestRecoilTextComponent() {
  const [recoilState, setRecoilState] = useRecoilState(exampleAtom);
  return (
    <View>
      <TextInput
        value={recoilState}
        onChangeText={(text) => setRecoilState(text)}
      />
    </View>
  );
}
```

Versions:
    "recoil": "^0.1.2",
    "expo": "^39.0.3",

**Comment by ecreeth** [comment]
Try to use `defaultValue` instead of `value` in the `TextInput`

**Comment by Svarto** [comment]
@ecreeth thanks! So basically not making it a controlled component, that is super. thanks for the tip!

**Comment by drarmstr** [comment]
Note that using `defaultValue` instead of `value` means that the text input won't update if the Recoil state externally changes.  React does some magic when applying React state to controlled text inputs, so you could also use an abstraction to map the Recoil state to React state to use for a text input.

**Comment by drarmstr** [comment]
Duplicate of #488
