### ISSUE TITLE
Expected atom effect "onSet" to return default value when performing a reset

### ISSUE THREAD

**Issue by jleroy-dev** [facebookexperimental/Recoil#738]
Hi there,

I am currently using `effects_UNSTABLE` feature.
When listening to `onSet` after performing a `reset` operation on the atom, the returned value is always an object.
I was expecting to be sent the `default` value that I did set for the atom.

Is it working as expected? Is there something I didn't understand correctly?

Repro:
https://codesandbox.io/s/funny-frog-xp3m8?file=/src/App.js

From this example:
https://recoiljs.org/docs/guides/atom-effects#logging-example

Thank you by advance, and thank you for your awesome work!

**Comment by BenjaBobs** [comment]
It seems to only happen in the `OnSet` hook which leaves me to believe that the `DefaultValue` is an object set as value temporarily to denote that the object should get the default value re-set.
https://codesandbox.io/s/goofy-water-tyfph?file=/src/App.js

**Comment by drarmstr** [comment]
The `onSet()` handler may be provided a `DefaultValue` object as the new value when an atom is reset.  This is similar to to a writeable selector getting a `DefaultValue` object as the new value when it is reset.

Note that this API is marked as `_UNSTABLE` and may change.  In particular how we handle providing the new/old values may need to be updated to properly handle atoms being set to asynchronous values or in error states.

**Comment by drarmstr** [comment]
Behavior updated to requested expectations with #1059
