### ISSUE TITLE
[ bounty ] - Persisting atoms ( remote db ), and loading them back in on. 

### ISSUE THREAD

**Issue by impactvelocity** [facebookexperimental/Recoil#739]
I am rebuilding my app I have been working on in React (previously Svelte...before first doing it in Vue.)

Recoil has been great to avoid re-renders, and have a good state / simple management. I am new to React, but getting the hang of it. 

**Goal** - Saving all the atoms, and saving them to a remote DB ( Hasura / Graphql ). It can just be a save button, doesn't to be auto save, but it would be nice. Then on load, load those atoms back into the state.

**Structure** - I have some simple atoms, but I will have 3 atomFamilies. Each atom family has an atom that holds all the ids in a list. 

Before with Vuex I was just taking the state as json, splitting it up, and saving it into json columns in the db. I would like to do the same thing here.

**HOW DO I ...**

Save a atomFamily & reload it?

For example...

**tasks** = atom that is a list of tasks id  ( atom: default [] )

**task** = atomFamily  ( each task in the list )

Right now I can take a snapshot of all the task ID's: snapshot.getLoadable(tasks), then i can also loop through those IDs, and build an object with each task in it. 

_Then the question is how do I load the atomFamily with the initializeState?_ 

The tasks (list of ids) atom is fairly straight forward it seems, just save the array to the db, and set it on load.  The atomFamily, I create an object array of them all. Then how do I set them? :)

[ not sure I can do this - but I am HAPPY to pay anyones time who can help me ]

**Comment by BenjaBobs** [comment]
Relevant: https://github.com/facebookexperimental/Recoil/issues/675

**Comment by drarmstr** [comment]
Please check out [this example](https://recoiljs.org/docs/guides/atom-effects#state-synchronization-example) in the documentation on initializing atom family values from remote storage.
