### ISSUE TITLE
Prettier config

### ISSUE THREAD

**Issue by jacques-blom** [facebookexperimental/Recoil#74]
What Prettier config do you use internally? It'd be great if we could embed it in the project as a `.prettierrc`, and perhaps run `prettier --check` on PRs to make sure contributors have run Prettier.

**Comment by claudiopro** [comment]
That's a desirable addition. Would you like to propose a PR 😄 ?
This is what we use at Facebook:

```json
{
  "arrowParens": "avoid",
  "singleQuote": true,
  "trailingComma": "all",
  "bracketSpacing": false,
  "jsxBracketSameLine": true,
  "overrides": [
    {
      "files": ["*.js", "*.jsx"],
      "options": {
        "parser": "flow",
      }
    }
  ]
}
```

**Comment by jacques-blom** [comment]
Thanks! On it 👍
