### ISSUE TITLE
recoil and portals

### ISSUE THREAD

**Issue by tttp** [facebookexperimental/Recoil#742]
Hi,

I'm rendering a component in a portal (createPortal), and it displays

    Error: This component must be used inside a <RecoilRoot> component.

is there a way to mix recoil and portals?

**Comment by tttp** [comment]
sorry for the noise, didn't initialise it as a child of the RecoilRoot, all good

**Comment by MattHeslington** [comment]
Hi, I have the same issue. How did you initialise as a child of RecoilRoot?

**Comment by drarmstr** [comment]
@MattHeslington - Make sure components using Recoil hooks are children of a [`<RecoilRoot>`](https://recoiljs.org/docs/api-reference/core/RecoilRoot) component or bridge from `useRecoilBridgeAcrossReactRoots()` (only for advanced use-cases).
