### ISSUE TITLE
Some hooks cause components to render twice (useRecoilValue, useRecoilState)

### ISSUE THREAD

**Issue by thupi** [facebookexperimental/Recoil#75]
Having tried to create a demo app using recoil and looking into the performance I found that some of the hooks cause React components to render twice un updates.

Codesandbox: https://codesandbox.io/s/recoil-double-render-issue-jdrkm?file=/src/App.js

The above demonstrates how updates to the root component(App) cause children using recoil hooks to render twice. The same is true when updating react state internally, in this case, the TextInput component.

The rerenders are logged in console for demo purposes :-)

**Comment by pyaesone17** [comment]
@thupi I think it is intended behaviour from React core itself.

https://github.com/facebook/react/issues/15074

**Comment by thupi** [comment]
Ohh, i see 🧐 Thanks for quick respons 😊
