### ISSUE TITLE
Component is not Rerendering after Page Refresh

### ISSUE THREAD

**Issue by calibeach** [facebookexperimental/Recoil#752]
Thank you!  My team and I are in our next iteration of a dev tool that we've been working on to help developers debug their recoil applications.

We are running into an interesting issue:  when using "useGotoRecoilSnapshot" and "useGotoRecoilSnapshot", we are able to "time travel" to different previous states successfully.

However, when we reload the page, we can still "time travel": view state, state changes, etc., but the DOM does not render the "Snapshot" that we are time traveling to.  To clarify, before the page refresh, we can use snapshot to render the DOM to its previous state, but after the refresh we cannot.

We've tried many things, including saving snapshots to session storage, etc., but none of them work.

Is this a bug with recoil's snapshot feature?

Thank you Recoil team for your help!

**Comment by drarmstr** [comment]
A lot of things could be going on here.  Remember, the `Snapshot` is just a snapshot of Recoil atom state.  It won't re-construct the DOM or React components.

For persisting state, it may be cleaner to use [`initializeState`](https://recoiljs.org/docs/api-reference/core/RecoilRoot) or [`atom effects`](https://recoiljs.org/docs/guides/atom-effects#local-storage-persistence)
