### ISSUE TITLE
Error: Cannot read from mutable source during the current render without tearing. This is a bug in React. Please file an issue.

### ISSUE THREAD

**Issue by ben-elsen** [facebookexperimental/Recoil#753]
Since I updated to the latest version, I get this error: 

```
Error: Cannot read from mutable source during the current render without tearing. This is a bug in React. Please file an issue.
```

```
×
Error: Cannot read from mutable source during the current render without tearing. This is a bug in React. Please file an issue.
▼ 38 stack frames were expanded.
readFromUnsubcribedMutableSource
node_modules/react-dom/cjs/react-dom.development.js:16038
(anonymous function)
node_modules/react-dom/cjs/react-dom.development.js:16058
mountState
node_modules/react-dom/cjs/react-dom.development.js:16199
useState
node_modules/react-dom/cjs/react-dom.development.js:16825
useMutableSource
node_modules/react-dom/cjs/react-dom.development.js:16057
mountMutableSource
node_modules/react-dom/cjs/react-dom.development.js:16186
useMutableSource
node_modules/react-dom/cjs/react-dom.development.js:16848
useMutableSource
node_modules/react/cjs/react.development.js:1621
useRecoilValueLoadable_MUTABLESOURCE
node_modules/recoil/es/recoil.js:2004
useRecoilValueLoadable
node_modules/recoil/es/recoil.js:2064
useRecoilValue
node_modules/recoil/es/recoil.js:2084
useRecoilState
node_modules/recoil/es/recoil.js:2132
SwitchNiche
src/components/App/AdminBase/Avatar/SwitchNiche/index.jsx:11
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js:15543
mountIndeterminateComponent
node_modules/react-dom/cjs/react-dom.development.js:18436
beginWork
node_modules/react-dom/cjs/react-dom.development.js:19867
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js:3905
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:3954
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:4016
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js:25031
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js:23765
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js:23685
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js:23644
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js:23215
(anonymous function)
node_modules/react-dom/cjs/react-dom.development.js:11544
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js:647
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js:11493
flushSyncCallbackQueueImpl
node_modules/react-dom/cjs/react-dom.development.js:11539
flushSyncCallbackQueue
node_modules/react-dom/cjs/react-dom.development.js:11526
commitRootImpl
node_modules/react-dom/cjs/react-dom.development.js:24292
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js:647
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js:11493
commitRoot
node_modules/react-dom/cjs/react-dom.development.js:23979
finishConcurrentRender
node_modules/react-dom/cjs/react-dom.development.js:23069
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js:22992
workLoop
node_modules/scheduler/cjs/scheduler.development.js:591
flushWork
node_modules/scheduler/cjs/scheduler.development.js:546
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js:158
```

**Comment by damikun** [comment]
Equal 

`Error: Cannot read from mutable source during the current render without tearing. This is a bug in React. Please file an issue.
PublicRouter
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/src/Utils/PublicRouter.tsx:9

   6 | type Props = {} & RouteProps;
   7 | 
   8 | export default function PublicRouter({ children, ...rest }: Props) {
>  9 |   const [user] = useRecoilState(user_atom);
  10 | 
  11 |   return (
  12 |     <Route

renderWithHooks
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:15590
mountIndeterminateComponent
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:18524
beginWork
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:19955
callCallback
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:310
invokeGuardedCallbackDev
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:359
invokeGuardedCallback
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:421
beginWork$1
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:25127
performUnitOfWork
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:23862
workLoopSync
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:23779
renderRootSync
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:23738
performSyncWorkOnRoot
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:23298
flushSyncCallbackQueueImpl/<
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:11579
unstable_runWithPriority
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/scheduler/cjs/scheduler.development.js:651
runWithPriority$1
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:11527
flushSyncCallbackQueueImpl
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:11574
flushSyncCallbackQueue
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:11560
commitRootImpl
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:24390
unstable_runWithPriority
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/scheduler/cjs/scheduler.development.js:651
runWithPriority$1
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:11527
commitRoot
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:24073
finishConcurrentRender
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:23240
performConcurrentWorkOnRoot
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/react-dom/cjs/react-dom.development.js:23079
workLoop
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/scheduler/cjs/scheduler.development.js:595
flushWork
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/scheduler/cjs/scheduler.development.js:550
performWorkUntilDeadline
C:/Users/dakupc/Documents/.NetDev/AKL/Frontend/node_modules/scheduler/cjs/scheduler.development.js:162
This screen is visible only in development. It will not appear if the app crashes in production.
```

**Comment by davidmccabe** [comment]
We haven't been able to reproduce this, can you please post a sandbox that reproduces it?

**Comment by collinscangarella** [comment]
I have also been running into this issue for several recoil (and react-experimental) releases. Unfortunately it's extremely difficult to recreate - sometimes it will happen consistently on a page, the next day it won't (with nothing being changed). One thing that may be useful is that I have only run into this issue when running yarn start.

**Comment by drarmstr** [comment]
Mutable Source no longer used in open-source React.
