### ISSUE TITLE
Initialize State - Documentation or Examples

### ISSUE THREAD

**Issue by calibeach** [facebookexperimental/Recoil#754]
Is there any additional documentation about how to use "initialize state" from a "mutable snapshot"?  I've followed a couple of tutorials that I found online, but I believe that the latest update has caused those examples to not work anymore.

**Comment by drarmstr** [comment]
Added a trivial example in #803.  Note that for proper support of initializing dynamic atoms (such as from [`atomFamily()`](https://recoiljs.org/docs/api-reference/utils/atomFamily) or for more flexible composition of multiple, per-atom, persistence policies you may want to use [Atom Effects](https://recoiljs.org/docs/guides/atom-effects) to initialize state.
