### ISSUE TITLE
[react-native] atomEffect not waiting for values to load from AsyncStorage

### ISSUE THREAD

**Issue by Svarto** [facebookexperimental/Recoil#756]
I am trying to use Recoil atomFamily with atomEffect to store user entered information in a form even if the app restarts, but due to how I have (so far) figured out to use Recoil atoms the form does not initialize with the saved data due to the asynchrounous retreival of AsyncStorage data resulting in the form having been rendered when the useRecoilState was still "".  See below for more detail:

I am asking for advice as I have two compounding problems:
1) I cannot use Recoil state in a controlled TextInput component as the updates rerenders the component and the cursor is jumping (see issues #737 #488) My solution to this is to use local state in the component, and update the Recoil atom through a useEffect hook (see code below)
2) My problem is that as the useRecoilState is asynchronous, the form has already been rendered before the stored values come back from AsyncStorage - resulting in the user seeing an empty form after a restart even if they had previous values saved. And due to 1, the locally controlled component does not update when the saved AsyncStorage data is retrieved.

Does anyone have any idea how I can manage this? Can I somehow force a wait for the Atom initialization from AsyncStorage to finish before returning a value? 

TextInput component:
```
import React, { useState, useEffect } from "react";
import { TextInput } from "react-native";
import { useRecoilState } from "recoil";
import { titleAtomFamily } from "../../state/atoms";

export function TitleInput({ recipeId}) {
    // Initialize the Global Atom state
  const [title, setTitle] = useRecoilState(titleAtomFamily(recipeId));

  // Local state - THIS INITIALIZES BEFORE ASYNCSTORAGE RETRIEVES SAVED GLOBAL STATE VALUE
  const [localTitle, setLocalTitle] = useState(title);

  // Update global state everytime local state changes
  useEffect(() => {
    setTitle(() => localTitle);
  }, [localTitle]);


  return (
    <TextInput
      placeholder={"Title*"}
      style={{ height: 40 }}
      value={localTitle}
      onChangeText={(value) => setLocalTitle(value)}
    />
  );
}

```

AtomFamily:
```
export const titleAtomFamily = atomFamily({
  key: "titleatomfamily",
  default: "",
  effects_UNSTABLE: (recipeId) => [
    localStorageEffect(`recipe_${recipeId}_title`),
  ],
});
```

AsyncStorage atomEffect:
```
import AsyncStorage from "@react-native-community/async-storage";
import { DefaultValue } from "recoil";

export const localStorageEffect = (key) => async ({ setSelf, onSet }) => {
  const savedValue = await AsyncStorage.getItem(key);

  if (savedValue != null) {
    setSelf(JSON.parse(savedValue));
  }

  onSet(async (newValue) => {
    if (newValue instanceof DefaultValue) {
      await AsyncStorage.removeItem(key);
    } else {
      await AsyncStorage.setItem(key, JSON.stringify(newValue));
    }
  });
};
```

**Comment by Svarto** [comment]
I played around and found out that it is possible to use React.Suspense with React Native and Recoil, by setting the default value to the saved AsyncStorage value, or if it is null, then to a default value.

I am not sure if there is a better way to handle this, so would really appreciate any thoughts or feedback in case this is not best practice.

AtomFamily code:
```
export const titleAtomFamily = atomFamily({
  key: "titleatomfamily",
  default: async (param) => defaultAsyncValue(param, "title", recipeData.title),
  effects_UNSTABLE: (recipeId) => [
    localStorageEffect(`recipe_${recipeId}_title`),
  ],
});
```

Default value function:
```
export const defaultAsyncValue = async (param, type, defaultValue) => {
  const savedValue = await AsyncStorage.getItem(`recipe_${param}_${type}`);
  if (savedValue != null) {
    return JSON.parse(savedValue);
  } else {
    return defaultValue;
  }
};
```

**Comment by drarmstr** [comment]
Please note that the atom effect functions themselves are not async.

For initialization you can:
* Set the atom default to an async Promise.  Suspense will be used until it resolves.
* Use `setSelf()` in an atom effect during the synchronous call of the effect to initialize the initial state.
* Use `setSelf()` in an atom effect to initialize to an async Promise.  Suspense will be used until it resolves.  The different between this and setting the default to the Promise is with this approach if you reset that atom state it will revert to the default, not the initialized value.
* Call `setSelf()` from an atom effect later asynchronously.  This will use the default atom value for initial state until the `setSelf()` is called later.

Documentation for two different approaches to initializing with async values is being added in #828
