### ISSUE TITLE
Bug: AtomEffect localStorage example - value overwritten by default value

### ISSUE THREAD

**Issue by florianbepunkt** [facebookexperimental/Recoil#757]
My atom that is synced to local storage always is overwritten by the default value specified. I used the example from the docs to persist / load a recoil atom from local storage

```
export const localStorageEffect = (key: string) => ({ setSelf, onSet }: any) => {
  const savedValue = localStorage.getItem(key);

  if (savedValue != null) {
    setSelf(JSON.parse(savedValue));
  }

  onSet((newValue: any) => {
    if (newValue instanceof DefaultValue) {
      localStorage.removeItem(key);
    } else {
      localStorage.setItem(key, JSON.stringify(newValue));
    }
  });
};
```

This is my atom

```
export const hintsState = atom<Partial<IRoundsState>>({
  key: "hintsState",
  default: {
    FIRST: {
      isHintRead: false,
    },
    SECOND: {
      isHintRead: false,
    },
    THIRD: {
      isHintRead: false,
    },
    hostSolutionWarningRead: false,
  },
  effects_UNSTABLE: [localStorageEffect(`cm-digital-hints`)],
});
```

I have a component that logs the atom value: const toBeLogged = useRecoilValue(hintsState).

the value gets logged twice, first the value that is stored in local storage (in my case FIRST.isHintRead = true), but then it is overwritten by the default value. So whatever I specify as default value is used in the end, regardless of the local storage.

**Comment by drarmstr** [comment]
Calling `setSelf()` synchronously in the effect should initialize the atom state to that value and the default value should not be used unless you are resetting the atom.  Do you have a reproducer on `codesandbox.io` by any chance?

**Comment by florianbepunkt** [comment]
Thank you. Since I can't reproduce this issue in an isolated environment, there must be some side effect in my code. Closing this.
