### ISSUE TITLE
[Typescript] Suggestion: Allow types with a `toJSON` function to be used as serializable param for families.

### ISSUE THREAD

**Issue by BenjaBobs** [facebookexperimental/Recoil#760]
Currently I can't use `Date` as parameter for family.
According to https://github.com/facebookexperimental/Recoil/blob/c6d786bb89c20730fec3068346c0b4f7265ea808/typescript/index.d.ts#L270-L273 the parameter needs to be primitive or an array of primitives.

As far as I can tell, this is because it needs to be serializable by `Recoil_stableStringify`:
https://github.com/facebookexperimental/Recoil/blob/ca888d3c3a55a3128279d0124ebca9002377770b/src/recoil_values/Recoil_selectorFamily.js#L31-L40

But `Recoil_stableStringify` handles objects with a `toJSON()` function:
https://github.com/facebookexperimental/Recoil/blob/ca888d3c3a55a3128279d0124ebca9002377770b/src/util/Recoil_stableStringify.js#L64-L71

So my suggestion is to add an interface supporting that as type:
```typescript
export type SerializableParam = 
	| Primitive 
	| { toJSON: () => string } // Add support for json serializable objects, such as Date
	| ReadonlyArray<SerializableParam> 
	| Readonly<{[key: string]: SerializableParam}>
	;
```

**Comment by BenjaBobs** [comment]
Any news/feedback on this?

**Comment by drarmstr** [comment]
@BenjaBobs - This sounds like a fine idea.  Would you be up for contributing a PR for this?

**Comment by BenjaBobs** [comment]
Sure, submitted a PR.
