### ISSUE TITLE
Storing function as atom value gets invoked?

### ISSUE THREAD

**Issue by adrianbw** [facebookexperimental/Recoil#761]
I have a setup like this:
```typescript
export const LinkConstructorAPI = atom<
  (args: any) => string
>({
  key: `${namespace}.LinkConstructorAPI`,
  default: undefined,
});

export const Component = () => {
  const setLinkConstructor = useSetRecoilState(LinkConstructorAPI);
  const linkConstructor = React.useCallback(
    (args: any) => {
        return `${linkHere}`;
      },
      [args]
    );
  }
  React.useEffect(() => {
    setLinkConstructor(linkConstructor);
  }, [linkConstructor, setLinkConstructor]);
  return (<></>);
}
```
When this component loads, it invokes that function as part of the setRecoilState action. Am I doing something wrong, or can Recoil not store functions?

**Comment by adrianbw** [comment]
Here's an example: https://codesandbox.io/s/awesome-chebyshev-r6mgj?file=/src/InternalComponent.tsx . If you look at the file, you can see that it updates the component's state when it shouldn't. Is this maybe because of the function version of SetterOrUpdater?

**Comment by drarmstr** [comment]
Yes, as mentioned in the docs, storing a function value in an atom is slightly different because of the updater form.  To work around that you can just set it to a function which calls the function you wish to use.  E.g.:

```jsx
function MyComponent() {
  const setLinkConstructor = useSetRecoilState(linkConstructorAtom);
  const linkConstructor = useCallback(args => `${linkHere}`, []);
  useEffect(() => {
    setLinkConstructor(() => linkConstructor);
  }, [linkConstructor]);
}
```
