### ISSUE TITLE
Incremental loading for infinite scrolling

### ISSUE THREAD

**Issue by mastorm** [facebookexperimental/Recoil#765]
I am implementing infinite scrolling for a list of tickets. Currently, recoil doesnt seem to offer a way to get all data that a selector has fetched.

Example:
```js
export const issues = selector({
  key: 'issueList',
  get: async ({ get }) => {
    const cursor = get(issuesCursor);
    const client = getApolloClient();
    const issues = await client.query<IssuesQuery, IssuesQueryVariables>({
      query: IssuesDocument,
      variables: {
        cursor,
      },
    });
    return { nextCursor: issues.data.issuesCursor.cursor, items: issues.data.issuesCursor.items };
  },
});
export const issueList = selector({
  key: 'nextIssuesCursor',
  get: ({ get }) => get(issues).items,
});
```

I would like to receive all issues from the issueList selector.

I can solve this issue with a hook, yet i would strongly prefer keeping all the data fetching in recoiljs.

**Comment by BenjaBobs** [comment]
There are a couple of strategies that can solve this.
You could store all of the data in a single array kept in an `atom`, and just append to that array when scrolling.
You could also store them in chunks/pages using an `atomFamily` with the parameter being the `cursor`, and then keep an array of all known cursors in an `atom`, and finally have a `selector` that returns a concatenated list of items by taking the array of cursors and mapping them to the `atomFamily`.

**Comment by mastorm** [comment]
@BenjaBobs That would still require me to mutate the atom from outside recoil. 

This is how i solved it: 
```js
export function useIssues() {
  const [issues, setIssues] = useRecoilState(issuesStore);
  const [, setCursor] = useRecoilState(issuesCursor);
  const currentIssues = useRecoilValue(currentIssueBatch);
  const nextCursor = useRecoilValue(nextIssuesCursor);

  useEffect(() => {
    setIssues((prev) => [...prev, ...currentIssues]);
  }, [currentIssues, setIssues]);

  const fetchMore = () => {
    setCursor(nextCursor ?? null);
  };
  return { issues, fetchMore };
}
```

which works quite well, but it would still be cool to have a way of accessing selectors previous states or have selectors write the state. I can understand why recoil wont allow writing state in getters, because you would open up a lot of possibilitys for accidental recursion, but it would still be nice to have something to solve in recoil only

**Comment by BenjaBobs** [comment]
You could do something like this if you want to keep it all in Recoil:
![image](https://user-images.githubusercontent.com/8708965/100426911-e8db2800-3091-11eb-937b-0f569a784043.png)

**Comment by mastorm** [comment]
That is so cool. Thanks @BenjaBobs !

**Comment by mastorm** [comment]
Theres no async selectors :( https://github.com/facebookexperimental/Recoil/issues/762

**Comment by BenjaBobs** [comment]
Ah, I see, guess my suggestion won't work then. And since `atomEffects` can set values of other atoms, I don't think this is currently possible unless using hacky ways such as storing a reference to a `set` function from a `useRecoilCallback` and then using that to set the value.

**Comment by drarmstr** [comment]
@mastorm / @BenjaBobs 
Would a solution using `useRecoilCallback()` like the following work?

```jsx
export const allItems = atom<Array<Item>>>({
  key: 'allItems',
  default: [],
});

const currentCursorInternal = atom<number>({
  key: 'currentCursorInternal',
  default: 0,
});

export fetchMoreItems = useRecoilCallback(({snapshot, set}) => async () => {
  set(currentCursorInternal, cursor => {
    const next = cursor + 1;
    promiseDone(ApiCall(next), newData => {
      // TODO use some queue mechanism to handle out-of-order responses.
      set(allItems, existing => [...existing, ...newData]);
    });
    return next;
  });
});
```

But, the most versatile or appropriate for this situation might be using the [`waitForNone()`](https://recoiljs.org/docs/api-reference/utils/waitForNone) helper to handle the incremental loading pattern:
```jsx
const itemQuery = selectorFamily({
  key: 'ItemQuery',
  get: cursor => () => ApiCall(cursor),
});

const currentCursorInternal = atom<number>({
  key: 'currentCursorInternal',
  default: 0,
});

export function useFetchMoreItems() {
  const setCurrentCursor = useSetRecoilState(currentCursorInternal);
  return () => setCurrentCursor(cursor => cursor + 1);
}

export const allItems = selector({
  key: 'AllItems',
  get: ({get}) => {
    const current = get(currentCursorInternal);
    const cursorRange = Array.from(Array(current).keys());
    return get(waitForNone(cursorRange.map(itemQuery)));
  },
});

function ShowItemsComponent() {
  const itemLoadables = useGetRecoilValue(allItems);
  const fetchMoreItems = useFetchMoreItems();
  return (
    <div>
      <button onClick={fetchMoreItems}>Fetch More Items</button>
      {itemLoadables.map(itemLoadable => ({
        hasValue: <Item item={itemLoadable.contents} />,
        hasError: <Error error={itemLoadable.contents} />,
        loading: <CoolShimmer />,
      }[itemLoadable.state])}
    </div>
  );
}
```

**Comment by mastorm** [comment]
I finished implementing the way @drarmstr  recommended and it worked like a charm. Thanks a lot.
