### ISSUE TITLE
Error: Objects are not valid as a React child (found: object with keys {text}). If you meant to render a collection of children, use an array instead.

### ISSUE THREAD

**Issue by softmarshmallow** [facebookexperimental/Recoil#766]
```ts

export const targetLayerSelector = selector({
    key: "target-layer-selector", // unique ID
    get: ({ get }) => {
        // const id = get(targetLayerIdAtom);
        // const layer = currentSceneRepository.layer(id)
        return {
            text: "hi"
        }
        // return layer.data

        return undefined!
    },
});
```

this causes

![image](https://user-images.githubusercontent.com/16307013/100424140-835a5c00-30d0-11eb-9657-055d0e2dbc2b.png)

**Comment by BenjaBobs** [comment]
From the error message this seems like it's happening in the rendering code. Are you trying to store React Components as Recoil state? If so, you could do something like
```typescript
import React from 'react';

export const targetLayerSelector = selector({
    key: "target-layer-selector", // unique ID
    get: ({ get }) => {
        return <p>Hi!</p>
    },
});
```

**Comment by softmarshmallow** [comment]
No.. I'm using it pretty straight forward. on the setting atom side, no error occurs, but only happens on the selector side. and selector side, as you can see, no logics inside it.

**Comment by softmarshmallow** [comment]
this works.

```ts
export const targetLayerSelector = selector({
    key: "target-layer-selector", // unique ID
    get: ({ get }) => {
        return "hi"
    },
});
```


But this won't
```ts
export const targetLayerSelector = selector({
    key: "target-layer-selector", // unique ID
    get: ({ get }) => {
        return { message: "hi" }
    },
});
```

**Comment by BenjaBobs** [comment]
That's because React doesn't know how to render a plain object. `{ message: "hi" }` is an `object`, whereas `"hi"` is a string, which it does know how to render.

**Comment by BenjaBobs** [comment]
More specifically, React knows how to render a `React.ReactNode`:
![image](https://user-images.githubusercontent.com/8708965/100425327-4752d700-308f-11eb-9ccd-e3fcb3000d25.png)

**Comment by softmarshmallow** [comment]
render? why does selector render stuff?

I'm calling with `const value = useRecoilValue(someSelector)`

```tsx
<p>{value}</p>
```

**Comment by softmarshmallow** [comment]
FYI, the data and the error after it.
![image](https://user-images.githubusercontent.com/16307013/100425350-6161d900-30d2-11eb-84fc-1d26253d46f8.png)

**Comment by softmarshmallow** [comment]
Sorry, my bad. It had nothing to do with recoil. I thought object in template string will automatically convert object as string.
(which is wierd.)

**Comment by BenjaBobs** [comment]
> render? why does selector render stuff?

Good question!
I suspect the error location supplied might not be right, because the error message indicates that React is trying to render something.

**Comment by softmarshmallow** [comment]
from 
         ` <Typography variant="h6">no key is set for selected layer "{targetLayer}"</Typography>`
to
         ` <Typography variant="h6">no key is set for selected layer "{JSON.stringify(targetLayer)}"</Typography>`

**Comment by softmarshmallow** [comment]
Thanks for the help!

**Comment by Feisal2023** [comment]
i am facing this issue Uncaught runtime errors:
×
ERROR
Objects are not valid as a React child (found: object with keys {star, review, reviewDate, name, userID}). If you meant to render a collection of children, use an array instead.   <>
                {product?.ratings.map((item, index) => {
                  const { star, review, reviewDate, name, userID } = item;
                  return (
                    <div key={index} className={styles.review}>
                      {/* <StarsRating value={star} style={{ fontSize: 10 }} /> */}
                      <StarRating
                        starDimension="20px"
                        starSpacing="2px"
                        starRatedColor="#F6B01E"
                        rating={star}
                        editing={false}
                      />
                      <p>{review}</p>
                      <span>
                        <b>{reviewDate}</b>
                      </span>
                      <br />
                      <span>
                        <b>by: {name}</b>
                      </span>
                    </div>
                  );
                })}
              </>

**Comment by Feisal2023** [comment]
and this is my code snippet import React from "react";
import useActive from "../../hooks/useActive";
import "./product_summary.scss";
import DOMPurify from "dompurify";
import StarRating from "react-star-ratings";
const ProductSummary = (props) => {
  console.log(props.ratings);
  const { active, handleActive, activeClass } = useActive("specs");

  return (
    <section id="product_summary" className="section">
      <div className="container">
        {/*===== Product-Summary-Tabs =====*/}
        <div className="prod_summary_tabs">
          <ul className="tabs">
            <li
              className={`tabs_item ${activeClass("specs")}`}
              onClick={() => handleActive("specs")}
            >
              Specifications
            </li>
            <li
              className={`tabs_item ${activeClass("overview")}`}
              onClick={() => handleActive("overview")}
            >
              Overview
            </li>
            <li
              className={`tabs_item ${activeClass("reviews")}`}
              onClick={() => handleActive("reviews")}
            >
              Reviews
            </li>
          </ul>
        </div>

        {/*===== Product-Summary-Details =====*/}
        <div className="prod_summary_details">
          {active === "specs" ? (
            <div className="prod_specs">
              <ul>
                <li>
                  <span>Brand</span>
                  <span>{props?.brand}</span>
                </li>
                <li>
                  <span>Sku</span>
                  <span>{props?.sku}</span>
                </li>
                <li>
                  <span>Color</span>
                  <span>{props?.color}</span>
                </li>
                <li>
                  <span>Quantity</span>
                  <span>{props?.quantity}</span>
                </li>
                <li>
                  <span>Warranty</span>
                  <span>1 Year</span>
                </li>
                <li>
                  <span>Brand Originality</span>
                  <span>100%</span>
                </li>
              </ul>
            </div>
          ) : active === "overview" ? (
            <div className="prod_overview">
              <p>
                <b>Product Description:</b>
              </p>
              <div
                dangerouslySetInnerHTML={{
                  __html: DOMPurify.sanitize(props?.description),
                }}
              ></div>
            </div>
          ) : (
            <>
              <h3>Product Reviews</h3>
              <div className="--m">
                {props?.ratings.length === 0 ? (
                  <p>There are no reviews for this product yet.</p>
                ) : (
                  <>
                    {props?.ratings.map((item, index) => {
                      const { star, review, reviewDate, name, userID } = item;
                      return (
                        <div key={index} className="review">
                          <StarRating
                            starDimension="20px"
                            starSpacing="2px"
                            starRatedColor="#F6B01E"
                            rating={star}
                            editing={false}
                          />
                          <p>{review}</p>
                          <span>
                            <b>{reviewDate}</b>
                          </span>
                          <br />
                          <span>
                            <b>by: {name}</b>
                          </span>
                        </div>
                      );
                    })}
                  </>
                )}
              </div>
            </>
          )}
        </div>
      </div>
    </section>
  );
};

export default ProductSummary;
while my console  import React from "react";
import useActive from "../../hooks/useActive";
import "./product_summary.scss";
import DOMPurify from "dompurify";
import StarRating from "react-star-ratings";
const ProductSummary = (props) => {
  console.log(props.ratings);
  const { active, handleActive, activeClass } = useActive("specs");

  return (
    <section id="product_summary" className="section">
      <div className="container">
        {/*===== Product-Summary-Tabs =====*/}
        <div className="prod_summary_tabs">
          <ul className="tabs">
            <li
              className={`tabs_item ${activeClass("specs")}`}
              onClick={() => handleActive("specs")}
            >
              Specifications
            </li>
            <li
              className={`tabs_item ${activeClass("overview")}`}
              onClick={() => handleActive("overview")}
            >
              Overview
            </li>
            <li
              className={`tabs_item ${activeClass("reviews")}`}
              onClick={() => handleActive("reviews")}
            >
              Reviews
            </li>
          </ul>
        </div>

        {/*===== Product-Summary-Details =====*/}
        <div className="prod_summary_details">
          {active === "specs" ? (
            <div className="prod_specs">
              <ul>
                <li>
                  <span>Brand</span>
                  <span>{props?.brand}</span>
                </li>
                <li>
                  <span>Sku</span>
                  <span>{props?.sku}</span>
                </li>
                <li>
                  <span>Color</span>
                  <span>{props?.color}</span>
                </li>
                <li>
                  <span>Quantity</span>
                  <span>{props?.quantity}</span>
                </li>
                <li>
                  <span>Warranty</span>
                  <span>1 Year</span>
                </li>
                <li>
                  <span>Brand Originality</span>
                  <span>100%</span>
                </li>
              </ul>
            </div>
          ) : active === "overview" ? (
            <div className="prod_overview">
              <p>
                <b>Product Description:</b>
              </p>
              <div
                dangerouslySetInnerHTML={{
                  __html: DOMPurify.sanitize(props?.description),
                }}
              ></div>
            </div>
          ) : (
            <>
              <h3>Product Reviews</h3>
              <div className="--m">
                {props?.ratings.length === 0 ? (
                  <p>There are no reviews for this product yet.</p>
                ) : (
                  <>
                    {props?.ratings.map((item, index) => {
                      const { star, review, reviewDate, name, userID } = item;
                      return (
                        <div key={index} className="review">
                          <StarRating
                            starDimension="20px"
                            starSpacing="2px"
                            starRatedColor="#F6B01E"
                            rating={star}
                            editing={false}
                          />
                          <p>{review}</p>
                          <span>
                            <b>{reviewDate}</b>
                          </span>
                          <br />
                          <span>
                            <b>by: {name}</b>
                          </span>
                        </div>
                      );
                    })}
                  </>
                )}
              </div>
            </>
          )}
        </div>
      </div>
    </section>
  );
};

export default ProductSummary; when i console.log(props?.ratings)
[{…}]0: {star: 2, review: 'not satisfied', reviewDate: 'Tue Feb 27 2024', name: 'Feisal', userID: '65d5d891dc5ae55627c99ebd'}length: 1[[Prototype]]: Array(0)
