### ISSUE TITLE
Minor bug in the documentation in the Query Refresh section

### ISSUE THREAD

**Issue by nickmarca** [facebookexperimental/Recoil#768]
Hello,

Sorry I'm not sure if it was noticed before,
I just would like to point out a minor bug that I spotted recently 
at this [url](https://recoiljs.org/docs/guides/asynchronous-data-queries/#use-a-request-id) under
the section `use a request id`.

In the code block below, the anonymous arrow function passed as parameter to the `setUserInfoQueryRequestID` function
is returning `undefined` which will cause the atom to not update.

`return () => {
    setUserInfoQueryRequestID(requestID => requestID++);
  };`

This is because `requestID++` is converted by the compiler/interpreter to the statement `requestID = requestID + 1;` and as we know statements in Javascript doesn't return anything.

I know it might be an obvious thing for most, but it can also lead some to think there's a bug in the library.

Thanks

<img width="821" alt="Screenshot 2020-11-26 at 00 26 56" src="https://user-images.githubusercontent.com/3733116/100495234-4da18b80-3141-11eb-93f1-d41a03bbc4a9.png">

**Comment by drarmstr** [comment]
Yeah.. `requestID++` is an expression which increments the value stored in `requestID` and returns the incremented value as the value of the expression.  But, the problem here is that `requestID` is an input argument, so not really mutable.  Fixed in #770
