### ISSUE TITLE
How to write simple unit test for an atom?

### ISSUE THREAD

**Issue by thealitahir** [facebookexperimental/Recoil#769]
This is my simple atom, I want to write a unit test for it but I couldn't find documentation anywhere to write a unit test for it, can someone please guide

```javascript
export const domainDocuments = atom({
	key: 'domainDocuments',
	default: [],
});
```

**Comment by BenjaBobs** [comment]
https://recoiljs.org/docs/guides/testing#example-jest-unit-testing-selectors

**Comment by thealitahir** [comment]
`const initialSnapshot = snapshot_UNSTABLE();`
There's no info about snapshot_UNSTABLE(); Where to import it from and what's its purpose?
@drarmstr

**Comment by drarmstr** [comment]
@thealitahir - https://recoiljs.org/docs/api-reference/core/Snapshot#building-a-snapshot
