### ISSUE TITLE
Atom unmounted

### ISSUE THREAD

**Issue by unadlib** [facebookexperimental/Recoil#77]
When 'atom' is not being used at all, from the source code, it is not currently unmounted. Will this be addressed in the future?

**Comment by acutmore** [comment]
Hi @unadlib, there is some information about this in https://github.com/facebookexperimental/Recoil/issues/30#issuecomment-629388549

> We are adding a feature soon where atoms will be deleted when no longer used, together with another hook that lets a component retain an atom without subscribing to it. These could be combined into a utility that gives you a list of IDs with automatic deletion of the individual atoms when they are removed from the list.
> 
> Currently you have to use the useResetRecoilState hook to delete atoms.

**Comment by unadlib** [comment]
> Hi @unadlib, there is some information about this in [#30 (comment)](https://github.com/facebookexperimental/Recoil/issues/30#issuecomment-629388549)
> 
> > We are adding a feature soon where atoms will be deleted when no longer used, together with another hook that lets a component retain an atom without subscribing to it. These could be combined into a utility that gives you a list of IDs with automatic deletion of the individual atoms when they are removed from the list.
> > Currently you have to use the useResetRecoilState hook to delete atoms.

Thank you.
