### ISSUE TITLE
Testing setters

### ISSUE THREAD

**Issue by delucca** [facebookexperimental/Recoil#772]
Hi!

I've read in the docs everything about testing, and it is pretty clear for me how to run unit tests on `getters`. But how about setters?

The suggested snapshot works smoothly to test the `get` key from our selectors, but I don't know how to test the `set`.

**Comment by drarmstr** [comment]
You can test setters by mutating state using the snapshot `map()` or `asyncMap()` methods. They take a function which gets a `set()` callback for setting atoms or selectors and return a new immutable `Snapshot` with the new state you can confirm.

**Comment by delucca** [comment]
Just to contribute to my own issue, I've taken another approach, instead of writing unit tests directly to the created Recoil atom/selector, I've exported the `get` and `set` functions. For example:

Instead of writing code like this:
```ts
const coolAtom = selector({
  key: 'cool',
  get: ({ get }) => (...),
  set: ({ get, set }, newValue) => (...),
})

export default coolAtom
```

I am now writing like this:
```ts
export const getCool => ({ get }) => (...)
export const setCool => ({ get, set }, new Value) => (...)

const coolAtom = selector({
  key: 'cool',
  get: getCool,
  set: setCool,
})

export default coolAtom
```

This way I can use the `getCool` and `setCool` functions directly on my unit tests, and pass stubs/spies to them instead of the mocking hell.
