### ISSUE TITLE
Setting atom value when resetting selector doesn't work?

### ISSUE THREAD

**Issue by wojtekmaj** [facebookexperimental/Recoil#773]
What I need is a simple writable state that is loaded asynchronously. I would also like to be able to reset it. However, I don't want the state to reset to previously fetched default value. I want to *properly* reset it: like I when I would have refreshed the page.

So, to cope with that, I built something like this:

```js
async function getValue() {
  return new Date().toISOString();
}

const defaultItemsState = atom({
  key: `ItemsState/default`,
  default: selector({
    key: `ItemsState/asyncDefault`,
    get: ({ get }) => getValue(),
  }),
});

export const itemsState = selector({
  key: `ItemsState`,
  get: ({ get }) => get(defaultItemsState),
  set: async ({ get, set }, newValue) => {
    let resolvedNewValue = newValue;

    if (newValue instanceof DefaultValue) {
      resolvedNewValue = await getValue();
    }
    
    set(defaultItemsState, resolvedNewValue);
  },
});
```

This set of atoms and selector:
* Correctly fetches and returns default initial value using `getValue`, when `useRecoilValue(itemsState)` is called.
* Correctly sets value in `defaultItemsState` when function returned by `useSetRecoilState(itemsState)` is called.
* Correctly calls `getValue` when function returned by `useResetRecoilState(itemsState)` is called.

BUT

* Does not set value in `defaultItemsState` when function returned by `useResetRecoilState(itemsState)` is called.

This confuses the hell out of me, because in both cases: when setting and resetting `itemsState`, `itemsState.get` is called, and in both cases I'm getting correct logs just before `set(defaultItemsState, resolvedNewValue)` line.

I created a simple repro:

https://codesandbox.io/s/recoil-reset-not-working-d2m8y?file=/src/App.js

I fail to understand why this happens. Can you give me a hint on how to fix this code? TIA.

**Comment by drarmstr** [comment]
Selector `set()` methods do not currently support async functions.  #762 

If you want a selector to model a data query and for some action to "refresh" the query, then consider the [query refresh pattern](https://recoiljs.org/docs/guides/asynchronous-data-queries/#query-refresh).

**Comment by wojtekmaj** [comment]
Ooh. Thank you.

I think it would be wise to warn or even crash in dev mode in such situations. What do you think?

**Comment by drarmstr** [comment]
Add error reporting in #777
