### ISSUE TITLE
Setting ref value to atom causes couple errors.

### ISSUE THREAD

**Issue by tomatualus** [facebookexperimental/Recoil#779]
Hello!

I am using react-three-fiber and recoil together to play around. What i stumbled upon almost instantly, is that when i set atoms value to a components ref, i get many errors.
  

    import React, { ReactNode } from "react";
    import { Canvas } from "react-three-fiber";
    import { atom, useRecoilBridgeAcrossReactRoots_UNSTABLE, useRecoilState } from "recoil";
    import * as THREE from "three";
    export const pointsState = atom<ReactNode>({
        key: 'pointsState',
        default: null,
    });

    export const TestComponent = () => {
        const [pointRef, setPointRef] = useRecoilState(pointsState);
        const RecoilBridge = useRecoilBridgeAcrossReactRoots_UNSTABLE();

        let raycaster = new THREE.Raycaster();
        raycaster.params.Points!.threshold = 0.25;

        let vertices = [
            new THREE.Vector3(-1, -1, 1),
            new THREE.Vector3(1, -1, 1),
            new THREE.Vector3(-1, 1, 1),
            new THREE.Vector3(1, 1, 1),
            new THREE.Vector3(-1, -1, -1),
            new THREE.Vector3(1, -1, -1),
            new THREE.Vector3(-1, 1, -1),
            new THREE.Vector3(1, 1, -1),
        ];

        return (
            <Canvas>
                <RecoilBridge>
                    <points ref={(ref) => {
                        console.log("Settings points ref", ref);
                        setPointRef(ref); // Crashes here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                        }}>
                        <pointsMaterial size={0.25} color={"yellow"} />
                        <geometry vertices={vertices} />
                    </points>
                </RecoilBridge>
            </Canvas>
        )
    }

And ofcourse the root component

    import React from 'react';
    import { RecoilRoot } from 'recoil';
    import { TestComponent } from './TestComponent';

    export const Root = () => {
        return (
            <RecoilRoot>
                <TestComponent />
            </RecoilRoot>
        );
    }

The errors are `TypeError: "x" is read-only` or `TypeError: "vertices" is read-only` or many more. Any help on this?

Ofcourse - why am i doing this? I need the components reference so i can raycast it, simple as that. I COULD use React.forwardRef, but if that would be the case, i would have prop hell soon.

**Comment by drarmstr** [comment]
Recoil values should only store read-only objects.  So, trying to freeze a component reference is likely causing the issue.  The motivation for this is that Recoil needs to be aware of state changes in atom values, so state changes by mutating objects is problematic.  If you're treating this more like a way to pass the reference around vs caring about the state of the component itself then it may work to hack the atom with `dangerouslyAllowMutability: true`.  Though, it may be cleaner to use a different mechanism to share component references.
