### ISSUE TITLE
Question: Can a selector return an instance object?

### ISSUE THREAD

**Issue by jjalonso** [facebookexperimental/Recoil#781]
I have been playing with one get selector returning an Object with functions inside and it fail trying to freez. alternative way? impossible? not recomended? I remind im not storing it, just retrieving the instance from API with an SDK on the get selector and returning it

**Comment by drarmstr** [comment]
You should be able to use an immutable object that contains references to functions as a value for a selector.  Some object types are sensitive to freezing.  I'm not entirely clear what you mean by "not storing it".  Could you clarify with an example or reproducer on codesandbox.io?

**Comment by jjalonso** [comment]
I actually changed the approach because had lots of freezing errors. With
not storing I meant that it was not saved in the state as object with
function. It was just asynchronously fetching in a get selector and
returning the object with functions. I think that returning it was the
problem.
