### ISSUE TITLE
Can this be used with many React App at the same time?

### ISSUE THREAD

**Issue by totaland** [facebookexperimental/Recoil#783]
Can recoil be used with many react app at the same time. Like if you have many small apps that are deployed separately and work on the same homepage such as home/app1, home/app2. How can this be used in that situation?

**Comment by BenjaBobs** [comment]
If they are wrapped by a top-level react app, you can use a `RecoilBridge`: https://recoiljs.org/docs/api-reference/core/useRecoilBridgeAcrossReactRoots

**Comment by drarmstr** [comment]
Thanks @BenjaBobs!  Also, if you don't actually want shared state across the apps, then you could just use sibling `<RecoilRoot>`s for independent Recoil apps.
