### ISSUE TITLE
[Question] Is it a right design for building mutable hierarchic

### ISSUE THREAD

**Issue by bnayae** [facebookexperimental/Recoil#784]
I'd decided to move ([my company's](https://weknow.network/)) state management implementation to Recoil (from REDUX) because I really like the design & simplicity of Recoil.

Right now I'm trying to figure out best-practices & guidelines before we make the actual transition.

I come out with an idea of structuring our state tree with Recoil.
It works but seem too much boilerplate.

My goal was to build a mutable hierarchic structure which can be fetched or mutate at the root level yet any of its sub state can be edited directly.

The biggest issue I'm having with this structure is that my current implementation initial the sub state (atom) with a work-around which is using selector instead of mutating the root state with a default value.

You can see the entire sample at: https://github.com/weknow-network/recoil-hierarchy

This is my root state (postObjectHierarchicSelector.ts):

```js
export const postObjectHierarchicSelector = selectorFamily<IPost, number>({
  key: 'object-hierarchic-post',
  get: (id) => ({ get }) => {
    const post: IPost = get(
      waitForAll({
        id: postIdFiledAtom(id),
        userId: postUserIdFiledAtom(id),
        title: postTitleFiledAtom(id),
        body: postBodyFiledAtom(id),
      })
    );

    return post;
  },
  set: (id) => async ({ set /*get */, reset }, post) => {
    if (guardRecoilDefaultValue(post)) {
      reset(postIdFiledAtom(id));
      reset(postUserIdFiledAtom(id));
      reset(postTitleFiledAtom(id));
      reset(postBodyFiledAtom(id));
      return;
    }

    set(postIdFiledAtom(id), post.id);
    set(postUserIdFiledAtom(id), post.userId);
    set(postTitleFiledAtom(id), post.title);
    set(postBodyFiledAtom(id), post.body);
  },
});
```

What I was looking for is being able to have Initialize hook where I can set default value at the first time.

Not being able to do so, I come out with the following work around:

1) Selector which fetch the initial state
```js
export const postByIdProxy = async (id: number): Promise<IPost> => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts/${id}`);
  const post = await res.json();
  // console.log(JSON.stringify(post));
  return post;
};

export const postObjectHierarchicInitSelector = selectorFamily<IPost, number>({
  key: 'object-hierarchic-post-init',
  get: (id) => async (/*{ get }*/) => {
    return await postByIdProxy(id);
  },
});
```

2) Each sub state initialize it state via sub initialize selector, for example:
```js
// just for getting the right portion out of the root init selector
const postIdFiledInitSelector = selectorFamily<number, number>({
  key: 'post-complex-origin/id/init',
  get: (id) => ({ get }) => {
    const post: IPost = get(postObjectHierarchicInitSelector(id));
    return post.id;
  },
});

// the actual atom
export const postIdFiledAtom = atomFamily<number, number>({
  key: 'post-complex-origin/id',
  default: postIdFiledInitSelector,
});
```

What would you suggest is the right pattern for it?

**Comment by drarmstr** [comment]
If I understand correctly, you would like local state, such as managed by an [`atom()`](https://recoiljs.org/docs/api-reference/core/atom), but you would like to asynchronously get the initial value.  If that is the case, then [this pattern](https://recoiljs.org/docs/guides/asynchronous-data-queries#query-default-atom-values) for querying the default atom of a selector is useful.  It appears like the solution you describe follows that pattern.
