### ISSUE TITLE
Are there any ways to reset ALL atoms at once?

### ISSUE THREAD

**Issue by anhnch** [facebookexperimental/Recoil#785]
When a user logs out and logs in with a different account, the cached values are still there. I'm aware of useResetRecoilxxx methods, but it's quite inconvenient to call all of them manually, besides there's a risk of missing some certain resets we add during the development. 

So the question is: Can we useResetRecoilAll (or something like that) to reset them ALL AT ONCE?

**Comment by drarmstr** [comment]
As discussed in #758:

If you are happy resetting ALL of your state, you could use a fresh `<RecoilRoot>`, or maybe apply a `key` prop with the user ID to `<RecoilRoot>`. Or, if you want to reset state to some known configuration for a new user, maybe using a `Snapshot` and `useGotoRecoilSnapshot()` may work?

**Comment by wozzo** [comment]
@drarmstr the key prop you mention doesn't appear to be documented in [the API reference for `RecoilRoot`](https://recoiljs.org/docs/api-reference/core/RecoilRoot).
Do you know if there is any documentation or examples of using it?

**Comment by drarmstr** [comment]
> @drarmstr the key prop you mention doesn't appear to be documented in [the API reference for `RecoilRoot`](https://recoiljs.org/docs/api-reference/core/RecoilRoot). Do you know if there is any documentation or examples of using it?

`key` is a standard reserved prop that all React components have, It's not particular to Recoil.  See the [React docs](https://reactjs.org/docs/reconciliation.html#recursing-on-children).

**Comment by wozzo** [comment]
Yeh, sorry meant to say I figured it out but forgot.
I still find I need to use selector families and pass the store Id with this approach to avoid the selectors being cached even where the key value changes.

**Comment by wozzo** [comment]
Ah. Cheers. Will have a play. With that next week.
Don't suppose you have an example that does that I could look at do you?
Thanks for your help

**Comment by drarmstr** [comment]
Something like:
```
atom({
  key: 'StoreID',
  effects: [
    ({setSelf, storeID}) => setSelf(storeID),
  ],
});
```

**Comment by dcantu96** [comment]
the approach above intends to update the StoreID atom with the new storeID from the `<RecoilRoot key="this-value">` and that will cause all selectors to reset/refresh ?

**Comment by kurtwilliam** [comment]
Alternatively, you can `location.reload();` to refresh the page and reset everything
