### ISSUE TITLE
Loadable.toPromise() does not return a promise that resolves to the loadable return type

### ISSUE THREAD

**Issue by wmain** [facebookexperimental/Recoil#786]
See the failing test in this repro: https://codesandbox.io/s/eager-thompson-2w4sn

According to `Loadable.toPromise`'s type signature, the returned promise should resolve to the type of the RecoilValue. What resolves, however, is an object with `__key` and `__value` properties. Am I missing something here or is this a bug?

**Comment by drarmstr** [comment]
This is a temporary regression until the open-source selector implementation changes over to the new implementation with improved async support.  We're using that internally already and just need to wrap up a few things before swapping it for the open-source build.

**Comment by wmain** [comment]
Any updates on this?

**Comment by drarmstr** [comment]
Yes, @csantos42 is getting closer to enabling this for open source.  We just ran into some minor issues with the new memory management features also under development.

**Comment by csantos42** [comment]
Should be fixed in next release! Fixed in #906
