### ISSUE TITLE
Reading value once without subscribing

### ISSUE THREAD

**Issue by moonrise-tk** [facebookexperimental/Recoil#791]
Hello! I have a question about the reading/setting API. I have a construct such that there's some editable content being stored in a `notesPage` atom. The editor handles all of the state management of the notes, and I can set it up so it updates the notes atom through an onChange handle. However, by using `useRecoilState`, I'm subscribing the `MainEditor` component to the atom, which I don't want to do. However, to show an initial page, I need to read once (the first time). How can I achieve this with Recoil? 

```
function MainEditor() {
    // TODO: how do I set this up so it reads once without subscribing?
    const [notesElement, setNotesElement] = useRecoilState(notesPage);
    return (
        <Editor
                    editorState={notesElement}
                    editable={true}
                    onChange={setNotesElement}>
        </Editor>
    );
}
```

**Comment by moonrise-tk** [comment]
I guess somehow I want to subscribe the component for updates that it hasn't made by itself but unsubscribe it for updates that are made by itself.

**Comment by drarmstr** [comment]
The common practice for React when you have hoisted state like this is that there is a single source of truth for state. The update callbacks update that state, which then propagates down with re-renders to actually update the UI. It looks like you're trying to have shared state in the atom, but also some local shadow of the state in the Editor, which is causing the extra updates you are trying to avoid. It would be cleaner to follow them React convention and keep the atom as single source of truth: require changes via the callback to update the atom to then fire the subscription, update the prop, and then re-render the Editor with the new state.  If you want to have some local or temporary edits reflected in the Editor UI before the changes are committed to the shared state, then you may want a separate "draft" state that is local and contained within the Editor for those local edits. Then, only when it is committed and to be shared with other components call the onChange() callback to update the atom. This way, when working with the local draft state, there are no subscriptions involved until it is actually committed and the Editor switches from draft state to the input prop which is from the shared atom as the source of truth.

**Comment by moonrise-tk** [comment]
Thank you for the help! I know this probably isn't the best place to ask for general architecture help, but maybe you've had this problem before, so perhaps you know how to deal with it in a "react"-y way.

The problem is that the prop I pass in to the editor is a JSON representation of the notes, which then gets parsed into a class during the initial render. Since editing requires the class to be mutable, I can't store the class itself in the atom. I certainly don't want parsing to happen after every change (user types a character) since it really destroys the speed of the editor.

I could treat the `onChange` callback as an `onCommit` callback like you said, and only write back to the atom periodically, but this still means the JSON needs to be re-parsed every so often which can really deteriorate the experience. Is there a way to use `useRecoilCallback` to get the state of an atom without subscription?

**Comment by drarmstr** [comment]
Well, one option is just not to use a JSON representation of the state for their prop.  You also don't need to combine all the the state in a single atom, but can use a collection of them. 

`useRecoilCallback()` can be used to get values without subscribing. But, had to be done via callback. E.g.

```jsx
const onCommit = useSetRecoilState(editorState);
const getInitialState = useRecoilCallback(({snapshot: {getLoadable}}) => () =>
  getLoadable(editorState).getValue()
);
return <Editor {...{getInitialState, onCommit}} />;
```
