### ISSUE TITLE
[React-native] What are the implications of the warning about time spent computing cache key?

### ISSUE THREAD

**Issue by Svarto** [facebookexperimental/Recoil#792]
Hi, thank you all so much for your work on this amazing library. I have recently started to get a warning when restarting the app in the simulator, and I am wondering what this means and what I can do to improve performance / address the warning:

`Recoil: Spent 19.368563998490572ms computing a cache key`

Then there is a long yellow warning with a datastructure that I assume is what Recoil created an atom for. In my case, it is an empty template for entering a recipe, so I was wondering if there is any way to preset the cache key or in any other way help avoid Recoil spending time computing the cache key as the data is known beforehand - i.e. could I prespecify a cache key to avoid the computing time?

**Comment by drarmstr** [comment]
Recoil uses reference equality by default for selector caches.  Is this warning referencing parameters used for an atom or selector family?  Those use value-equality by default, and can produce this warning to compute the keys.  One option is to use IDs or handles to reference complex objects instead of the objects themselves.

**Comment by FezVrasta** [comment]
@drarmstr may you please point me to the documentation where it's explained how to configure a custom id resolver?

**Comment by drarmstr** [comment]
That would be a feature request for custom equality checks for family parameters.  Related would be custom equality/serializer in #1416 request for custom equality checks for selector dependencies.
