### ISSUE TITLE
Setting an object value inside an atom returns "Cannot assign to read only property 'xxxxx' of object '#<Object>'"

### ISSUE THREAD

**Issue by pixel-mattp** [facebookexperimental/Recoil#794]
I am trying to edit a key of 'activeCourse' inside an object of an atom value.  However, whenever i do so it returns the error: 

`Cannot assign to read only property 'activeCourse' of object '#<Object>'`

The atom is called 'trainingAtom' and default value is an array of objects:

```
[
  {
     _id: '5fc42caa244ccadea8e2f263',
     activeCourse: 'r4r3545243j',
     activeDetail: null,
   },
   {
      _id: '5fc42caa244ceecadea8e2f263',
      activeCourse: null,
      activeDetail: null,
    },
]
```

I am using the following function within my component:

```
const [test, setTest] = useRecoilState(trainingAtom);

useEffect(() => {
        let _test = [...test];
        const index = _test.findIndex((val) => val._id === id);
        _test[index].activeCourse = 123456;
        setTest(_test);
}, [id]);
```

This function works if I use normal React state - but anything inside Recoil throws the error.  
Note, I have also tried to use the `set` function inside a selector but it gives the same error.  

What am I doing wrong?

**Comment by bentron2000** [comment]
I have also encountered this issue.

**Comment by cbuv** [comment]
have you tried using updater instead of value? 
like this: 
```
export const Test = ({id}: any) => {
  const [test, setTest] = useRecoilState(trainingAtom);

  useEffect(() => {
    setTest((old: any) => {
      let _test = [...old];
      const index = _test.findIndex((val) => val._id === id);
      //@ts-ignore
      _test[index].activeCourse = 123456;
      return _test;
    });
  }, [id, setTest]);
  return (<div>{JSON.stringify(test)}</div>);
}
```

**Comment by pixel-mattp** [comment]
@cbuv - this works.  Seems strange that it doesn't seem to like the spread operator from state directly.  Thanks for this.

**Comment by cbuv** [comment]
Yeah, the docs could be more clear about this. 

From the docs: (useRecoilState)
This API is similar to the React useState() hook except it takes a Recoil state instead of a default value as an argument. It returns a tuple of the current value of the state and a setter function.

I think the latter part should include how it differs from React, even if setter is best practice. Primitives can use value, but not arrays, guess setter must be used with array of primitives too

**Comment by drarmstr** [comment]
Clarified in docs #800 that atom/selector values are frozen.  

Note, this is not different from React `useState()`.  Objects used for both React and Recoil state should not be mutated directly, as this may bypass the frameworks knowledge of state changes and not properly re-render components.

**Comment by icfantv** [comment]
@drarmstr clarification on this: with the addition of the `dangerouslyAllowMutability` option in the above-referenced PR (and ignoring whether or not this would be really be considered "appropriate" behavior), are there other, negative, consequences of setting that flag to `true`, mutating the object property directly, and then calling the atom/selector setter function to update the value in state w/ the mutated object so that the app updates where so subscribed?  Thanks.

**Comment by drarmstr** [comment]
The only ramification of `dangerouslyAllowMutability` is currently to freeze the value or not.  However, mutating stored values for state changes is problematic, even if you manually trigger updates, because it may break equality checks and optimizations.

**Comment by icfantv** [comment]
@drarmstr yea, I got bit by that equality check yesterday actually.  I don't wanna thread hijack here but I do have a question about my particular use case which is sorta unique (maybe).  Where should I ask that?

**Comment by FezVrasta** [comment]
I'm still getting this error even with `dangerouslyAllowMutability`, is there something I can do to avoid it?

(we are storing a class instance inside of Recoil so we can't really avoid this)

**Comment by icfantv** [comment]
@FezVrasta TBH, that seems like a poor design choice unless you make your class instance immutable.  Please consider doing a write-up of your issue and post on StackOverflow to get better assistance (make sure you tag it with `recoiljs`).

**Comment by artygrand** [comment]
@drarmstr I trying to use updater as @cbuv suggests, but in my case, I have list of big deep nested objects.
For example if I need just to change `status` in `lots[].clients[].bid.status`, I have to write like below to avoid error

```
let lots= [...old];

...

let lot = {...lots[x]};
let client = {...lot.clients[y]};
let bid = {...client.bid}
bid.status = val as BidStatus;
client.bid = bid;
lot.clients = [...lot.clients];
lot.clients[y] = client;
lots[x] = lot;

...

return lots;
```

Should I use dangerouslyAllowMutability or it is possible in any other way?

**Comment by icfantv** [comment]
@artygrand this seems like a great question for StackOverflow.
