### ISSUE TITLE
Hydrate multiple atoms' state on demand

### ISSUE THREAD

**Issue by lmartins** [facebookexperimental/Recoil#799]
Is there a way with Recoil that allows me to re-hydrate the app's overall state on-demand?

I'm already persisting data from local storage, and it is working beautifully, but now I need to extend that to also allow a user to load state from a previous "snapshot" that has been stored into that user's profile on a different application. Is this doable with the current APIs?

**Comment by lmartins** [comment]
@drarmstr thanks so much for your input.

Perhaps my wording here was not the ideal, as I'm not working with an actual recoil snapshot. My intent was to essentially pull data from an API, loop through the keys of the object that is returned, and essentially load each value into the corresponding  atom. Essentially in a process similar to what the Recoil Persist library does for localStorage https://github.com/polemius/recoil-persist/blob/c823ce064b18a15ab8285408730d00b8fb434228/index.js#L36

In that library, because it is attached to the initialState from `recoil-root`, I have access to the `set` function and allows me to use that. Looking through the docs I'm having some trouble identifying what would be the best alternative.

In this scenario is snapshots still the suggested approach?

**Comment by drarmstr** [comment]
[`useRecoilCallback()`](https://recoiljs.org/docs/api-reference/core/useRecoilCallback) may be appropriate here for creating a callback which can be used to hydrate a set of known atoms in a type-safe way.

**Comment by lmartins** [comment]
Okay, I will give it a try and post here if I get it to work in case it is useful for anyone else. Thank you for the feedback Douglas.

**Comment by lmartins** [comment]
@drarmstr `useRecoilCallback` worked beautifully for what I was trying to achieve. 

I'm hesitant to post it as an example because while it is working without unwanted side-effects, I am getting `recoil.js:2316 Uncaught TypeError: fn(...) is not a function` when I run the callback. 

The callback setup looks like this:
```js
const loadStoredConfig = useRecoilCallback(({ set }) => {
    refetch().then((data) => {
      hydrateState({ data, set });
    });
});
```

The implementation for `hydrateState` looks like this:
```js
  function hydrateState({ data, set }) {
    Object.keys(data).forEach((key) => {
      try {
        let stateKey = lookupAtomWithKey(key);
        set(stateKey, data[key]);
      } catch (error) {
        console.error(error);
      }
    });
  }
```

I'll close this for now, please let me know if posting the full example would be of any use here.

Thanks so much for all the help.

**Comment by drarmstr** [comment]
To avoid that error you may want to try:

```jsx

const loadStoredConfig = useRecoilCallback(({ set }) => () => {
    refetch().then((data) => {
      hydrateState({ data, set });
    });
});
```

**Comment by Ice-wiz** [comment]
thanks , I was looking for the same thing
