### ISSUE TITLE
Consideration of API for decorator about atom() and selector()

### ISSUE THREAD

**Issue by unadlib** [facebookexperimental/Recoil#80]
It seems that the current use of atom() and selector() is a bit cumbersome, whether to consider supporting decorator forms as well, such as this:
```js
class Counter {
  @atom
  myCounter = 0;

  @action
  increase() {
     this.myCounter += 0;
  }

  @computed
  get num() {
     return this.myCounter + 1;
  }
}
```

**Comment by drarmstr** [comment]
You would still need to specify a key and other optional options for the nodes.  So, I don't see that it would really save lines.  Decorators are also currently less idiomatic Javascript.  Do you see something that could be more succinctly expressed via decorators?
