### ISSUE TITLE
Can I initialize atom family with RecoilRoot?

### ISSUE THREAD

**Issue by arncet** [facebookexperimental/Recoil#807]
Hello, 
I'm looking for a way to initialize some atom family with RecoilRoot's `initializeState`.
My `App` component has props (options) that need to be propagate to children. 
To prevent passing them from parents to deep children i choose to create a store with these options.
My `App` contains a lot of heavy components that need some part of options and i don't want all those components update when a piece of options change, that's why i decide to not put all my options inside an object (classic atom).
`atomFamily` looks great for this case, but i dont know how to initialize options before the first render.

This is what my project looks like :

```js
// Defined options atom family
const optionsState = atomFamily({
   key: 'optionsState',
   default: null
})

// App root
const App = ({ optionA, optionB, optionC }) =>
  <RecoilRoot initializeState={???}>
    ... // deep children
    <HeavyComponentA />
    <HeavyComponentB />
    <HeavyComponentC />
  </RecoilRoot>

// HeavyComponentA need to re-render only when option 'A' change
const HeavyComponentA = () => {
  const optionA = useRecoilValue(optionsState('A'))
```

**Comment by drarmstr** [comment]
Initializing atom family state with `initializeState` is difficult. Consider using Atom Effects for state initialization.

**Comment by arncet** [comment]
Thanks @drarmstr, i'll look for this way.
