### ISSUE TITLE
Duplicate atom key "verification-step". This is a FATAL ERROR in production. But it is safe to ignore this warning if it occurred because of hot module replacement.

### ISSUE THREAD

**Issue by prantaDutta** [facebookexperimental/Recoil#809]
Hi, I am new to Recoil, actually, I am trying it today. So I have this warning in my terminal. I don't understand why hot module replacement will create this warning? Should I do something about this? I am using nextjs not react btw.

**Comment by drarmstr** [comment]
Duplicate of #733
