### ISSUE TITLE
[question] how can I design a `selector` when using `atomFamily`

### ISSUE THREAD

**Issue by postbird** [facebookexperimental/Recoil#810]
The sample program is a TODO application, and I use `atomFamily` to seprate the large list to improve performance.

It works well, if I modify any todo item, it only re-render itself not the whole list.

The `atom` I defined: (notice that I dont use selector to filter todo list here)

```javascript
// atom to store ids
const todoIds = atom({
	key: uuidv4(),
	default: [],
});

// atomFamily to store each todo
const todoWithId = atomFamily({
	key: uuidv4(),
	default: [],
});

// component example:
const List = () => {
  const ids = useRecoilValue(todoIds);
  return ids.map(id => <TodoItem id={id} key={id}>)
}
```

however, if I need to filter the todo list (such as: `ALL`/`COMPLETED`/`ACTIVE`), it dones't work.

I add a new atom and a selector, render list with `selector value` not ` atom value`

it caused that when I modified a todo's info, the whole list will be re-rendered each time.

```javascript
// atom to store filter options
const todoFilter = atom({
	key: uuidv4(),
	default: 'ALL',
});

// a selector to filter ids
const todoIdsByFilter = selector({
	key: uuidv4(),
	get: ({ get }) => {
		const ids = get(todoIds);
		const filter = get(todoFilter);
		return ids.filter(id => {
			const todo = get(todoWithId(id));
			switch (filter) {
				case 'COMPLETED':
					return todo.completed;
				case 'ACTIVE':
					return !todo.completed;
				default:
					return true;
			}
		});
	},
});

//component example:
const List = () => {
  const ids = useRecoilValue(todoIdsByFilter);
  return ids.map(id => <TodoItem id={id} key={id}>)
}
```

**Is there any best practice to let me known how to design the selector in this scenes?**

demo with `selector` filter:

![GIF](https://user-images.githubusercontent.com/16200574/103306443-89818680-4a48-11eb-933b-d7786b50a526.gif)

demo without filter selector:
![GIF3](https://user-images.githubusercontent.com/16200574/103306686-26dcba80-4a49-11eb-8e71-c3c82b6eadc9.gif)

**Comment by drarmstr** [comment]
Optimizations like #749, when activated, will help avoid re-renders if the value of the selector for the list of IDs doesn't actually change.  Though, that optimization is still based on reference-equality, and so may require memoization of the selector value for objects.

If you maintain the state which determines a TODO visibility separately, that can also avoid re-renders.  For example, if your filtering is based on "completed," then having a separate atom family for the completed state means updating other parts of the TODO detail won't cause an update to the ID list selector.

But additionally, consider where re-rendering is actually a real performance concern for your application to focus your efforts and avoid premature optimization.

**Comment by pthieu** [comment]
@postbird did you resolve this?
