### ISSUE TITLE
Recoil set state on mount unreliable

### ISSUE THREAD

**Issue by leofab86** [facebookexperimental/Recoil#816]
I have a scenario where a component mounts and needs to update recoil state immediately (so that the UI shows the updated state on the first frame instead of flashing the non-updated state first)

With react useState and useLayoutEffect, I seem to be able to rely on the useState update showing up in the first frame. But not so with Recoil set state. In some components it works, where the recoil update is in time before the paint, while others it doesn't.

Is this something we could theoretically control? Or is it just dumb luck?

**Comment by drarmstr** [comment]
Setting a Recoil State in an effect after the first render will update the state with the next batch.  So, you will get a re-render.  To avoid that, you can initialize state for the first render using [Atom Effects](https://recoiljs.org/docs/guides/atom-effects) or the [`initializeState`](https://recoiljs.org/docs/api-reference/core/RecoilRoot) prop of `<RecoilRoot>`.
