### ISSUE TITLE
French Documentation Translation

### ISSUE THREAD

**Issue by Keized** [facebookexperimental/Recoil#817]
I wish to contribute to the translation of the documentation into French. A PR has already been open for 6 months for the French translation. In this case, can I open a second to add the translations of the last documentation version ?

**Comment by drarmstr** [comment]
Best if we can consolidate into a single PR.  

@csantos42 - Any update on adding the index of translations so we can merge the translation PRs?

**Comment by fguitton** [comment]
This is already being tracked in #377 with the latest changes.
Any proof-readying is most welcomed, don't hesitate to comment or suggest changes.
There is some documentation changes in #744 which haven't been done, waiting for the v0.2 as suggested.

**Comment by drarmstr** [comment]
Duplicate of #377
