### ISSUE TITLE
Should errors from Atom Effects get caught by error boundaries?

### ISSUE THREAD

**Issue by sebinsua** [facebookexperimental/Recoil#818]
[Similar to this issue](https://github.com/facebookexperimental/Recoil/issues/669#issuecomment-720228581), I have some UI state that I'd like to save to a backend.

I thought I could use Recoil's experimental [Atom Effects](https://recoiljs.org/docs/guides/atom-effects/#write-through-cache-example) to achieve this, and that this would allow me to colocate any logic to debounce requests or retry on failure.

However, on trying this, I noticed that [errors produced by this would not caught by the error boundaries I'd setup (CodeSandbox link)](https://codesandbox.io/s/hungry-haze-muhco?file=/src/App.js).

Is this the expected behaviour? What patterns are people using to deal with errors that happen within `onSet`? I had thought that I might also get Suspense 'loading' behaviours from Atom effects but that also doesn't appear to be the case.

In this situation I might be able to get away with just catching and logging an error, but I would like to have a better understanding of different approaches. The Recoil docs are good at explaining all of the APIs but there are so many ways of doing things, and I don't know the pros/cons and best practices.

*e.g.*

```js
import React, { Suspense } from "react";
import { ErrorBoundary } from "react-error-boundary";
import { RecoilRoot, atom, useRecoilCallback } from "recoil";

const badAtom = atom({
  key: "badAtom",
  /** @type {string | undefined} */
  default: undefined,
  effects_UNSTABLE: [
    ({ onSet }) => {
      onSet(async (value) => {
        // throw new Error("Sync error");

        await new Promise((_, reject) => {
          setTimeout(
            () => reject(new Error(`This ${value} should be caught... `)),
            5000
          );
        });
      });
    }
  ]
});

function BadItem() {
  const handleClick = useRecoilCallback(
    ({ set }) => () => {
      set(badAtom, "error");
      // throw new Error("Sync error");
    },
    []
  );

  return <button onClick={handleClick}>Click Me!</button>;
}

export default function App() {
  return (
    <div className="App">
      <RecoilRoot>
        <ErrorBoundary
          fallbackRender={({ error }) => <div>{error.message}</div>}
        >
          <Suspense>
            <BadItem />
          </Suspense>
        </ErrorBoundary>
      </RecoilRoot>
    </div>
  );
}
```

**Comment by drarmstr** [comment]
Errors thrown within the `onSet()` handler wouldn't propagate up to the render, they are executed as async side-effects after a React batch.  In React, side-effects shouldn't occur during a render.  Similarly, the error thrown in your `handleClick()` callback is also not executed during a render, but called asynchronously later outside of the render.  As such, errors during these async callbacks don't occur during the render and won't be caught by `<ErrorBoundary>`'s. 

In addition, while the handler passed to `onSet()` is called asynchronously when the Recoil State is set, it itself is not an `async` function and should not return a `Promise`.  Returning a rejected `Promise` from the handler is meaningless.  TypeScript or Flow should warn about this mismatched type signature.

To catch errors during an `onSet()` handler or other async callback, you could add a `try/catch` block within the handler itself.

**Comment by DevonStern** [comment]
@drarmstr If errors thrown during the execution of an atom effect are not supposed to be caught by error boundaries, then why does the [documentation](https://recoiljs.org/docs/guides/atom-effects/#error-handling) say so? I have been trying to get an error thrown by an atom effect to be caught by an error boundary, so if that's not actually possible it would be good to update the docs. ;)

Also, if an error occurs in an atom effect, is there any way to revert the atom to its previous state before it was last set? We're mostly using atom effects to save state, either to the device or to a server, and if it fails to save I would like to revert to the previous state so it is in sync with the persisted data. Is there a simple way to do this?

**Comment by drarmstr** [comment]
The callbacks provided to `onSet()` are called later on asynchronously, not from the atom effect function.  That's similar to errors thrown by a callback in `useTimeout()` not able to be caught by the function calling the `setTimeout()`.  They are handled from React batching, not individual sets.  Errors from the atom effect function itself do update the atom value and are thus then caught by error boundaries around components using those atoms.  If you want to handle errors and revert in an atom effect you can use a traditional `try/catch` to catch the error and avoid calling `setSelf()`.  For async cases you can have a Promise resolve to a `new DefaultValue()` to abort async initializations.

**Comment by DevonStern** [comment]
I see, thank you for the clarification!
