### ISSUE TITLE
selectorFamily() missing from recoil?

### ISSUE THREAD

**Issue by shubhaemk** [facebookexperimental/Recoil#82]
selectorFamily and many other Utility features seems missing or am I doing something wrong?

**Comment by drarmstr** [comment]
We want to keep the core API simple.  So, we export optional helpers that are built on top of the core API in a separate utils module.  @claudiopro I think #33 tries to update the open-source build to properly export these?

**Comment by shubhaemk** [comment]
Thanks for the clarification. Ill close the issue now.

**Comment by drarmstr** [comment]
The code's all in there, though, so hopefully you can still use it in the meantime while we're trying to polish up the builds and export.

**Comment by shubhaemk** [comment]
> @shubhaemk - The code's all in there, though, so hopefully you can still use it in the meantime while we're trying to polish up the builds and export.

Yes. Totally, I can also build it for my own use with the build tool I know, till it's released.

**Comment by ryansolid** [comment]
Ahh.. I see. And it's actually never been part of a successful npm release (I tried all 7 versions) before finding this issue. Hopefully this will be fixed soon, it's blocking me submitting to benchmarks (automated/version controlled) and kinda critical for performance in those benchmarks.
