### ISSUE TITLE
Access node metadata in useRecoilTransactionObserver

### ISSUE THREAD

**Issue by hellosmithy** [facebookexperimental/Recoil#821]
Apologies if there is a way to do this that I've missed. But it appears that the metadata attached to atom nodes for e.g. `persistence_UNSTABLE` are not accessible from inside the `useRecoilTransactionObserver_UNSTABLE` hook.
It was my understanding that this is the hook for managing custom persistence logic, so it would seem logical to be able to introspect on persistence metadata here.

In addition it would be useful to be able to add arbitrary custom metadata here for third-party libraries to build on top of Recoil. Is this planned to be supported?

For example:

```TypeScript
export const myToggle = atom({
  key: 'myToggle',
  default: true,
  persistence_UNSTABLE: {
    type: 'url',
  },
});

...

useRecoilTransactionObserver_UNSTABLE(({ snapshot }) => {
  for (const node of snapshot.getNodes_UNSTABLE({ isModified: true })) {
    // node does not have `persistence` on it as it's of type RecoilState not Node
  }
});
```

**Comment by drarmstr** [comment]
`persistence_UNSTABLE` is deprecated.  Please review the [Atom Effects](https://recoiljs.org/docs/guides/atom-effects) guide for updated persistence capability.  Effects were built to help allow management of custom metadata in a composable, type-safe way and keep it out of the Recoil core.
