### ISSUE TITLE
I need the lifecycle methods (through class components) in react but in the same time I don't want to lose the convenience of Recoil. Please help!

### ISSUE THREAD

**Issue by manyopensource** [facebookexperimental/Recoil#824]

**Comment by drarmstr** [comment]
The lifecycle methods mostly have equivalents when using hooks that generally end up cleaner and better co-locate logic.  See the [React docs](https://reactjs.org/docs/hooks-faq.html#how-do-lifecycle-methods-correspond-to-hooks).  Some exceptions include methods for error boundaries, but you can generally use those in dedicated components that don't need Recoil.

**Comment by manyopensource** [comment]
@drarmstr 

I have a problem with react portals, I can't clear the portal component (functional) using `portalNode.innerHTML = '';`. This clears even new data that are being rendered there. So I thought I need lifecycle methods to solve it. If you could help me with this I'd appreciate that!

**Comment by drarmstr** [comment]
Manually changing innerHTML in React sounds dangerous.  Anyway, class components and functional components can work side-by-side.  So, you can also refactor legacy logic in a wrapper or helper component or user a wrapper component to access Recoil and pass state/setters as props, etc.

**Comment by manyopensource** [comment]
@drarmstr 

The html came from the server and I need to rerender the content on the client (I have the data).

**Comment by manyopensource** [comment]
Solved! Thanks!
