### ISSUE TITLE
App stuck / crash when trying to increment an atom from several components

### ISSUE THREAD

**Issue by yemd** [facebookexperimental/Recoil#827]
I am trying to keep track of different rendering status, for that, I'm trying to increment an atom from those components.

Trying to increment the same atom from those components causes the App to hang.

It happens when components are trying to update the state with different values, all atoms updating with the same value work.

Using Expo, it starts to take all my CPU and I have to kill the client, this naive way of implementing it might be the cause,

I also tried with selectors and I have the same effect

```
export const cardsCountState = atom({
    key: 'cardsCountState',
    default: 0
})

```
```
    const [cardsCount, setCardsCount] = useRecoilState(cardsCountState);

    useEffect(() => {
            setCardsCount(Math.floor(Math.random() * 100))
        }
    )
```

**Comment by drarmstr** [comment]
This implementation looks problematic.  In it there is a component which subscribes to state changes via `useRecoilState()` and will re-render when the state changes.  The same component sets up a side-effect using `useEffect()` to change the state with each render.  I would expect this to go into an infinite loop.

If you want a component to be able to update some state without also subscribing to re-render itself when that state changes you can use the [`useSetRecoilState()`](https://recoiljs.org/docs/api-reference/core/useSetRecoilState) hook.

**Comment by yemd** [comment]
Thanks for your input, indeed, it was not the most practical way to implement it, will try useSetRecoilState nonetheless for the sake of knowing
