### ISSUE TITLE
recoil-toolkit: Contribution to Recoil community

### ISSUE THREAD

**Issue by salvoravida** [facebookexperimental/Recoil#839]
https://github.com/salvoravida/recoil-toolkit

Hi folks, i'm going do develop some hi level wrapper for recoil, 
like useRecoilTask, and some plus features!

May give some help/ideas to the great work of recoil!

**Comment by drarmstr** [comment]
Great to hear about this @salvoravida!  As you work through and mature some patterns, it would be great to touch base on what is popular and what the pain points are.  Please keep us updated!
