### ISSUE TITLE
Warning: Cannot update a component (`he`) while rendering a different component

### ISSUE THREAD

**Issue by atanasster** [facebookexperimental/Recoil#84]
Hi,

Thanks a lot for this library, it looks great and comes at a perfect time :)

Anyone seeing this warning when using `useRecoilState`/ `useRecoilSetState` in a component (ie a checkbox) while updating the atom async from another component?

I am not using any `useState` myself and the on top of the call stack is the line of code that calls `useRecoilState` although no details from a call stack in recoiljs itself are shown.

If its not a known issue, please let me know what will help the most - I can post the link to my git repo (with a bit more code), or try to re-create a sample.

![grab60](https://user-images.githubusercontent.com/6075606/82159257-f39f3f80-985a-11ea-85b4-86e2989eea84.jpg)

**Comment by acutmore** [comment]
Hi @atanasster. #12 covers this issue.

**Comment by atanasster** [comment]
oh, thanks - its being looked at, so I will close this issue

**Comment by lippyDesign** [comment]
What is the status of this? For us it happens when we use selector to select data from an atom that depends on api state

**Comment by vivek12345** [comment]
do we have an update here? What is the solution? I am facing a similar error. Using recoil selector for an async call.

**Comment by drarmstr** [comment]
Duplicate of #12

**Comment by codal-hkrishnani** [comment]
I was facing same issue, The fix worked for me was if u are doing  

> setParams/setOptions

 outside of useEffect then this issue is occurring. So try to do such things inside useEffect. It'll work like charm
