### ISSUE TITLE
[question] how to prefetch selectFamily

### ISSUE THREAD

**Issue by sunginHwang** [facebookexperimental/Recoil#841]
i study for recoil `query Refresh` like this [asynchronous-data-queries](https://github.com/facebookexperimental/Recoil/blob/docs/docs/docs/guides/asynchronous-data-queries.md)

### query Refresh example code
```jsx
const userInfoQueryRequestIDState = atomFamily({
  key: 'UserInfoQueryRequestID',
  default: 0,
});

const userInfoQuery = selectorFamily({
  key: 'UserInfoQuery',
  get: userID => async ({get}) => {
    get(userInfoQueryRequestIDState(userID)); // Add request ID as a dependency
    const response = await myDBQuery({userID});
    if (response.error) {
      throw response.error;
    }
    return response;
  },
});

function useRefreshUserInfo(userID) {
  setUserInfoQueryRequestID = useSetRecoilState(userInfoQueryRequestIDState(userID));
  return () => {
    setUserInfoQueryRequestID(requestID => requestID + 1);
  };
}

function CurrentUserInfo() {
  const currentUserID = useRecoilValue(currentUserIDState);
  const currentUserInfo = useRecoilValue(userInfoQuery(currentUserID));
  const refreshUserInfo = useRefreshUserInfo(currentUserID);

  return (
    <div>
      <h1>{currentUser.name}</h1>
      <button onClick={refreshUserInfo}>Refresh</button>
    </div>
  );
}
```

Refresh is work. and i want add `prefetch` using for useRecoilCallback. but prefetch is not working for `userInfoQuery`
because  `userInfoQuery` has dependency (userInfoQueryRequestIDState) 

how to work `selectorFamily` prefetch with atomFamilyDependency.. 
plz help :)

**Comment by drarmstr** [comment]
In the code you pasted above, `userInfoQuery` is a selector family that takes a `userID` as a parameter.  It depends on `userInfoQueryRequestIDState`, but that is also a family and it passes the `userID` parameter.  So, issuing a query should have consistent state.  The Request ID is used to manually re-fresh the query, but that state is only incremented per-userID when manually refreshing.  So, that shouldn't impact a pre-fetch unless you are also incrementing that ID as part of query/prefetch steps.  I don't see the pre-fetch code in your example, though.

**Comment by sunginHwang** [comment]
@drarmstr 
thanks for help

i write pre-fetch code like this
```jsx
 const changeUser = useRecoilCallback(({snapshot, set}) => async (userID: number) => {
        await set(userInfoQueryRequestIDState(userID), 999); // selectorFamily dependency update~!! 
        snapshot.getLoadable(userInfoQuery(userID)); // but not changed dependency value
    });
```

i expected like this case
1. userInfoQueryRequestIDState changed 999 
2. load userInfoQuery (dependency changed 0 -> 999) 

but `userInfoQueryRequestIDState` changed after running `snapshot.getLoadable(userInfoQuery(userID))` .

How can I run `userInfoQueryRequestIDState` change first?

**Comment by drarmstr** [comment]
@sunginHwang - `set()` does not return a `Promise`; you can't `await` that call.  Moreover, I'm not sure why you want to set the Request ID at that point?  changing the Request ID was intended to re-query to [replace an existing cached query result](https://recoiljs.org/docs/guides/asynchronous-data-queries#use-a-request-id).  In this case for the initial query for a new userID there shouldn't be a need.  What is likely happening for you is that you are pre-fetching the query based on the default Request ID, then setting the Request ID to 999 takes effect which causes the pre-fetch to be ignored.  The solution should hopefully just be removing the `set()` line.
