### ISSUE TITLE
Initializing Recoil Root for Jest/React-testing-library unit testing

### ISSUE THREAD

**Issue by lleki** [facebookexperimental/Recoil#846]
Hi! I'm having a hard time setting up a testing environment to mock my recoil state to test my component. 

Getting error: Uncaught [Error: Missing definition for RecoilValue: "undefined""]

I'm using `atomFamily` for my `selectedRateState` so that I can use a selector as default value but replicating this to test is proving quite difficult. If I switch `selectedRateState` to just `atom` like for `currentRateInformation` then I think it works. but I will need access to my selectors in default value which I can't if I use atom. Any help would be appreciated.

/store/atom
```
export const currentRateInformation = atom({
    key: 'currentRateInformation',
    default: undefined,
});

export const selectedRateState = atomFamily({
    key: 'selectedRateState',
    default: getSelectedRate,
});
```

/selectors

```
export const getSelectedRate = selectorFamily({
    key: 'getSelectedRate',
    get: (id) => async () => {
        try {
            const { data } = await apiClient.getSelectedRate(id);
            const rateInfo = extractRelevantRateInfo(data);
            return rateInfo;
        } catch (error) {
            console.error('getSelectedRate error', error);
            throw error;
        }
    },
});
```

RateDetails.tsx

```
export const RateDetails = withI18n()(({ rateId, i18n, onBackClick }: any) => {
    const rate = useRecoilValue(selectedRateState(rateId));

    return (
        <>
            <StyledButtonContainer>
                <Button
                    data-testid="expanded-page-back-button"
                    secondary
                    icon={<ChevronIcon />}
                    label={i18n._('back')}
                    onClick={onBackClick}
                    size="medium"
                />
            </StyledButtonContainer>
         ...
        </>
    );
});
```
RateDetails-test.tsx

```
import React from 'react';
import { fireEvent, waitFor, render } from '@testing-library/react';
import { RecoilRoot } from 'recoil';

import { currentApplicationIdState, selectedRateState } from 'store/atom';
import { product } from 'components/rates/rate-page-subsection.test';

import { RateDetails } from '../[rateId]';

describe('Expanded Page', () => {
    const initializeState = ({ set }: any) => {
        set(currentApplicationIdState, 123);  <--- this works
        set(selectedRateState, () => product); <--- fails here
    };
    it('RateDetails: back button should go back', async () => {
        const backMock = jest.fn();

        const { findByTestId } = render(
            <RecoilRoot initializeState={initializeState}>
                <RateDetails rateId="16996" onBackClick={backMock} />
            </RecoilRoot>
        );

        const backButton = await findByTestId('expanded-page-back-button');

        fireEvent.click(backButton);
        expect(backMock).toHaveBeenCalled();
    });
});
```

**Comment by drarmstr** [comment]
What is the issue you are trying to report?  I see this comment in your source:

>        set(selectedRateState, () => product); <--- fails here

This shouldn't work because `selectedRateState` is an atom family, not an atom, so it is a function you need to call to get the actual atom. 

>        set(selectedRateState(id), () => product);

**Comment by lleki** [comment]
> What is the issue you are trying to report? I see this comment in your source:
> 
> > ```
> >    set(selectedRateState, () => product); <--- fails here
> > ```
> 
> This shouldn't work because `selectedRateState` is an atom family, not an atom, so it is a function you need to call to get the actual atom.
> 
> > ```
> >    set(selectedRateState(id), () => product);
> > ```

Oh, I thought the first param of set() was referring to the 'key' not the actual function. Now that I made your suggested change, I get this error

Error: Uncaught [Error: Tried to set the value of Recoil selector selectedRateState__1__withFallback using an updater function, but it is an async selector in a pending or error state; this is not supported.]

My goal is not really to test the atoms/selectors but just to mock it enough for me to test the trigger of my `onBackClick` call. In past tests, it was enough what I had because I referred to atom, not atom family. Now that I need to mock atom family, I'm unsure how to proceed.

thanks!

**Comment by drarmstr** [comment]
Not sure I can help more without really diving into your testing environment.  If you're just trying to mock atom families out, it might be sufficient to mock them with a `memoize()` wrapper around an `atom()` call.

**Comment by lleki** [comment]
> Not sure I can help more without really diving into your testing environment. If you're just trying to mock atom families out, it might be sufficient to mock them with a `memoize()` wrapper around an `atom()` call.

oh yes thats exactly what I wanted to do. I'll try that! thanks

**Comment by itsankitverma** [comment]
This thread helped me a lot. Thanks for sharing.
