### ISSUE TITLE
handle api request in selector or initializeState

### ISSUE THREAD

**Issue by 1omercohen** [facebookexperimental/Recoil#848]
in both away, i get data but it not set to recoil atom it is still empty
that my daom =>
`
const DataAtom= atom({
    key: "csrStatusState",
    default: []
});
`
that init from rootRecoil =>
`
const initializeState = async({ set }) => {
    let response = await api.call();
    console.log('data', respnse.data)
    set(DataAtom, response.data)
};
`
or
`
const setInitData= selector({ 
  key: "setInitData",
   set:async ({set, get, reset}) =>{
   const response = await api.call();
    set(DataAtom, response.data)
   }
 })
`
the DataAtom is still empty Array

**Comment by Hainesy** [comment]
Set the default on your atom to be a selector with a `get` that returns your promise.

i.e.

```
const DataAtom = atom({
  key: "csrStatusState",
  default: selector({
    key: `my-key`,
    get: () => api.call().then(response => response.data)
  })
});
```

**Comment by drarmstr** [comment]
Thanks @Hainesy !  Yes, an async selector will work for asynchronously setting a default and having the atom in a pending state until then.  The `initializeState` prop in `<RecoilRoot>` is not async and will not update the state after initial synchronous initialization.
