### ISSUE TITLE
How to refresh/invalidate an asynchronous selector?

### ISSUE THREAD

**Issue by philippta** [facebookexperimental/Recoil#85]
Selectors can be used to asynchronously fetch data from an API. But how is it possible to trigger a re-fetch of this data?

Given this selector:
```javascript
const todosState = selector({
  key: "todosState",
  get: async () => {
    const result = await fetch("https://example.com/todos");
    const todos = await result.json();
    return todos;
  },
});
```
In a scenario where a user wanted to reload his todos, because he knows his coworker added a new todo to the list. How would he trigger this selector to re-fetch the todos from the API?

**Comment by acutmore** [comment]
Hi @philippta. Selectors are re-run when an atom/selector it uses (depends on) changes. To force a selector to update you could do something like this:

```javascript
const forceTodoUpdate = Recoil.atom({
  key: "forceTODO",
  default: 0,
});

const todosState = selector({
  key: "todosState",
  get: async ({ get }) => {
    get(forceTodoUpdate); // 'register' forceTodoUpdate as a dependency
    const result = await fetch("https://example.com/todos");
    const todos = await result.json();
    return todos;
  },
});

function Component() {
  const todoUpdates = useSetRecoilState(forceTodoUpdate);
  const forceUpdate = () => todoUpdates((n) => n + 1);
  const todos = useRecoilValue(todosState);

  // rest of component here
}
```

**Comment by AjaxSolutions** [comment]
@acutmore How would you abort the fetch on unmount in this example?

**Comment by philippta** [comment]
@acutmore Thanks for your suggestion. Although your code works as intended, it feels more like a workaround instead of an official solution. I genuinely thought this update could be triggered using the `useResetRecoilState()` function. 

An obvious way to make this less of a workaround would be to simply use an atom and handle the update manually. However, I really like the concept of the [Data Flow Graph](https://recoiljs.org/docs/guides/asynchronous-data-queries#data-flow-graph) mentioned in the doc, which makes data fetching really declarative and implicit for the consumer of the selector.

How about adding a re-evaluate feature to the API, either with `useResetRecoilState()` or with a new function in the [selector options](https://recoiljs.org/docs/api-reference/core/selector)?

**Comment by acutmore** [comment]
Hi @philippta. I agree, does feels more like a workaround. Maybe someone from the Recoil team will have a more official solution.

I had another go using `useResetRecoilState`. Calling `reset` sets an Atom's value back to the `default: ...` value in the Atom's config, or calls a selector's `set` passing in Recoil's `DefaultValue`. I had a go and selectors do not seem to support async set. So this gets back to synchronously updating an atom to force a selector's async get to re-run.

```javascript
const todosTrigger = atom({
  key: "todosTrigger",
  default: 0
});

const todosSelector = selector({
  key: "todosSelector",
  get: async ({ get }) => {
    get(todosTrigger);
    return await getTodos();
  },
  set: ({ set }, value) => {
    if (value instanceof Recoil.DefaultValue) {
      set(todosTrigger, v => v + 1);
    }
  }
});

function Todos() {
  const todos = useRecoilValue(todosSelector);
  const reset = useResetRecoilState(todosSelector);
  console.log(todos);
  return <button onClick={() => reset()}>Reset</button>;
}
```

**Comment by acutmore** [comment]
> @acutmore How would you abort the fetch on unmount in this example?
@AjaxSolutions 

Good question. I do not know. I raised #51 to ask about how cancelation might work.

**Comment by davidmccabe** [comment]
@acutmore 's example is exactly what I was going to suggest. Good work!

**Comment by atulmy** [comment]
I'm facing following warning when using above described method to force cache update:

```
Warning: Cannot update a component (`he`) while rendering a different component (`List`). To locate the bad setState() call inside `List`, follow the stack trace as described in https://fb.me/setstate-in-render
    in List (created by Context.Consumer)
    in Route (at Layout/index.js:43)
    in Switch (at Layout/index.js:32)
    in main (at Layout/index.js:27)
    in Router (created by BrowserRouter)
    in BrowserRouter (at Layout/index.js:20)
    in Layout (at src/index.js:13)
    in RecoilRoot (at src/index.js:12)
    in StrictMode (at src/index.js:11)
```

```javascript
// auth
export const userAuth = atom({
  key: 'userAuth',
  default: userAuthDefault
})
```

```javascript
// note list
export const noteList = selector({
  key: 'noteList',
  get: async ({ get }) => {
    // force update cached data based on user
    get(userAuth)

    let notes = []

    try {
      const { data } = await list()

      if(data && data.success) {
        notes = data.list
      }
    } catch (e) {
      console.log(e.message)
    }

    return notes
  }
})
```

Any idea what may be going wrong?

**Comment by acutmore** [comment]
Hi @atulmy. The warning you are seeing is a known issue, more details here: #12. For now it should be safe to ignore it.

**Comment by tobias-tengler** [comment]
> 
> 
> Hi @philippta. I agree, does feels more like a workaround. Maybe someone from the Recoil team will have a more official solution.
> 
> I had another go using `useResetRecoilState`. Calling `reset` sets an Atom's value back to the `default: ...` value in the Atom's config, or calls a selector's `set` passing in Recoil's `DefaultValue`. I had a go and selectors do not seem to support async set. So this gets back to synchronously updating an atom to force a selector's async get to re-run.
> 
> ```js
> const todosTrigger = atom({
>   key: "todosTrigger",
>   default: 0
> });
> 
> const todosSelector = selector({
>   key: "todosSelector",
>   get: async ({ get }) => {
>     get(todosTrigger);
>     return await getTodos();
>   },
>   set: ({ set }, value) => {
>     if (value instanceof Recoil.DefaultValue) {
>       set(todosTrigger, v => v + 1);
>     }
>   }
> });
> 
> function Todos() {
>   const todos = useRecoilValue(todosSelector);
>   const reset = useResetRecoilState(todosSelector);
>   console.log(todos);
>   return <button onClick={() => reset()}>Reset</button>;
> }
> ```

Is this still the recommended approach? Still feels like a workaround. 😕We're just trying out Recoil with a new project at the moment and we already have 3 of those triggers, which are becoming kind of unwieldy.

Having an API to re-run a selector would make more sense in my opinion. Something like an extension of the previously mentioned `useResetRecoilState`. That way the operation would be tied to a specific selector directly, like `useResetRecoilState(mySelector)`, and not indirectly via a `useSetRecoilState(mySelectorTrigger)`.

Since the library is pretty new and it's our first time using it, maybe we're also just using it incorrectly...
Let's imagine we have a table of entries, to which we like to apply filters. Our filters are atoms. We fetch the entries with an async selector and then `get` the entries and the filters in a separate selector, where we apply the filters to the entries. Then we use this `filteredEntriesSelector` in our component.
This works perfect, until the user navigates away from the page (we use react-router, the page is not refreshed) and then back to the page again. Now he is being shown stale data, since the selector is not re-run again. Currently we solve this by running the trigger workaround, when the user clicks on the button that navigates to the page.

Are we doing this correctly and recoil is limited in that regard or are we using it incorrectly?

**Comment by flurescein** [comment]
Totally agree with @tobias-tengler! `useSetRecoilState` for selectors is what recoil lacks to be most perfect state management library. Recoil is already a beauty silver bullet, but using a trigger atom looks like a weird safety catch.

**Comment by drarmstr** [comment]
Are you using selectors here vs atoms because you want the automatic use of React Suspense for the pending state?  If so, then would being able to set an atom to a pending Promise be seen as a cleaner solution for this pattern?

**Comment by flurescein** [comment]
@drarmstr, your words are sweet as honey! But I can't use Promise as default now, isn't it?

In my (imaginary) application, atom gets data from the server. This state is used in many components, but user can refetch the default state. Right now, I see no way to do this other than creating a fetch counter. But I don't need a fetch counter in my application!

**Comment by tobias-tengler** [comment]
> Are you using selectors here vs atoms because you want the automatic use of React Suspense for the pending state? If so, then would being able to set an atom to a pending Promise be seen as a cleaner solution for this pattern?

Yes, Suspense was the driving factor for using Recoil not only for State Management, but also for loading remote resources in our case.

Using the default atom value sounds like a good idea, but I can't get it working with `useResetRecoilState`: [Example](https://codesandbox.io/s/long-shadow-gsvrt?file=/src/Test.jsx)

**Comment by drarmstr** [comment]
Atoms can currently have a default value that is an async Promise, however Promises are a one-shot concept for resolving to a value or error.  You can reset an atom and it will revert to the value of that original default promise, either pending, resolved, or error.  One thing I'm working on is working through a proposal to be able to subsequently set atoms to a promise, so they could be used to store the results of a new query refresh by explicitly setting them to a new promise.  So, instead of using "reset" you would set it to the new query.

**Comment by anhnch** [comment]
The ForceReload feels like a workaround but not an ugly solution. I've tried it with Suspense but the code didn't work. I can't figure out what the problem is. 

`const ForceReload = atom({
	key: 'forcereload',
	default: 0
})

const UserData = selector({
	key: 'userdata',
	get: async ({ get }) => {
		get(ForceReload); // make UserData selector dependent
		return await fetchAsyncData('http://example.com');
	}
})

const Screen1 = props => {
	const reload = useSetRecoilState(ForceReload);
	const UserInfo = () => {
		const user = useRecoilValue(UserData);
		return <Text>{user.name}</Text>
	}
	return <>
		<Suspense fallback={<Spinner />}>
			<UserInfo />
		</Suspense>
		<Button onPress={() => reload(Math.random())}>Reload</Button>
	</>
}`
One more thing, I know that Recoil doesn't support React Native yet, but I managed to get it to work perfectly, except the forcereload  workaround. I'm not sure this is because of the way React Native renders or because I did it wrong.

**Comment by acutmore** [comment]
@anhnch 

The force-reload-atom pattern is working for me with Suspense in this sandbox:

https://codesandbox.io/s/stoic-star-l5eer?file=/src/App.js

Are you able to post a sandbox that replicates the error?

**Comment by anhnch** [comment]
> @anhnch
> 
> The force-reload-atom pattern is working for me with Suspense in this sandbox:
> 
> https://codesandbox.io/s/stoic-star-l5eer?file=/src/App.js
> 
> Are you able to post a sandbox that replicates the error?

Yes, I have tried on codesandbox with React. It works! Maybe there's something wrong with React Native. I installed react-dom to make Recoil work on React Native. Could this be a problem?

**Comment by anhnch** [comment]
> @anhnch
> 
> The force-reload-atom pattern is working for me with Suspense in this sandbox:
> 
> https://codesandbox.io/s/stoic-star-l5eer?file=/src/App.js
> 
> Are you able to post a sandbox that replicates the error?

Yes I've double-checked. It works on React Native too. The problem is I have one redundant line `const userData = useRecoilState(UserData)` outside of the `UserInfo` component on the very top of the messy code. It works on the first rendering because `userData` already has a value that was set by the parent screen. When reloading, the `const userData = useRecoilState(UserData)` is really outside of Suspense. Thanks for your time.

**Comment by kspacja** [comment]
My other way to workaround. I'm sure that doesn't cover whole cases, but this more natural, easier to maintain for me and reusable:
`
export const asyncSelectorFamily = ({ get: getFn, key }) =>
  recoilSelectorFamily({
    key,
    get: ({ __date, obj }) => ({ get }) => {
      const getWithDate = (selector, obj) => {
        const curriedSelector =
          typeof selector === 'function'
            ? selector({ __date, ...obj })
            : selector;

        return get(curriedSelector);
      };

      return getFn(obj, __date)({ get: getWithDate });
    },
  });

const lastKeys = {};
export const useAsyncRootState = (key, selector, obj) => {
  lastKeys[key] = lastKeys[key] || key;
  const [__date, setDate] = useState(lastKeys[key]);

  const rerun = () => {
    const newKey = key + Date.now();
    setDate(newKey);
    lastKeys[key] = newKey;
  };

  const [loadable] = useRecoilStateLoadable(selector({ obj, __date }));

  return [loadable, rerun];
};

(...)

export const threadsState = asyncSelectorFamily({
  key: 'threads',
  get: () => async () => {
    return fetch('/threads');
  },
});

`

Feel free to use!

**Comment by drarmstr** [comment]
Duplicate of #422

**Comment by drarmstr** [comment]
Document query refresh pattern in #676

**Comment by ivanjeremic** [comment]
Maybe recoil can take some inspiration from ReactQuery, I'm not familiar with the details under the hood of both libraries but both Recoil and ReactQuery have "keys" ReactQuery uses them to invalidate queries and they get re-fetched automatically, maybe we can have something like this in recoil `invalidateAtom('Key')`

**Comment by iheyunfei** [comment]
It seems to me that the current solution isn't good enough . pure selectors are good, but pure async selectos aren't good.  recoil itself should provide ability to re-compute async selector for recovering from error or refreshing data. For now , I had to deal with these problem case by case.

**Comment by drarmstr** [comment]
For simple re-evaluations you can use [this pattern](https://recoiljs.org/docs/guides/asynchronous-data-queries#query-refresh).  For more complex use cases with async re-evaluations or recovering from error states, check out [atom effects](https://recoiljs.org/docs/guides/atom-effects).

**Comment by aaely** [comment]
So I used the force update, and it didn't work at all. Same values despite closing, reloading, etc. I actually had to kill the service and restart it to get the change to reflect....

**Comment by drarmstr** [comment]
> So I used the force update, and it didn't work at all. Same values despite closing, reloading, etc. I actually had to kill the service and restart it to get the change to reflect....

Do you have a codesandbox reproducer?

**Comment by aaely** [comment]
> > So I used the force update, and it didn't work at all. Same values despite closing, reloading, etc. I actually had to kill the service and restart it to get the change to reflect....
> 
> Do you have a codesandbox reproducer?

It ended up being a strange issue with the keep-alive connection between my back end and db. I forgot about this lol. It was driving me insane because NO MATTER WHAT I did the issue wouldn't go away. Im removing the comment, thanks for the follow up tho.

**Comment by bobbyecho** [comment]
after research a few days about how invalidate an asynchronous selector, i ended my solution with using epoc in millisecond and set to atom that we use for invalidating selector cache

maybe this is not the best solution, but it works to invalidate any selector in all cases

```
const getCurrentMsEpoc = () => {
  return Math.round(Date.now() / 1000);
};

const useInvalidateSelector = (incrementingState) => {
  const setInvalidate = useSetRecoilState(incrementingState);

  return () => setInvalidate(getCurrentMsEpoc());
};

export default useInvalidateSelector;

const refreshListPokemonAtom = atom<number>({
  key: 'refreshListPokemon',
  default: 0
});

const fetchListPokemon = selector({
  key: 'fetchListPokemon',
  get: async ({get}) => {
    get(refreshListPokemonAtom);

    const resultListPokemon = await listPokemonModel.getAll();

    return resultListPokemon;
  }
});

const List = () => {
  const list = useRecoilValue(fetchListPokemon);
  const refreshList = useInvalidateSelector(refreshListPokemonAtom);

  const renderItem = ({item}: {item}) => <Item {...props} />;

  return (
    <FlatList
      onRefresh={refreshList}
      data={list?.results ?? []}
      renderItem={renderItem}
      refreshing={false}
    />
  );
};
```

**Comment by RPisRyan** [comment]
[Selector refresher](https://recoiljs.org/docs/guides/asynchronous-data-queries/#userecoilrefresher) is now part of unstable API.

**Comment by baoskee** [comment]
The problem with selector refresher is that it's a hook. It would be nice if you can refresh one selector inside another selector...

**Comment by 0Shadow02** [comment]
Hey guys, if you are facing an issue where you are updating the database but want to reflect it on the page immediately, you can use  [useRecoilRefresher_UNSTABLE(state)](https://recoiljs.org/docs/api-reference/core/useRecoilRefresher/). It works for me.

Component where you are updating the database-
```
 const userpost = useRecoilRefresher_UNSTABLE(BlogsAtom( )) {
 --------your code here---------

 return <>
         <button onClick={() =>{ refresh()
           if(success){
              refresh()
          ------code-------
                  }
           }}>Refresh</button>}
        </>
```

You can also check it out on the Recoil Docs 
Here is my blog application repo you can see it here how I implemented this thing - [github/page](https://github.com/0Shadow02/PAGE_Bloging_Website_Project)
