### ISSUE TITLE
Why I get Double Render ?

### ISSUE THREAD

**Issue by NijatInHIT** [facebookexperimental/Recoil#853]
Recoil is great !
But, why I got double render?  there is a super simple case, please have a look
[https://codesandbox.io/s/keen-fog-rgs7c?fontsize=14&hidenavigation=1&theme=dark](url)

**Comment by NijatInHIT** [comment]
got answer from @salvoravida/recoil~

**Comment by bentron2000** [comment]
> got answer from @salvoravida/recoil~

Can you reference more fully for others? cheers b

**Comment by NijatInHIT** [comment]
https://github.com/facebookexperimental/Recoil/issues/307
https://github.com/facebookexperimental/Recoil/pull/820

**Comment by NijatInHIT** [comment]
> > got answer from @salvoravida/recoil~
> 
> Can you reference more fully for others? cheers b

Sure, reference is under below👌

https://github.com/facebookexperimental/Recoil/issues/307
https://github.com/facebookexperimental/Recoil/pull/820
