### ISSUE TITLE
Does recoil state support values that are instances of Set or Map?

### ISSUE THREAD

**Issue by foxtree** [facebookexperimental/Recoil#855]
Are instances of `Set` and `Map` legitimate values in `recoil` state?   
(...in recoil `atom`, `selector`, `selectorFamily`, and other APIs?)

Are there any constraints, as may still be the case with Redux, where states must only contain "serializable objects" ?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by drarmstr** [comment]
Yes, you can store `Set` and `Map` objects in atoms and selectors.  However, you should not mutate them.  You can create immutable clones when updating state.  

They can also be used for family parameters as well, but for that they will be serialized as an array and an object respectively if you are concerned about key collisions.  Objects they contain will be serialized as well.
