### ISSUE TITLE
atomFamily garbage collection

### ISSUE THREAD

**Issue by RexToCode** [facebookexperimental/Recoil#863]
I have a list of items (components) that I am planning to use atomFamily.  For each time creating new item, there will be a new Id push into the array, at the same time to create a unique atom in atomFamily with its id.  This array will be used for mapping out components for the list.  Id(s) will be removing from the array when submitting to backend.  I am having a few uncertainties:
1.  After submitting, id(s)  will be removed from the array.  Will I actually have to reset the corresponding atom(s) (in atomFamily) because the corresponding atom(s) are actually not in-use anymore since it's key (id) is no longer existing in the array subscribing to any components.  If i haven't understood wrongly, I should reset the atom based on the removal of its corresponding key(id) from the array, so that such atom will be removed physically.  Perhaps, in this way, it will lessen the "burden" to the app since less states (atoms)?  Or "default" atom (after resetting) doesn't bring any burden to the app, then I won't need to bother about the not-in-use atom(s)? 

2. If I use the array length to create Id, will it cause problem to the atomFamily after each time I clear the array and add new Id again which will eventually create the same id that i used to create an atom before?  For example, firstly "1" is added to the array, so at the same time it will create an atom in atomFamily with "1"; after submitting, "1" will be removed from the array, but "1" is still existing in the atomFamily, which means when i add item again while the array is empty, it will generate "1" again into the array, and create atom again with "1" which was used before.  So, based on the question #1 above, if atom will be physically removed after reseting, then there shouldn't be any problem; however, if this atom with the same id still exists (even after resetting), applying to my example here, it will just use the same atom that is still existing with new value that I assign when creating new Id, as an replacement(overwrite)?

Thanks for the help in advance.

**Comment by justintoman** [comment]
1. As far as I know, there is no way to remove atoms from an atom family. If they don't get used for a while they're supposedly garbage collected, though I don't know the specifics of how that works. I've understood it to be unimportant.

2. If you reset an atom in the atomFamily at key "1", and then you access "1" again, it will be the same atom, though its value will be reset and you should be able to use it for whatever you want later on. Is there a problem with re-using the same atom?

I've done this exact pattern several times and it seems to work fine for me. If you don't have a large number of items, then I don't think you need to worry about orphaned atoms in the family becoming cumbersome in memory. I've done this on the order of 10-30 atoms and it seems performant.

**Comment by RexToCode** [comment]
> 1. As far as I know, there is no way to remove atoms from an atom family. If they don't get used for a while they're supposedly garbage collected, though I don't know the specifics of how that works. I've understood it to be unimportant.
> 2. If you reset an atom in the atomFamily at key "1", and then you access "1" again, it will be the same atom, though its value will be reset and you should be able to use it for whatever you want later on. Is there a problem with re-using the same atom?
> 
> I've done this exact pattern several times and it seems to work fine for me. If you don't have a large number of items, then I don't think you need to worry about orphaned atoms in the family becoming cumbersome in memory. I've done this on the order of 10-30 atoms and it seems performant.

Hi Justin, thanks for your sharing!
I have done some trials, and it happened to be an issue when repeatedly use the same key (such as "1" referring to my example) to "create" atom into atomFamily....actually it's within expectation.  So, based on my assumption, the two best options should be: (1) avoid using the same id when creating new item  (2) reuse the atom by checking the existence of such id/key before creating a new one......but it still ends up to be a matter of how "necessarily" I should care about the burden it may give to the app regarding those so-called garbaged-atoms.  I am assuming there could be up to around a total of 100-200 atoms from two atomFamilies during usage.   I personally not in favour of option (2) because I don't want to add another logic processing to the action because I already have some more other processing in the same action......I hope I can get an answer about how much I should care about the unused atoms, so I will know which way is better to go for.

**Comment by drarmstr** [comment]
If you re-use the atom family parameter for a new component then you will get the same underlying atom and thus get the previous state, unless it was reset.

You can reset an atom, such as with [`useResetRecoilState()`](https://recoiljs.org/docs/api-reference/core/useResetRecoilState).  This will cause the atom to revert to its default state as well as release memory actually storing the state.  However, even with that there is a slight leak for the atom configuration with that family parameter.  In practice this hasn't been a significant concern unless a large number of atoms are being used, a couple hundred for your use case shouldn't be a problem.  We are currently working on garbage collection functionality which can be opted-into for atoms, including those in families, to automatically release their resources when no longer being referenced.

**Comment by davidskuza** [comment]
> We are currently working on garbage collection functionality which can be opted-into for atoms, including those in families, to automatically release their resources when no longer being referenced.

This seems to be important especially for long running applications.

**Comment by RexToCode** [comment]
We are currently working on garbage collection functionality which can be opted-into for atoms, including those in families, to automatically release their resources when no longer being referenced.

Got it.  Thanks for your sharing.  I look forward to it, since I still feel restless knowing that there are unnecessary states  in the app memory.
