### ISSUE TITLE
[Question] How to reset an atom to his default value?

### ISSUE THREAD

**Issue by lironezra** [facebookexperimental/Recoil#865]
Hi,

I'm trying to reset atom to his default value when user logout from my application with the useRecoilCallBack function like that:

`const resetRecoilAtomState = useRecoilCallback(({ reset }) => () => {
        reset(userState);        
    });
`

`userState` that passed to `reset` is the atom, I'm also tried to pass the `userState` atom value to `reset` and it not working either, what am I doing wrong?

Thanks for the help!

**Comment by BenjaBobs** [comment]
I think you can use [`useResetRecoilState`](https://recoiljs.org/docs/api-reference/core/useResetRecoilState/).

**Comment by lironezra** [comment]
I have tried it now, not working as well, it's seems like the state not effected at all.
Thank you!

**Comment by justintoman** [comment]
> I think you can use [`useResetRecoilState`](https://recoiljs.org/docs/api-reference/core/useResetRecoilState/).

This is correct. Can you provide more information? Can you show the code of the atom and where you invoke the reset?

**Comment by lironezra** [comment]
Hi, 

Here is my atom `userState`:

```
export const userState = atom({
    key: 'userState',
    default: {
        isAuthenticated: false,
        userRoles: [],
        userCompanyName: '',
        isStoreRegistered: true,
        loginLoading: false,
        verifyLoading: true,
        APIError: null
    }
});
```
Than I created this function variable from `useResetRecoilState`: 
`const resetUserState = useResetRecoilState(userState);`

And I invoked that function like that:

```
    const onClickLogout = async () => {
        await APIService.logoutUser();
        resetUserState();
        navigateTo('/login');
    }
```

What am I doing wrong?

Thanks for the help guys!

**Comment by justintoman** [comment]
I assume if you mutate the state object instead of setting it to change it, then it will modify the reference to the original default value, so you'll see the changes even after resetting. Make sure you aren't mutating--maybe try wrapping the default value in `Object.freeze({ isAuthenticated: false, etc... })`.

**Comment by drarmstr** [comment]
@lironezra  - Do you have a reproducer for the issue?

**Comment by lironezra** [comment]
Hi @drarmstr,

I tired to reproduce the issue, but it seems to work in codesanbox.
Here is my code: [https://codesandbox.io/s/charming-margulis-nuz15?file=/src/App.js](url).

I find out my mistake somewhere after user logged out.
`useResetRecoilState` worked as expected!

Thanks anyway!
