### ISSUE TITLE
Only last call to 'set' is respected when using some write-only selectors

### ISSUE THREAD

**Issue by brett-mitchell-itential** [facebookexperimental/Recoil#866]
Recoil version: 0.1.2
React version: 17.01 and 16.14.0
Minimal sandbox: https://codesandbox.io/s/loving-rgb-0mfg0 (Note: See lines 70-81 to switch between the two behaviors)

### Background

When setting up an atom to track ids for members of an atomFamily, I've found it helpful to abstract to the concept of a collection of id-value tuples using a factory function.

```typescript
const atomCollection = ({ singularKey, pluralKey, default: dflt }) => {
  const item = atomFamily({ key: singularKey, default: dflt });
  const ids = atom({ key: pluralKey, default: [] });

  return { item, ids };
};
```

On it's own, this isn't really _that_ helpful, so I like to add a couple of helper methods with write-only selectors to make dealing with these tightly coupled atoms a bit nicer.

```typescript
const atomCollection = ({ singularKey, pluralKey, default: dflt }) => {
  const item = atomFamily({ key: singularKey, default: dflt });
  const ids = atom({ key: pluralKey, default: [] });

  // Write-only selector for adding a new [id, value] tuple to the collection
  const addOne = selector({
    key: `${singularKey}/${pluralKey}/addOne`,
    set: ({ set }, [id, value]) => {
      set(item(id), value);
      set(ids, R.pipe(R.concat([id]), R.uniq));
    },
  });

  return { item, ids, addOne };
};
```

### Problem

All this works fine until I attempt to loop over the addOne selector:

```typescript
const itemColl = atomCollection({ singularKey: 'item', pluralKey: 'items', default: id => id });

const SomeComponent = ({ ...props }) => {
  const addOneItem = useSetRecoilState(itemColl.addOne);
  useEffect(() => {
    // For some reason, only [3, { val: 3 }] will be added to the collection
    [
      [1, { val: 1 }],
      [2, { val: 2 }],
      [3, { val: 3 }]
    ].forEach(addOneItem);
  }, []);

  return ( ...rendering );
};
```

### Possible Cause?

It seems that when looping over a write-only selector in this kind of a scenario, the batched updates to the members of the collection are getting overwritten, leaving only the last one to finally get executed and persisted.

### Workaround

The odd thing is, I'm able to write an 'addAll' variant of this method which does not suffer from the same problem. Both selectors can be found implemented in the sandbox linked above:

```typescript
const atomCollection = ({ singularKey, pluralKey, default: dflt }) => {
  // ... Previous atomCollection code

  const addAll = selector({
    key: `${singularKey}/${pluralKey}/addAll`,
    set: ({ set }, values) => {
      values.forEach(([id, value]) => set(item(id), value));
      const newIds = values.map(([id]) => id);
      set(identifiers, prev => [...prev, ...newIds]);
    },
  });

  return { item, ids, addOne, addAll };
};
```

**Comment by drarmstr** [comment]
In your `addOne` selector:
```jsx
    set: ({ set }, [id, value]) => {
      set(item(id), value);
      set(ids, R.pipe(R.concat([id]), R.uniq));
    },
```
You are setting the new `ids` value based on `R.concat([id])` which would appear to just be building an array based on the new id and not taking into account the existing ids.  To actually concatenate the new id you would need to use the updater form of the setter by passing in a function which gets the existing set of ids as a parameter.  e.g.:
```jsx
    set: ({ set }, [id, value]) => {
      set(item(id), value);
      set(ids, existingIds => [...existingIds, id]);  // You can use JS Sets for uniqueness or continue using Ramda or whatever
    },
```

**Comment by brett-mitchell-itential** [comment]
@drarmstr Thanks for the reply! I apologize for not removing the `ramda` bits of my code: `R.pipe(R.concat([id]), R.uniq)` is essentially a point-free equivalent of `(previous) => Array.from(new Set([id, ...previous]))`.

I will look into changing the collection type to use functions for use in `useRecoilCallback` instead of selectors. Seems like a better fit like you said.

When it comes to the issue at hand, however, the `add` implementation in the example does use the form you suggested, but still suffers from the same problem. Is this expected behavior and still just coming from the fact that I'm misusing `selector`, or should all of those looped updates be picked up?
