### ISSUE TITLE
converge two .flowconfig

### ISSUE THREAD

**Issue by aaronabramov** [facebookexperimental/Recoil#876]
currently we have two different flow config files

- `packages/recoil-devtools/.flowconfig`
- `.flowconfig`

with `packages/recoil-devtools/.flowconfig` being slightly less strict than `.flowconfig`

We need to change code under `packages/recoil-devrools` to conform to `.flowconfig` and remove `packages/recoil-devtools/.flowconfig`.

after that we'll need to make sure github actions run `flow` against both `src` and `packages/recoil-devtools`

**Comment by aaronabramov** [comment]
@mallchel do you want to take this one?

**Comment by mallchel** [comment]
@aaronabramov yep, I'll make a PR

**Comment by mallchel** [comment]
@aaronabramov Can we close this one?
