### ISSUE TITLE
Awating code in a selector setter breaks my app. Is this a bug or a feature?

### ISSUE THREAD

**Issue by digizen** [facebookexperimental/Recoil#888]
I'm trying to figure out if the behaviour I'm seeing within Recoil and my application is by design or if there's a bug somewhere.

My app displays a list of items, and allows editing. Clicking "save" triggers a selector's "set" function, which both updates the downstream atom and triggers a save to IndexedDB via an async method. 

The problem is that clicking "save" reverts the value that I just edited back to the prior version of the atom, or at least doesn't update the atom to the new value in time for render. 

I've isolated the problem to the sequence of steps within the setter. If I call the await statement to save my item to IndexedDB, and then ask the atom to update (step 2 then step 1 below), my UI component will re-render with the original value of the item. The app then looks like it "undoes" the change I just made.  The IndexedDB is updated though, so refreshing the app via Ctrl-R surfaces the changes. The "completed set." message does get printed to the console - so it's not like the async-await chain is broken somewhere, but it's the very last thing that prints to the console  - it follows the debug console output messages I've put into the render function. If the calls are reversed (step 1 then step 2), everything works fine with rendering, the IndexedDB is also correctly updated. 

```js
export const itemsListFamily = selectorFamily<SingleItem, string>({
    key: 'ItemsSelectorFamily',
    get: (item_id: string) => ({ get }) => {
        return get(itemAtomFamily(item_id));
    },
    set: (item_id) => async ({ set }, newValue) => { 
        // step 1
        set(itemAtomFamily(item_id), newValue);

        // step 2: flipping this and the step 1 set statement breaks the app. 
        const savedItem = await SaveExistingItemToLocalStore(newValue as SingleItem);

        console.log('completed set.');
    }
});
```

Does this make sense? Why does having an async call inside setter cause this problem? Does the order matter?

Thanks in advance for your help,
Greg

**Comment by drarmstr** [comment]
Selector's don't accept `async` `set` methods.  Please see #762 for a feature request for this for use in transactions.  Please consider [`useRecoilCallback()`](https://recoiljs.org/docs/api-reference/core/useRecoilCallback) for async setting use cases like this.
