### ISSUE TITLE
cacheImplementationForParams is not exposed in types

### ISSUE THREAD

**Issue by wmain** [facebookexperimental/Recoil#891]
According to the docs `cacheImplementationForParams` should be exposed, but it's currently [commented out](https://github.com/facebookexperimental/Recoil/blob/master/typescript/index.d.ts#L289) in the type definitions.

Sidenote: Will this API be available on atom families?

**Comment by drarmstr** [comment]
@wmain - Where do you see it exposed in the docs?  It should be removed if it shows up anywhere.  This prop was not meant to be documented and is not recommended to use.  We explored that approach internally, but it doesn't work with our new selector implementation.  Instead, @csantos42 is currently working on a mechanism to expose cache options in the atom/selector/family options.

**Comment by KebapBoy** [comment]
@drarmstr It's referenced here: https://recoiljs.org/docs/api-reference/utils/selectorFamily

**Comment by drarmstr** [comment]
Updated current temporary API in #907
