### ISSUE TITLE
Asynchronous selector triggers re-render on unmounted RecoilRoot

### ISSUE THREAD

**Issue by mondaychen** [facebookexperimental/Recoil#897]
If there's a pending asynchronous selector when a `RecoilRoot` is unmounted, it seems to trigger another re-render on this unmounted component, indicating a memory leak.

## How to reproduce
https://codesandbox.io/s/recoil-example-unmount-root-bug-lbig1?file=/src/App.js

This example is using a fake fetch that resolves after 5 seconds.
Click "tab 1" to mount the root, click "tab 0" to unmount it before 5 seconds. You will see this message in console when the fake fetch is resolved:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Batcher (https://lbig1.csb.app/node_modules/recoil/es/recoil.js:1095:20)
    at RecoilRoot (https://lbig1.csb.app/node_modules/recoil/es/recoil.js:1150:50)
    at RecoilRootWrapper
    at div
```

**Comment by drarmstr** [comment]
@csantos42 ?

**Comment by zxhhh11** [comment]
Could you please tell me how to solve this problem ? I also encounter the same error when use it

**Comment by mondaychen** [comment]
@zxhhh11 latest release should have fixed this issue
