### ISSUE TITLE
Cannot install recoil with latest react version 17.0.1

### ISSUE THREAD

**Issue by frustak** [facebookexperimental/Recoil#899]
I tried to install recoil in a fresh create-react-app project and this error has accord:
```bash
❯ npm install recoil
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from recoil@0.1.2
npm ERR! node_modules/recoil
npm ERR!   recoil@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```
Maybe updating the project's react peer dependency from 17.0.0 to 17.0.1 would solve this issue.

**Comment by mondaychen** [comment]
The peer dependency is `^16.13.1 || ^17.0.0` so it should work with any of `17.0.x`.
I'm not able to reproduce this issue on a fresh create-react-app project. Which version of npm and create-react-app are you using?

**Comment by frustak** [comment]
The npm version is `7.5.3` and I'm using the command directly from React website `npx create-react-app my-app`

**Comment by zkSharks** [comment]
I'm seeing the same behavior with Node 15.5.1 / NPM 7.4.0.  After running `npm uninstall react` (and react-dom and recoil), and then `npm install recoil@0.1.2` followed by `npm ls react`, I get:

```
-- recoil@0.1.2
  -- react@16.14.0
```

So I checked the package.json in node_modules for recoil, and see this:

```
  "peerDependencies": {
    "react": "^16.13.1"
  },
```

Still digging...

**Comment by mondaychen** [comment]
Ah OK, apparently we really should release a new version now. The last release was 4 months ago -- react 17 wasn't stable back then so we had react 16.13.1 as peer dependency. https://cdn.jsdelivr.net/npm/recoil@0.1.2/package.json

cc @davidmccabe @drarmstr

**Comment by mondaychen** [comment]
hey @frustak @zkSharks can you test with latest version 0.1.3?

**Comment by frustak** [comment]
Thanks, it works perfectly fine now.
