### ISSUE TITLE
Atom whose state is loadable cannot be used in a selector

### ISSUE THREAD

**Issue by Hainesy** [facebookexperimental/Recoil#908]
We have an atom whose default value is a selector that makes an asynchronous API request to get its value.

This atom's state can happily be fetched using `useRecoilValueLoadable`.

However if I try to use the atom in another selector, and the API request has failed and returns an error, then the derived selector will fail, throwing the error returned from the API request.

What we need here is a `getLoadable` in the selector options.

Or am I doing something philosophically wrong?

**Comment by drarmstr** [comment]
You can use [`noWait()`](https://recoiljs.org/docs/api-reference/utils/noWait) in a selector implementation similar to the `useRecoilValueLoadable()` hook.
