### ISSUE TITLE
Setters/Getters causing Enzyme infinite render loop

### ISSUE THREAD

**Issue by delucca** [facebookexperimental/Recoil#909]
Hi everyone.

I've been facing a big issue with Recoil Enzyme testing for the past few months. Until now, I was able to work around this by using `shallow` instead of `mount`, but this week I've faced a scenario where I need to test using mount.

The issue is the following: everytime I cast a setter upon a given component lifecycle, I got one of the following errors:

1. If I have a getter for the same atom in the same component, I receive the following error:
```
    Too many re-renders. React limits the number of renders to prevent an infinite loop.
```
2. If I remove the getter from the same component, and pass that to a child, I got an warning and the contents of the getter are undefined (only in the child, but if I debug I can check that actually that given atom has the expected content). Here is the warning that I get:
```
    Warning: Cannot update a component (`Batcher`) while rendering a different component (`Me`). To locate the bad setState() call inside `Me`, follow the stack trace as described in https://fb.me/setstate-in-render
        in Me
        in RecoilRoot
        in ApolloProvider (created by MockedProvider)
        in MockedProvider (created by WrapperComponent)
        in WrapperComponent

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnAboutRenderPhaseUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:23241:15)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21165:3)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:15660:5)
      at node_modules/recoil/cjs/recoil.js:1621:40
      at Object.replaceState (node_modules/recoil/cjs/recoil.js:1807:53)

  console.error
    Warning: Cannot update a component (`NamedAvatar`) while rendering a different component (`Batcher`). To locate the bad setState() call inside `Batcher`, follow the stack trace as described in https://fb.me/setstate-in-render
        in Batcher (created by RecoilRoot)
        in RecoilRoot
        in ApolloProvider (created by MockedProvider)
        in MockedProvider (created by WrapperComponent)
        in WrapperComponent
```

Here is a sample implementation, explaining the error:

I have two simple components:
- `Me`
- `NamedAvatar`

The first one (`Me`) is a simple wrapper, that fetched data from my GraphQL server and loads it in my Recoil state.

The second one (`NamedAvatar`) just displays the user name/avatar

Here are a sample impl:
```tsx
const Me = () => {
  const [me, setMe] = useRecoilState(meAtom)
  const setUser = useSetRecoilState(selectUser(me))
  const { loading } = useQuery<GetUserNamedAvatarDataQuery>(queries.GET_USER_NAMED_AVATAR_DATA, {
    onCompleted: (data) => {
      setMe(data.me.id)
      setUser(data.me)
    },
  })

  return <NamedAvatar userID={me} isLoading={loading} />
}
```

```tsx
const NamedAvatar = ({ userID, isLoading }: NamedAvatarProperties): ReactElement => {
  const user = useRecoilValue(selectUser(userID))

  const isLoaded = Boolean(user) || !isLoading

  return (
    <Flex alignItems="center" gridGap={15}>
      <SkeletonCircle isLoaded={isLoaded} size="50px">
        <Avatar name={user?.fullName} src={user?.picture} />
      </SkeletonCircle>

      <Box textAlign="left">
        <Skeleton isLoaded={isLoaded} {...buildSkeletonMinSize(isLoaded, 100, 24)}>
          <Text color="gray.500" fontWeight={500}>
            {user?.fullName}
          </Text>
        </Skeleton>

        <Skeleton
          isLoaded={isLoaded}
          {...buildSkeletonMinSize(isLoaded, 60, 10)}
          mt={isLoaded ? 0 : '8px'}
        >
          <Text fontSize="sm" color="gray.500">
            {user?.companies?.[0]?.name}
          </Text>
        </Skeleton>
      </Box>
    </Flex>
  )
}
```

`Flex`, `Box`, and all the children from `NamedAvatar` component are from `ChakraUI` lib. So, they're not messing anything up.

Using the above impl, I've created the following test case:
```tsx
  it.only('displays the user full name', async () => {
    const fakeFullName = faker.name.findName()

    const fakeMe = {
      id: faker.random.uuid(),
      firstName: faker.name.firstName(),
      fullName: fakeFullName,
      picture: faker.internet.avatar(),
      companies: [
        {
          id: faker.random.uuid(),
          name: faker.company.companyName(),
        },
      ],
    }

    const mocks = [
      {
        request: {
          query: queries.GET_USER_NAMED_AVATAR_DATA,
        },
        result: {
          data: {
            me: fakeMe,
          },
        },
      },
    ]

    const wrapper = enzyme.mount(
      <MockedProvider mocks={mocks}>
        <recoil.RecoilRoot>
          <Me />
        </recoil.RecoilRoot>
      </MockedProvider>,
    )

    await waitForComponentToPaint(wrapper)
    const userNameComponent = wrapper.find('NamedAvatar').find('Text').first()

    expect(userNameComponent.text()).toEqual(fakeFullName)
  })
```

Being `waitForComponentToPaint` this:
```tsx
export const waitForComponentToPaint = async (wrapper: any) => {
  await act(async () => {
    await new Promise((resolve) => {
      setTimeout(resolve, 0)
    })
    wrapper.update()
  })
}
```

And my selector:
```ts
import deepmerge from 'deepmerge'
import { DefaultValue, selectorFamily } from 'recoil'

import { overwriteMerge } from 'lib/deepmerge'
import { User } from 'src/components/User/types'
import { PREFIX } from 'src/state/recoil/intl/constants'
import { RecoilInterfaceReadWrite } from 'src/state/recoil/types'

import userAtomFamily from './atom-family'

const KEY = `${PREFIX}::SELECTOR`

export const updateUser = (id?: User['id']) => (
  { get, set }: RecoilInterfaceReadWrite,
  newUser: Partial<User> | DefaultValue | undefined,
) => {
  if (!id) return
  if (!newUser) return

  const atom = userAtomFamily(id)
  const currentValue = get(atom) ?? {}
  const newValue = deepmerge(currentValue, newUser as Partial<User>, {
    arrayMerge: overwriteMerge,
  })

  set(atom, newValue)
}

export const selectUser = selectorFamily<Partial<User> | undefined, User['id'] | undefined>({
  key: KEY,
  get: (id) => ({ get }) => get(userAtomFamily(id)),
  set: updateUser,
})

export default selectUser
```

And the atom family:
```ts
import { atomFamily } from 'recoil'

import { User } from 'src/components/User/types'

import { PREFIX } from './constants'

const KEY = `${PREFIX}::FAMILY`

export const userAtomFamily = atomFamily<Partial<User> | undefined, User['id'] | undefined>({
  key: KEY,
  default: undefined,
})

export default userAtomFamily
```

So, in this test I always fall in one of the two scenarios:
1. If I change the `NamedAvatar` to receive the user as a prop and move the `Me` parent from `useSetRecoilState` to `useRecoilState`, passing the state to the `NamedAvatar`, I receive the infinite loop error.
2. If I keep this impl (which is better imho), I receive the Batcher warning and the `user` state is empty inside the `NamedAvatar` (although I can debug and see that it was successfully updated in the Recoil itself)

**IMPORTANT:** I can't pass the `data` directly from my Apollo GraphQL result directly to the child, because other components may change that atom value.

**Comment by mondaychen** [comment]
While I appreciate detailed issue description, your question is way too long for me to fully understand and provide help to. Is it possible to provide a minimal version of test that can reproduce your issue?

**Comment by delucca** [comment]
> While I appreciate detailed issue description, your question is way too long for me to fully understand and provide help to. Is it possible to provide a minimal version of test that can reproduce your issue?

Sure. I will try to make a minimal reproducible Codesandbox/

**Comment by mondaychen** [comment]
You can start from this one https://codesandbox.io/s/recoil-basic-example-wti09?file=/src/App.js

**Comment by 42shadow42** [comment]
@delucca I replicated this based on your code snippets using version 0.0.8, then upgraded to the latest version (0.1.3) can you confirm 0.1.3 has this problem?

**Comment by 42shadow42** [comment]
@delucca I looked further into why the test was failing and came up with. The folks from recoil can probably confirm it:

I think the problem lies in the Me component:

```ts
const Me = () => {
  const [me, setMe] = useRecoilState(meAtom)
  const setUser = useSetRecoilState(selectUser(me))
  const { loading } = useQuery<GetUserNamedAvatarDataQuery>(queries.GET_USER_NAMED_AVATAR_DATA, {
    onCompleted: (data) => {
      setMe(data.me.id)
      setUser(data.me)
    },
  })

  return <NamedAvatar userID={me} isLoading={loading} />
}
```

In this component you get the "me" state, and a setter for "user" based on "me" in your callback you call "setMe" and "setUser", the problem is that the render that created the callback referred to the "setUser" based on the original (previous) "me" or undefined causing "setUser" to be a no-op based on your setter implementation. Finally NamedAvatar is rerendered using the new value of "me" cannot locate a user and returns undefined.

To resolve this issue I did this:

```ts
const Me = () => {
  const me = useRecoilValue(meAtom)
  const setUser = useRecoilCallback(({set}) => {
    return (me, user) => {
      set(meAtom, me)
      set(selectUser(me), user)
    }
  })

  const { loading } = useQuery(queries.GET_USER_NAMED_AVATAR_DATA, {
    onCompleted: (data) => {
      setUser(data.me.id, data.me)
    },
  })

  return <NamedAvatar userID={me} isLoading={loading} />
}
```

The use of useRecoilCallback allow you to call set, on the atom selected by the new "me" setting the appropriate user.

@mondaychen Does that theory sound right to you?

**Comment by delucca** [comment]
> @delucca I looked further into why the test was failing and came up with. The folks from recoil can probably confirm it:
> 
> I think the problem lies in the Me component:
> 
> ```ts
> const Me = () => {
>   const [me, setMe] = useRecoilState(meAtom)
>   const setUser = useSetRecoilState(selectUser(me))
>   const { loading } = useQuery<GetUserNamedAvatarDataQuery>(queries.GET_USER_NAMED_AVATAR_DATA, {
>     onCompleted: (data) => {
>       setMe(data.me.id)
>       setUser(data.me)
>     },
>   })
> 
>   return <NamedAvatar userID={me} isLoading={loading} />
> }
> ```
> 
> In this component you get the "me" state, and a setter for "user" based on "me" in your callback you call "setMe" and "setUser", the problem is that the render that created the callback referred to the "setUser" based on the original (previous) "me" or undefined causing "setUser" to be a no-op based on your setter implementation. Finally NamedAvatar is rerendered using the new value of "me" cannot locate a user and returns undefined.
> 
> To resolve this issue I did this:
> 
> ```ts
> const Me = () => {
>   const me = useRecoilValue(meAtom)
>   const setUser = useRecoilCallback(({set}) => {
>     return (me, user) => {
>       set(meAtom, me)
>       set(selectUser(me), user)
>     }
>   })
> 
>   const { loading } = useQuery(queries.GET_USER_NAMED_AVATAR_DATA, {
>     onCompleted: (data) => {
>       setUser(data.me.id, data.me)
>     },
>   })
> 
>   return <NamedAvatar userID={me} isLoading={loading} />
> }
> ```
> 
> The use of useRecoilCallback allow you to call set, on the atom selected by the new "me" setting the appropriate user.
> 
> @mondaychen Does that theory sound right to you?

Interesting.

Thanks for your reply! I'm going to give it a try using `useRecoilCallback` and see if that fixes my issue :)

Thanks!

**Comment by 42shadow42** [comment]
@delucca Please let me know, thanks!

**Comment by delucca** [comment]
> @delucca Please let me know, thanks!

I don't think that was the issue. I was not able to test on the provided example yet, but I'm trying to code a different test where I have two components, both of them in the same level of the node tree (they are children of the same parent). The first one sets the state after an Apollo query, and the second one simply reads that state (using `useRecoilValue`).

As soon as I add the second component, I stumble upon that infinite loop issue.
