### ISSUE TITLE
Need of dumpStates

### ISSUE THREAD

**Issue by andriy-andriyuk** [facebookexperimental/Recoil#91]
Hello.
Is it possible to add some function (not a hook), like dumpStates.
Goal is next. I pass an array of RecoilStates and get their values. So, I am able to get values of RecoilStates I passed at any time.

Usage example - form submission.

**Comment by davidmccabe** [comment]
For form submission, you might have a look at the `useRecoilCallback` hook.

**Comment by andriy-andriyuk** [comment]
Thanks! It worked and worked perfectly.
Using useRecoilCallback with ({getPromise, set}) and getting what I need.
Thanks, again.
Recoil is AWESOME!
