### ISSUE TITLE
Recoil doesn't work with Swiper.js

### ISSUE THREAD

**Issue by baeharam** [facebookexperimental/Recoil#913]
I'm using recoil with [swiper](https://swiperjs.com/) and React/Typescript. But, it doesn't work with swiper instance. I wanna store swiper instance in atom to share between components. But, it breaks.

Reproduction: https://codesandbox.io/s/tender-bartik-dv4t1?file=/src/App.tsx

**Comment by JohannesKlauss** [comment]
You can only store serializable objects in an atom, not class instances.

**Comment by baeharam** [comment]
@JohannesKlauss Thanks for your answer! Then, how can I share class instance between component in Recoil environment? Is there no way?

**Comment by BenjaBobs** [comment]
You could create an instance outside of React components, and then export it. Then it'd be a global instance you can import from anywhere.

**Comment by baeharam** [comment]
@BenjaBobs Simple and basic solution, thanks. But, I solved this problem by using function property of atom object. Anyway, close issue!
