### ISSUE TITLE
Are there release notes for 0.1.3?

### ISSUE THREAD

**Issue by JohannesKlauss** [facebookexperimental/Recoil#916]
I saw that version 0.1.3 has been published on npm, but I cannot find release notes anywhere, would be good to know about potential breaking changes, deprecations and new additions :)

**Comment by drarmstr** [comment]
0.1.3 fixed compatibility with the latest React release, just a simple dependency version fix in package.json. The upcoming 0.2 release has actual fixes and new features.  We're just confirming what's in nightly is stable now and are about ready to release.
