### ISSUE TITLE
Got unexpected null or undefined

### ISSUE THREAD

**Issue by nxz91** [facebookexperimental/Recoil#920]
First of all, you have a great state management library here! We're evaluating to move over, and started running into some issues. Perhaps a troubleshooting section would help - e.g. with a hint to Object.freeze for all of us moving from the Context API.

I couldn't find anything relating to the following issue that happens inside Recoil:

<img width="365" alt="Screenshot 2021-03-10 at 21 08 54" src="https://user-images.githubusercontent.com/13373411/110690955-d4581100-81e4-11eb-810d-961711457b68.png">

It happens when trying to set the state of an atom. Any idea what might be causing this?

**Comment by BenjaBobs** [comment]
I've never seen that error before. Could you provide some context? What React version are you using, and how are you setting the state?

**Comment by nxz91** [comment]
The string "Got unexpected null or undefined" is written like this in recoil.js:74. This is happening when setting the state using const setState = useSetRecoilState(someAtom) and calling setState(previous => ...) from inside an event listener.

React: 17.0.2

**Comment by nxz91** [comment]
We're building www.wonder.me and think Recoil could fit quite perfectly to our real-time use case, so would really love to resolve these two issues and do the move over to Recoil :)

**Comment by BenjaBobs** [comment]
I'm not sure exactly why you're encountering this. From briefly looking at the source it seems to me that it might be due to updating state between two renders?
Is the event listener an async function?

**Comment by drarmstr** [comment]
It's really difficult to debug this without additional context.  Do you have a cutdown reproducer on codesandbox.io?

**Comment by nxz91** [comment]
This did also not happen again after understanding Recoil a little better (I cannot pinpoint exactly where)

**Comment by Hainesy** [comment]
I'm also seeing this since upgrading to 2.0.0, but struggling to unearth the cause right now...

**Comment by Hainesy** [comment]
I think the root cause of this is expecting setting a recoil value to be updated by the next render, which it sometimes isn't. This means it behaves manifestly different to `useState`.

**Comment by SmallHollow** [comment]
I'm also getting this after upgrading to 0.3.x (didn't happen in earlier versions). So far I'm having trouble locating the cause but I'll post again if I find it.

**Comment by rluncasu** [comment]
encountered the same issue today & found the culprit, at least in my case, maybe will help someone:
I had defined the atom wrong, like this:
```
export const searchState = atom({
  userTerm: "",
});
```
when I should've defined it like this (according to docs):
```
export const searchState = atom({
  key: "searchState",
  default: {
    userTerm: "",
  },
});
```
An interesting note is that the wrong definition worked fine in development but crashed in prod build.
The crash happened not while setting the atom but when reading it like this:
```
function UsersTable({ onDelete, users }) {
const [searchTerms, setSearchTerms] = useRecoilState(searchState);
const [searchField, setSearchField] = useState(searchTerms?.userTerm || "");
```

changing to the correct atom def fixed it for me.

"recoil": "0.3.1",
 "react": "^16.13.1",
 "react-dom": "^16.13.1",

**Comment by SmallHollow** [comment]
@rluncasu , I can't believe it but out of 50 "correct" atoms one happened to be exactly like in your example. Feeling kind of dumb :-) Fixing it solved my problem, thanks!

**Comment by sakanaproductions** [comment]
I'm getting the error with the following selector:
```
export const currentDayAtom = selector({
  key: "currentDayAtom",
  get: async ({ get }) => {
    const currentDay = JSON.parse(localStorage.getItem("currentDay"));

    console.log(currentDay);

    if (currentDay) {
      return currentDay;
    }

    if (get(empRecAtom)?.KeyEmployee) {
      get(curDayRequestIDState);
      const response = await api.findRecords("employee_days", [
        {
          fields: [
            {
              fieldname: "_kf_KeyEmployee",
              fieldvalue: get(empRecAtom).KeyEmployee,
            },
            {
              fieldname: "Date",
              fieldvalue: DateTime.now().toLocaleString(DateTime.DATE_SHORT),
            },
          ],
        },
      ]);

      let day = null;
      if (!response) {
        const created = await createFMDayRec({
          date: DateTime.now(),
          //status: "Unknown",
          curState: "Not Clocked In",
          submitted: 0,
        });

        day = await api.getRecord("employee_days", created?.response?.recordId);
        day = day.response.data[0];
      } else {
        day = response.response.data[0];
      }

      let mapped = null;
      if (day) {
        mapped = {};
        for (let [key, value] of dayStructMap) {
          mapped[value] = day.fieldData[key];
        }
        mapped.recordId = day.recordId;
      }

      return mapped;
    }

    return null;
  },
  set: ({ set }, value) => {
    if (value instanceof Recoil.DefaultValue) {
      set(curDayRequestIDState, (v) => v + 1);
    }
  },
});
```

The output for the `console.log(currentDay)` is:
```
KeyEmployee: "050628123654164"
breakPremium: ""
breakPremiumReason: ""
curState: "Clocked In"
date: "09/07/2021"
dayEndedTime: ""
daySubmittedTime: ""
recordId: "34599"
status: "Work"
submitted: 0
totalDuration: ""
```

It's not null, so I'm not sure why I'm getting this error.

**Comment by shivampip** [comment]
@rluncasu Thank you, you are lifesaver.
