### ISSUE TITLE
Want a new version release

### ISSUE THREAD

**Issue by otakustay** [facebookexperimental/Recoil#922]
It has been 5 months since the last release, we are blocked by npm@7's robust peer version check since current release has a peer of `react>=16.3.1` which is incompatible with react@17

Could it be possible to release a new version sooner including support for react@17?

**Comment by jsoneaday** [comment]
Also any roadmap for leaving experimental status? Or perhaps a date for release of next version with the clean up of unused atoms?

**Comment by drarmstr** [comment]
The `0.1.3` release should have fixed the React version issue.  It's on NPM, though not linked to on GitHub as it was cherry-picked.  `0.2` will be out shortly.  The GC is still behind a feature flag in nightly.  @davidmccabe may have details if you want to experiment/test.

**Comment by jsoneaday** [comment]
Cool. Does 0.2 mean production ready or just a significant update? David's video seems to indicate you guys are using it in your own production apps so I'm wondering why it hasn't been released from experimental.

**Comment by drarmstr** [comment]
I'm not aware, really, of a formal definition of "experimental".

**Comment by jsoneaday** [comment]
> I'm not aware, really, of a formal definition of "experimental".

I'm confused both the readme and the about indicate that Recoil is experimental. That indicates to me that it is not production ready. Or how else would you perceive something that is experimental? Do companies normally use experimental code in their apps?

**Comment by jsoneaday** [comment]
With the release of Jotai you should consider removing the experimental label from Recoil. Recoil seems like a great project which I intend to use, but some people especially companies may be scared off by the experimental tag.

Just a suggestion.
