### ISSUE TITLE
Why Recoil cannot store class instance, but can store object that uses class instance?

### ISSUE THREAD

**Issue by baeharam** [facebookexperimental/Recoil#928]
I'm using Swiper.js and have to use class instance of Swiper. However, I cannot store class instance in atom because it is not serializable. But, I could store object that uses class instance...why? How it works internally?

**Impossible**

```typescript
const swiperAtom = atom({
  key: 'swiper',
  default: <swiperInstance>
});
```

**Possible**

```typescript
const swiperAtom = atom({
  key: 'swiper',
  default: {
    update: <swiperInstance>.update()
  }
});
```

**Comment by BenjaBobs** [comment]
What is the type of `<swiperInstance>.update()`? I'm assuming the function returns some data structure that Recoil is fine with.
