### ISSUE TITLE
This component must be used inside a recoil root component

### ISSUE THREAD

**Issue by lockhaicttv** [facebookexperimental/Recoil#929]
I know this issue probably can stupid but this is a problem I meet when I importing recoil Hook in a Modal inside children component although Parent component under <RecoilRoot/>

![image](https://user-images.githubusercontent.com/32085956/111686103-e5f17800-87e5-11eb-8ef5-62e1c59fd4a2.png)

**Comment by lockhaicttv** [comment]
Tks all supporters ♥

**Comment by BenjaBobs** [comment]
So generally modals exist outside of of the normal root, but many libraries provide a way to place it inside the root. You can either try to get the modal placed inside the tree, or you can send callbacks to the modal through props, and have the callbacks access recoil state.

**Comment by lockhaicttv** [comment]
I tried to send callback through props but it's not work

**Comment by lockhaicttv** [comment]
But thank you for your support, love recoil team and all-volunteer

**Comment by BenjaBobs** [comment]
Can you provide the code where you trigger the modal and how it is set up?

**Comment by lockhaicttv** [comment]
I am writing a callback function and give it through props instead of giving a hook setRecoilState for children component, tks for your idea

**Comment by lockhaicttv** [comment]
It's working, tkssss ♥
