### ISSUE TITLE
Selector as defaults for atom not cached if have dependencies

### ISSUE THREAD

**Issue by artygrand** [facebookexperimental/Recoil#933]
In earlier issues I saw that it should be cached, but in me case it is not.

I have code like this and every time I use the `itemList` the selector is executed.
```JS
import auth from 'atoms/auth';

const defaults = selector({
    key: 'defaults',
    get: async ({get}) => {
        const wl = {};
        let res = await Api.Get(get(auth).uuid);
        res.data.forEach((item) => wl[item.id] = true)
        return wl;
    }
});

const itemList= atom({
    key: 'myAtom',
    default: defaults ,
});
```
But once I replace `get(auth).sub` with static string, selector becomes cached. The auth value, of course, does not change during session. I really can't understand.

And second thing. If I change `itemList` value from my code then the selector stops being called.

Recoil 0.1.2 and 0.1.3

Thank you!

**Comment by BenjaBobs** [comment]
This might be fixed by https://github.com/facebookexperimental/Recoil/pull/749, we'll have to see when Recoil 0.2.0 drops.

**Comment by csantos42** [comment]
> If I change itemList value from my code then the selector stops being called.

This part is expected-- if you update an atom that once had a default value set to a selector, you opt out of the selector in favor of the updated value. If you need the selector to run each time, you could have an underlying atom that is updated in a writable selector's `set` property, allowing you to seemingly update a selector's value while ensuring the selector's `get` runs every time.

Regarding the first issue, that sounds like it might be a bug but we would need a minimal reproducible sample to confirm, could you whip up a codesandbox replicating the issue?

**Comment by artygrand** [comment]
The second thing is not as bug here, but as part of behaviour when issue is fixed, and you confirmed it.

As for sandbox, I have moved the test component from my code. But everything works as it should. Now I'm completely confused.
https://codesandbox.io/s/frosty-worker-v0koq?file=/src/App.js

Any ideas what to check?

**Comment by 42shadow42** [comment]
@artygrand I'm looking at your sandbox and I'm not sure what the problem seems to be.... Can you elaborate?

**Comment by drarmstr** [comment]
The selector is cached, but will re-evaluate if the dependency is updated.  Sounds like this may be a duplicate of #749 then?

**Comment by artygrand** [comment]
Fixed in update

**Comment by 13916253446** [comment]
I When can I use?
