### ISSUE TITLE
[Question] finder/file explore like UI state

### ISSUE THREAD

**Issue by RayLuxembourg** [facebookexperimental/Recoil#937]
I wanted to give it a try to recoil even though it experimental.
I used it to create a very cool monitoring app at my workplace.

I am having trouble refactoring the app to be cleaner and properly implementing recoil.

I have finder/file explore like visual UI
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/xXBRh.png

and each column gets its list asynchronously. 

 1. When I change a selection from the first column, I would like the other columns to return to the default state (empty). Following this pattern, when previous column changes the next column goes back to be empty (default state)
 2. Every column is dependent on the previous columns selection, in
    order to have an API call /first/second/third

**Comment by BenjaBobs** [comment]
I'd probably do that as an atomFamily and a selectorFamily.
The family parameter for both would be the level (the column).
The atomFamily would hold the selected item for each level, and the selectorFamily would return the items for each level based on the atomFamily value at previous level.

**Comment by csantos42** [comment]
Agree with BenjaBobs that `atomFamily()` and `selectorFamily()` are good options here. For more info see:

* https://recoiljs.org/docs/api-reference/utils/atomFamily/
* https://recoiljs.org/docs/api-reference/utils/selectorFamily/

**Comment by RayLuxembourg** [comment]
I found an optimal way to do this while going over all features.
Mainly recoil callback helped a lot since it exposes reset function.
Selectors  set functions also helped a lot.
And finally atom family for single case where i needed to do something specific to an item in the list 
Cannot wait for this library to get out of experimental release.
