### ISSUE TITLE
Simple question about change detection in Recoil

### ISSUE THREAD

**Issue by mulgurul** [facebookexperimental/Recoil#938]
Hi
Really happy with Recoil, and getting better at using it:-) So thanks a lot for a great clean package.

But I have this important question to understand change detection and performance implication, I read a lot of the documentation to find some explanation, but no luck:

If I have a Atom which is by default an object with lets say two properties:

`{ 
a: dataObjectA
b: dataObjectB 
}`

If I then have a selector on just property 'a' and a selector on just property 'b' and I change/set new value on 'a', will this trigger a change event on components using selector 'b'.

My concerns is poor performance if I use compound objects like a  "store" for the App state etc.
So I need to understand if i need to separate the store into individual atoms to avoid unnecessary re-rendering in irrelevant parts of the application.

Hope the explanation is clear and someone with a deeper knowledge of how Recoil works its ways can help me here.

Thanks a lot.

Peter Meldgaard, Denmark

**Comment by BenjaBobs** [comment]
I hope this setup explains it a bit:
```typescript
const appState = atom({
	key: 'appState',
	default: { a: {}, b: {} }
})

// this selector will update every time appState is changed
const selectorA = selector({
	key: 'selectorA',
	get: ({ get }) => {
		const state = get(appState);
		return state.a;
	}
})

// this selector will update every time appState is changed
const selectorB = selector({
	key: 'selectorB',
	get: ({ get }) => {
		const state = get(appState);
		return state.b;
	}
})

// to my understanding, currently this will update every time appState changes
// however when Recoil 0.2.0 is released, it will only update when selectorA does not return the same value.
const selectorC = selector({
	key: 'selectorC',
	get: ({ get }) => {
		const a = get(selectorA);

		return a;
	}
})
```
Also, based on [this](https://github.com/facebookexperimental/Recoil/pull/935) I think v0.2.0 will be released soon-ish.

**Comment by mulgurul** [comment]
Thanks a lot for your quick reply @BenjaBobs. As I understand your reply, then I need to separate the properties into indiv. atoms, by the time of writing this to avoid unnecessary re-rendering. And then look into next version soon.  
This is not quite optimal in my architecture of the App, but just how it is, so thanks again:-)

**Comment by BenjaBobs** [comment]
You could use an atomFamily to accomplish it, but it comes with other implications. https://recoiljs.org/docs/api-reference/utils/atomFamily

**Comment by csantos42** [comment]
Great answer thanks BenjaBobs! You're correct that this case should be handled in `0.2.0`
