### ISSUE TITLE
partial transactions / stale snapshots lead to overwritten state

### ISSUE THREAD

**Issue by bearbytes** [facebookexperimental/Recoil#940]
Hi,

I'm trying to wrap my head around how to best think about *transactions* in Recoil.

On the one hand, we have a lot of unrelated atoms that can be updated independently of each other.
On the other hand, there are situations where we want to update multiple atoms at the same time, to avoid displaying state that is out of sync.

There are 2 ways in which we can update state:
1. using the normal setter, via `useRecoilState`, `useSetRecoilState` or `useRecoilCallback(({ set }) => {...})`
   In the first method, Recoil may combine multiple `set`s into one transaction and only re-render the views once after all changes are applied. But it *can* also decide to render UI between `set`s, leading to UI states where only partial changes are applied, and also increasing the processing total time an update takes.
   
2. using `gotoSnapshot(snapshot.map(...))`
  In the second method, Recoil will collect all the changes into a snapshot, then apply (`goto`) the new snapshot, leading to only a single UI update.

Generally, I prefer to use the second method, but there is a huge issue with it:
When I `gotoSnapshot`, I update not only the states that I actually wanted to update, but also overwrite any changes to unrelated atoms that might have been updated at the same time (for whatever reason) while I am building up the new snapshot, because I replace the whole application state with whatever was in the initial `snapshot` when my function started.

In a large application, there might be multiple asynchronous processes running in parallel, that want to update a small set of atoms. Having one transaction overwrite completely unrelated changes is a big nono, and forces me to always use method 1 from above, at the cost of consistency and performance.

Dealing with conflicts where multiple transactions want to update the same data is complicated, but I believe it should be easily possible to have a "partial snapshot", that updates only some atoms, without having to apply the full snapshot of all the states in the application.

Imagine something like this:
```js
useRecoilCallback(({ mergeSnapshot }) => async () => {
  await someNetworkCall()

  const partialSnapshot = snapshot_UNSTABLE(mutableSnapshot => {
    mutableSnapshot.set(state1, "foo")
    mutableSnapshot.set(state2, "bar")
  })
 
  // This method will take the **current** snapshot (not the stale `snapshot` that is given to us in `useRecoilCallback`)
  // and only update those atoms that we actually changed.
  mergeSnapshot(partialSnapshot)
})
```

**Comment by csantos42** [comment]
> But it can also decide to render UI between sets, leading to UI states where only partial changes are applied

In the context of calling subsequent `set()`s in a callback, the updates will be batched, so in this case you can assume your changes will all be applied in one go to the individual atoms that you're updating (assuming you call the `set()`s synchronously)
