### ISSUE TITLE
generated function as parameter in effect

### ISSUE THREAD

**Issue by mildfuzz** [facebookexperimental/Recoil#945]
I would like to add an effect that will keep certain parts of my app in sync, but in order to do this I need to be able to pass a function into the effect.

At the moment, this is not possible because a function does fulfil the `SerializableParam` type that is required by `atomFamily`

Is there a work around I am missing?

**Comment by BenjaBobs** [comment]
There might be. Can you try explaining with code what you (ideally) want to do / how you want to do it?
It might be a use case that someone else has run into.

**Comment by mildfuzz** [comment]
something like this:
```
const myStateFamily = atomFamily({
  key: 'myStateFamily',
  default: null,
  effects_UNSTABLE: (mySyncFunc) => ({setSelf, onSet, trigger}) => {
    // Subscribe to local changes and update the server value
    onSet((data) => {
      mySyncFunc(data)
    })
  },
})

const SyncedComponent = () => {
  const mySyncFunction = useMySyncFunctionFactory()
  const state = useRecoilState(myStateFamily(mySyncFunction))
  return <pre>{JSON.strinify(state, null, 4)}</pre>
}
```

**Comment by mondaychen** [comment]
I don't think it's a good idea to use a function as a parameter of `atomFamily`.
What exactly do you mean by "keep my app in sync"? To save the data to some database?

**Comment by BenjaBobs** [comment]
It looks like (and correct me if I misunderstood) that you are looking to use `atomFamily` to select which *sync function* to use for the atom.
I don't think that's possible as you write it there, and I also think it may not be a good idea.
If you really want to do it though, you could setup a structure like this:
[![](https://mermaid.ink/img/eyJjb2RlIjoiZmxvd2NoYXJ0IFREXG4gIGF0b20tLT5zZWxlY3RvcldpdGhTeW5jQVxuICBhdG9tLS0-c2VsZWN0b3JXaXRoU3luY0JcbiAgc2VsZWN0b3JXaXRoU3luY0EtLT58dXNlQXRvbVdpdGhTeW5jQXxjb21wb25lbnRBXG4gIHNlbGVjdG9yV2l0aFN5bmNCLS0-fHVzZUF0b21XaXRoU3luY0J8Y29tcG9uZW50QlxuXHRcdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZmxvd2NoYXJ0IFREXG4gIGF0b20tLT5zZWxlY3RvcldpdGhTeW5jQVxuICBhdG9tLS0-c2VsZWN0b3JXaXRoU3luY0JcbiAgc2VsZWN0b3JXaXRoU3luY0EtLT58dXNlQXRvbVdpdGhTeW5jQXxjb21wb25lbnRBXG4gIHNlbGVjdG9yV2l0aFN5bmNCLS0-fHVzZUF0b21XaXRoU3luY0J8Y29tcG9uZW50QlxuXHRcdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)
And then in `selectorWithSyncA` define a `setter` method, which both sets `atom` as well as run `syncFunctionA`.
That way you run only the specific sync function when setting, and all the dependencies will still update.

I must say though, that it seems like a very complex use case, and I'm having a hard time understanding why you'd want different sync functions.

**Comment by mildfuzz** [comment]
Specifically, I want to add an effect to maintain syncronicity with react hooks form, so the function would be the `setValue` function returned from useForm

**Comment by BenjaBobs** [comment]
Ah, Recoil + forms is a topic that's been brought up before.
Have you had a look at https://github.com/serverscom/recoil-form?

**Comment by mildfuzz** [comment]
Considered it, reality is that a fresh project like that is unlikely to fly on this project. Would certainly consider it.

That said, seems like this is a valid use case of what I am proposing, and nothing to say similar usecase's aren't plentiful, so maybe it's worth considering?

**Comment by drarmstr** [comment]
By using a family with this pattern, it would also mean that you would have separate atoms and state for each sync function.  Is that intentional?

**Comment by mildfuzz** [comment]
Sorry, no, disregard that.

**Comment by drarmstr** [comment]
Ok, so sounds like the original question is moot for this issue then.  One pattern that may be helpful for passing functions to atom effects is this:

```
const myEffect = ({syncFunc}) => effectInterface => {
  ... logic to sync using atom effect interface and syncFunc() ...
};

const myState = atom({
  key: 'MyAtom',
  effects_UNSTABLE: [
    myEffect({syncFunc: syncA}),
  ],
});
```

That only allows a single sync function per atom, of course.
