### ISSUE TITLE
AtomEffect: calling setSelf with a promise triggers onSet

### ISSUE THREAD

**Issue by sseppola** [facebookexperimental/Recoil#953]
The [docs](https://recoiljs.org/docs/guides/atom-effects/) specify `The callback is not called due to changes from this effect's own setSelf()`

However, this does not apply when setSelf is called with a promise. I've made a CodeSandbox to demonstrate:
https://codesandbox.io/s/atom-effects-triggers-own-onset-gy1ty

**Comment by ShravanSunder** [comment]
may be fixed with #979

**Comment by drarmstr** [comment]
@ShravanSunder - looks like a slightly different cause.  But, I have a fix with #
