### ISSUE TITLE
New helper function to get value from Loadable or fall back on default

### ISSUE THREAD

**Issue by owzh** [facebookexperimental/Recoil#955]
For Loadable, could we add a helper to pull back the current value or fall back on default value if one is provided? Currently, for my project, I have a function to do special handling on loadable read and fall back on a default value. However, we have to provide the helper with default value each time we use it and it's a bit of work to keep them in sync.

```
const newSelector = selector({
   key: 'newSelector',
   default: [], // this is not supported but part of the request for this ticket here
   get: async () => getApiToLoadValue()
});

// This is the helper that I have for my project. As you can see, we have to specify a default each time we need to use this hook.
const useValueLoadableWithDefaultValue = ({ selectorState, defaultValue }) => {
  const { state, contents } = useRecoilValueLoadable(selectorState);
  if (state === 'hasValue') {
    return contents;
  }
  return defaultValue;
};

const useNewSelector = () => useValueLoadableWithDefaultValue({ selectorState: newSelector,  defaultValue: [] });
```

Same thing when it comes to time that we need to read it from a snapshot.
```
// This is the helper that we are using currently. Again, we have to keep specifying a default.
const getValueFromSnapshotLoadableWithDefault = ({ snapshot, loadableSelector, defaultValue }) => {
    return snapshot.getLoadable(loadableSelector).valueMaybe() || defaultValue;
}

const useSomeCallback = () =>
  useRecoilCallback(({ snapshot, set }) => () => {
    const value = getValueFromSnapshotLoadableWithDefault({ snapshot, loadableSelector: newSelector, defaultValue: [] });
  }
});
```

It would be nice if we could do something like the following using a native Recoil api.
```
const useSomeCallback = () =>
  useRecoilCallback(({ snapshot, set }) => () => {
    const value = snapshot.getLoadable(newSelector).getValueOrDefaultValue();
  }
});
```

Please let me know if this is a valid use case for folks out there. Thanks!

**Comment by BenjaBobs** [comment]
Loadable has `.valueMaybe()` which returns the value if `state` is `'hasValue'` and `undefined` otherwise.
https://recoiljs.org/docs/api-reference/core/Loadable

For default values you can do `const val = loadable.valueMaybe() || defaultVal`.

**Comment by owzh** [comment]
Right, that's what I have right now. But I am asking if Recoil could handle a default when we create the selector. Then, when we need to call valueMaybe() or potentially a new loadable api, it would return the value if state 'hasValue', otherwise, return default instead of undefined. I find myself keep having to provide a default each time i use loadable on a selector and I have to make sure the default is the same everywhere.

Providing a fallback is not a big deal if a selector is only used once or twice. But when it's used across several components, it's a bit error prone to have to remember to provide a default each time and make sure we provide the same default value everywhere.

**Comment by BenjaBobs** [comment]
Ah, now I get you. You can build it into your selector with the `noWait` util function:

```typescript
const selectorWithDefault = selector({ get } => {
    const loadable = get(noWait(myAtom));

    if (loadable.state === 'hasValue') return loadable.contents;

    return myDefaultValue;
}
```

**Comment by owzh** [comment]
Thanks for the feedback. It seems like we have to create an atom first and then use the snippet you have posted to load it. Is there a way to do it using just the selector? We are trying to use it for our async selectors.

Our current selector looks like this:

```
const newSelector = selector({
   key: 'newSelector',
   get: async () => {
     const data = await getApiToLoadValue();
     return data.filter(item => item.someCondition);
});
```

I was hoping selector would support a default prop. Something like the following:

```
const newSelector = selector({
   key: 'newSelector',
   default: [],
   get: async () => {
     const data = await getApiToLoadValue();
     return data.filter(item => item.someCondition);
});
```

This way, i don't have to create an atom first and then populate it using a selector. Or use a custom function to provide a default value. Not a hard problem to work around but more code and more verbose.

**Comment by owzh** [comment]
But with the code snippet that you have provided. I was able to create a helper to load async functions.

```
export const selectorWithDefaultValue = ({ key, atom: atomState, default: defaultValue }) =>
  selector({
    key,
    get: ({ get }) => {
      const loadable = get(noWait(atomState));
      if (loadable.state === 'hasValue') return loadable.contents;
      return defaultValue;
    },
  });
```

Then, i was able to do something like

```
const someStateWithDefault = selectorWithDefaultValue({
  key: 'someStateWithDefault',
  default: [],
  atom: selector({
    key: 'atomState',
    get: async () => getApiToLoadValue(),
  }),
});
```

Then the hook to read the value.
```
const useSomeState = () => useRecoilValue(someStateWithDefault);
```

But please let me know if supporting a default prop for selector is a valid request. Will close out this ticket if we don't want to support it natively. Kudos to the Recoil team for this great lib!

**Comment by BenjaBobs** [comment]
Nice, good to know you found a solution.
As far as the feature request goes, I'm not sure of the use case exactly.
If the selector is fetching some data and you want to have a fallback during, I think I would instead use an atom, with the default value, and then do the fetching either outsude of Recoil or in an atom effect, and then set the atom value.

Of course I don't know if that's applicable to your situation, so my point might be moot. Can you provide some more specifics of your use case?

**Comment by owzh** [comment]
Ahh, atom effects looks like it would meet our needs. 

The main thing is we are trying to use the selectors in useRecoilCallback. 

```
const useSomeCallback = () =>
  useRecoilCallback(({ snapshot, set }) => () => {
    const value = snapshot.getLoadable(someSelectorState).getValue();
    // do other stuff
  }
});
```

We want to pull out the values from these selectors using getValue() or valueMaybe() and not have to worry about it might be throwing an error or being undefined. We don't want to handle it and want it to just fallback on a default value that's defined during atom/selector creation. This is somewhat solved with the snippet that I posted above. It just means we have to be mindful and use the new `selectorWithDefaultValue` during creation.
