### ISSUE TITLE
I have general questions, can we have GitHub discussion or a place to chat?

### ISSUE THREAD

**Issue by ivanjeremic** [facebookexperimental/Recoil#957]
Around recoil is no discord or discussion chat, can we have one to avoid asking in GitHub issues?

**Comment by LexSwed** [comment]
Agree, Discussions here can take some work off the maintainers' shoulders since many questions will be answered there by other devs, avoiding many Q&A issues created

**Comment by davidmccabe** [comment]
https://discord.gg/b8ajkNFsWr

**Comment by ShravanSunder** [comment]
github discussions would be a great way to share ideas or Q&A in a more persistent format compared to conversation in discord.

**Comment by drarmstr** [comment]
Thanks for the suggestion!  We're looking into enabling it now.

**Comment by drarmstr** [comment]
It's just been enabled!
