### ISSUE TITLE
Sample example for <RecoilRoot> with initializeState in SSR use case

### ISSUE THREAD

**Issue by dsathyakumar** [facebookexperimental/Recoil#958]
Hello!

I'm looking for a sample of using `<RecoilRoot>` with SSR of React (`renderToNodeStream`).
There is a prop called `initializeState` but the docs / examples aren't available / not very helpful.
Is there a working example of `<RecoilRoot>` with `initializeState` + hydrate ?

**Comment by davidmccabe** [comment]
An example would be something like:

```
function initializeState({set}) {
  set(atomA, 123);
  set(atomB, 456);
} 

...

<RecoilRoot initializeState={initializeState}>
...
 ```

The function you provide will be invoked and the resulting state used during the initial render, so you should be able to observe that state via SSR. Does that work?

**Comment by rtritto** [comment]
There is a way to reinitialize?

[CodeSandbox](https://codesandbox.io/s/next-recoil-reload-reset-state-page-example-p85wv2)

## Steps to reproduce
- Go to page 1 (note content#1)
- Click to _Link_ component to navigate to page 2

## Actual
content#1

## Expect
content#2

**Comment by drarmstr** [comment]
You can give the `<RecoilRoot>` a `key` prop that you can change to cause it to use and initialize a new store.
