### ISSUE TITLE
Loadable TypeScript inference issue

### ISSUE THREAD

**Issue by RayLuxembourg** [facebookexperimental/Recoil#961]
I am not sure if this a typescript limitation or not but it is very wrong the hasValue state displays both error and success O_O
According to the flow in the docs [loadable docs](https://recoiljs.org/docs/api-reference/core/Loadable)
hasValue should be inferred only as the expected object on success

```
        const { state, contents } = useRecoilValueLoadable(userSelector);
        case 'hasValue':
        currentRole = RoleUX[contents.role] || contents.role;

```

![](https://i.imgur.com/BGXLXSB.png)

After some investigation, I realize this happens when you destruct from useRecoilValueLoadable.

Regarding this interface 
```
interface BaseLoadable<T> {
  getValue: () => T;
  toPromise: () => Promise<T>;
  valueMaybe: () => T | void;
  valueOrThrow: () => T;
  errorMaybe: () => Error | void;
  errorOrThrow: () => Error;
  promiseMaybe: () => Promise<T> | void;
  promiseOrThrow: () => Promise<T>;
  map: <S>(map: (from: T) => Promise<S> | S) => Loadable<S>;
}
```
Shouldn't those conditional voids be declared on proper state type?
for example,
```
interface ValueLoadable<T> extends BaseLoadable<T> {
  state: 'hasValue';
  contents: T;
  valueMaybe: () => T;
}

```
and removed from BaseLoadable and that way the type can become more accurate?

**Comment by BenjaBobs** [comment]
To add to that, having `valueMaybe` return type `undefined` instead of `void` would make it easier to use with the `?.` operator.

**Comment by drarmstr** [comment]
Sounds like some nice improvements, thanks!
