### ISSUE TITLE
Manipulating Recoil state in big asynchronous functions

### ISSUE THREAD

**Issue by nxz91** [facebookexperimental/Recoil#962]
When writing asynchronous functions, we would like to get and set Recoil state along the way. The problem with simply using useRecoilCallback with asynchronous functions is that snapshot.getPromise() will return the value from the time function execution began, and not when snapshot.getPromise() is called. To find out what the current value of a Recoil key is, we were thinking the following could work, but then we were wondering **if this is discouraged for any reason**, because no such helper function exists:

```
const getRecoilInterface = useRecoilCallback((callbackInterface) => () =>
    callbackInterface
)
```

You can then just use getRecoilInterface().snapshot.getPromise() to get the current value of any atom and getRecoilInterface().set() to set any atom.

It looks like a very simple solution, but is there anything that speaks against this?

**Comment by BenjaBobs** [comment]
I believe that there is no direct interface because keeping track of the state asynchronously is tricky, and it is easy for the api consumers to make code that has race conditions. @drarmstr can you confirm?

**Comment by nxz91** [comment]
Race conditions inside Recoil? I'm not sure I understand

**Comment by BenjaBobs** [comment]
So if you have an async recoil callback which does this:
1) Read some data from recoil state, which we'll call `A`
2) Fetch currency rates from some api, which we'll call `B`
3) Set recoil state based on `A` and `B`

The data `A` may be old by the time you get to step `3`, so setting state based on `A` can potentially be destructive.

**Comment by nxz91** [comment]
Yes, those race conditions are the reason why I would like to use "getRecoilInterface" instead. If there are no other objections, then it sounds like an extremely useful thing to have / encourage people to use.

**Comment by drarmstr** [comment]
This "recoil interface" can work for getting the "current" value at the time the callback is called for that React context and it's possible for advanced cases where you're sure what you're doing.  But, we don't want to broadly encourage it necessarily.  We want to default to users working with consistent state.  For example, in a callback reading state A, then doing something, then reading state B.  The state A and B should be consistent and legal to both be in that state, which is the case when you look at the same snapshot for both of them based on the state when the callback was issued.  If it defaulted to getting state B from some newer snapshot, then A and B may have incompatible values.  That approach has led to bugs.

**Comment by wonderberlin** [comment]
Got it, thanks!

**Comment by nxz91** [comment]
Got it, thanks!
