### ISSUE TITLE
Batch update a set of states before triggering re-renders to the subscribed components

### ISSUE THREAD

**Issue by jimin4** [facebookexperimental/Recoil#969]
If I have to set states from multiple different atoms as part of some high level action user is taking, I want all subscribing components for any of the impacted atoms to be re-rendered only once when the entire states are set as a batch. Is this possible with Recoil?

**Comment by bearbytes** [comment]
Updates should be batched automatically if they occur synchronously, ie.
```ts
const setA = useSetRecoilState(atomA)
const setB = useSetRecoilState(atomB)

const transaction = () => {
   // No component will be rendered between these two updates
   setA(1)
   setB(2)
}
```

**Comment by drarmstr** [comment]
For asynchronous transactions there is a proposal in #762
