### ISSUE TITLE
[Feature Suggestion] Helper function for Getting Serialized Atom/Selector Family Key.

### ISSUE THREAD

**Issue by mthines** [facebookexperimental/Recoil#980]
Hey!

As I needed to pull some data from localstorage for some `atomFamily` & `selectorFamily`, I ran into the issue that (obviously) the the keys had been merged with the `id` passed to the `atomFamily`.

I searched for a helper function within the `Recoil` library to just pass the same info as when invoking the `atomFamily` and then it'll get the key value returned, but without luck, so I ended up creating a small helper function.

Maybe I just didn't search good enough, or was unlucky, but wouldn't it make sense to make the function that serializes the key available for import and use?

Something like the following:
```tsx
/**
 * @returns Serialized Key for Atom & Selector Family
 */
export const getSerializedFamilyKey = <T extends string | string[] | Record<string, string>, P extends SerializableParam>(
  atomKey: string,
  familyKey: T,
) => `${atomKey}__${JSON.stringify(familyKey)}` as P;
```

As usual, great work guys 💪

**Comment by drarmstr** [comment]
You do not need to use the same key as the atom for localstorage persistence.  The exact format of the key string is undocumented and could be subject to change.

**Comment by mthines** [comment]
That's true.
I'll close the issue
