### ISSUE TITLE
Add ability to clear/disable selector cache

### ISSUE THREAD

**Issue by GeoMarkou** [facebookexperimental/Recoil#981]
There's some cases where you don't want responses to be cached, because they depend on the currently logged-in user. If the user logs out, it's a security issue for their data to be cached. It would be good to have some way to clear the cached values on log out.

What's the recommended way to handle this situation?

```Typescript
export const selector_user_first_name = selector<string>({
    key: 'user_first_name',
    get: async () => {
        return await (await fetch('/User/FirstName')).text();
    }
});

export const LogOut = () => {
    await fetch('/User/Logout', { method: 'POST' });
    clearSelector(selector_user_first_name );
}
```

**Comment by drarmstr** [comment]
@csantos42 is working on exactly this.

**Comment by ahfarmer** [comment]
Perhaps consider renaming this issue to 'Add ability to clear a selector' because this issue doesn't address the ability to disable caching entirely on a selector. I've brought that up here: https://github.com/facebookexperimental/Recoil/issues/1064

**Comment by GeoMarkou** [comment]
No worries; either clearing or disabling caching would be useful, but you're right all my examples reference "clearing" not "disabling"

**Comment by drarmstr** [comment]
Ability to [configure selector caches](https://recoiljs.org/blog/2021/07/30/0.4.0-release#configurable-selector-caches) now available in Recoil 0.4.

**Comment by florianbepunkt** [comment]
@drarmstr Selector cache policies do not fully address this issue. As far as I can tell from the docs, it is not possible to disable or imperatively clear a cache. We have some unit tests where cached selector data is bleeding between tests (see issue https://github.com/facebookexperimental/Recoil/issues/981)

There is no cache strategy of "none". Also a cache strategy of `{ eviction: 'lru', maxSize: 0 }` does not disable caching.

**Comment by drarmstr** [comment]
Yes, the minimum caching right now is the most recent.  As selector values are often looked up for dependencies we are hesitant about un-intuitive performance implications or people running into problems expecting to view "current" state without proper state changes of dependencies.  

Looking closer at the description of this issue if security is your concern, then it may be safer to completely flush all state.  Perhaps use a `key` prop for the `<RecoilRoot>` based on the logged in user so that all Recoil state should be lost when that key changes?

**Comment by drarmstr** [comment]
Yes, the minimum caching right now is the most recent. As selector values are often looked up for dependencies we are hesitant about un-intuitive performance implications or people running into problems expecting to view "current" state without proper state changes of dependencies.

Something that may work for this situation is flushing the records for atoms/selectors that go out of scope, which should be part of the upcoming garbage collection memory management feature?  (cc @csantos42, @davidmccabe)

**Comment by drarmstr** [comment]
Duplicate of #972
